### ISSUE TITLE
syntax: don't indent switch cases

### ISSUE THREAD

**Issue by RalphCorderoy** [mvdan/sh#101]
A `case` statement is equivalent to an if-elif-else-fi chain and so the indentation should match.

    if [[ $foo = y ]]; then
        bar
        xyzzy
    fi
    case "$foo" in
    y)
        bar
        xyzzy
        ;;
    esac

It's unusual for the case's patterns to be indented. Other languages don't do it either, e.g. K&R C, `go fmt`.

**Comment by mvdan** [comment]
I actually wondered quite a lot about this, and decided to indent cases (thus duplicate indentation for their bodies) because that's what I'm used to seeing more often, and that's what the Google style encouraged.

I agree with you that I prefer not duplicating the indentation. And I agree that I should probably have gone with the opposite, given my recent decision to not follow the Google style guide as closely anymore.

Some questions arise:

* Do you have anything to back this as the canonical, original or most popular style?
* Should there be a flag for this? (I sure hope not)

**Comment by mvdan** [comment]
Here's a point against this, as per the POSIX Shell language spec - the example does indent the cases:

```
case word in
    [(] pattern1 ) compound-list ;;
    [[(] pattern[ | pattern] ... ) compound-list ;;] ...
    [[(] pattern[ | pattern] ... ) compound-list]
esac
```

I'd also like to go for no double indentation, but I'm struggling to find a reason why other than "I prefer it".

**Comment by RalphCorderoy** [comment]
Hi @mvdan, are you aware of _The Unix Programming Environment_, by Kernighan and Pike, https://bit.ly/unixprog

It introduces `case` on page 134, the reference given in the Index for it, and has

    case word in
    pattern) commands ;;
    pattern) commands ;;
    ...
    esac

They then use it in their version of cal(1) to turn month names into numbers, with the same indentation.

Is that sufficient? If not, I can dig up more examples of pedigree. :-)

**Comment by mvdan** [comment]
Awesome, that's all I need. I'll get to this for v2.

**Comment by mvdan** [comment]
Note to self - if people complain about the change, consider adding a flag to go back to the v1 behaviour, similar to how we added `-bn`.

**Comment by mvdan** [comment]
@RalphCorderoy done - the change is quite simple, but I'd still appreciate if you tested it out.

**Comment by ebfe** [comment]
I'd like to register my vote for adding a flag to go back to the old behaviour :)

Not because i think the old indentation was the "right" one, but mostly because it causes huge diffs to the v1 format.

**Comment by mvdan** [comment]
I'm not sure if I buy the argument. Let me list my concerns:

* More options are a bad idea in the long term, and noone is against the new format per se
* Whitespace diffs can be ignored, e.g with `git diff -w`
* You'll only switch from v1 to v2 once (and the time to do such big changes is exactly then)

I haven't completely made my mind on this, but I still think not adding an option is the sanest way forward. Also worth noting that not many people use and depend on the current v1 format - at least that I know.

**Comment by mvdan** [comment]
One argument in favor, though, is that we did add an option for `-bn`, which is also a formatter flag.

**Comment by ebfe** [comment]
All reasonable points. However adding automatic/enforced formatting to a
codebase is an even harder sell if it rewrites a significant portion of the
code on (major) updates. If v2 is very close to whatever the "final" `shfmt`
format will look like, then this might not matter too much, but in that case
I'd also remove the `-bn` option.

**Comment by mvdan** [comment]
v2 is pretty final, at least for the foreseeable future. I doubt there will be any more changes to the format as big as this one.

Regarding `-bn` - the reason it was kept wasn't diffs, but rather objective usefulness. That style is part of the Google Shell style, and it can be useful to have the binary command operands at the start of each line for readability. Of course it has the drawback of the backslash, hence the option.

On one hand, indenting cases is also part of the Google Shell style, so it could also have some value on its own. On the other however, this change is a purely whitespace one - the other adds characters and moves a token. This one is much less intrusive and more subtle.

I hope that explains why the two options are different in my head.

I'm still somewhat leaning against the option. Thoughts and counter-arguments welcome.
