### ISSUE TITLE
Create Python bindings

### ISSUE THREAD

**Issue by sisp** [mvdan/sh#1011]
I've stumbled over this project because [Task](https://taskfile.dev/) uses it:

> Task uses [mvdan.cc/sh](https://mvdan.cc/sh/), a native Go sh interpreter. So you can write sh/bash commands, and it will work even on Windows, where sh or bash are usually not available. Just remember any executable called must be available by the OS or in PATH.
>
> — https://taskfile.dev/usage/#getting-started

We have a similar use case in [Copier](https://github.com/copier-org/copier) where cross-platform shell commands may be declare by template creators through the [tasks feature](https://copier.readthedocs.io/en/stable/configuring/#tasks). Copier is written in Python though, so I've been wondering whether you might be open to providing Python bindings to `sh` since there already exists a JS package (through transpilation though). It seems possible to create Python bindings for Go libraries using [`gopy`](https://github.com/go-python/gopy). I'd be happy to look into it if you agree on the general idea. :slightly_smiling_face:

**Comment by mvdan** [comment]
By all means go ahead :) I don't have the time to do this myself, but am happy to help on our side where needed. You might struggle with the syntax tree types, since those are trees of pointers which make use of interfaces to mimic sum types. That's ultimately why I wrote https://pkg.go.dev/mvdan.cc/sh/v3/syntax/typedjson - not just for `shfmt --to-json`, but also for interfacing with languages like JS so that the syntax tree can be encoded to bytes.

**Comment by mvdan** [comment]
I'm going to close this as there isn't anything actionable to do here. As said above, I'm happy to support the effort to do bindings, but I don't have the time to do them myself, so they won't be in this repository.

**Comment by mbhall88** [comment]
Agreed that Python bindings would be very valuable. I maintain a tool called [`snakefmt`](https://github.com/snakemake/snakefmt) which formats Snakemake (a DSL built on top of python) code. Part of Snakemake "rules" are shell blocks. e.g.,

```python
rule download_reference:
    output:
        reference="<resources>/references/ASM1672810v1.gbff.gz",
    log:
        "<logs>/download_reference.log",
    params:
        url="https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/016/728/105/GCF_016728105.1_ASM1672810v1/GCF_016728105.1_ASM1672810v1_genomic.gbff.gz",
        md5_url="https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/016/728/105/GCF_016728105.1_ASM1672810v1/md5checksums.txt",
    shell:
        """
        exec > {log} 2>&1

        wget {params.url} -qO {output.reference}
        # Verify the downloaded file using the provided MD5 checksums
        wget {params.md5_url} -qO - | 
          grep "GCF_016728105.1_ASM1672810v1_genomic.gbff.gz" | 
          awk '{{print $1 "  {output.reference}"}}' | 
          md5sum -c
        """
```

I would like to be able to support formatting the contents of the `shell` directive without having to call out to an external tool. And our users have [previously requested ](https://github.com/snakemake/snakefmt/issues/170)such a feature.

I know you have clearly stated you do not have the time to suport this, which is fair enough. But thought I would just post this in case it inspires someone to do the bindings. I have no Go experience so would not be able to do it myself.
