### ISSUE TITLE
syntax: add support for Bash's select

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#102]
I didn't even know this existed.

**Comment by Learn-Digital-Audio** [comment]
I just started using your excellent program, and go at error right away on:

select f in "${files[@]}"; do
    [[ -n "$f" ]] && break
    echo ">>> Invalid Selection" >&2
done

**shell format error:15:28: "do" can only be used in a loop**

Great news this is getting fixed! Any idea how long till v2 arrives? :)

**Comment by mvdan** [comment]
I was working on this just two days ago but got blocked by some mksh/bash weirdness.

v2 is mostly ready, I'm just making sure I don't forget anything. Plan on releasing very soon.

**Comment by Learn-Digital-Audio** [comment]
Fantastic news! I am using it in VS Code with this extension:

https://github.com/foxundermoon/vs-shell-format
