### ISSUE TITLE
Error on case toggle "~~"

### ISSUE THREAD

**Issue by mayrholu** [mvdan/sh#1026]
When using case toggle such as `echo ${PROJECT~~}` an (unintuitive) error is thrown:
`<file, line...>: LitWord cannot be followed by a word`

Remove the `~~` and the error is gone.

Let me know if you need additional info.

**Comment by mvdan** [comment]
Where is this language feature documented? I can't find it in `man bash`, nor by googling for "shell case toggle".

**Comment by mayrholu** [comment]
Check for example [this](https://medium.com/mkdir-awesome/case-transformation-in-bash-and-posix-with-examples-acdc1e0d0bc4#:~:text=Use%20%5E%20to%20convert%20the%20first,toggle%20cases%20for%20all%20characters.) guide

**Comment by mvdan** [comment]
Interesting, and it does work, although Bash appears to not have it documented _at all_ and the only test for it is disabled.

I'm very reluctant to support a language feature that isn't documented. For all we know, it could be an accident or a historical feature that is in some stage of removal.

**Comment by mvdan** [comment]
I'm going to close this for now per the above - this is not planned as long as it's not documented. Happy to reopen if new information is brought forward.
