### ISSUE TITLE
Windows Executable from Releases doesn't install. It just hangs.

### ISSUE THREAD

**Issue by fmotion1** [mvdan/sh#1040]
Trying to install `shfmt` on Windows 10 Pro x64 Version 22H2 (Build 19045.3448). 
Using this binary: `shfmt_v3.7.0_windows_amd64.exe`

When I open the executable, all I see is a blinking cursor:

![shfmt_v3 7 0_windows_amd64_lzJtwcrJod](https://github.com/mvdan/sh/assets/33441569/f570a5ec-06cc-4d9d-96ca-de8c6e6f1b42)

What am I doing wrong? How can I get this installed?

Thanks so much.

**Comment by mvdan** [comment]
We publish the shfmt binary itself, not an installer for it. If you just run it directly, it reads shell script from standard input, so that's what I suspect is happening here with the terminal waiting for you.
