### ISSUE TITLE
syntax: dash support

### ISSUE THREAD

**Issue by nihilus** [mvdan/sh#105]
Being almost identical to bash 2.x with some constraints (which is very popular shellshellin in embedded systems because of busybox ash), I think it is a no-brainer to implement fora guy who know Golang.

**Comment by mvdan** [comment]
Just to clarify - we already support Bash and POSIX Shell. The latter will reject any non-POSIX language features such as Bash arrays.

Are you suggesting supporting another shell language variant for Dash?

Could you give me an example of a program that is valid Dash but not POSIX Shell?

**Comment by mvdan** [comment]
Also, don't mix dash and ash - they are different shells. I don't know if they are different languages, though.

**Comment by nihilus** [comment]
Here are some of the most common errors I get with a recent version of shfmt:
* slicing is a bash feature
* arithmetic expressions must consist of names and numbers
* $ literal must be escaped or single-quoted

and this seems to have changed from march or april.

**Comment by mvdan** [comment]
> slicing is a bash feature

What exactly are you running?

> arithmetic expressions must consist of names and numbers
> $ literal must be escaped or single-quoted

These are expected and don't change with what language is being used. You should fix both. If you don't know how, I need to improve the error messages.

**Comment by nihilus** [comment]
I did a simple run with my build environment with an updated version of 'shfmt'.

**Comment by mvdan** [comment]
If you run `shfmt somefile.sh`, it should not give the `slicing is a bash feature` error. That's when you use `shfmt -p`, i.e. in POSIX mode, on scripts that are Bash.

**Comment by nihilus** [comment]
I run it on my Almquist shell files, without '-p' I get lots of strange errors about 'if-then' and such.

**Comment by mvdan** [comment]
Can you provide one such example of a strange error?

**Comment by nihilus** [comment]
- "then" can only be used in an if
- "export" must be followed by words
- "do" can only be used in a loop

**Comment by mvdan** [comment]
The errors are not of much use without a shell program to reproduce them.

**Comment by nihilus** [comment]
For export I do like this:
`export LANG="${GETTEXT_LANGUAGE}.UTF-8"
export TEXTDOMAIN="$TEXTDOMAIN"
export TEXTDOMAINDIR="$TEXTDOMAINDIR"`

**Comment by mvdan** [comment]
This parses fine here:

```
 $ shfmt <<'EOF'
> export LANG="${GETTEXT_LANGUAGE}.UTF-8"
> export TEXTDOMAIN="$TEXTDOMAIN"
> export TEXTDOMAINDIR="$TEXTDOMAINDIR"
> EOF
export LANG="${GETTEXT_LANGUAGE}.UTF-8"
export TEXTDOMAIN="$TEXTDOMAIN"
export TEXTDOMAINDIR="$TEXTDOMAINDIR"
```

**Comment by mvdan** [comment]
Bump @nihilus

**Comment by nihilus** [comment]
@mvdan I need to look further what it is the issue with those scripts and why shfmt complains.

**Comment by mvdan** [comment]
I see nothing to do here, and the issue lacks information. I'm going to close this for now.

If you find any bug, please open another issue. Or if you think the parser should treat ash/dash separately, open an issue with an explanation as to why it would be necessary.

Thanks!
