### ISSUE TITLE
cmd/shfmt: document how --filename relates to EditorConfig support

### ISSUE THREAD

**Issue by tcrawford-figure** [mvdan/sh#1055]
I'm imagining something like the following:

```shell
shfmt --editorconfig-path=../relative/path/to/.editorconfig foo.sh
shfmt --editorconfig-path=/absolute/path/to/.editorconfig foo.sh
```

This becomes useful when integrating shfmt into other applications/plugins. Please see the following PR, if interested, for Gradle plugin integration: https://github.com/diffplug/spotless/pull/2031.

A different flag name can be used than what I provided, but this at least gives the gist of what I'm looking for.

**Comment by mvdan** [comment]
Not sure I understand; the entire point of editorconfig files is that they apply to the files relative to their location. When would you want to use this flag?

**Comment by tcrawford-figure** [comment]
@mvdan There seems to be some potentially unexpected behavior with how `.editorconfig` is respected. 

Take the following `.editorconfig` for example:

```ini
root = true

[*]
charset = utf-8

[*.sh]
indent_style = space
indent_size = 2
space_redirects = true
switch_case_indent = true
```

When I have a file named `foo.sh` with the following contents:
```shell
#!/usr/bin/env bash

function foo()
{
  if [ -x $file ]
  then
myArray=(item1 item2 item3)
  elif [ $file1 -nt $file2 ]
  then
    unset myArray
          else
    echo "Usage: $0 file ..."
  fi
}

for (( i = 0; i <   5; i++  ))
do
      read -p r
print -n $r
                    wait $!
done
```

I can successfully format this file, with `.editorconfig` respected, by invoking:
```shell
shfmt foo.sh
```

However, if I instead add the contents of `foo.sh` to stdin, the `.editorconfig` is not respected:
```shell
shfmt < foo.sh
```

Given this, what I have noticed is if I provide a `--filename foo.sh` to shfmt, the `.editorconfig` is respected:
```shell
shfmt < foo.sh --filename foo.sh
```

I'm not sure if this is a known feature/issue/limitation? If it is, I think that an update to the man page that mentions that this flag is required when providing content to stdin in order for the _nearest_ `.editorconfig` to be respected would be a good change.

So this is where my original request came from for having an `--editorconfig-path` flag. 
It may not be necessary and the `--filename` flag may be the preferred method to fix this.

**Comment by mvdan** [comment]
That is all working as intended. When you pass in a file via stdin, the filename is not known. We added the filename flag precisely for this purpose (and for related others such as error positions).

**Comment by tcrawford-figure** [comment]
@mvdan Thanks for confirming! Would documentation in the man page regarding this requirement be worth adding?

**Comment by mvdan** [comment]
Oops, this was indeed an undocumented fact. Opening a PR.

**Comment by tcrawford-figure** [comment]
@mvdan perfect! Thank you!
