### ISSUE TITLE
Multiple commands in one line

### ISSUE THREAD

**Issue by mastromberger** [mvdan/sh#1061]
I use in some scripts multiple commands in one line, e.g. variables with initial values.
ACTION=0; TOCLIP=0; AMON=""; GEOM=""

shfmt -d suggests following - is there a way to keep multiple commands with a semicolon in one line?

-ACTION=0; TOCLIP=0; AMON=""; GEOM=""
+ACTION=0
+TOCLIP=0
+AMON=""
+GEOM=""

**Comment by mvdan** [comment]
Sorry, but that's not planned. See https://github.com/mvdan/sh/issues/679#issuecomment-790539371.

**Comment by mvdan** [comment]
That said, note that you can always doo `FOO=x BAR=y BAZ=z` in a single line.
