### ISSUE TITLE
man page: incorrect statement regarding use of `-` (read from stdin) and `--filename` flag

### ISSUE THREAD

**Issue by ktetzlaff** [mvdan/sh#1079]
A little nitpick ...

The [shfmt man page](https://github.com/mvdan/sh/blob/68b762e/cmd/shfmt/shfmt.1.scd) states

> If any EditorConfig files are found, they will be used to apply formatting options. If any parser or printer flags are given to the tool, no EditorConfig formatting options will be used. A default like -i=0 can be used for this purpose.

Here's the problem: The `--filename` flag, which is intended to help with finding EditorConfig files when reading from stdin is listed under *Parser flags* and thus (according to the statement above) should stop EditorConfig formatting options from being used.

Possible solutions:
1. Move the `--filename` flag to either the *Generic* or *Utility* flags section, or
2. add an explicit exception for the `--filename` flag to the statement quoted above.

**Comment by mvdan** [comment]
Good point, and thank you for bringing it up. I agree with your first suggestion; even though the filename affects the parser, it also affects other parts of the tool such as the EditorConfig logic, so it can go under generic flags.
