### ISSUE TITLE
how to leave one-line subshells as they are

### ISSUE THREAD

**Issue by Karmenzind** [mvdan/sh#1091]
`shfmt` will change some simple one-line subshell expressions into multi lines, which is unnecessary for me:

```diff
$ shfmt -d /tmp/a.sh
diff /tmp/a.sh.orig /tmp/a.sh
--- /tmp/a.sh.orig
+++ /tmp/a.sh
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
 # vim:set et sw=4 ts=4:
-CURDIR=$(cd `dirname $0`; pwd)
+CURDIR=$(
+       cd $(dirname $0)
+       pwd
+)
```

Could you please add a configuration option like `keep_oneline_subshell = true`, or simply provide a comment tag like `# @shfmt-ignore`?

**Comment by mvdan** [comment]
See https://github.com/mvdan/sh/issues/679#issuecomment-790539371. There are no plans for this. You can always use a single command instead, like `cd $(dirname $0) && pwd`.
