### ISSUE TITLE
cmd/shfmt: --list exit code

### ISSUE THREAD

**Issue by sdavids** [mvdan/sh#1093]
```shell
$ mkdir /tmp/test && cd "$_"
$ echo 'readonly  a=1' >test.sh
$ shfmt -d test.sh
diff test.sh.orig test.sh
--- test.sh.orig
+++ test.sh
@@ -1,1 +1,1 @@
-readonly  a=1
+readonly a=1
$ echo $?
1
$ shfmt -l test.sh
test.sh
$ echo $?
0
```

`-l`/`--list` should also return `1`.

If you consider it a breaking API change you might want to introduce `--set-exit-if-changed` like [google-java-format](https://github.com/google/google-java-format/blob/8c652edd6bde53be99fe1a83377bce4e281ec957/core/src/main/java/com/google/googlejavaformat/java/UsageException.java#L56).

**Comment by sdavids** [comment]
The use case would be:

`shfmt --list $PWD >/dev/null`

vs .

`shfmt --diff $PWD >/dev/null`


in a [Git hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks).

Currently only `shfmt --diff . >/dev/null` works.

With `--list` the workaround would be something like:

```shell
diff="$(shfmt --list $PWD)"
if [ -z "${diff}" ]; then
  exit 0
else
  exit 1
fi
```

---

`--list` is faster than `--diff` and produces less I/O to throw away.

**Comment by mvdan** [comment]
There is some precedent with --diff using status codes; the `diff` tool does so, and `gofmt -d` will start doing this too very soon.

There is less precedent with --list that I'm aware of, and I'm a bit worried about breaking users with the reasonable use case of listing unformatted files, but who don't want to treat the presence of them as a failure. They likely are still interested in existing failures such as invalid syntax, so ignoring the status code entirely is not a good solution.

Personally, I think the "is empty" solution is good enough. It's pretty easy to do in shell and other programming languages.

**Comment by mvdan** [comment]
I'm going to close this as "won't fix" for now given the reasoning I gave above.
