### ISSUE TITLE
Add --ignore <glob> parameter

### ISSUE THREAD

**Issue by sdavids** [mvdan/sh#1095]
Having `--ignore <glob>` or however you want to call it would improve the usability of this tool.

Yes, there are [workarounds](https://github.com/mvdan/sh/issues/288#issuecomment-419354631) but they have [issues](https://github.com/mvdan/sh/issues/288#issuecomment-579582229).

The non-standard key in `.editorconfig` has [its issue](https://github.com/mvdan/sh/issues/1094), too.

---

Filtering while tree-walking inside of the tool is always better than piping to `xargs`, doing a for-loop, or having to create an extra file.

[SC2038](https://www.shellcheck.net/wiki/SC2038)
[SC2044](https://www.shellcheck.net/wiki/SC2044)

**Comment by mvdan** [comment]
What exactly is the problem with the entry in editorconfig? If the issue with the key is the lack of the prefix, we can fix that. At this point it's still unlikely I will add a flag for this unless good arguments are brought forward. "I find a flag easier than an editorconfig file" doesn't seem like a particularly strong argument.

**Comment by sdavids** [comment]
It is not "easier" it is not having the file at all.

---

Let's say you want to format a repository but the maintainer of that project does not want the `.editorconfig` file committed.

You then have to have to juggle with `git stash` and/or always be careful not to commit `.editorconfig`.

Or remember to:

```shell
$ printf '[node_modules/**]\nignore = true\n' >.editorconfig && shfmt -w . && rm .editorconfig
```

every time you work on that repo.

Instead of 

```shell
$ shfmt -w -e node_modules .
```

**Comment by mvdan** [comment]
It seems to me like you have manual steps no matter what you do in this scenario. Yes, the flag is shorter/faster than the other methods, but it's still a manual step you must remember.

You could always drop an `.editorconfig` in a parent directory. The search for those files does not end at the root of the VCS repository. You could, for example, have an editorconfig file to ignore all `node_modules` directories somewhere closer to your home directory.

Also note that editorconfig entries are a list of patterns to match filenames. And we also support matching by language (https://github.com/mvdan/sh/issues/664#issuecomment-1916589355). Fitting all this into a flag seems odd.

**Comment by sdavids** [comment]
I think the most common use case is that you format a directory and find out that 1 or 2 files (or 1 directory containing files) were formatted even though you did not want them to be formatted.

```shell
$ shfmt -w .
$ git status -s
 M node_modules/test.sh
 M test.sh
```
😲
```shell
$ shfmt --help
```
⇓
```shell
$ git reset --hard
$ shfmt -w --exclude node_modules .
$ git status -s
 M test.sh
$ git add -A
$ git commit -m 'chore: format'
```
🎉

---

```shell
$ shfmt -w .
$ git status -s
 M node_modules/test.sh
 M test.sh
```
😲
```shell
$ shfmt --help
```
🤔
```shell
$ man shfmt
```
📘👀⌛

```shell
$ printf '[node_modules/**]\nignore = true\n' >.editorconfig
$ shfmt -w .
$ git status -s
 M test.sh
?? .editorconfig
```
🤔

🌐👀⌛

```shell
$ git add -A -- ':!.editorconfig'
$ git commit -m 'chore: format'
$ git stash push -u -m shfm_exclude_node_modules
```
🎉



---


> You could always drop an `.editorconfig` in a parent directory. The search for those files does not end at the root of the VCS repository. You could, for example, have an editorconfig file to ignore all `node_modules` directories somewhere closer to your home directory.

This depends on the `root` [key](https://spec.editorconfig.org/#supported-pairs).

In shared repositories you usually want to set that key in the repository's root directory, otherwise you will not get stable formatting between the team members thereby defeating the purpose of `.editorconfig` in the first place—you would be forced to set all keys explicitly otherwise and if team members use different editors you would have to include all of their keys too.

---

> Also note that editorconfig entries are a list of patterns to match filenames. And we also support matching by language ([#664 (comment)](https://github.com/mvdan/sh/issues/664#issuecomment-1916589355)). Fitting all this into a flag seems odd.

This issue asks for a file-based exclusion not a language-based exclusion.

See the common case above why people might want to exclude files.

If one has complex needs it is better to use a config file (`.editorconfig`) no matter what tool one uses.

**Comment by sdavids** [comment]
Also, as far as I can tell all options supported by `.editorconfig` are available as CLI flags but the `ignore` option.

**Comment by sdavids** [comment]
Another reason I found:

https://github.com/mvdan/sh/blob/master/cmd/shfmt/shfmt.1.scd

> If any parser or printer flags are given to the tool, no EditorConfig formatting options will be used. A default like -i=0 can be used for this purpose.

Well, it cannot because `ignore` will be ignored in that case (pun intended).

**Comment by mvdan** [comment]
> In shared repositories you usually want to set that key in the repository's root directory, otherwise you will not get stable formatting between the team members thereby defeating the purpose of `.editorconfig` in the first place.

I only suggest a parent `.editorconfig` file for cases where the project does not want such a file committed, like in your original example. Yes, if the project does have such a file committed, then add the entry with `ignore`. If you think that's too generic, then let's track that in https://github.com/mvdan/sh/issues/1094.

EditorConfig files also stack. You can drop an `.editorconfig` file in the subdirectory to be ignored if you wish. It's really pretty flexible for this use case.

> This issue asks for a file-based exclusion not a language-based exclusion.

I would rather not offer, maintain, and document two parallel and different ways to ignore files and directories.

> Well, it cannot be used for that purpose because `ignore` will be ignored in that case (pun intended).

It won't. I think the man page is already clear about this, because `ignore=true` is not a formatting option (it does not affect the parsing or printing of shell), but I've added a test now to lock in this behavior.

I'm going to close this for now. I appreciate your passionate arguments, but there's a high bar to adding more options and features to this tool.

**Comment by sdavids** [comment]
This will work even with spaces in paths:

```console
shfmt -f . | grep -Z -v -e .husky -e node_modules | xargs shfmt -l -w
```

**Comment by sdavids** [comment]
I found a workaround.

It is slow and inefficient but at least it works—even for file paths containing spaces.

```console
$ mkdir -p /tmp/test/node_modules && cd $_/..
$ mkdir -p .husky/_
$ echo 'echo  "no space"' >test.sh
$ echo 'echo  "with space"' >a\ test.sh
$ echo 'echo  "ignore node_modules"' >node_modules/ignore.sh
$ echo 'echo  "ignore husky"' >.husky/_/ignore.sh
$ chmod -R u+x *.sh
```

```console
$ shfmt -f . | grep -v -e .husky/_/ -e node_modules/ | xargs -I {} sh -c 'builtin printf "%q\n" "{}"' | xargs shfmt -d
diff a test.sh.orig a test.sh
--- a test.sh.orig
+++ a test.sh
@@ -1,1 +1,1 @@
-echo  "with space"
+echo "with space"
diff test.sh.orig test.sh
--- test.sh.orig
+++ test.sh
@@ -1,1 +1,1 @@
-echo  "no space"
+echo "no space"
```

**Comment by sdavids** [comment]
Here is another use case:

"Copy all scripts from one directory to another."

When all scripts have extensions one could whip out `find` but if [they don't](https://rwxrob.github.io/blog/#_scripts_without_suffixes) `shfmt -f=0` becomes handy.

---

Let’s say you have a repo with some useful scripts:

```console
$ mkdir -p /tmp/test/.githooks && cd "$_/.."
$ printf '#!/usr/bin/env sh\necho one\n' >one.sh
$ printf '#!/usr/bin/env bash\necho two\n' >two
$ printf '#!/usr/bin/env sh\nshfmt --diff .\n' >.githooks/pre-commit
$ chmod u+x one.sh two .githooks/pre-commit

$ git init -q
$ git add one.sh two .githooks/pre-commit
$ git config set core.hooksPath .githooks
$ git commit -q -m initial

$ tree --noreport -a -I .git .
.
├── .githooks
│   └── pre-commit
├── one.sh
└── two
```

Copy them to another host/directory:

```console
$ shfmt -f=0 /tmp/test | rsync -az --files-from=- --from0 --no-relative / /tmp/other

$ ls -l /tmp/other
total 24
-rwx------  1 redacted  wheel  27 May 11 10:47 one.sh
-rwx------  1 redacted  wheel  33 May 11 10:49 pre-commit
-rwx------  1 redacted  wheel  29 May 11 10:54 two
```

Copy them into a running Docker container:

```console
$ docker run --rm -d --init --name shfmt-cp-test busybox:1.37.0 sleep infinity

$ shfmt -f=0 /tmp/test | xargs -0 -I {} docker cp -q "{}" shfmt-cp-test:/tmp

$ docker exec shfmt-cp-test ls -l /tmp
total 12
-rwx------    1 502      root            27 May 11 08:47 one.sh
-rwx------    1 502      root            33 May 11 08:49 pre-commit
-rwx------    1 502      root            29 May 11 08:54 two

$ docker stop shfmt-cp-test
```

Copy them via SSH/SCP (the password is `root` for the example below):
```console
$ docker run -p 2222:22 --rm -d --name shfmt-ssh-test testcontainers/sshd:1.2.0

$ ssh-keygen -t ed25519 -N '' -f id_ed25519
$ ssh-copy-id -p 2222 -i id_ed25519 -o PreferredAuthentications=password -o PubkeyAuthentication=no -o PasswordAuthentication=yes -o StrictHostKeyChecking=no -o 'UserKnownHostsFile=/dev/null' root@localhost
$ ssh -p 2222 -i id_ed25519 -o StrictHostKeyChecking=no -o 'UserKnownHostsFile=/dev/null' root@localhost
# exit

$ shfmt -f=0 /tmp/test | xargs -0 -I {} scp -P 2222 -i id_ed25519 -o StrictHostKeyChecking=no -o 'UserKnownHostsFile=/dev/null' -q -C "{}" root@localhost:/tmp

$ docker exec shfmt-ssh-test ls -l /tmp
total 12
-rwx------    1 root     root            27 May 11 09:52 one.sh
-rwx------    1 root     root            33 May 11 09:52 pre-commit
-rwx------    1 root     root            29 May 11 09:52 two

$ docker stop shfmt-ssh-test
```

Note in all cases `pre-commit` was copied over also.

Now one could add an entry to `.editorconfig` :

```
[.githooks/**]
ignore = true
```

But where should we place it?

If we put it inside the repo then the githooks will not be formatted/checked—which is suboptimal.

We could place it outside of the repository but then we would have to remember to always execute the commands from a place where this `.editorconfig` is queried.

For ad hoc copies one would have to edit the global `.editorconfig` beforehand and not forget to remove the entry unless you want your global config cluttered.

`rsync` has an `exclude` flag so we could filter them on that end but neither `docker cp` nor  `scp` have such a flag.

---

`shfmt -f=0 --ignore .githooks` or `shfmt -f=0 --ignore '.githooks/**'` would be much better.
