### ISSUE TITLE
broken indentation

### ISSUE THREAD

**Issue by mattn** [mvdan/sh#11]
input
```sh
cat foo.txt | while read line; do
	echo 1
done
```
output
```sh
cat foo.txt | while read line; do
		echo 1
	done
```

**Comment by mvdan** [comment]
That is by design, though - one level comes from the binary expression (pipe), another from the while statement.

This might be clearer if you do:

```sh
cat foo.txt \
    | while read line; do
        echo 1
    done
```

**Comment by mvdan** [comment]
By "this might be clearer" I mean that you might see where the indentation levels come from easier. Not that it's a better way to style your code.

**Comment by mvdan** [comment]
Then again, it makes sense to only stack the two indentation levels if on separate lines like in my example, but not in yours. Will see if it can be fixed.

**Comment by mattn** [comment]
I don't have strong objection. :)
But I know some people who use my indentation.

https://github.com/search?l=&q=while+read+done+language%3AShell&ref=advsearch&type=Code&utf8=%E2%9C%93

Or another one.

```sh
cat foo.txt | while read line
do
  echo 1
done
```

**Comment by mvdan** [comment]
Yeah, I was just playing around with it and yours makes more sense. I just need to tweak the indentation of binary expressions to only take place if they are on a separate line.

**Comment by mvdan** [comment]
I have the fix, but this new method is bringing with it tons of little indenting issues that I want to fix before pushing.

**Comment by mvdan** [comment]
@mattn very similar issue, which do you think is better?

```sh
if foo \
                && bar; then
        bar
fi
```
```sh
if foo \
        && bar; then
        bar
fi
```

I like the former because you can easily tell the condition from the actual block, but not sure about it.

**Comment by mvdan** [comment]
Went for the former, already implemented.

**Comment by mattn** [comment]
Hmm, I prefer your second in above. btw, typing `gg=G` on vim, seems wrong :-(

```sh
if foo \
	&& bar; then
bar
fi
```

**Comment by mvdan** [comment]
I've given up using vim for reference as far as this project goes, there is weirdness everywhere:

```sh
x | while a; do
b
        done

        (
        foo
        )
```

As for condition continuations, `gofmt` goes with the second option. So not sure what to do again.

**Comment by mvdan** [comment]
Reverted to old behaviour in e5c8092aed224bbfdd0d8131c0042f61a8c2c5f4.
