### ISSUE TITLE
syntax: declare assignments break following clauses

### ISSUE THREAD

**Issue by paulbellamy** [mvdan/sh#110]
For example, the following script complains:
```
#!/bin/bash

local foo=bar
local baz=something
while true; do
  sleep 1
done
```

`example:5:13: "do" can only be used in a loop`

If you add semicolons after the local vars, it works (but removes the semicolons, so next time it breaks).

**Comment by mvdan** [comment]
You're right - thanks for spotting!

Smaller repro:

```
declare a=b
{ x; }
```

The good news is that this is not a bug in `v1` nor in `v1.3.0`. So I'll fix this in master, but for now you can just stick to the stable.
