### ISSUE TITLE
shfmt still complains that " &> redirects are a bash/mksh feature" although it parses the script as bash

### ISSUE THREAD

**Issue by coiby** [mvdan/sh#1102]
## Problem
shfmt makes the following complaint,
```
&> redirects are a bash/mksh feature (parsed as bash via -ln=auto)
``` 
which doesn't sound reasonable to me because the script is already parsed as bash

## How to reproduce it
```bash
cat << 'EOF' > test.sh
#!/bin/bash
echo test 1 &>2
EOF


cat << 'EOF' > .editorconfig
root = true

[*]
shell_variant = posix
EOF

if ! shfmt -d test.sh; then
    echo "test failed"
fi
```

**Comment by mvdan** [comment]
Thanks for reporting this. As far as I can tell, the behavior in terms of parsing is correct - `shell_variant = posix` is applied from EditorConfig like a `-ln=posix` flag, so you are actually parsing in POSIX mode. It's the error message which is wrong and very confusing. I've fixed that now.

**Comment by coiby** [comment]
Thanks for coming up with a fix quickly! 

I have one question. In the reproducer, the shebang is `!/bin/bash`. So do you imply EditConfig will overwrite  shebang?
