### ISSUE TITLE
A compatibility option feature

### ISSUE THREAD

**Issue by ayii0111** [mvdan/sh#1105]
Could an option be added that allows VSCode to ignore errors detected in code and continue formatting other parts?
Otherwise, when I use it to format zsh scripts, sometimes the syntax is actually correct, but shfmt marks it as erroneous, which prevents the remaining code from being formatted.

**Comment by mcabansag** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by mvdan** [comment]
Sorry but no. This would significantly overcomplicate the program's code and UX. The solution is to add the missing features (zsh) and fix any bugs causing these issues.
