### ISSUE TITLE
curl cmd parse unexpected

### ISSUE THREAD

**Issue by McDaddy** [mvdan/sh#1111]
my input is `curl https://www.xxx.com?a=1&b=2`
the parse result turns into two statements
1. curl https://www.xxx.com?a=1
2. b=2

I think it's not expected. Can someone please help?

**Comment by cafebeef1** [comment]
The parse result is correct, you can run `set -x` before curl commands. If you want to run curl with query string, you should add `\` before `&`: `curl https://www.xxx.com?a=1\&b=2`

**Comment by cafebeef1** [comment]
> my input is `curl https://www.xxx.com?a=1&b=2` the parse result turns into two statements
> 
> 1. curl https://www.xxx.com?a=1
> 2. b=2
> 
> I think it's not expected. Can someone please help?

The parse result is corret. you can try it with `bash` and add `set -x` before run `curl https://www.xxx.com?a=1&b=2`. If you want to run curl with query string, add `\` before `&`: `curl https://www.xxx.com?a=1\&b=2`

**Comment by theclapp** [comment]
`&` normally runs a command in background, e.g. you may've seen `some_command &`. The `&` in your command was interpreted as that operator.

See the bash manpage [here](https://www.man7.org/linux/man-pages/man1/bash.1.html#:~:text=If%20a%20command%20is%20terminated%20by%20the%20control%20operator%20%26%2C%20the%20shell%0A%20%20%20%20%20%20%20executes%20the%20command%20in%20the%20background%20in%20a%20subshell).

As @cafebeef1 said, you can escape the `&` itself (e.g. `\&`) or quote the whole url, `curl "https://www.xxx.com?a=1&b=2"`
