### ISSUE TITLE
syntax: redirection to process substitution is broken

### ISSUE THREAD

**Issue by mmlb** [mvdan/sh#116]
```sh
[manny@manny shfmt]$ git describe --always
v1.3.0-137-g8be04b0
[manny@manny shfmt]$ shfmt --version
v2-devel
[manny@manny shfmt]$ shfmt <<'EOF'
> foo  \
>         1> >(echo stdout ) \
>         2> >(echo stderr )
> EOF
foo \
        1>>(echo stdout) \
        2>>(echo stderr)
```

**Comment by mmlb** [comment]
some more process substitution borkedness:
```sh
[manny@manny shfmt]$ ./shfmt <<'EOF'
cat afile | foo 2> >(cat somefile) | \
bar
EOF
cat afile | foo 2> >(cat somefile) |
bar
[manny@manny shfmt]$ ./shfmt <<'EOF'
cat afile | foo 2>somefile | \
bar
EOF
cat afile | foo 2>somefile |
        bar
[manny@manny shfmt]$ ./shfmt <<'EOF'
foo 2> >(cat somefile) | \
bar
EOF
foo 2> >(cat somefile) |
        bar
```

**Comment by mvdan** [comment]
> v1.3.0-137-g8be04b0

Running master, my man :) Thanks for helping with the testing, honestly.

**Comment by mvdan** [comment]
I'm not sure I understand the ones in your second post. If you still find breakage after the fix, please open a separate issue as it would be a separate bug.

**Comment by mvdan** [comment]
Ah, here's one I could understand:

```
 $ shfmt <<'EOF'
> x | >() | \
> bar
> EOF
x | >() |
bar
```

That needs indenting!

**Comment by mmlb** [comment]
I hadn't actually updated in a while, but I tried master to see if it's been fixed by chance since w/e I was running at.

Yup on the needs indenting, sorry probably should have been a bit more explicit.

**Comment by mvdan** [comment]
Damn, you uncovered a can of worms with that indentation bug...

Basically, the issue is with nested statements within a chain of binary commands. It fucks up the indentation good. The fix won't be trivial.

**Comment by mvdan** [comment]
I'm looking into doing 1.3.1 now and will include the `> >()` fix, but not the other one. The other one is way larger and I'm not 100% sure it will have zero regressions.

**Comment by mmlb** [comment]
yeah I had a suspicion that the indent bug would be bad, sorry (not sorry, it's for the good of the project !)

**Comment by mmlb** [comment]
also once again thanks very much for this shfmt is quite possibly the best thing to sh scripts for me in a while, better than shellcheck even (shellcheck has less *obvious* benefits, I mean code was working just fine with my most likely good env/inputs).

**Comment by mvdan** [comment]
:) glad it's helpful.

In the past I rejected a simplify option like gofmt's `-s`, e.g. to turn `${foo}` into `$foo`, `"\\bar"` into `'\bar'` and `(($x > 2))` into `((x > 2))`. But I'm thinking more and more about it recently. Do you think you'd use that, or would it be too pedantic?

I originally rejected it because you might want the longer versions for consistency in some cases.

**Comment by mmlb** [comment]
yeah I'd definitely use that

**Comment by mvdan** [comment]
Opened a new issue for it; input welcome.
