### ISSUE TITLE
proposal: add simplify (-s) flag to shfmt, take 2

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#117]
Revival of https://github.com/mvdan/sh/issues/34 after more thought and input from others.

Some ideas I'm mostly sure about:

* `${foo:0} -> ${foo}` (all useless slices)
* `${foo//} -> ${foo}` (all useless replacements)
* `${foo:-} -> ${foo}` (all useless defaults)
* `"foo\$bar" -> 'foo$bar'`
* `$((x + $((y - z)))) -> $((x + (y - z)))`
* `$(($x + ${y} + ${z[i]})) -> $((x + y + z[i]))`
* `[[ "$foo" == "bar" ]] -> [[ $foo == "bar" ]]` (don't unquote the right, as that makes it a pattern)
* `$( (stmts) ) -> $(stmts)`

Some that might be too pedantic:

* `[[ ! -z $x ]] -> [[ -n $x ]]` and similar
* `${foo} -> $foo` (where it doesn't change the meaning of the program)
* `foo""bar -> foobar` (removing useless parts of words)

/cc @RalphCorderoy @mmlb @meatballhat @focusaurus @ebfe

**Comment by mmlb** [comment]
I like all of these including the "too pedantic" ones, `${foo} -> $foo` being my most wanted

**Comment by mvdan** [comment]
I too would like that one - but what about when `${foo}` helps with consistency? For example:

```
echo "${foo}"
echo "${bar}_etc"
```

Which would be converted into the less consistent and no longer aligned:

```
echo "$foo"
echo "${bar}_etc"
```

**Comment by mmlb** [comment]
that's my preference and what I currently do. I try to stick to less typing/mental-parsing throughout the script and will only use `${bar}` if it's actually necessary.

I also have the suspicion that many people using `${foo}` think that it's the equivalent of `"$foo"`. I base this on random scripts I see with `${foo}` used for what looks like fs paths and `$baz` for simple variables defined in the script...

**Comment by focusaurus** [comment]
I would not like this one `${foo} -> $foo`. I always use curlies as I generally prefer consistency. I would not like this one `[[ "$foo" == "bar" ]] -> [[ $foo == "bar" ]]` but mostly because it's different than what I am used to and unquoted variables make me nervous.

**Comment by mvdan** [comment]
> but mostly because it's different than what I am used to and unquoted variables make me nervous.

That's more like a subjective reason :) As you said, it's only because it's different than what you're used to and presumably because your eyes are not used to knowing that `[[ $x ]]` is okay. But it's still the same program, just simpler.

I'm still inclined to not do the `${foo} -> $foo` transformation. Even if this simplification would be hidden behind `-s`, I don't want it to have controversial rules that we don't all agree on. If you personally prefer `$foo`, you can always enforce that yourself and `shfmt` won't change it.

**Comment by mvdan** [comment]
Almost all the rules proposed are now done and available in `shfmt -s` (you have to install master). Please test them out and let me know how it works for you.

I skipped the `${foo:0}` and `foo""bar` ones because those can actually make sense sometimes. I've also not simplified `${foo}` as there is no consensus around that, and it's debatable where it always leads to a simpler program.

If you find any bugs, or have any suggestions for more simplifications, please file separate issues.
