### ISSUE TITLE
interp: support evaluation of single commands

### ISSUE THREAD

**Issue by hzlmn** [mvdan/sh#119]
Hi, I am wondering does `interp` package support evaluation of certain Node? It currently possible by creating file chunks, but it seems a bit hacky.

Also there are missing examples of defining env for Runner. I am wondering how i can provide custom env for Runner struct?

Thanks ahead

**Comment by mvdan** [comment]
> support evaluation of certain Node? It currently possible by creating file chunks, but it seems a bit hacky

If you mean feeding it an arbitrary `syntax.Node` instead of a `*syntax.File`, not at the moment. It's crossed my mind, though:

https://github.com/mvdan/sh/blob/cd4317d3fc395d68b2cd839a85c423bce95cbdd6/interp/interp.go#L31

The tricky bit is that not all nodes might be possible, and only `*syntax.File` has all the position info.

What node type were you thinking about in particular?

> Also there are missing examples of defining env for Runner. I am wondering how i can provide custom env for Runner struct?

Well, it's very much a work in progress so there are no examples yet. But I'm pretty much following the method from `os/exec.Cmd`. In particular, `Runner.Env` works in the exact same way. `Runner` has godoc for its fields too.

**Comment by mvdan** [comment]
Bump @hzlmn

**Comment by hzlmn** [comment]
@mvdan Sorry, somehow missed it. Yes, i mean passing syntax.Node instead of full File. It would be great because i need partial evaluation for some nodes in File but not full File.

**Comment by mvdan** [comment]
My question was more towards what specific node type you were thinking of. Most nodes don't make sense on their own, like a single word.

**Comment by hzlmn** [comment]
I was thinking about call expression and function declaration.

**Comment by mvdan** [comment]
Both of those are commands, so I'll look into adding support for lone commands.

**Comment by hzlmn** [comment]
Okay, thank you.

**Comment by mvdan** [comment]
The only problem that comes to mind API-wise is position information. If you're evaluating lone commands, would you still want stuff like interpreter errors to contain valid positions? Because the position information is in the `ast.File` at the moment, so we would need extra machinery to do so.

**Comment by hzlmn** [comment]
It would be nice, but not very critical, basically i need this feature for pre-evaluating of some values and inlining them. Like if i have something like 
``` sh
call_some_func $HOME
```
and then inline it to
```sh
call_some_func "/home/user"
```

**Comment by mvdan** [comment]
I can't come up with a sane way to add this to the API. I was thinking of adding a func like:

```
func Command(cmd syntax.Command) *Runner {
        return &Runner{File: &syntax.File{
                Stmts: []*syntax.Stmt{{
                        Cmd: cmd,
                }},
        }}
}
```

But you can already do that by initialising a Runner yourself.

**Comment by mvdan** [comment]
Bump @hzlmn

**Comment by hzlmn** [comment]
If it not possible or hard to implement  you can close it, i basically achieved it as in your code snippet.

**Comment by mvdan** [comment]
Not impossible or hard, just not particularly useful to add to the API. If we figure out a better API in the future we can come back to it.

**Comment by mvdan** [comment]
@hzlmn now that the position info is self-contained, I've renamed `Runner.File` to `Runner.Node`, allowing `File`, `Stmt` and `Command`. Let me know if that helps.

**Comment by hzlmn** [comment]
@mvdan Great news, gonna give it a try on a weekend. By the way thanks for excellent package support 😄

**Comment by mvdan** [comment]
Package support?

**Comment by hzlmn** [comment]
I mean thank you for constantly improving this package and adding more features :)

**Comment by mvdan** [comment]
:) happy that it's useful.
