### ISSUE TITLE
interp: implement file globbing

### ISSUE THREAD

**Issue by andreynering** [mvdan/sh#123]
Take as example this script:

```sh
touch file.txt
rm *.txt
```

The globbing on the second sentence seems not working on Linux. It's not seeing the file created above:

```sh
$ gosh test.sh
rm: cannot remove '*.txt': No such file or directory
exit status 1
```

Curiously, it works on Windows. The behavior is the expected: you only get this error if no `.txt` file exists.

**Comment by mvdan** [comment]
Globbing is not implemented at all at the moment - see #87. It's tricky because it should only apply to non-quoted parts of words.

I have yet to figure out a way to do this in a sane way. Suggestions (and patches) welcome.

**Comment by mvdan** [comment]
Also, it's possible that on Windows the program (or the operating system) are the ones doing the globbing for you. I'm fairly certain Linux would never do globbing for you in this scenario, as it's left entirely to the shell.

**Comment by mvdan** [comment]
Since this is a basic feature, I've implemented the simplest fix. I'd rather be wrong on `'*.txt'` than on `*.txt`.

**Comment by andreynering** [comment]
@mvdan Thank you!
