### ISSUE TITLE
Consider renaming repo and root package to "gosh"

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#125]
Now that we're about to release 2.0, it's a good time to consider this since we can break the import paths.

Points in favor:

* Easier to google and identify, as `sh` is too short and common
* No longer seems like the package is restricted to POSIX Shell

Points against:

* `gosh` would now be ambiguous, as it would mean both the collection and `cmd/gosh`
* `gosh/syntax` doesn't say "shell syntax package" as well as `sh/syntax` does

Any input appreciated. Of course, old links would keep on working. Old code would break if you weren't vendoring master, but that's already the case since we've broken backwards compatibility for 2.0.

/cc @andreynering @pocke @meatballhat @mmlb @paulbellamy

**Comment by andreynering** [comment]
I would not change that to prevent breaking code/tools that use it, but that's my personal opinion.

`shfmt` seems to be popular, but now `go get github.com/mvdan/sh/cmd/shfmt` will break. It's common in Go projects to have `go get`'s in Makefile's or similar, as example.

That said, I'm fine either way. It won't cause trouble for me personally. 😉

**Comment by mvdan** [comment]
Even in the case of `go get`s, people should still vendor the tool. The behaviour of any of the executables can change in master, or they can just get renamed or deleted.

I know that it can still be a pain for some people, which is why I'm giving this some thought. I'm generally happy with the current name, but some people have complained that the project name is not identifiable/searchable and they do have a point.

**Comment by mmlb** [comment]
I really like just `sh`.

`sh` isn't really synonymous with POSIX shell for me (and seemingly many others if we consider bashisms in `#!/bin/sh` scripts). 

`shfmt` is very googleable, and my hunch is that `shfmt` is more memorable than `gosh format`.

**Comment by mvdan** [comment]
Note that this isn't about the `shfmt` name - the name of the executable program would remain the same.

`shfmt` and `gosh` are googleable for `cmd/shfmt` and `cmd/gosh` at the moment. This issue is about making the whole thing googleable, which now contains paths that aren't very identifiable like `sh/syntax` and `sh/interp`.

**Comment by mvdan** [comment]
Okay, deciding against this - at least for 2.x. Thanks for the input.
