### ISSUE TITLE
shfmt not support arithmetic expressions well

### ISSUE THREAD

**Issue by xdc0209** [mvdan/sh#126]
my bash shell is: 
1 #!/bin/bash
2 
3 current_day=$(( $(date +"%s") / $((60\*60\*24)) ))
4 

and the output is:
XDC@XDC-PC MINGW64 /d/JavaTools/source-code/script-code/linux-shell/bash/shell_lib
$ ./shfmt_v1.3.1_windows_amd64.exe comm_lib.sh
comm_lib.sh:3:17: arithmetic expressions must consist of names and numbers

XDC@XDC-PC MINGW64 /d/JavaTools/source-code/script-code/linux-shell/bash/shell_lib
$

**Comment by xdc0209** [comment]
now I hava seen the Caveats:
> $(( and (( ambiguity is not suported. Backtracking would greatly complicate the parser and make stream support - io.Reader - impossible. In practice, the POSIX spec recommends to space the operands if $( ( is meant. 

Does it mean the problem in my issuse is not supported?

**Comment by mvdan** [comment]
This is different - in 1.x, for a while I decided to forbid `$()` inside arithmetic expressions.

This is reverted in master, which will be 2.0 soon.

For now, you should either run master or a version prior to 1.3.0, which introduces `Disallow some arithmetic expressions like ((1=3)) and (($(echo 1 + 2)))`.

**Comment by mvdan** [comment]
To be extra sure, this is master:

```
$ shfmt <<<'current_day=$(( $(date +"%s") / $((60*60*24)) ))'
current_day=$(($(date +"%s") / $((60 * 60 * 24))))
```
