### ISSUE TITLE
syntax: regression in parsing of "declare"

### ISSUE THREAD

**Issue by cyphar** [mvdan/sh#129]
We just hit this in runc in the past few days. If you run `shfmt` on something like this:

```
export completion_func=_some_func_name
declare -F $completion_func
```

You get this error even though it is entirely valid `bash`.

```
2:12: "declare" must be followed by names or assignments
```

**Comment by mvdan** [comment]
Thanks! Will look into it.

**Comment by mvdan** [comment]
@cyphar just to confirm, you only use `declare ... $var` in the context where `$var` only holds a name like `foo`, correct? You wouldn't do it where `var='foo[0]'` or `var='foo=bar'`, hopefully?

**Comment by cyphar** [comment]
Yeah, it would only be used in cases where it's a name. `declare -F a=b` is not valid (and outputs an error).

**Comment by cyphar** [comment]
`declare -F $var` is only valid if `$var` is a name. However, note that `declare $var` is valid if `var="a=b"`. For example:

```
$ export var="a=b"
$ declare $var
$ echo $a
b
```

**Comment by mvdan** [comment]
I ran the same tests - that's why I'm asking. I think I'll just allow this assuming that `$var` just contains a name no matter what, as otherwise this would be a rabbit hole.

**Comment by cyphar** [comment]
Thanks for the incredibly fast turnaround @mvdan. :smile_cat:
