### ISSUE TITLE
cmd/shfmt: consider adding positions to -exp.tojson

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#135]
So the following:

```
$ shfmt -exp.tojson <<<'echo foo'
[...]
"Parts": [
        {
                "Type": "Lit",
                "Value": "echo"
        }
]
[...]
```

Would become something like:

```
$ shfmt -exp.tojson <<<'echo foo'
[...]
"Parts": [
        {
                "Type": "Lit",
                "Value": "echo",
                "ValuePos": {"Offset": 0, "Line": 1, "Col": 1}
        }
]
[...]
```

Questions to be answered:

* Is this useful? (definitely useful if we ever want to add `-exp.fromjson` to convert back while keeping position info)
* Would we want to simplify this representation somehow, to avoid verbosity? (like omitting the offset)
* Should `Pos` and `End` be included? What about when they're just fields, like in the case of `Lit.Pos() == Lit.ValuePos`?
* Or should we include just `Pos` and `End` and ignore position fields?

For the sake of simplicity, assuming we want to do this, I'd keep all positions - `Pos`, `End` and any fields - even if they are duplicated. The JSON interface is meant for ease of use and integration with other languages, not for performance or brevity.

**Comment by ebfe** [comment]
I've been mostly using this as an debugging aid to quickly see how things are parsed. I don't really miss the positions but see how they could be usefull for other things (syntax highlighting or similar).

One thing worth considering for an potential `-exp.fromjson` is that editing/removing/adding a node in the json likely invalidates all positions/offsets for the following nodes.

**Comment by mvdan** [comment]
> editing/removing/adding a node in the json likely invalidates all positions/offsets for the following nodes.

That applies to modifying the AST directly in Go too.

The printer/formatter uses lines and columns now though, so it's okay-ish. the worst that can happen is that an empty line is inserted.

In v1 (not master), the printer did use offsets, so it did get broken in more ways.

**Comment by ebfe** [comment]
Oh, that's very nice to hear.
