### ISSUE TITLE
interp: add a flag that makes cd do real os.Chdir calls

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#137]
There are several issues in how interp/gosh handles the current working
directory, which i think could be summarized with "cd doesn't actually
chdir()".

One example is that `cd foo` succeeds even if we don't have permissions to enter
that directory. 

```sh
d=${PWD}
rm -rf dir_a dir_b
mkdir dir_a dir_b
touch dir_a/in_a dir_b/in_b
chmod -x dir_b

cd dir_a
echo $PWD
ls

cd ../dir_b
echo $PWD
ls

chmod +x ${d}/dir_b
```

```
$ bash x.sh
/tmp/dirs/dir_a
/tmp/dirs/dir_a
in_a
x.sh: line 11: cd: ../dir_b: Permission denied
/tmp/dirs/dir_a
in_a
```

```
$ gosh x.sh
/tmp/dirs/dir_a
in_a
/tmp/dirs/dir_b
```

Another case is the behaviour when the current directory is renamed/moved:

```sh
d=${PWD}
chmod +x dir_b
rm -rf dir_a dir_a.moved dir_b
mkdir dir_a dir_b
touch dir_a/in_a dir_b/in_b

cd dir_a
echo $PWD
ls

mv ${d}/dir_a ${d}/dir_a.moved
echo $PWD
ls
```

```
$ bash y.sh
/tmp/dirs/dir_a
/tmp/dirs/dir_a
in_a
/tmp/dirs/dir_a
in_a
```

```
$ gosh y.sh
/tmp/dirs/dir_a
in_a
/tmp/dirs/dir_a
```

In both cases the second `ls` fails silently when `os/exec` tries to `chdir` into
`$PWD`. I'm not sure these can be really fixed without `cd` calling chdir
(which would likely also mean forking subshells and only be able to use a
single Runner instance per process)

In theory there's `fchdir`, so interp could keep an open fd to $PWD, but there
is no way to pass that into `os/exec`.

**Comment by mvdan** [comment]
The reason permissions et al don't error is because I coded the basics of `interp` in a week, so I went with happy paths to avoid suicide. There are quite a few edge cases left to treat properly. This is one of the reasons why it's still experimental.

As for chdir, you're correct - the reason why it doesn't actually chdir is because it would limit to a single Runner. And in Go you can't fork AFAICT, so that means one runner per program.

Perhaps we could have a flag to tell the runner whether or not to use "fake" chdirs. I don't think we can habe the best of both worlds without any of the drawbacks.

**Comment by mvdan** [comment]
I've updated the issue with my suggestion above. I'll get to this after 2.0 unless anyone proposes a better idea.

**Comment by mvdan** [comment]
@ebfe do you have any input on the suggestion above? Still thinking about it, still leaning towards doing it but not 100% sure it's a good idea.

**Comment by ebfe** [comment]
Without os/exec providing a way to pass a fd as current dir I don't see a good
solution.

Actually doing the chdirs is likely fine for implementing a shell, even if
opening subshells then becomes more complicated. Not sure about other usecases.
A good middleground for now might be to check permissions on cd. That's still
racy and doesn't catch all cases, but it might be good enough until something
better comes along?

Another idea that crossed my mind recently: Could interp defer all filesystem
access and relevant syscalls (execve, chdir) it does to an interface? That way
one could experiment with different execution models and provide a way to
implement, for example, the windows /dev/null override outside of the core.

**Comment by andreynering** [comment]
Just my personal opinion.

This may have it use cases, but if done, this should be optional and not enabled by default.

As an alternative, wouldn't this work for you? Change the dir after the runner finished.

```go
r := interp.Runner{...}
_ = r.Run(...)
_ = os.Chdir(r.Dir)
```

**Comment by mvdan** [comment]
@ebfe I completely forgot about subshells. Not even using a single Runner per process would allow subshells to just work.

I guess I could work around the issue by implementing some sort of internal scheduler of subshells, that kept track of their directories and other per-process state. Basically, emulating processes. That is quite a bit of work though, so I don't know whether or when I'd do it.

Your idea on "pluggable" interfaces for system stuff is interesting. It would actually be quite powerful. You could replace the actual disk with a fake filesystem, for example. Or ban the use of certain commands like su and sudo.

@andreynering of course, all of this would be optional. By default, the interpreter should be as close to Bash and as simple as possible.

One question that @ebfe raises whether tweaks for non-unix compatibility should also live in one of these modules, like the one for /dev/null. I'm starting to think they should - and they could be provided by this family of packages too.

I'm on the phone now, so I'll give this a think and I'll open the appropriate design issues once I'm on the laptop again. Thank you both!

**Comment by mvdan** [comment]
As said above, real chdir calls don't make much sense. Closing this; will be opening new issues for the ideas discussed above.

**Comment by mvdan** [comment]
> A good middleground for now might be to check permissions on cd. That's still
> racy and doesn't catch all cases, but it might be good enough until something
> better comes along?

Note that `cd` now checks if the path is a directory now - 318a1b7ec634f3ef293d26d413558e972d3f241a. I haven't gotten to permissions yet, will open an issue.
