### ISSUE TITLE
interp: redirect to /dev/null don't work on Windows

### ISSUE THREAD

**Issue by andreynering** [mvdan/sh#140]
```sh
$ gosh -c "echo foo > /dev/null"
exit status 1
```

Maybe gosh should force any redirect to `/dev/null` to an `ioutil.Discard` instead? Maybe even on Unix-like systems for performance?

**Comment by mvdan** [comment]
I've thought about this kind of unix-like compatibility. Basically, all of `/dev/` isn't portable at all.

But it doesn't stop there. What about path separators? As in `foo/bar` instead of `foo\bar`. Do you know how Bash on Windows deals with these?

**Comment by andreynering** [comment]
> What about path separators? As in foo/bar instead of foo\bar. Do you know how Bash on Windows deals with these?

Git Bash on Windows doesn't work with backslash (`\`) on Windows, only regular slash (`/`) just like Linux.

I think you don't need to port all `/dev/*` files to gosh, just the most common. I don't have a lot of knowledge of Unix-systems, but maybe these are enough?

* `/dev/null`
* `/dev/stdin`
* `/dev/zero`

**Comment by mvdan** [comment]
Handling the common cases in redirects would probably fix a good chunk of the scripts. But this wouldn't be a proper solution. What about `cat /dev/zero`, for example? How do you know if a slash is part of a path versus part of a string used in another way?

I'll open a separate, broader issue about this.
