### ISSUE TITLE
interp: consider portability of Linux and Unix-isms

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#141]
A lot of the shell scripts nowadays do some or all of the following:

* Hard-code `/` as a path separator
* Make use of `/dev/` and `/proc/`, e.g. `/dev/null` and `/dev/urandom`
* Use `./foo` to call binaries in the current directory

This will break with `interp` on Windows, most notably.

The current solution to this is doing nothing about it. It's up to the shell script to be portable.

A slightly better version of this solution would be to provide some helper funcs like `filepath.Join`. This way, shell scripts could be updated to be more portable. Would require work from the user's side, though.

Then we have the option to automatically translate/emulate Linux/Unix-isms to other systems like Windows. This is sort of what Bash on Windows does. What it does (I think) is translate system calls, so at the low level, when one opens the file `foo/bar`, it actually opens `foo\bar`.

Unfortunately, we can't do the same as we don't have control over the system calls. In the case of path separators, we could try to replace them while interpreting a program, but this would break strings that weren't paths like `echo "foo / bar"`.

I'm not convinced there's a clean, good solution to this. Input and suggestions are very welcome.

/cc @andreynering, re #140

**Comment by andreynering** [comment]
Note that many programming languages, including Go, accept both `\` and `/` as path separator on Windows.

So as example, this will work only on Windows:

```go
f, err := os.Open("path\\to\\file")
```

But this works everywhere, including on Windows:

```go
f, err := os.Open("path/to/file")
```

This means that relative paths are already working on gosh, including calling an executable as your example:

```go
./binary
```

The only things missing are:

1) Absolute path. It understands `C:\` and `C:/`, but not `/`
2) `/dev/*` files

About (1), maybe scripts should handle it. About (2), maybe it's only possible to cover the most simple cases (`/dev/null`, etc).

**Comment by andreynering** [comment]
I didn't tried it, but I'm thinking in something like this for `/dev/null`:

```go
type DevNull struct{}

func (DevNull) Read(r []byte) (int, error) {
	return 0, io.EOF
}

func (DevNull) Write(w []byte) (int, error) {
	return len(w), nil
}

func (DevNull) Close() error {
	return nil
}
```

**Comment by mvdan** [comment]
> This means that relative paths are already working on gosh, including calling an executable as your example:

Wow, I didn't know this. If that's the case, then why is `filepath` even a thing? Or is this automated only in certain calls like `os.Open`?

> Absolute path

I'm afraid this falls under the same category as file separators. I would think that if the `os` package handles separators, it would also handle this.

Also, what makes `C:` the root one and not, say, `D:`? Sorry, I haven't used Windows in nearly a decade.

> maybe it's only possible to cover the most simple cases (/dev/null, etc)

I agree, but that seems like complicating things a bit. For example, `</dev/zero` will work, but `cat /dev/zero` won't. And the same for programs that themselves open these files, but the shell code never sees the paths to swap them out.

I think not doing anything about this (`/dev` and `/proc`) is cleaner and simpler than having parts of it work sometimes. I know this is not the answer you're looking for short-term, but I'm thinking more long-term.

**Comment by andreynering** [comment]
> Wow, I didn't know this. If that's the case, then why is filepath even a thing? Or is this automated only in certain calls like os.Open?

`filepath` does more than that. Sure there's `filepath.ToSlash` and `filepath.FromSlash` that's called automatically on funcs like `os.Open`, but there are other useful things there.

> I'm afraid this falls under the same category as file separators. I would think that if the os package handles separators, it would also handle this.
>
> Also, what makes C: the root one and not, say, D:? Sorry, I haven't used Windows in nearly a decade.

Both `C:\` and `D:\` are roots, of different disks (you can also have `E:\`, `F:\` and so on). This would make it complicate to translate `/` to something else on Windows, and the reason I think gosh should not try to handle it.

> I know this is not the answer you're looking for short-term, but I'm thinking more long-term.

No problem, that was just a suggestion. 👍

**Comment by mvdan** [comment]
I'm going to keep this open for now. This has been in the back of my mind for a while. I'm actually surprised that the `interp` package works OK for windows most of the times.

I do see how there's no better, portable way of using stuff like `/dev/null` and `/dev/urandom`, so I'm not completely against emulating those under some specific circumstances like redirects. Perhaps there's no better solution than to have this special rule and document it well, as well as document the limits of `interp`'s portability well.

@andreynering if you can come up with a small PR - say, just for `/dev/null` - and confirm that it works for your use-case, we will be in a better position to decide whether this complexity tradeoff is worth it.

**Comment by andreynering** [comment]
I just did a simple test to see how Go handle root with `/` on Windows:

```go
f, err := os.Open("/root.txt")
```

The above code looks for the root of the working directory.

- If WD is `C:\some\dir` it will look to `C:\root.txt`
- If WD is `D:\some\dir` it will look to `D:\root.txt`
- And so on...

This seems reasonable to me, and means Gosh actually already work with absolute dirs.

**Comment by mvdan** [comment]
That's good. I thought it would be weird if `os` handled separators but not root paths. That's even better than us hard-coding `C:`.

**Comment by andreynering** [comment]
You may be curious to know the output of tests on Windows:

- [On Git Bash](https://gist.githubusercontent.com/andreynering/2c0fc441f5db5b89d60d69c03c0a4e4e/raw/9267d4cf28532d681b16540f28024ef35f25e4d1/git-bash.log)
- [On cmd](https://gist.githubusercontent.com/andreynering/2c0fc441f5db5b89d60d69c03c0a4e4e/raw/9267d4cf28532d681b16540f28024ef35f25e4d1/cmd.log)

Please don't try to fix that! Many of these failures, it seems, because Git Bash behaves intentionally different than on, say, Ubuntu. It does the minimum required to Git work on Windows.

Despite that, gosh works very well on Windows, at least for simple use cases.

**Comment by mvdan** [comment]
@andreynering I honestly don't have the time nor interest to test things on Windows right now. I'm happy to hear that things mostly work there. I have no plans to add specific fixes for Windows myself for that very reason - not even testing on that platform yet.

If anyone (you?) is interested, I'd be open to pull requests and adding some sort of CI for it, like AppVeyor. But it seems like the tests would need quite a bit of work first.

About the same goes for exotic unix-like systems like Plan9 and even Mac - I'm not testing on those, and I don't know if all the tests would pass.

**Comment by andreynering** [comment]
@mvdan I'm not asking you to fix tests on Windows. I know it's a lot of work, don't worry about it. =)

I'll maybe take a look to improve some tests when have some time, but maybe impossible to have 100% pass. First thing would be skip the [confirm test](https://github.com/mvdan/sh/blob/master/interp/interp_test.go#L1202) if bash is not available in the path.

CI would be nice, but only if we ever get tests minimally working.

**Comment by mvdan** [comment]
Sure - let me know if you need help with that, if you ever work on it.

**Comment by mvdan** [comment]
@andreynering so I've been thinking about this more, especially since the recent `os/user` discussion, and I'm wondering if supporting bare Windows (instead of just Bash on Ubuntu on Windows) is worth it.

Of course it would be awesome if it were to work, but it just can't work reliably. Paths and `/dev` are just one example. I'm sure we would find more; Unix shells are called that for a reason.

I think our best course of action is to officially support Ubuntu on Windows (once we adapt the tests to work there too) as just another `GOOS=linux`, and to experiment with bare Windows if anyone has the time and machines to do so (such as yourself). But I would not say that we support bare Windows, at least now.

Is there a way to get a CI running Bash on Ubuntu on Windows? We'd need that to do stable releases with its support.

**Comment by andreynering** [comment]
Tests passes fine on Ubuntu Bash. I wouldn't setup a CI for it because if tests passes on regular Ubuntu (Travis), it will likely passes on Ubuntu Bash, too.

---

I then have a proposal:

- Keep using CGO and `os/user`. That's not terrible, I've even being able to make Windows builds from Ubuntu since (I think) `os/user` don't use CGO on Windows
- Use build tags to have no-op functionality on non-unix system for `syscall` calls

---

Otherwise, if you don't want to support Windows, I'm fine with that, I don't want to consume much of your time. In that case, I'd create a fork, to update upstream from time to time and fix any problem on Windows by doing the proposed above.

**Comment by mvdan** [comment]
> Tests passes fine on Ubuntu Bash

You showed errors above (`on Git Bash`) - what are those from? That's why I was thinking of a CI.

> Keep using CGO and os/user.

I honestly don't know too well how libraries depending on CGO (and in particular the ones in `std`) will behave with `CGO_ENABLED=0`, or if built in a way (e.g. cross-compiled) that won't allow dynamic linking to libc et al. So perhaps trying to remove it is premature.

> Use build tags to have no-op functionality on non-unix system for syscall calls

Of course.

> Otherwise, if you don't want to support Windows, I'm fine with that, I don't want to consume much of your time. In that case, I'd create a fork, to update upstream from time to time and fix any problem on Windows by doing the proposed above.

I think the best scenario would be for the core to assume unix-like, and for anyone interested (such as yourself) to work on modules to improve support on Windows. They could patch some things, such as replacing `/dev/null` in redirects.

That way, I don't have to guarantee that the interpreter will work on Windows, but you can submit improvements and they can be kept here in the main repository. And you could have something like a helper to simplify enabling all of these Windows-specific add-ons.

**Comment by andreynering** [comment]
Git Bash != Ubuntu Bash

Ubuntu Bash from Microsoft is an complete Ubuntu environment inside Windows. Most non-gui Linux programs should work there.

When you install Git on Windows, it comes with a shell where basic Unix tools are available (but compiled for Windows), because Git require those. This includes sh, bash, mkdir, touch, find, etc, etc. This is the "Git Bash".

---

Build tags to protect syscall + interfaces for things like /dev/null are enough for me.

**Comment by mvdan** [comment]
Oh I see, I didn't know you could install some coreutils on Windows. Thanks for the clarification.

**Comment by mvdan** [comment]
I think the modules are a nice solution to this. By default, the interpreter doesn't do any magic to try to make linux and unix stuff work elsewhere. But we can keep adding more extra functionality to add little pieces of glue.

I'm going to close this, as this was just a discussion issue.
