### ISSUE TITLE
v2.0-beta1: printer_test.go:447: open canonical.sh: no such file or directory

### ISSUE THREAD

**Issue by cheako** [mvdan/sh#145]
> --- FAIL: TestPrintMultiline (0.00s)
> 	printer_test.go:447: open canonical.sh: no such file or directory

I looked at the Travis logs and I think you should turn on some extra output as there is no indication of what tests are run.  I'll keep looking at my environment.

**Comment by mvdan** [comment]
Where did you find this error, exactly?

**Comment by cheako** [comment]
```dh_auto_test -O--buildsystem=golang```
If I remove obj-i686-linux-gnu/src/github.com/mvdan/sh/syntax/printer_test.go this test passes and indeed this folder does not contain the canonical.sh file.
I've also reproduced this via the internal command:
```cheako@debian:~/src/sh$ GOPATH=`pwd`/obj-i686-linux-gnu go test -v -p 4 github.com/mvdan/sh/cmd/gosh github.com/mvdan/sh/cmd/shfmt github.com/mvdan/sh/fileutil github.com/mvdan/sh/interp github.com/mvdan/sh/syntax```

**Comment by mvdan** [comment]
To clarify, this test is passing both locally and on Travis.

It's failing for you beause the file `syntax/canonical.sh` (relative to the root of the repo) was removed. Do you know why that would be? It's there in git.

I could make the test be skipped if the file doesn't exist, but that kind of beats the purpose of the test. Same goes for deleting `printer_test.go` entirely.

**Comment by cheako** [comment]
There was a dh option for this use case.
