### ISSUE TITLE
interp: make pieces of the interpreter modular and replaceable

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#147]
Right now the interpreter is somewhat configurable, but not very much. For example, if I wanted to make it so that direct calls to `su` and `sudo` are forbidden, it cannot be done with the interpreter at the moment.

The idea is to make pieces of the interpreter pluggable via interfaces, with at least one implementation - the one with the current behavior, for example.

Then we - or other packages - could provide other implementations with different characteristics.

Some ideas:

* Directory handling, i.e. `cd` (and possibly `pushd` and `popd` too)
  - Now entirely mocked, no real `os.Chdir` calls
  - Could provide an alternative with real `os.Chdir`
* Filesystem access
  - Now just uses `os.OpenFile` (and mocks `/dev/null` for Windows)
  - The compatibility stuff should be moved to an alternative implementation, to keep the defaults simple
  - Could this apply to paths that we don't open directly, like `prog-that-opens /dev/null`?
* Command execution
  - Current version just uses `exec.CommandContext`
  - Alternatives could be useful e.g. to whitelist or blacklist what programs are allowed
* Environment variables
   - Current version is fairly simple with maps
   - Not sure why alternatives would be useful, but could be interesting (e.g. persistent storage, running hooks on certain sets/gets, etc)
* Node interpretation
   - Currently, as we walk each node, we only interpret it
   - Extra code could be added, for example to implement `set -x`

I'm not thinking about the interfaces just yet, but they should be as simple as possible. Ideally, there would be an easy way to layer them too. Perhaps encapsulating via an anonymous field and doing it manually would be enough.

/cc @ebfe @andreynering

**Comment by mvdan** [comment]
Ah yes, builtins would be included. Basically, all simple commands, of the form "arg0 arg1 arg2 ...".

We would have to expose "is this string a builtin" and "execute this builtin", so that the default implementation would be something like:

```
if IsBuiltin(cmd) {
    return ExecBuiltin(cmd, args...)
}
cmd := exec.CommandContext(...)
...
```

Technically, a simple command is like `[name=val ...] [arg ...]`, so assignments are also part of it. But I think we should skip them from this interface.

**Comment by mvdan** [comment]
Apologies for dropping the ball on this one a bit - been busy with other projects and real life. Will start adding stuff soon.

**Comment by mvdan** [comment]
The exec and open modules are now in master. @andreynering I have moved your `/dev/*` stuff to the non-default open module, so we can maintain it there. If you update your vendored interp copy, be sure to enable the module or you'd undo your `/dev/null` thing.

I don't know what other module I could add next. Suggestions welcome.

**Comment by andreynering** [comment]
> Apologies for dropping the ball on this one a bit - been busy with other projects and real life. Will start adding stuff soon.

@mvdan You don't need to apology. Also, thanks again for your great work to OSS. :)

I just have a little doubt: is the exec module also intended to override buildins, or you plan to add another module for buildins?

That said, I think these modules would be enough for me.

---

I have a small suggestion, but it's more cosmetic than useful.

Maybe you should consider use interfaces instead of funcs for modules. If one want to just write a function, the package can export a helper type to make the function implement the interface. [http.HandlerFunc](https://golang.org/pkg/net/http/#HandlerFunc) is an example of this pattern in the stdlib.

**Comment by mvdan** [comment]
> you plan to add another module for buildins?

I think they should be different modules. To make builtins a module, I would likely need to refactor how they work to make for a nice interface.

> Maybe you should consider use interfaces instead of funcs for modules.

What would the advantage be? One can use methods as funcs too, so you could do `r.Exec = foo.execImpl`.

In my opinion, an interface here would only be worthwhile if a module needed multiple methods. But as far as I can see, all modules should be okay with just a function signature. So it seems unnecessary to add the extra boilerplate for interfaces.

**Comment by andreynering** [comment]
That end up being personal preference, but I'm fine with function signature.

**Comment by mvdan** [comment]
Done a few of these for 2.1 - moving to 2.2.

**Comment by mvdan** [comment]
I'm going to do variables next. That one will very likely need an interface, as you need many operations like set, unset, and delete. At that point, I'm likely going to make the rest of the modules be interfaces too.

**Comment by mvdan** [comment]
Variables were done in https://github.com/mvdan/sh/commit/51b208bb5455b7d4c59453427ae2900005b2862f a while ago.

I won't do other parts of the interpreter, for now. If people have suggestions for other pieces that would be nice to have, please open a new issue and I'll be happy to take a look.
