### ISSUE TITLE
interp: cd should check if the dir has the right permissions

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#148]
I believe we only need execute permissons for the current user to `cd` to the directory.

As suggested in https://github.com/mvdan/sh/issues/137#issuecomment-320436970.

CC @ebfe

**Comment by andreynering** [comment]
@mvdan `os/user` packages seems to be Unix (Linux?) specific:

```sh
$ go get -u -v github.com/mvdan/sh/...
github.com/mvdan/sh (download)
github.com/mvdan/sh/syntax
github.com/mvdan/sh/interp
github.com/mvdan/sh/cmd/shfmt
# github.com/mvdan/sh/interp
..\..\mvdan\sh\interp\builtin.go:166: undefined: syscall.Stat_t
```

One possible solution is to use build tags to only check that on Linux, but that won't solve another problem `os/user` adds: it's not easy to cross-compile because that package uses CGO.

**Comment by mvdan** [comment]
I'm not sure what can we do without relying on CGO then. It seems like our only solution is to actually try to enter the directory, even if we're using fake chdirs.

I'm thinking a worker goroutine just for this, that would try to enter the dir, record the error and immediately return to the original directory if the dir was changed. Overhead should be minimal, it should be entirely portable and it should have zero CGO as it would only be using the `os` package.

Thoughts, @ebfe @andreynering?

**Comment by andreynering** [comment]
Seems that it would introduce a race condition?

I also don't know how to do that. My only (not optimal) idea is introduce a `cgo` build tag. That should also guard Linux (also Mac?) since that syscall func do not exists on Windows.

**Comment by mvdan** [comment]
> Seems that it would introduce a race condition?

Not if it's all done sequentially in a worker goroutine - that's what I meant by `worker goroutine for this`. Potentially this can be a bottleneck, but given that this is a shell interpreter anyway, I'd say it will be fine - most programs will not use concurrency.

I do keep cgo guarded by tags as an option, but I don't like that option much. It would only add the feature for some systems, it would still require cgo and it's hard to tell if it would be correct. On the other hand, actually trying to `chdir` will give us exactly what we want on all platforms.

**Comment by andreynering** [comment]
> Most programs will not use concurrency

Task uses concurrency to run multiple shell scripts in parallel. I think calls to `filepath.*` methods can also suffer from a race condition, since some of them check the current directory.

Just a thought, I know this is very unlikely. Maybe this is the best option until we have a better idea.

**Comment by mvdan** [comment]
Ah, I see what you mean. I was thinking of `chdir` races, but if the real current directory can be anything, other stuff that uses it might break.

Still open to suggestions on how to do this. For now, not checking permissions seems to me like a better idea than relying on cgo or breaking programs in unpredictable ways.
