### ISSUE TITLE
shfmt: exit non-zero if stdout produces alterations

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#149]
In order to integrate shfmt into Continuous Integration systems, it would be helpful if shfmt exited with a non-zero status when style changes are recommended, and `-w` is not supplied.

**Comment by mvdan** [comment]
I believe https://github.com/mvdan/sh/issues/122 will be sufficient. That mode can be made to give an exit code depending on whether or not the diff is empty.

**Comment by mvdan** [comment]
I think `-d` with exit codes will be sufficient as said above, so I'm closing this as a dup.
