### ISSUE TITLE
cmd/shfmt: treats symlinks to directories as files when walking

### ISSUE THREAD

**Issue by soulshake** [mvdan/sh#152]
Reproduced in [this sample repo](https://github.com/soulshake/tmp-shfmt-symlink-issue):

```
$ shfmt .
open dir1/dir2: is a directory

$ echo $?
1
```

**Comment by mvdan** [comment]
Seems like the root cause is that `filepath.Walk` does an `lstat` instead of a `stat`, so it doesn't follow symlinks. Will review the PR, thanks!
