### ISSUE TITLE
syntax: want to indent switch cases like in v1

### ISSUE THREAD

**Issue by uli42** [mvdan/sh#155]
This code

```
    case x in
        a)   v1=1;;
        b)   v1=2;;
        c)   v1=4;;
    esac
```

becomes this

```
case x in
a) v1=1 ;;
b) v1=2 ;;
c) v1=4 ;;
esac
```
when run with `shfmt -i 4` (2.0beta1).

My personal preference is to indent the lines with the patterns and I think that most people prefer it that way.

**Comment by ebfe** [comment]
#101

**Comment by mvdan** [comment]
Thanks for opening the issue. I decided not to add an option for this, but I wasn't 100% sure it was the right decision. I simply defaulted to not adding more options unless it was clearly necessary.

@ebfe's point was larger diffs when updating from v1 to v2. I understand @uli42's point is simply preference of formatting. Some popular style guides like Google's also indent cases.

I'm still not a fan of adding more options - I wouldn't want to add more, like for placing `then` and `do`s on separate lines - but I feel like not adding this option would discard far too many people.

Unless anyone disagrees, I'll add an option to indent cases (v1 behavior) in the first v2 release.

**Comment by uli42** [comment]
An option is perfectly fine for me. But you could also add some kind of heuristic on the source file to determine the preferred style.

**Comment by mvdan** [comment]
That's an interesting idea. However, being able to force a specific style is also useful, so the option should be there.

Perhaps I could add the heuristic for 2.1 or a later version, but I'm not sure exactly how it would work. If you have an idea of how it would, feel free to open an issue and describe it.

**Comment by mvdan** [comment]
Thanks all. Pinging @z0mbix who I think was also in favor of the option.
