### ISSUE TITLE
interp: avoid os/user to avoid depending on cgo

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#157]
Unfortunately, that package depends on cgo (for libc and others). We only use it to fetch the current user's home directory, at the moment.

/cc @andreynering

**Comment by andreynering** [comment]
Seems that [go-homedir](https://github.com/mitchellh/go-homedir) solves this. I don't know if you're fine using packages outside stdlib.

This don't helps with the permission issue, though.

**Comment by mvdan** [comment]
I recently added a package outside of the stdlib in `cmd/gosh` for the interactive shell, so it would be okay.

Also worth mentioning that the build works with `CGO_ENABLED=0` (and the tests seem to pass too), so I'm not sure if an external dependency is necessary.

**Comment by mvdan** [comment]
On second thought, `go-homedir` on Unix just does `$HOME`, `getent passwd` and `sh -c 'cd && pwd'`. These seem OK for regular programs, but they seem particularly bad for a shell.

* We're a shell, `HOME` may not be set - we are the one to set it
* I guess `getent` is an option?
* We can't rely on another shell either

So I think we would probably roll this on our own, if we want to drop `os/user`.

**Comment by mvdan** [comment]
Clarification on the first point - I forgot that you can overwrite `HOME` for a shell, like:

```
$ HOME=/foo bash -c 'echo $HOME'
/foo
```

So the `HOME` check is still valid.

**Comment by mvdan** [comment]
We're keeping CGO for now - we're using it for other things too, such as getting a directory's owner. We can come back to this if using CGO by default ever becomes an issue.
