### ISSUE TITLE
interp: support TimeClause (time keyword)

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#159]
A regression of some sort, as before we used to parse and interpret this as a command and run `/bin/time`.

See https://github.com/go-task/task/issues/67.

**Comment by mvdan** [comment]
Here's a good question - how do we get the CPU and system times? Elapsed time is trivial, of course.

Also note that we may time just a command or any program, like `time { for i in {1..1000}; do echo $i; done }`.

**Comment by mvdan** [comment]
Ignored user and sys times for now.

**Comment by ebfe** [comment]
> Here's a good question - how do we get the CPU and system times?

For unix systems:

https://golang.org/pkg/syscall/#Rusage
https://golang.org/pkg/syscall/#Getrusage
https://golang.org/pkg/os/#ProcessState.SysUsage

**Comment by mvdan** [comment]
> https://golang.org/pkg/syscall/#Rusage
> https://golang.org/pkg/syscall/#Getrusage

Thanks - those indeed seem like per-process user and sys time.

I'm just worried that these are going to be terribly wrong quite often, given how we don't fork processes and how many interpreters may be running concurrently.

I know Go's runtime keeps track of CPU cycles somehow. Maybe we could do something similar. For now, I'd say reporting always 0 seconds is better than reporting something that looks right but isn't.

> https://golang.org/pkg/os/#ProcessState.SysUsage

`time` in Bash runs more than just simple commands, so this isn't useful I'm afraid.

**Comment by ebfe** [comment]
>> https://golang.org/pkg/os/#ProcessState.SysUsage

> time in Bash runs more than just simple commands, so this isn't useful I'm afraid.

I wouldn't discard this as "not useful" even if it doesn't work for builtins or you'd have to do some aggregating for more complex statements.

**Comment by mvdan** [comment]
True, not entirely useless. But without a way to count user/sys time for Go code, it's just part of the picture. And it can be wildly inaccurate just like `getrusage`. 

Not decided yet on what to do, but defaulting on nothing for now as neither sounds like a good solution so far.

**Comment by ebfe** [comment]
Why would getrusage be inaccurate? I mean sure you can't do proper accounting when there are multiple Interpreter running concurrently, but is there anything Go specific that would throw getrusage off?

Otherwise it's the same problem as with cd/chdir: that the typical solution assumes a single shell per process and the classic implementation doesn't work (signal handling is probably another instance of this). Or do i miss something?

**Comment by mvdan** [comment]
Yes, that is basically it. Not even multiple interpreters would throw this out the window - background processes and other cases that would normally fork, like a subshell, would also affect it.

I wouldn't say that `time` showing these values would be useful then. Why do you think they would be useful?
