### ISSUE TITLE
print: never collapse "( (" into "(("

### ISSUE THREAD

**Issue by benley** [mvdan/sh#16]
shfmt incorrectly reformats

```sh
git_lines="$( ( echo "$git_data";
    cat "$(dirname "$0")/foo.txt") | sort |uniq)"
```

to

```sh
git_lines="$((
	echo "$git_data"
	cat "$(dirname "$0")/foo.txt"
) | sort | uniq)"
```

Which breaks; `$((stuff))` is arithmetic expansion, but `$( (stuff) )` is a nested subshell inside a command substitution.

**Comment by mvdan** [comment]
Thanks for reporting!

**Comment by mvdan** [comment]
I just realised that the same would happen with nested subshells, as Bash will interpret `((foo))` as a C-style conditional as in `if ((foo)) then...`.
