### ISSUE TITLE
syntax: pure ksh(93) parser?

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#161]
Thanks for publishing mvdan/sh, it's really helpful for validating scripts!

Could mvdan/sh get a pure ksh(93) parser, to validate non-mksh scripts?

By the way, I noticed a little gap in linting--tools like shlint recommend running `sh -n` to validate `#!/bin/sh` files. However, most *nix systems symlink `/bin/sh` to bash, ksh, or other superset shells, so it's easy for bashisms to accidentally be ignored in portable sh scripts. So I applied your mvdan/sh parser to a simple Go application, guaranteeing that users are actually `-n`'ing their scripts against the appropriate parser.

https://github.com/mcandre/slick

Have a nice day, yo!

**Comment by mvdan** [comment]
Happy to see you're using this to build something!

Adding more language variants to the parser is always an option, but it adds complexity and maintenance burden in the long run. I want to be sure it's worth it.

Is ksh all that popular? How different is it from other variants like POSIX and mksh?

**Comment by mvdan** [comment]
Two weeks with no reply, so I'm closing this for now. @mcandre feel free to reopen if you can give more information as requested.
