### ISSUE TITLE
syntax: clarify bash syntax versions

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#162]
Does mvdan/sh parse bash v3 syntax or bash v4 syntax? Bash adds some things like recursive globs, so it would be great if mvdan/sh offered differentiated parsers for these two versions of the language.

**Comment by mvdan** [comment]
At the moment, the syntax package attempts to follow the latest Bash release, i.e. v4. I don't know if it's absolutely complete, but if anything is missing it would be something really new or obscure.

Regarding globs, note that they're not special syntax. They're just part of a string. It's the interpreter that expands these special characters (and others) when not quoted.

I hadn't thought about keeping Bash v3 as a separate language to accept. Why would that be useful? Is v3 commonly used in some context?

**Comment by mvdan** [comment]
Two weeks with no reply, so I'm closing this for now. @mcandre feel free to reopen if you can give more information as requested.
