### ISSUE TITLE
syntax: $FOO.bar is parsed as ${FOO.bar}

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#163]
```
$ cat x.sh
FOO=foo
echo $FOO.bar
$ bash x.sh
foo.bar
$ gosh x.sh

$ shfmt -exp.tojson < x.sh
[...]
	{
		"Param": {
			"Value": "FOO.bar"
		},
		"Short": true,
		"Type": "ParamExp"
	}
[...]
```

**Comment by mvdan** [comment]
Thanks for reporting!

**Comment by ebfe** [comment]
Thanks for the fast fix :)

**Comment by mvdan** [comment]
It's actually broken - `$foo` should only read valid names, so all punctuation and non-ascii should stop it too.

**Comment by mvdan** [comment]
^ done: c32e0986ffd02b6416c1e0f9a57dc2b02ec6a280

**Comment by mvdan** [comment]
And two more edge cases that this made me spot: d2e4d5d439c335d087a8aabf1abec04b632f9886 0ae374e489cbfebafc37c321c369cebd5a8d98db
