### ISSUE TITLE
backtick conversion issue

### ISSUE THREAD

**Issue by jfmherokiller** [mvdan/sh#169]
When sfmt encounters backticks it seems to always convert the expression to $() however this expression fails if the backticks are used in a certain way.

An example of this issue
```
`is-supported "ls --color" --color -G`
```
Src of is-supported
```
if [ $# -eq 1 ]; then
  if eval "$1" > /dev/null 2>&1; then 
    exit 0
  else
    exit 1
  fi
else
  if eval "$1" > /dev/null 2>&1; then
    echo -n "$2"
  else
    echo -n "$3"
  fi
fi
```
in the above example the backtick expression is converted to 

`$(is-supported "ls --color" --color -G)`
however it should actually be 
`$(echo $(is-supported "ls --color" --color -G))`

The reason the extra echo makes a difference is because without it -G is returned regardless of if `is-supported` echos `--color` or `-G`

I noticed this issue when i was using shfmt to optimize and beautify my dotfiles repo. 

It was messing up the ls aliases im using
an example of one such alias is provided below in hopes it helps debug the issue
`alias l="ls -lahA $LS_COLORS"`

**Comment by mvdan** [comment]
In the shell language, backticks and $( are exactly the same thing. I'm not sure I follow how this could change a program in any way.

Would help if you provided a small program to show this difference. That echo-eval-echo dance is non-trivial to follow.

**Comment by jfmherokiller** [comment]
well after i ran more tests it seems the issue was not just this but also the order of my path variable. So the ls the file was seeing was the wrong version.

A simpler version of the above provided program: 
```
  if eval "$1" > /dev/null 2>&1; then
    echo -n "$2"
  else
    echo -n "$3"
  fi
```
it takes 3 arguments "the program + args to run" "Echo Me If exit code 0" "echo me if exit code not zero"

**Comment by mvdan** [comment]
I still don't see why changing `` `foo` `` to `$(foo)` should ever change the behavior of a program. Please provide a small, self-contained program that shows how the two behave differently.

**Comment by mvdan** [comment]
Still lacking information, so I'm going to close this one for now. @jfmherokiller feel free to reopen if you have more info or a more concise and obvious example.
