### ISSUE TITLE
interp: bash brace expansion

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#172]
Consider:
```
echo a{1,2}
```

bash: `a1 a2`
gosh: `a{1,2}`

The parser currently parses this a literal:

```
[...]
	{
		"Type": "Lit",
		"Value": "a{1,2}"
	}
[...]
```

Should it?

**Comment by mvdan** [comment]
I have wondered about this in the past, and honestly never looked into it. Thanks for bringing it up. From a quick experiment:

```
$ a='b{c,d}'
$ echo $a
b{c,d}
$ echo b{c,d}
bc bd
```

So at least it doesn't happen after expanding variables.

The silly way of expanding these in the AST won't work, as then we will rewrite the `b{c,d}` program into `bc bd`. Perhaps we need a new AST node for this.

**Comment by mvdan** [comment]
Also - luckily - this seems to be a Bash feature.

**Comment by mvdan** [comment]
Ah, I see it is somewhat related to globbing, so it should run at the same stage. Then, this should be done in `interp` with no AST changes, as we have no extra AST information for globbing characters like `*`.

Should be easy to implement, fingers crossed.

**Comment by mvdan** [comment]
Correction - it should not happen at the same level as globbing. Globbing happens after variables are expanded, but this needs to go before those.

**Comment by mvdan** [comment]
Yet it seems like any expansion *inside* it does still work, like:

```
$ echo a{b,'c'}
ab ac
$ echo a{b,$empty}
ab a
```

I assume this is because they get expanded after, such as `a{b,'c'}` becoming `ab a'c'`, which is then `ab ac`.

**Comment by ebfe** [comment]
Yes, that sounds right:
```sh
X=_
X1=a
X2=b
X3=3
echo $X{1,2,${X3}}
```

```
a b _3
```

**Comment by mvdan** [comment]
I'm currently having a crack at it, and it's not trivial. Especially given how this all falls back to doing nothing if there are no commas or if the braces aren't matched. And there can be any nodes in between, of course.

The API I'm currently going with is `func(*Word) []*Word`, i.e. a func that "explodes" all the combinations. It leaves all word parts other than `*Lit` intact. This may be a bit wasteful, but it makes for a nice, static func that is independent of everything else. And expanding words (e.g. globbing) is generally not trivially cheap anyway.

**Comment by mvdan** [comment]
Managed to get that API working. For now, I'm keeping it hidden in interp. It's independent from the interpreter, so at some point I want to expose it somewhere - perhaps `syntax`.

Something else that has been in my mind for a while is a "static analysis" package of some sort. One that would be similar to `interp`, but without state. These funcs could go there. Other stuff we could put in it could include a version of `Runner.Fields` where you supply the variables in the call itself, meaning that you could convert a bunch of words to strings in a custom way.

This last one would be a much better version of https://golang.org/pkg/os/#Expand, as we support many things that it doesn't - such as `${foo:1:3}` and so on.
