### ISSUE TITLE
interp: export without assignment clears variable

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#173]
```
X=1
echo $X
export X
echo $X
```

bash: 
```
1
1
```

gosh:
```
1

```

**Comment by ebfe** [comment]
With an assignment it works.

```
X=1
echo $X
export X=2
echo $X
```

gosh:
```
1
2
```

**Comment by ebfe** [comment]
I think the cuplrit is missing `as.Naked` handling in either `Runnner.assignValue` or the `syntax.DeclClause` case in `Runner.cmd`.

**Comment by mvdan** [comment]
Correct as usual :) I simply forgot to account for that case.

**Comment by mvdan** [comment]
@ebfe fixed - thanks for all these useful reports. Before you stumble upon this other issue - note that interp doesn't handle `export` yet, so it acts just like `declare`. Feel free to open an issue about it, though.

**Comment by ebfe** [comment]
> @ebfe fixed - thanks for all these useful reports. Before you stumble
> upon this other issue - note that interp doesn't handle `export` yet,
> so it acts just like `declare`. Feel free to open an issue about it,
> though.

Thanks for the quick fix(es)! Yes, i already noticed export not doing
any exporting, though it's good enough for me atm if it doesn't clear 
values :). I took a quick peek what it would take to make exporting
work, but it wasn't clean how the interaction between r.vars,
r.envMap and r.Env should look like.

**Comment by mvdan** [comment]
I think that, the way the interpreter currently works, all variables are exported by default. There's definitely something to be fixed.
