### ISSUE TITLE
interp: bash brace expansion order

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#176]
```
echo a{1,2,3,4,5}
```

bash: `a1 a2 a3 a4 a5`
gosh: `a1 a5 a3 a2 a2`

**Comment by mvdan** [comment]
Ah, this is because I tried to be smart about the math here and I completely failed. Will fall back to a stupider, simpler approach.

**Comment by mvdan** [comment]
Yeah, the dumb way works. It allocates and copies exponential amounts of data, but it works.

I'll revisit ways to reduce the amount of work involved if it ever becomes a real issue.
