### ISSUE TITLE
BinaryCmd with a nil Y operand inside a LetClause

### ISSUE THREAD

**Issue by mkovacs** [mvdan/sh#18]
I understand that this doesn't affect the correctness of `shfmt`, and also that the AST likely wasn't designed to be used outside of this repository. Still, a separate `sh-ast` package would be super useful.

To reproduce, parse the following snippet, then inspect the AST.

```
function generate_piece {
  while true; do
    let pos=RANDOM%fields_total
    let board[$pos] || {
      let value=RANDOM%10?2:4
      board[$pos]=$value
      last_added=$pos
      printf "Generated new piece with value $value at position [$pos]\n" >&3
      break;
    }
  done
  let pieces++
}
```

I think the offending statement is a LetClause of the form:
```
let word || {
  stmt
}
```

**Comment by mvdan** [comment]
> I understand that this doesn't affect the correctness of shfmt, and also that the AST likely wasn't designed to be used outside of this repository. Still, a separate sh-ast package would be super useful.

If that were the case, I wouldn't have made `github.com/mvdan/sh` an easily importable and reusable package :)

It is true that feature development on the parser stalled a little as soon as I got all that I needed for `shfmt`. So for example, issues #1 and #4 are still open.

The parser and AST are not at all limited to the use case of the formatter and `shfmt`, though. I'll look into this.

**Comment by mvdan** [comment]
I cannot reproduce this. What confuses me the most is that `BinaryCmd` has `X, Y Stmt`, so there is no way that any of these can be nil. They could be empty statements, but then `shfmt` would not work properly. And it does:

```
 $ shfmt <<EOF
function generate_piece {
  while true; do
    let pos=RANDOM%fields_total
    let board[$pos] || {
      let value=RANDOM%10?2:4
      board[$pos]=$value
      last_added=$pos
      printf "Generated new piece with value $value at position [$pos]\n" >&3
      break;
    }
  done
  let pieces++
}
EOF
function generate_piece() {
        while true; do
                let pos=RANDOM%fields_total
                let board[] || {
                        let value=RANDOM%10?2:4
                        board[]=
                        last_added=
                        printf "Generated new piece with value  at position []\n" >&3
                        break
                }
        done
        let pieces++
}
```

It seems to not like `$pos` for some reason, but that's a separate issue :)

Moreover, I set up a quick AST test for this and both statements are indeed correct.

**Comment by mvdan** [comment]
Forget the `$pos` thing, I forgot heredocs expand vars. If I use a file, it works just fine.

**Comment by mkovacs** [comment]
You're right, my code had other issues.
After fixing those, I isolated a real issue: https://github.com/mvdan/sh/issues/20

**Comment by mvdan** [comment]
Not actually a bug, so untagging.
