### ISSUE TITLE
interp: provide more access to the internal state of Runner

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#180]
I'm mostly thinking of `r.vars` and `r.funcs`. With `r.Fields` accessing the
value of a (known) variable became easier, but unless I'm missing something
it's not possible at the moment to enumerate all variables/functions. In theory
just walking the AST works. In practice this get's ugly as soon as there are a
few conditionals or "dynamic"-variable/function names like `declare foo_${i}=bar` etc.

**Comment by mvdan** [comment]
I've been thinking the same recently. In particular, I've been thinking about shell scripts that are used as configuration files, e.g. Arch PKGBUILDS. This started with #165.

Ideally, you'd be able to give a filename/node, and you would be able to retrieve all the variables and functions defined.

However, I'm not 100% sure if simply exporting the `vars` and `funcs` fields would be a good idea. For example, we might want to make this setting and getting of names a module at some point, and being able to hook directly into the maps would be a restriction.

Then again, the interp package is not stable - so I'm fine with exporting these now and potentially changing this in the future. Want to send a patch?

**Comment by ebfe** [comment]
> In particular, I've been thinking about shell scripts that are used as configuration files, e.g. Arch PKGBUILDS. This started with #165.

Yes, that's basically what I'm working on at the moment (except for VoidLinux templates)

> Then again, the interp package is not stable - so I'm fine with exporting these now and potentially changing this in the future. Want to send a patch?

Can do. Exporting `vars` is a bit ugly because it contains
unexported types. Maybe 2 functions instead:

```go
// Vars returns the names of all declared variables.
func (r Runner) Vars() []string 
// Vars returns the names of all declared functions.
func (r Runner) Funcs() []string

```

which just return the keys of the maps?

**Comment by mvdan** [comment]
Hmm, I should revisit how the variables are stored first, as it's a bit of a mindfuck at the moment with readonly, nameref and the rest of the variable types.

I'll get to this once I'm done fighting with patterns.

**Comment by mvdan** [comment]
Done - the maps are exposed now, and the types too. I will likely add more exposed helpers around these in the near future, as now all the code is hidden in the interpreter.
