### ISSUE TITLE
interp: unquoted parameter expansion in assignment

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#182]
```
X="a b c d"
Y=$X
Z="$X"
echo $X
echo $Y
echo $Z
```

bash
```
a b c d
a b c d
a b c d
```

gosh
```
a b c d
abcd
a b c d
```

**Comment by mvdan** [comment]
Quotes combined with parameter expansions are just a neverending pit of sadness, aren't they.

**Comment by ebfe** [comment]
Yes, they are :/. This might be related:

```
unset X
if [ -n "$X" ]; then
	echo "y"
else
	echo "n"
fi
if [ -n $X ]; then
	echo "y"
else
	echo "n"
fi
```

bash
```
n
y
```

gosh
```
n
x.sh:7:4: -n must be followed by a word
```

**Comment by mvdan** [comment]
Not really related - I simply don't understand how that's supposed to work. `[ -n $x ]` when `x` is not a set variable should expand to three fields, i.e. `[ -n ]`. I understand how `[[ -n $x ]]` and `[ -n "$x" ]` work, but I don't see how the unquoted, builtin one does.

**Comment by ebfe** [comment]
I think it's handled the sasme as `[ "-n" ]`.

**Comment by ebfe** [comment]
> I think it's handled the sasme as `[ "-n" ]`.

Which in turn means `[ -n "-n"]` as `-n` is apparently the default.

**Comment by mvdan** [comment]
Jesus christ. Will fix.

**Comment by mvdan** [comment]
Also - yes, the interpreter does know that `-n` is the default operator. But what it didn't know is that an operator can fall back to being an argument if there is no argument following it.
