### ISSUE TITLE
interp: use our own $PATH to find binaries

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#185]
We should stop using `exec.LookPath`, as that hard-codes the environment's PATH instead of the runner's one.

`exec.LookPath` also does something we don't want - it uses different methods on Windows and Plan9. The POSIX Shell spec clearly defines PATH as `:` separated (http://pubs.opengroup.org/onlinepubs/9699919799/), so we don't want to support others.

Something we could do for slightly better Widows support, however, is to try to translate PATH equivalents such as Window's into the POSIX format when the interpreter is started. See https://golang.org/src/os/exec/lp_windows.go for more info.

/cc @andreynering for the windows stuff

**Comment by andreynering** [comment]
Nice catch.

Yeah, just convert from `;` to `:` on startup and then assume `:` while interpreting.

**Comment by mvdan** [comment]
@andreynering done - don't have a Windows machine, so if you could give it a test that would be helpful.

**Comment by andreynering** [comment]
Something is not right...

```bash
$ go version
go version go1.9 windows/386
```

```bash
$ gosh -c "go version"
"go": executable file not found in $PATH
exit status 127
```

**Comment by mvdan** [comment]
@andreynering is that on plain Windows? I believe the issue is the `.exe` extensions, which I forgot about.

**Comment by andreynering** [comment]
@mvdan Yes, plain Windows.

It makes sense the the issue may be the `.exe` extension.

**Comment by mvdan** [comment]
There were two bugs in my previous implementation; see the commit above for details.

I don't even know why I tried getting this right without tests.

**Comment by andreynering** [comment]
I confirm it is working fine now.
