### ISSUE TITLE
interp: assigning a string switches array variables type to string

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#189]
```
a=(1 2 3)
echo ${a[@]}
a="str"
echo ${a[@]}
declare -A aa=([foo]=bar [bar]=foo)
echo ${aa[@]}
aa="str"
echo ${aa[@]}


```

bash
```
1 2 3
str 2 3
foo bar
foo bar str
```

gosh
```
1 2 3
str
bar foo
str
```

**Comment by ebfe** [comment]
Type switch needed [here](https://github.com/mvdan/sh/blob/master/interp/interp.go#L328) instead of only checking `index==nil`?

**Comment by mvdan** [comment]
Ah, it does an indexed assign, defaulting to the zero index. Will fix.

**Comment by mvdan** [comment]
It was that, plus a bad assumption of how associative arrays worked on my part. Now the script works just like in Bash.
