### ISSUE TITLE
parse: function definitions are incorrect

### ISSUE THREAD

**Issue by mmlb** [mvdan/sh#19]
According to http://www.tldp.org/LDP/abs/html/functions.html and http://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html#tag_02_09_05 for bash and sh respectively function definitions can be either:

```sh
function function_name {
...
}
```
(bash only)
or 
```sh
function_name() {
...
}
```

Note that when the `function` keyword exists there is no `()` after the name, but there *must* be one in `sh` mode.

**Comment by mmlb** [comment]
hmm on the other hand https://www.gnu.org/software/bash/manual/html_node/Shell-Functions.html#Shell-Functions list it as optional :sweat:

**Comment by mvdan** [comment]
Surely you mean when they are formatted?

Using `()` in the bash style is valid syntax and works in bash. The reason behind using it, besides consistency, is so that the format is less confusing. See 8f92740761eb827bc9fffe85fef941575edd1dbf.

**Comment by mvdan** [comment]
To expand on the commit above - if we don't introduce `()`, we would break the following program:

```
function foo() (bar)
```

(subshells as function bodies are valid).

**Comment by mmlb** [comment]
Right. Sorry, checked issues but not the code :(. Guess its time to dig into `sh.vim` I think

**Comment by mvdan** [comment]
No problem :) Just wanted to point out why I was forced to do this. I too was trying not to use `()` in this case.

**Comment by mmlb** [comment]
Yep it makes sense and TBH it's not the first time I've run into this issue.

**Comment by mmlb** [comment]
just fyi for anyone else using (neo)vim and hitting this, updating `indent/sh.vim` via https://github.com/chrisbra/vim-sh-indent either as a plugin or once it gets pulled into vim works.
