### ISSUE TITLE
interp: Runner.Exec no longer called if the executable isn't found in PATH

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#194]
edb75bb8f7dc8a325bc2cfc149e37c084b2c9630 introduced PATH handling and as a side
effect no longer calls Runner.Exec if the executable isn't found in PATH. The
use-cases I have for Runner.Exec is denying executing other binaries at all, and
emulating some binaries (to avoid forking in the first place and to reduce
dependencies on external binaries). Unless the binaries exists in PATH, the
latter is no longer possible.

Having said that, a "call hook" on a level below Runner.Exec might be useful
too (e.g. enabling/disabling builtins, call-traces that include function calls
and arguments etc.)

**Comment by mvdan** [comment]
Hmm, I thought about this change of behavior (and I even rewrote some of the tests that it broke).

You are right - being able to do stuff at the `CallExpr` level (i.e. before `Exec` as well as before any builtins) would be useful. But I'd like to make that more generic, e.g. being able to have a pre and post funcs that get executed on all nodes and can return an error.

As for this specific change, I'm thinking that the solution is to move the "executable file not found in $PATH" error from the interpreter (before calling `ModuleExec`) to `DefautExec`. This fixes the regression, including what happened with my tests and your breakage.
