### ISSUE TITLE
syntax: misparsed short ParamExp if Param is followed by \

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#199]
```sh
X=foo
echo -e "$X\n"
```

bash:
```
foo

```

gosh:
```

```

```json

"Parts": [
	{
		"Param": {
			"Value": "X\\n"
		},
		"Short": true,
		"Type": "ParamExp"
	}
],
```

**Comment by mvdan** [comment]
Ah, I believe that the issue is that the lexer does a good job at making sure it parses a valid name, but that doesn't hold if backslashes are involved. But at the same time, we want escaped newlines to still work ok. This will be a tricky one.

**Comment by mvdan** [comment]
Actually not a tricky one, fortunately.
