### ISSUE TITLE
parse: support multiline arrays

### ISSUE THREAD

**Issue by brenol** [mvdan/sh#2]
Should it support multiline arrays? Like this:

```sh
var=( 
    1 
    2 
    3
)
echo $var
```

Right now it's failing:
```
$ shfmt test.sh
test.sh:3:5: reached literal without matching token ( with )
```

I'm asking because in the canonical example there is nothing like a multiline array.

By the way, really nice tool!

**Comment by mvdan** [comment]
Bash supports this, so sounds like a bug. Thanks for reporting!

**Comment by mvdan** [comment]
Parsing is fixed, I'm doing the printing part now.
