### ISSUE TITLE
cmd/shfmt: add program minification

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#202]
shfmt is awesome! For engineering situations where the number of bytes involved in a script is critical, it would be nice to have a way to minify shell scripts, POSIX sh, bash, zsh, csh, and so on. Could shfmt get an option to reformat shell scripts with respect to reducing extraneous characters?

* Strip out comments.
* Reduce line breaks to semi-colons (`;`), though keep the final EOL newline for POSIX compliance.
* Reduce extraneous whitespace generally.
* Reduce un-interpolated string constants to either raw un-quoted (`...`), or single-quoted (`'...'`), or double-quoted (`"..."`) format, depending on which format features the minimal number of characters in the literal.
* Rebind un-exported bindings to shorter variable names.

**Comment by mvdan** [comment]
Could you clarify what the use case here is? In what situation would, say, 10% less bytes in a shell program matter this much? I can understand javascript if it has to be sent over the network to many thousands of clients, but this isn't the case.

**Comment by mcandre** [comment]
It's a multiplicative thing. The more a script is downloaded, the more it matters. That's why JS is often minified.

https://get.rvm.io is pulled quite often for users installing RVM for example. Reducing the extra characters would save the hosting provider a lot of bandwidth.

**Comment by mvdan** [comment]
I see - thanks for the suggestion. I'll give this a go.

**Comment by mvdan** [comment]
@mcandre done for now - try `shfmt -mn`. It does all that you described (plus other stuff that came to mind), minus the variables part as that's trickier.

**Comment by mvdan** [comment]
Numbers from the shell script you linked above (note that it's invalid bash though, that `]]` after a newline needs fixing):

```
 $ cat rvm-installer | wc
    926    2571   24086
 $ shfmt rvm-installer | wc
    880    2529   22098
 $ shfmt -mn rvm-installer | wc
    677    2042   18725
```
