### ISSUE TITLE
error installing with go on debian testing (10)

### ISSUE THREAD

**Issue by Bulmer** [mvdan/sh#205]
I am having trouble installing shfmt on Debian Testing.
I have: go version go1.9.2 linux/amd64
me@mine:/ go get -u github.com/mvdan/sh/cmd/shfmt
package github.com/mvdan/sh/cmd/shfmt: code in directory /root/go/src/github.com/mvdan/sh/cmd/shfmt expects import "mvdan.cc/sh/cmd/shfmt"

**Comment by mvdan** [comment]
Please see the readme - you're using the wrong go get argument.

**Comment by Bulmer** [comment]
well it seemed to install ok,(no error this time) but I still get this:
bash: shfmt: command not found

**Comment by mvdan** [comment]
You probably did not set up $PATH to properly include $GOPATH/bin. See https://golang.org/doc/code.html.
