### ISSUE TITLE
cmd/shfmt: should not fail when non-bash files are missing permissions

### ISSUE THREAD

**Issue by dominikschulz** [mvdan/sh#207]
https://github.com/mvdan/sh/blob/master/cmd/shfmt/main.go#L200 tries to open all files for reading and writing (O_RDWR) if the `-w` flag is given. This seems to be used even for checking if it's a script at all.
If a file has no write permissions for the current user and it's not a script shfmt should not fail.

A fix would be to either open the files as O_RDONLY first and only if it's a script attempt to open for writing as well or the ignore any errors when opening files (possibly controlled by a flag).

**Comment by mvdan** [comment]
> If a file has no write permissions for the current user and it's not a script shfmt should not fail.

That's a good point.

> ignore any errors when opening files (possibly controlled by a flag)

I'm not a big fan of unnecessary flags and exposing internal detail. This seems like a clear case of something not to do.

> A fix would be to either open the files as O_RDONLY first and only if it's a script attempt to open for writing 

I thought about doing this, but I didn't like the idea of opening the same file twice.

Then again, in the vast majority of scenarios we won't need to write - as in general, you only overwrite the file once, and then never again as it's already in the desired format. So we would still be opening the files once in most cases. Will do this approach.

**Comment by mvdan** [comment]
@dominikschulz if you'd like to submit a patch yourself, just let me know and it's all yours. Otherwise, I'll get to this sometime soon.

**Comment by dominikschulz** [comment]
Thanks! I'll look into it, maybe I can pull up a PR. No promises, though.
