### ISSUE TITLE
cmd/shfmt: set appropriate exit status when -d is used

### ISSUE THREAD

**Issue by dominikschulz** [mvdan/sh#208]
If listing files which are not properly formated (`shfmt -l`) it should set a non-zero exit status if any files differ to simplify usage in e.g. Makefiles.

**Comment by mvdan** [comment]
Non-zero exit statuses are only ever used for actual errors. We could add a special exit status for "some files were overwritten", but I wonder if that is necessary.

In general, I would simply do `files=$(shfmt -l ...); if [[ -n $files ]]; then ...; fi`. That also seems clearer and more explicit to a reader than a special exit code, like `files=$(shfmt -l ...); if [[ $? -eq 4 ]]; then ...; fi`.

**Comment by mvdan** [comment]
I don't see the `files=$(shfmt -l ...)` approach as a workaround, to be honest. `shfmt` gives you a list of files, and you check if the list is non-empty. That seems simple and self-explanatory to me. Adding another flag and exit code on top of this seems unnecessary.

**Comment by mvdan** [comment]
On second thought, this gets trickier in certain usecases, such as makefiles and CI yaml files. I wonder if we should add this after all.

Is there precedent in other tools? Do other implementations use a flag, or simply do this by default?

**Comment by dominikschulz** [comment]
AFAIK golint has a special flag for this.

**Comment by mvdan** [comment]
I meant in other formatting tools, such as rustfmt, clang-format, or gofmt. Linters are a different kind of tool. Since you proposed this change, I presume that you're used to the feature existing in other formatters.

**Comment by dominikschulz** [comment]
You're right. I didn't grasp your question at first. In my day job I'm only concerned about Go and sometimes Bash, but since I asked for this and I agree that consistency is very helpful, I did a little research.

| Tool | Non-Zero Exit Code by default | Non-Zero Exit Code by flag | Notes |
| -----  | ---------------------------------------- | ------------------------------------ | -------- |
| [gofmt](https://golang.org/cmd/gofmt/) | no | no | Need to capture and compare for non-empty stdout |
| [clang-format](https://clang.llvm.org/docs/ClangFormat.html) | no | no | Need to capture and compare output to input |
| [perltidy](https://metacpan.org/pod/distribution/Perl-Tidy/lib/Perl/Tidy.pod) | no | no | Need to capture and compare for non-empty stdout |
| [rustfmt](https://github.com/rust-lang-nursery/rustfmt) | no | yes | Has a special `check` command for CI workflows |

Unfortunately most commands don't seem to support this. I'm fine with the workaround, but still think having an explicit exit code might make some use cases a little easier.

**Comment by mvdan** [comment]
@dominikschulz thanks for the research :) This is precisely what I meant.

Your finding on rustfmt gave me an idea. It seems likely that the cases where one would want an exit code are very similar to the cases where one would want to output a diff. What if we made the existing `-d` flag exit with code 1 if any files changed, just like the `diff` program would?

You could then argue that `-l` should be the same, but I don't want to break existing uses of `shfmt`. And one could say that `shfmt -l -w` should not exit with code 1 on any changes, as they are being written to disk after all. So I'd be fine with just doing it for `-d`.

**Comment by mvdan** [comment]
(The reason I mentioned this after reading about `rustfmt` is because that's what its `check` mode does - output diffs and use exit codes)

**Comment by mvdan** [comment]
I actually proposed this in #149 already, but completely forgot to implement it. Will add it in a few days unless anyone disagrees.
