### ISSUE TITLE
interp: support shopt -s globstar

### ISSUE THREAD

**Issue by masaeedu** [mvdan/sh#213]
I'm trying to figure out how to `shopt -s globstar`. This is needed on Windows platforms, since use of `find` is complicated by the presence of Windows's own `find.exe` very high up in the PATH (it's in system32).

On Windows, trying to use the `shopt` builtin results in:

```
"shopt": executable file not found in $PATH                 
task: Failed to run task "adjust_ref_paths": exit status 127
```

**Comment by mvdan** [comment]
This is missing because the bash builtin isn't implemented. Will look into it soon, but help is welcome - let me know if you'd like to look into it.
