### ISSUE TITLE
syntax: backslashes within single quotes are removed inside a backquote command substitution

### ISSUE THREAD

**Issue by eralbru** [mvdan/sh#215]
Examples:
 awk '/^id\t/ {print $2}'  will be changed to awk '/^idt/ {print $2}'  # so search for TAB is not working anymore
cut -f2 -d\! will be changed to cut -f2 -d!
sed -e 's/.*@\(....\)\..*$/GIC-\1/' will be changed to sed -e 's/.*@(....)..*$/GIC-1/'

Using 'shfmt -i 2 -ci' on bash-scripts

**Comment by mvdan** [comment]
What version of `shfmt` are you using?

**Comment by eralbru** [comment]
shfmt -version
v2.2.1


Am 15.02.2018 um 13:24 schrieb Daniel Martí <notifications@github.com<mailto:notifications@github.com>>:


What version of shfmt are you using?

**Comment by mvdan** [comment]
Could you provide a full shell script that reproduces this problem? Simply using `awk '/^id\t/ {print $2}'` does not remove the backslash.

**Comment by eralbru** [comment]
Here an example script.
[afs-server_stat_collection.gz](https://github.com/mvdan/sh/files/1727626/afs-server_stat_collection.gz)
Need to be unzipped first.

**Comment by mvdan** [comment]
Thank you - I know what the bug is now.

**Comment by eralbru** [comment]
Great.

- Ralf

Am 15.02.2018 um 13:39 schrieb Daniel Martí <notifications@github.com<mailto:notifications@github.com>>:


Thank you - I know what the bug is now.

**Comment by mvdan** [comment]
@eralbru this regression was introduced in master after the 2.2.1 release. Since you're running master, you should either update to get the fix, or use 2.2.1 instead. Thanks for reporting!

**Comment by eralbru** [comment]
Here an example script.

**Comment by eralbru** [comment]
New version is working.
