### ISSUE TITLE
syntax: backslashes within double quotes are removed inside a backquote command substitution

### ISSUE THREAD

**Issue by eralbru** [mvdan/sh#216]
Hi again,

found a similar problem with the fowling code:

#!/bin/bash
#

ORASQLTMPFILE="/tmp/afs-oracle_import.dat"
ORASQLTMPMEMBERFILE="/tmp/afs-oracle_member-import.dat"
ORASQLFILE="/afs/sunrise.ericsson.se/afsadm/data/Report/afs-oracle_import.dat"
ORASQLMEMBERFILE="/afs/sunrise.ericsson.se/afsadm/data/Report/afs-oracle_userimport.dat"
AFSHUBFILE=/afs/sunrise.ericsson.se/afsadm/etc/afshubfile
MASTER=`grep "^MASTER" $AFSHUBFILE | awk '{print $2}'`
KEYTAB=/etc/cron.admin.keytab
REALM=RND.KI.SW.ERICSSON.SE
KRBUSER="cron/admin@${REALM}"
CELL=`fs wscell | sed -e "s/.*to cell '\(.*\)'/\1/"`
DATE=`/bin/date +%Y-%m-%d`
DAY=`/bin/date +%d`

GENERATION=`echo "$MODEL" | sed -e 's/.*\([0-9]\)$/\1/'`
##################

the line 
  CELL=`fs wscell | sed -e "s/.*to cell '\(.*\)'/\1/"`
will be changed to 
  CELL=$(fs wscell | sed -e "s/.*to cell '(.*)'/1/")
which is a problem.

/Ralf

**Comment by mvdan** [comment]
Thanks again for reporting. Double quotes occurred to me and I checked, but I must have missed something.

**Comment by mvdan** [comment]
Yes - this is another bug in the logic to handle backslashes within backquotes. I really, really hate backquotes. They are so hard to get right.

Good thing that the formatter gets rid of them :)

**Comment by eralbru** [comment]
It working!

Thanks.

Am 15.02.2018 um 15:46 schrieb Daniel Martí <notifications@github.com<mailto:notifications@github.com>>:


Closed #216<https://github.com/mvdan/sh/issues/216> via f19cc87<https://github.com/mvdan/sh/commit/f19cc87eb6c827b271766115b2547dcda29ace8f>.
