### ISSUE TITLE
syntax: respect line breaks in case clause pattern lists

### ISSUE THREAD

**Issue by dsifford** [mvdan/sh#217]
Hi there,

I'm wondering if there might be a way to either add support to respecting breaks in case options OR add the ability to ignore entire lines (e.g. `# shfmt:ignore-next-line`, etc). The second flavor I think has potential to be the most useful.

Anyway... consider the following example..

```sh
#!/bin/bash

case "$1" in
    alfa|bravo|charlie|delta|echo|foxtrot|golf|hotel|india|juliett|kilo|\
    lima|mike|november|oscar|papa|quebec|romeo|sierra|tango|uniform|victor|\
    whiskey|x-ray|yankee|zulu)
        # do stuff ....
        ;;
esac
```

When ran with `-ci -bn` (and all other variants to my knowledge), the output will always become this....

```sh
#!/bin/bash

case "$1" in
	alfa | bravo | charlie | delta | echo | foxtrot | golf | hotel | india | juliett | kilo | lima | mike | november | oscar | papa | quebec | romeo | sierra | tango | uniform | victor | whiskey | x-ray | yankee | zulu)

		# do stuff ....
		;;
esac
```

Any thoughts?

Thanks for considering!

**Comment by dsifford** [comment]
Here's a real-world file where this issue occurs: https://github.com/ranger/ranger/blob/master/ranger/data/scope.sh

**Comment by mvdan** [comment]
It probably makes sense to respect the original lines here. After all, we do it for word lists, such as:

```
for a in 1 2 3 \
        4 5 6; do
        echo $a
done
```

Thanks for raising the issue.

**Comment by dsifford** [comment]
@mvdan Holy smokes, do you work quickly! :smile: 

Greatly appreciate it! Thanks so much.

**Comment by mvdan** [comment]
:) it was an easy fix. Happy to be of help.

**Comment by dsifford** [comment]
@mvdan If you don't mind me asking here, what's your usual policy when it comes to the release cycle for this project? 

I noticed that you're the maintainer of the AUR package, which is awesome, but there has not yet been a release there or here on GitHub since January (`v2.2.1`) and several important changes have made it to master since then.

Thanks for clarifying!

**Comment by mvdan** [comment]
If there were any major bugs in the last stable, I would have done 2.2.2 by now. But I don't think there are any - some of the seemingly bad fixes were fixes to regressions introduced after 2.2.1. And others, like this one, are more like a change in behavior that belongs to 2.3.

I do plan on doing 2.3 in the next few days, though.

**Comment by dsifford** [comment]
Aha, got it. Makes sense.

Thanks for clarifying. Looking forward to seeing this one land :smile:

**Comment by mvdan** [comment]
I also tend to spend a bit of time fuzzing the syntax package before every major release. After any number of non-trivial errors, I tend to introduce at least a couple of off-by-one or nil dereference panics. So it's not as simple as tagging a release.

**Comment by mvdan** [comment]
done :)
