### ISSUE TITLE
syntax: for name do bash compatibility

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#219]
Apparently the `;` after `NAME` is optional in bash, as long as there is no `in WORDS`

```
for arg do
	echo $arg
done
```

bash x.sh 1 2 3
```
1
2
3
```

shfmt x.sh
```
x.sh:1:1: "for foo" must be followed by "in", ; or a newline
```

**Comment by mvdan** [comment]
This is the relevant part of the spec I missed:

```
Omitting:

in word...

shall be equivalent to:

in "$@"
```

**Comment by mvdan** [comment]
Rather; we do support this when there's a semicolon or a newline, but not when there is a "do" without any of those.
