### ISSUE TITLE
syntax: nested backticks

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#220]
```
echo `while read line; do echo \`echo $line\`;  done`
```

echo -e "1\n2\n" | bash x.sh
```
1 2
```

shfmt
```
x.sh:1:7: while statement must end with "done"
```

Replacing `` with $() works fine.

**Comment by mvdan** [comment]
Well, I had written support for backslashes within backticks, but not nested backticks. Thanks for reminding me.
