### ISSUE TITLE
syntax: add support for redirections to KeepPadding

### ISSUE THREAD

**Issue by xdc0209** [mvdan/sh#224]
## CMD
shfmt_v2.3.0_windows_amd64.exe  -i 4 -ci -kp -w java_info_collect.sh

## Picture
![image](https://user-images.githubusercontent.com/3997527/38036876-4e962e46-32da-11e8-9197-789ff4cce400.png)

## Request
Would it be possible to let "kp"  keep Redirect column?

Thanks, for making shfmt!

**Comment by xdc0209** [comment]
or add another option like kp?

**Comment by xdc0209** [comment]
Code for debug:

```bash
function os_info_collect()
{
    print_info "============================================================================================"
    print_info "获取OS信息："
    print_info "Get os info."
    print_info "============================================================================================"
    echo "Dump os info to $output_dir ..." | tee -a $log
    date         >$output_dir/os_date.txt     2>&1
    ifconfig     >$output_dir/os_ifconfig.txt 2>&1
    ip addr      >$output_dir/os_ip.txt       2>&1
    netstat -anp >$output_dir/os_netstat.txt  2>&1
    ps -eflww    >$output_dir/os_ps.txt       2>&1
    top -bc -n 5 >$output_dir/os_top.txt      2>&1
    df -h        >$output_dir/os_df.txt       2>&1
    echo | tee -a $log
    echo | tee -a $log
}
```

**Comment by mvdan** [comment]
Please don't use screenshots to share these - copy-pasting of code is much easier for both you and me.

This feature is certainly possible. We do it for assignments, so I don't see a reason not to.

**Comment by xdc0209** [comment]
Thank you. Look forward to future releases.
