### ISSUE TITLE
add git commit ID to version string

### ISSUE THREAD

**Issue by Finkregh** [mvdan/sh#238]
It would be nice to have the git commit ID in the version output. Like that we could differ between builds of the master branch and "proper ones"/releases from a tag.

Thanks anyway!

**Comment by mvdan** [comment]
Any proposal on how to do so? Regular `go build`/`go install` does not allow running arbitrary programs like `git`. We could add a `Makefile` or a build script, but those installing using the standard commands would still not run that.

**Comment by mvdan** [comment]
Both of those require running extra commands on top of or before `go build`, so they won't work all the time. Sadly, there isn't a way to do this natively at the moment. But perhaps vgo will make this possible in a clean way - see https://github.com/golang/protobuf/pull/599#issuecomment-388134948.

It doesn't look like vgo will be incorporated into mainline Go soon though, so I'm going to close this issue for now and revisit it once there has been movement.
