### ISSUE TITLE
shfmt does not like quoted variables inside of heredocs

### ISSUE THREAD

**Issue by mmlb** [mvdan/sh#24]
```sh
[manny@maxwell ~]$ cat t.sh 
cat <<EOF
"$name"
EOF
[manny@maxwell ~]$ shfmt t.sh 
cat <<EOF
"$nameEOF
```

**Comment by mvdan** [comment]
Thanks for reporting! I only recently added support for variables in heredocs so in the meantime you can revert to before #22 was fixed.

**Comment by mvdan** [comment]
To explain, before everything was read as a literal so this bug would very probably not happen.
