### ISSUE TITLE
Latest shfmt seems to have issues with the file in this issue

### ISSUE THREAD

**Issue by rmohr** [mvdan/sh#241]
This file in our project https://github.com/kubevirt/kubevirt/blob/5dceffde3bb24d7401931e235ca9a72e66865278/cluster/vagrant-openshift/setup_master.sh is reformatted if we use latest master (https://github.com/mvdan/sh/commit/f2ae3bece7944c04dc315ce767e09490bf277f87).

The diff after the format looks like this:

```diff
diff --git a/cluster/vagrant-openshift/setup_master.sh b/cluster/vagrant-openshift/setup_master.sh
index 24479769..0e2c48bc 100644
--- a/cluster/vagrant-openshift/setup_master.sh
+++ b/cluster/vagrant-openshift/setup_master.sh
@@ -29,9 +29,9 @@ sed -i '/host_key_checking/s/^#//g' /etc/ansible/ansible.cfg
 inv_nodes=""
 IFS=. read ip1 ip2 ip3 ip4 <<<"$master_ip"
 for node in $(seq 0 $(($nodes - 1))); do
-    node_ip="$ip1.$ip2.$ip3.$(($ip4 + node + 1))"
-    node_hostname="node$node openshift_node_labels=\"{'region': 'infra','zone': 'default'}\" openshift_ip=$node_ip"
-    inv_nodes="$inv_nodes$node_hostname\n"
+       node_ip="$ip1.$ip2.$ip3.$(($ip4 + node + 1))"
+       node_hostname="node$node openshift_node_labels=\"{'region': 'infra','zone': 'default'}\" openshift_ip=$node_ip"
+       inv_nodes="$inv_nodes$node_hostname\n"
 done
 
 openshift_ansible_dir="/root/openshift-ansible"
@@ -43,6 +43,8 @@ git clone https://github.com/openshift/openshift-ansible.git $openshift_ansible_
 
 # Create ansible inventory file
 cat >$inventory_file <<EOF
+
+# Run OpenShift ansible playbook
 [OSEv3:children]
 masters
 nodes
@@ -71,7 +73,6 @@ master openshift_node_labels="{'region': 'infra','zone': 'default'}" openshift_s
 $inv_nodes
 EOF
 
-# Run OpenShift ansible playbook
 ansible-playbook -i $inventory_file $openshift_ansible_dir/playbooks/deploy_cluster.yml
 
 # Create OpenShift user
```

Especially that it moves  the comment around looks strange. Maybe it has issues with `<< EOF`?

Moved back to `v2.3.0` and everything looks fine there.

**Comment by mvdan** [comment]
I'd suggest you stay with a stable version or pin/vendor a specific commit. Otherwise, with a large project and lots of shell files, it's likely that master will break your CI from time to time. In any case, thanks for being an alpha tester :)

**Comment by mvdan** [comment]
I think the indentation one is correct - if I use `shfmt -i 4` like in your script, it goes away. I presume you got this diff by running `shfmt -d` alone, hence it replaced the four spaces with tabs.

**Comment by rmohr** [comment]
> In any case, thanks for being an alpha tester :)

You are welcome :)

> I think the indentation one is correct - if I use shfmt -i 4 like in your script, it goes away. I presume you got this diff by running shfmt -d alone, hence it replaced the four spaces with tabs.

That can very well be. Then we can simply pick up the `-i 4` for this one.

**Comment by mvdan** [comment]
The fix is live, so if you guys are happy with master, simply restarting CI should fix things.

**Comment by rmohr** [comment]
Can confirm that it works. Thanks. :+1:
