### ISSUE TITLE
shfmt: 2 runs are needed for piping into while to have decent formatting

### ISSUE THREAD

**Issue by frou** [mvdan/sh#242]
Hi there - thanks for the nice tool.

When starting with something like this:

(A)
```
somecmd | while read X
do
    echo "$X"
done
```

running through shfmt outputs:

(B)
```
somecmd | while
	read X; do
	echo "$X"
done
```

and running that through shfmt again outputs:

(C)
```
somecmd | while
	read X
do
	echo "$X"
done
```

---

Either (A) or (C) seems like decent formatting, but not (B). Can (B) not be output in the first place?

**Comment by mvdan** [comment]
Yes, the formatter output should be stable. Thanks for reporting!

**Comment by frou** [comment]
Thank you - I appreciate it
