### ISSUE TITLE
here document with command substitution 

### ISSUE THREAD

**Issue by fmercier** [mvdan/sh#245]
Hello,
I've an issue when formatting code having at the same time a Here document and a command substitution. Example:
```
$  cat ./here-doc-eval.sh
#!/bin/bash
test=`wc -l <<-EOT
    line 1
    line 2
EOT`
echo $test

$ ./here-doc-eval.sh
2

$ cat ./here-doc-eval.sh | ./shfmt_v2.4.0_windows_amd64.exe
<standard input>:6:4: reached EOF without closing quote `
```

**Comment by mvdan** [comment]
Thanks for reporting!

**Comment by mvdan** [comment]
So, as far as I can see, we are following POSIX Shell. See http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_07_04:

> The here-document shall be treated as a single word that begins after the next <newline> and continues until there is a line containing only the delimiter and a <newline>, with no <blank> characters in between.

And we are following `man bash` too:

> This  type  of redirection instructs the shell to read input from the current source until a line containing only delimiter (with no trailing blanks) is seen.

And here's more proof - if one uses other tokens, bash no longer accepts the program:

```
$ cat f1.sh
echo `<<EOT
EOT`
$ bash f1.sh
$ cat f2.sh
echo $(<<EOT
EOT)
$ bash f2.sh
f2.sh: line 4: warning: here-document at line 3 delimited by end-of-file (wanted `EOT')
```

So it seems to me like it's a bug in bash to not follow the spec and its own documented behavior in the first case.

**Comment by fmercier** [comment]
Hello,
Thanks to explain, I was not aware using a bash bug as it is working on Linux/AIX/Solaris/Cygwin !
I'll correct all by scripts to comply with the spec.

**Comment by mvdan** [comment]
Just to add to the reply above - `shfmt` rewrites `` `foo bar` `` into `$(foo bar)`, since backquotes are deprecated and discouraged by the POSIX Shell spec and Bash. So, even if we added support for this weird Bash behavior, programs would still break, as I showed you earlier that the `EOT)` line doesn't work.
