### ISSUE TITLE
interp: Add PTY "redirection" support for interactive apps that can't fallback to STDOUT/STDIN

### ISSUE THREAD

**Issue by andreynering** [mvdan/sh#247]
@mvdan Creating issue for brainstorming. Feel free to close this if you think it's not worth it.

See https://github.com/go-task/task/issues/114 for context.

In short: It's a common use case for Task to call interactive terminal applications (text editors, database consoles, etc). The great news is that most of them work just fine through `mvdan/sh`.

But some of them require PTY and can't fallback to `stdout`/`stdin` (like `psql`, the PostgreSQL console).

I tried [kr/pty](https://github.com/kr/pty) and but was buggy (keyboard arrow and ESC not working correctly, etc).

I may try again when finding a better way to implement this.

**Comment by mvdan** [comment]
Thanks for opening this issue - we might indeed want to do something about this. It's interesting, however, that `os/exec` doesn't seem to have any tty or pty handling. What happens if one runs psql via `os/exec`? I presume it fails all the same.

Is the issue with psql on the interpreter that it detects stdout to *not* be a terminal, and bails, or that it directly uses /dev/tty or some other device, bypassing stdout?

**Comment by andreynering** [comment]
> It's interesting, however, that os/exec doesn't seem to have any tty or pty handling.

Yep, I found https://github.com/kr/pty and https://github.com/google/goterm, the later not worked at all for me.

> What happens if one runs psql via os/exec? I presume it fails all the same.

Yes, you should have the same result.

> Is the issue with psql on the interpreter that it detects stdout to not be a terminal, and bails, or that it directly uses /dev/tty or some other device, bypassing stdout?

I really don't know, actually.

**Comment by mvdan** [comment]
There's been no progress here, and we don't even know if there's anything that the interp package could do better, so I'm closing the issue for now. If that changes in the future, please reopen the issue or file a new one.

**Comment by andreynering** [comment]
Hi @mvdan,

FYI, I was able to fix some of the issues users were facing on https://github.com/go-task/task/pull/200. So, maybe PTY was not the problem after all (at least for some of the tools).

**Comment by mvdan** [comment]
Great, thanks. So I assume there's nothing to fix here?

**Comment by andreynering** [comment]
@mvdan I think so =)

I'm still waiting for users feedback, tho.
