### ISSUE TITLE
Indent Only mode

### ISSUE THREAD

**Issue by dcsobral** [mvdan/sh#248]
Sometimes all you want is fix indentation, and even with options such as -kp and -bn, shfmt may change things you don't want it to. 

So, provide a mode where the _only_ thing it does is change indentation.

**Comment by mvdan** [comment]
Can you give examples of things that shfmt changes that you wish it didn't?

Could you clarify why `-kp` isn't enough? It's not exactly what you are after, but I would imagine it would work for you.

As for not changing **anything** besides indentation, I'm afraid this is not the tool to do that. To put it simply, the printer doesn't support printing all input programs as-is. A couple of examples:

* Backquotes are always changed with subshells - `` `foo` `` is replaced by `$(foo)`
* Literals split in multiple lines via backslash-newline are merged into single lines (the syntax tree doesn't keep the splitting information)

**Comment by dcsobral** [comment]
Some examples are statements being broken that I'd rather not, the `then` keyword being placed as a second statement in the same line as `if`, and spaces after redirection. But that's strictly for me.

Indentation is the most valuable formatting option, as it serves as a visual clue to scope. Pretty much everything else in formatting comes down to cosmetic preference, so being able to _only_ indent lines gives an immediate benefit without having to tweak configuration options, or undo changes you don't want, or just not use the tool at all.

I'm rather concerned about the examples you give. I don't particularly care for the backquote myself, but the line split is an issue when it comes to right margin, which I just realize is not supported. For literals, in particular, a person can make semantic sense of it and break it at a sensible point, whereas the tool cannot do so -- not for literals.

**Comment by mvdan** [comment]
Thanks for your reply. I see your point of view, but I still don't think this is achievable.

To be able to do this, the package would need massive refactoring to be able to only touch indentation. Perhaps someone could write a simpler version of `shfmt`, which would simply parse the syntax tree, and calculate the indentation level to apply to each line. Then, in plaintext, it would replace the whitespace line-per-line as appropriate.

That would have to be a different tool than `shfmt` though, as this tool does not work in plaintext.

**Comment by mvdan** [comment]
It's pretty clear to me that this feature doesn't belong in `shfmt`. And, as shown above, it would be simple to implement via use of `syntax.Parser`. Since there hasn't been more input, I'm going to close this issue for now.
