### ISSUE TITLE
parse: backquotes separated from word

### ISSUE THREAD

**Issue by fwip** [mvdan/sh#25]
```#!/bin/bash
for fastq in $SAMPLE_NAME*.fastq.gz; do
	zcat $fastq \
		>filtered_`basename $fastq .gz`;
done
```
becomes
```#!/bin/bash
for fastq in $SAMPLE_NAME*.fastq.gz; do
	zcat $fastq \
		`basename $fastq .gz` >filtered_
done
```

I'm not exactly sure what combination triggers this, but it doesn't seem to happen without output redirection. Using `$()` syntax also seems to be handled correctly, which surprised me.

**Comment by mvdan** [comment]
Interesting, thanks for reporting!

**Comment by mvdan** [comment]
Found the culprit, it's a parsing bug caused by a quick way of doing things that I took a few months ago which worked most of the time (but not always, obviously).
