### ISSUE TITLE
syntax: heredocs inside of a process substitution are mangled

### ISSUE THREAD

**Issue by lollipopman** [mvdan/sh#256]
I was trying to use a here doc in a bash process substitution, but shfmt seems to mangle the code:

original:
```
#!/bin/bash
cat <(cat <<-'EOF'
	butter
	bubbles
EOF
)
```
after shfmt:
```
#!/bin/bash
cat <(
	cat <<-'EOF')
		butter
		bubbles
	EOF
```

**Comment by mvdan** [comment]
Heredocs are an endless source of pain. I'll look into this, thanks.

**Comment by mvdan** [comment]
Fixed - thanks again for reporting. The new output is:

```
#!/bin/bash
cat <(
        cat <<-'EOF'
                butter
                bubbles
        EOF
)
```

**Comment by lollipopman** [comment]
awesome, thanks!
