### ISSUE TITLE
syntax: does not parse bash {varname}< redirections correctly

### ISSUE THREAD

**Issue by lollipopman** [mvdan/sh#257]
bash allows you to specify {varname} as the file descriptor to a redirection, with this syntax bash allocates the next available file descriptor and assigns it to varname. shfmt does not appear to recognize this syntax and inserts a space, which breaks the code.

original
```
#!/bin/bash

exec {fd}</etc/motd
cat <&$fd
exec {fd}<&-

printf -v bubbles 'bubbles'
exec {fd}<<<"${bubbles}"
cat <&$fd
exec {fd}<&-

exec {fd}<<-'EOF'
	butter
EOF
cat <&$fd
exec {fd}<&-
```

after passing through shfmt:
```
#!/bin/bash

exec {fd} </etc/motd
cat <&$fd
exec {fd} <&-

printf -v bubbles 'bubbles'
exec {fd} <<<"${bubbles}"
cat <&$fd
exec {fd} <&-

exec {fd} <<-'EOF'
	butter
EOF
cat <&$fd
exec {fd} <&-
```

**Comment by mvdan** [comment]
Thanks for pointing this out - I didn't know this was a Bash feature:

> Each redirection that may be preceded by a file descriptor number may instead be preceded by a word of the form {varname}.  In this case, for each redirection operator except >&- and <&-, the shell will allocate a file descriptor greater than or equal to 10 and assign it to varname.  If >&- or  <&-  is  preceded  by {varname}, the value of varname defines the file descriptor to close.

This will ltake a non-trivial amount of work, as the parser will need help from the lexer, and the syntax tree will need to hold the extra info. Will get to it soon-ish.

**Comment by mvdan** [comment]
The big question is what should `{varname}<foo` do when the parser is not in Bash mode, such as in POSIX or mksh mode.

Option A is do what we do now. This is correct, but a bit dangerous. Formatting such programs in the POSIX mode can break them, and the POSIX parser accepting the programs might make people think that the feature is supported in POSIX.

Option B is to reject it as an error. This is technically breaking with the POSIX standard, but it wouldn't possibly do unexpected things like the above. I'm also thinking that noone would ever write `{varname}<foo` meaning `{varname} <foo`, anyway.

I'm going to go with B for now, and see if it breaks anything. We already drift away from the POSIX spec in a few special cases, so adding another doesn't seem much of a stretch.

**Comment by lollipopman** [comment]
is `{varname}<foo` valid in POSIX or mksh? I couldn't seem to make it do anything in mksh. Bash has this in their docs:

> In addition to the creation of a subshell, there is a subtle difference between these two constructs due to historical reasons. The braces are reserved words, so they must be separated from the list by blanks or other shell metacharacters. The parentheses are operators, and are recognized as separate tokens by the shell even if they are not separated from the list by whitespace.

**Comment by mvdan** [comment]
Yes, it is technically valid. As per POSIX, they simply treat `{varname}` as a separate argument for the command.

```
$ mksh
$ echo {foo}>/dev/stdout
{foo}
```

```
$ dash
$ echo {foo}>/dev/stdout
{foo}
```

**Comment by lollipopman** [comment]
ah, that is nasty, I would then vote for Option B and error. I think it is better to always error when the intent of the syntax is unknown.
