### ISSUE TITLE
syntax: $\" within double quotes is parsed incorrectly

### ISSUE THREAD

**Issue by jraschke** [mvdan/sh#263]
Hi,

I used commit a7d25ad0c897cdcd788fb8b6d7c185d76ee61d10 do build an new version of shfmt.

Now I have a problem with the following shell code, ( part of generating apache vhost files )

```
cat  /tmp/t.sh

vhost="
    <FilesMatch \"\.php$\">
        SetHandler \"proxy:unix:///var/run/fpm_${account}.sock|fcgi://localhost\"
    </FilesMatch>
"
```
It seems that the  combination ` $\"` inside double quotes confuses shfmt.

```
cat  /tmp/t.sh | ~/gocode-test/bin/shfmt  -mn
vhost="
    <FilesMatch \"\.php$${account}.sock|fcgi://localhost\"
    </FilesMatch>
"
```
or shorter:
```
echo ' X="\"test1$\" is test2 with $test3"' | ~/gocode-test/bin/shfmt  -s
X="\"test1$$test3"
```

**Comment by mvdan** [comment]
Oh dear, the fun that backslashes are :)

**Comment by jraschke** [comment]
Hi,

thanks for fixing.

works fine.

Sincere regards,
Juergen
