### ISSUE TITLE
all: /v2 import paths require newer versions of Go

### ISSUE THREAD

**Issue by rmohr** [mvdan/sh#267]
I run into the following issues if I do `go get` for latest master:

```bash
$ go get -u mvdan.cc/sh/cmd/shfmt
package mvdan.cc/sh/v2/fileutil: cannot find package "mvdan.cc/sh/v2/fileutil" in any of:
	/home/rmohr/.gimme/versions/go1.8.3.linux.amd64/src/mvdan.cc/sh/v2/fileutil (from $GOROOT)
	/home/rmohr/go/src/mvdan.cc/sh/v2/fileutil (from $GOPATH)
package mvdan.cc/sh/v2/syntax: cannot find package "mvdan.cc/sh/v2/syntax" in any of:
	/home/rmohr/.gimme/versions/go1.8.3.linux.amd64/src/mvdan.cc/sh/v2/syntax (from $GOROOT)
	/home/rmohr/go/src/mvdan.cc/sh/v2/syntax (from $GOPATH)
```

**Comment by suyanlong** [comment]
me too with golang1.10

**Comment by mvdan** [comment]
You need to use Go 1.9.7 or 1.10.3 or later, since that is when the minimal support for Go modules was backported. See https://golang.org/doc/devel/release.html#go1.10.minor for more details.

Also note that this software requires Go 1.9 or later, as it is clearly stated in the README. I'll add a note about the modules part too.

And, as a general recommendation, you should not depend on master. I try not to break it, but I will make mistakes from time to time. You should be using the latest release, which is v2.5.0 at the moment. It doesn't include this v2 import path either, as I did the switch to Go modules after the release.

**Comment by rmohr** [comment]
> Also note that this software requires Go 1.9 or later, as it is clearly stated in the README. I'll add a note about the modules part too.

Yes, I did it with 1.10 too, just posted the 1.8 output because it was the same.

> And, as a general recommendation, you should not depend on master. I try not to break it, but I will make mistakes from time to time. You should be using the latest release, which is v2.5.0 at the moment. It doesn't include this v2 import path either, as I did the switch to Go modules after the release.

Yes, we were actually using v2.3. It was just that we were using "go get" to fetch the sources and then checkout out v2.3 from it. We are now cloning the repo with git.

**Comment by rmohr** [comment]
Here with the original version:

```
go version go1.10 linux/amd64
package mvdan.cc/sh/v2/fileutil: cannot find package "mvdan.cc/sh/v2/fileutil" in any of:
	/gimme/.gimme/versions/go1.10.linux.amd64/src/mvdan.cc/sh/v2/fileutil (from $GOROOT)
	/go/src/mvdan.cc/sh/v2/fileutil (from $GOPATH)
package mvdan.cc/sh/v2/syntax: cannot find package "mvdan.cc/sh/v2/syntax" in any of:
	/gimme/.gimme/versions/go1.10.linux.amd64/src/mvdan.cc/sh/v2/syntax (from $GOROOT)
	/go/src/mvdan.cc/sh/v2/syntax (from $GOPATH)
```

Still not 1.10.3, so might work with that version.

**Comment by mvdan** [comment]
> It was just that we were using "go get" to fetch the sources and then checkout out v2.3 from it. We are now cloning the repo with git.

Ah, gotcha. Then it's safest to do `go get -d`, which only downloads the packages.

> Still not 1.10.3, so might work with that version.

Yup - the module support was backported in 1.10.3.

**Comment by mvdan** [comment]
I've added a note to the README and updated the issue title, so that others can chime in if they find any issues. I'd like to leave master as it is now, as it shouldn't be a problem for users to either pin v2.5.0, or update their Go bugfix version.

**Comment by rmohr** [comment]
Great. :+1:

**Comment by mvdan** [comment]
I'd like to keep the issue open for a few days, in case others run into the same problem :)

**Comment by gfiedler** [comment]
Here are Go versions coming with some Linux distributions:

* 1.6.2 (ubuntu:16.04)
* 1.7.4 (debian:9)
* 1.9.4 (centos:7)
* 1.10.1 (ubuntu:18.04)

None of them fulfill the installation requirements and the documented `go get -u mvdan.cc/sh/cmd/shfmt` doesn't work anymore.

It would be nice if you would describe how `shfmt` can be installed on such systems.

**Comment by mvdan** [comment]
Also note that Ubuntu 16.04 also has Go 1.10 in its backports repo, but unsurprisingly, it's also four months behind on important bugfixes: https://packages.ubuntu.com/xenial-backports/devel/golang-1.10-go

**Comment by mvdan** [comment]
@rmohr @suyanlong @gfiedler how many of you are still on Go 1.10? I'm thinking of switching to modules again, now that 1.10.3 has been out for almost five months.

**Comment by nihilus** [comment]
Maybe a note should be written in the README.md?

**Comment by mvdan** [comment]
A note about what? There already are install instructions for the stable version v2, as well as the current v3: https://github.com/mvdan/sh#shfmt

**Comment by nihilus** [comment]
@mvdan Maybe I am blind, but I don't see anything about that you need a specific golang version there or how to install v3 if 'go get' fails.

**Comment by mvdan** [comment]
The section specifies you need Go 1.11 or later to install either the latest v2 or v3 with those single-line commands. Older versions can always be installed via manual git checkouts of tags, but that's a more manual process.

I'm not sure what you mean by "how to install v3 if go get fails". If you're on a Go version older than 1.11, you need to upgrade. Otherwise, if you encounter any issues, report them on this issue tracker.

**Comment by nihilus** [comment]
@mvdan Must be the drugs kickin' in, but yes I can see clearly that it is explicitly written now. Like most developers I tend to speed-read things like this. 

I do think it should be stated that it doesn't really require 1.11 and have a reference for e.g. Ubuntu Xenial, which works fine when you clone the branch separately. :-)

**Comment by mvdan** [comment]
Good point; I've added that. I was only trying to get the install section within a reasonable size, which is turning out to be a challenge.

**Comment by nihilus** [comment]
@mvdan makes sense, and yes "less is more for the most".  Hate to bug you, but I created a new issue about what is more like a "feature request" since I use shfmt since years in my company's CD/CI-pipeline and we've got last time I check 75 kLOC of ash/dash scripts.
