### ISSUE TITLE
interp: escaped quotes in arguments

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#269]
```sh
f() {
        eval "echo \"$1\""
}

f "f \"o o\" o"
```

```
bash: f o o o
gosh: "f "o o" o"
```
Seems there is some unescaping missing, though I'm unsure where exactly it should happen.

**Comment by ebfe** [comment]
Even simpler testcase:

```sh
eval "echo  \"f \"o\ o\" o\""
```

So the ParamExpr is not the issue

**Comment by ebfe** [comment]
```sh
echo "\""
```

```
bash: "
gosh: \"
```

**Comment by mvdan** [comment]
Thanks for the report and the fix! Just curious - what do you use these packages for?

**Comment by ebfe** [comment]
> Just curious - what do you use these packages for?

I use interp for evaluating scripts/statements that consist
mostly of variable assignments (e.g. xbps templates) while not
actually executing anything external. This is mostly for
nested conditionals/case patterns and wired parameter expansions that
get too ugly too analyse when working purely from the AST.
