### ISSUE TITLE
printer: comments in empty cases are moved after the case

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#27]
$ cat x.sh
    case $x in
    	foo)
    		# do nothing
    		;;
    	bar)
    		# do something
    		echo bar
    		;;
    esac

    $ shfmt x.sh
    case $x in
    	foo) ;;
    	# do nothing
    
    	bar)
    		# do something
    		echo bar
    		;;
    esac

**Comment by mvdan** [comment]
Thanks for reporting!
