### ISSUE TITLE
stripped semi-colons in for loops within a case statement

### ISSUE THREAD

**Issue by larryhynes** [mvdan/sh#272]
Hi

In the test script

```sh
#!/usr/bin/env sh

case "$x" in
y)
	for a in foo bar baz; do
		echo "$a"
	done
	;;
z)
	for b in foo bar baz; do
		echo "$b"
	done
	;;
esac

```

`shfmt` removes the semi-colon before `do` in the second `for` loop:

`$ shfmt -p -d test.sh`

```diff
diff -u t.sh.orig t.sh
@@ -7,7 +7,7 @@
 	done
 	;;
 z)
-	for b in foo bar baz; do
+	for b in foo bar baz do
 		echo "$b"
 	done
 	;;
```

Is this expected behaviour, or am I missing something here?

**Comment by mvdan** [comment]
The tool is indeed breaking the program - thanks for reporting! This will likely be a very silly bug or a very tricky edge case.
