### ISSUE TITLE
cmd/shfmt: document -d's non-zero exit status behavior

### ISSUE THREAD

**Issue by PeterDaveHello** [mvdan/sh#274]
Hi @mvdan,

I'd like to integrate `shfmt` with various tests on CI, would it be possible to support to return non-zero exit status when any file was changed(with `-w`), so that we can fail the CI task?

Many thanks!

**Comment by mvdan** [comment]
Currently this is possible with `shfmt -d`, which is what most people use on CI.

I guess we could add the behavior to `shfmt -w`, but that would break a lot of existing scripts and programs. Right now, an exit code 1 there means "something went wrong" as opposed to "some files were modified".

**Comment by mvdan** [comment]
@PeterDaveHello I forgot to specifically ask - does `shfmt -d` solve your problem? If so, this issue can be closed. If not, we may come up with something else, but breaking `shfmt -w` is not an option.

**Comment by PeterDaveHello** [comment]
@mvdan not very exactly as the first comment, but yes, I can use `-d` to archive the non-zero return, just didn't realize the return of `-d` is different with `-w`, will like to send a pull request for that info(and close this issue by that PR), should I?

**Comment by mvdan** [comment]
That's a good point - I'll clarify this in the documentation.
