### ISSUE TITLE
syntax: indents comments documenting an elif/else branch

### ISSUE THREAD

**Issue by Carpetsmoker** [mvdan/sh#279]
The following program:

	# Documenting this if.
	if :; then
		:
	# Documenting this elif.
	elif :; then
		:
	# Documenting this else.
	else
		:
	fi

Gets formatted by `shfmt` to:

	# Documenting this if.
	if :; then
		:
		# Documenting this elif.
	elif :; then
		:
		# Documenting this else.
	else
		:
	fi

The comments documenting the branches get indented, which is unexpected.

**Comment by mvdan** [comment]
Thanks for reporting this! This issue is a bit tricky. Right now the formatter is based mostly on line numbers, and based on those we can't know if that comment is for the block or for the else.

I believe that gofmt has a solution to this, which is to understand that distinction based on the previous indentation. I need to investigate that and play with it. If you have any ideas, feel free to let me know.

**Comment by Carpetsmoker** [comment]
gofmt doesn't really have the issue with `else if` and `else`, as the closing braces need to be on the same line:

```go
if true {
    ...
    // Will always be indented.
} else {
    ...
}
```

It does have a similar ambiguity with `switch`/`case`, where it will accept both indented and on the same level as the `case`:

```go
	switch "X" {
	case "X":
		// Always indented.
		fmt.Println("X")
	// Documenting the case.
	case "Y":
		fmt.Println("X")
		// Indented doc.
	case "Z":
		fmt.Println("X")
	}
```

I don't know the technical implementation, but from looking at how it behaves, it looks like it checks if the comment block is followed by a `case`, and if so, it accepts one of either indentation.

**Comment by mvdan** [comment]
Yes - switch cases are indeed what I meant when it comes to `gofmt`. I had forgotten that Go's ifs have explicit statement tokens :)

**Comment by mvdan** [comment]
The issue is actually trickier for elses - we currently don't attach comments to `else` or `elseif`, so the comments get put with the previous blocks. Need to figure out how to fit the comments first.

**Comment by mvdan** [comment]
@Carpetsmoker please have a look at the changes made in master; this should fix your problem. I'll release 2.6 sometime later this month, so it would be great if you could verify that the feature works well for you before I release the final version.

**Comment by Carpetsmoker** [comment]
Yup, this has been working well for me for the last week; thanks :+1:

**Comment by mvdan** [comment]
Awesome - thanks for confirming!
