### ISSUE TITLE
ppc64le support?

### ISSUE THREAD

**Issue by leth** [mvdan/sh#280]
Would it be possible to add ppc64le to the list of available architectures?

An contributor to one of our projects has [requested that we disable shfmt linting if it is not installed](https://github.com/weaveworks/build-tools/pull/139) as a version is not available for ppc64le.

I was going to open a PR, but I had a look in the repository but couldn't find any configuration for how releases are build.

**Comment by mvdan** [comment]
This package is written purely in Go, so in theory any target that is supported by Go should work.

As to what tool I use to build the binaries, I use https://github.com/mitchellh/gox with certain flags. In particular, `gox -gocmd=/usr/bin/go -ldflags='-w -s' -output="{{.Dir}}_$(git describe)_{{.OS}}_{{.Arch}}"`.

As you can see in https://github.com/mitchellh/gox/blob/master/platform.go, by default the tool only builds binaries for certain popular targets. The `linux/ppc*` ones aren't enabled by default, as you can see in https://github.com/mitchellh/gox/blob/master/platform.go.

I can understand that it would be convenient if all the binaries were provided, but I wonder if that's necessary. I imagine that users on rare platforms/architectures are already used to building binaries on their own. I could double the amount of published binaries of course, but there's a tradeoff to be made here.

**Comment by leth** [comment]
Thanks for the info!

> I could double the amount of published binaries of course, but there's a tradeoff to be made here.

Of course! It's your call, feel free to close this issue :) I don't have a good idea of which platforms are the popular ones.

**Comment by mvdan** [comment]
I've had a quick look around, and most projects written in Go only provide a handful of binaries, if any. So by any metric, I think the amount of platforms that I build binaries for is already acceptable. I'll close this issue for now.
