### ISSUE TITLE
interp: About the stability of the API

### ISSUE THREAD

**Issue by andreynering** [mvdan/sh#283]
I know the interpreter API is currently unstable, as said by the documentation:

> This package is a work in progress and EXPERIMENTAL; its API is not subject to the 1.x backwards compatibility guarantee.

Asking anyways: do you have a roadmap to make it stable (i.e. disallowing [most] background incompatible changes on future releases)?

While that don't happen, it'd be nice to have a minimal example somewhere (GoDoc? README?) showing how to run a simplest sh command using interp. If you change the API, you should change this example as well

**Comment by mvdan** [comment]
Completely agreed that examples are needed. I need to add some :)

About stability - refactoring the constructors and modules has been part of that. The old API was a lazy hack, and the new one is better designed. I need to think about any other changes that I'd wish to make before I remove the experimental notice.

As for the timeline, I'd like to do that before the end of the year - ideally in the next couple of months.

**Comment by ebfe** [comment]
While we're at the topic of stability, are you set on how ModuleOpen works
right now? I've recently been wondering whether it wouldn't make more sense to
have all the filesystem access that the shell does to go through it
(globs/binary lookups etc.). Though this might get a bit tricky at exec time.

**Comment by mvdan** [comment]
`Chdir` should also be included in the filesystem module, as it affects how relative paths work.

**Comment by ebfe** [comment]
I kind of like the approach of [net/http.Filesystem](https://golang.org/pkg/net/http/#FileSystem), that might be worth copying.

**Comment by mvdan** [comment]
Such a limited interface is also an option - this is similar to what we do currently. However, there are some limitations:

* How do we handle `stat` versus `lstat`?
* To `lstat` a file, we must `open` it first
* We're missing an equivalent of `os.SameFile`, which isn't as trivial as it may seem

The second point is purely performance, so one can say it's not a priority. And the third could be done on a best-effort basis. I agree that a simpler API would be nicer, but I'm not convinced that it can be done - particularly, when it comes to the first point.

**Comment by ebfe** [comment]
Oh, now I see. I had mostly cd/globbing/path lookup in mind. But
interp/test.go is a completly different story :/

You are probably right and the solution is the interface you initially
proposed.

**Comment by mvdan** [comment]
Completely ignoring the test family of filesystem syscalls is also an option - that's what we do now. But as you can imagine, that greatly limits what the module can do. So I think we should completely abstract away the filesystem, one way or another.

**Comment by andreynering** [comment]
@mvdan Thanks! In fact it makes sense to complete these refactorings before "releasing" the stable version

I don't have a strong opinion on the discussion above, but I think interfaces will probably be more flexible and powerful

**Comment by mvdan** [comment]
I've made good progress on the biggest chunk of work I wanted to do here - decoupling field/parameter expansion from the interpreter. You can see the current state in the new `mvdan.cc/sh/expand` package, which is allowing to add higher-level APIs in `mvdan.cc/sh/shell` without using the interpreter and potentially running arbitrary code.

I'm pretty much done with the refactor, now I just need to clean up a few things and polish the API. Then I'll be free to stabilize `interp` for v2 :) Apologies for not having done this sooner.

**Comment by andreynering** [comment]
🎉🎉🎉

Thanks for all your work @mvdan!

Just a reminder: do not forget updating the README/documentation with a few examples. 😉

**Comment by mvdan** [comment]
Thanks for the reminder - these are very important, so I'll create a separate issue.
