### ISSUE TITLE
sqlplus with EOF formatting

### ISSUE THREAD

**Issue by plorenc** [mvdan/sh#284]
When calling sqlplus this way:
```
RETVAL=`sqlplus -S ${V_LOGIN_CTDL_SQL} <<EOF
${SQL_COMMAND}
EOF`
```
all the text below is formatted as a sql command continuation - not as a continuation of shell script.

**Comment by mvdan** [comment]
Sorry, I don't understand this issue. Please show what you ran with `shfmt`, what you got, and what you expected.

**Comment by plorenc** [comment]
Hi Daniel, 
Maybe I was wrong putting this there. Let me explain. 
There is an Visual Studio Code extension called shell-format. It uses shfmt to do its job. 
I do not know whether the issue is connected more with shfmt or shell-format extension. Then if it is not a shfmt issue then forget about it. 

There is a print-screen from VSC from a wrong formatted shell script:
![image](https://user-images.githubusercontent.com/20758652/44796693-d372ad00-abad-11e8-8f2b-7e51f741a8a1.png)
You can see that before using << EOF the formatting is OK.
It should look like this (but I had to remove "<< EOF" from the line 70 and it is necessary):
![image](https://user-images.githubusercontent.com/20758652/44797093-9ce96200-abae-11e8-9c10-4cc7aa4ea1e5.png)

**Comment by mvdan** [comment]
I don't know the shell-format extension well, but as far as I know, the only thing it does is formatting code. That is, rewriting it to be properly indented and so on. This library could certainly be used to implement syntax highlighting, but I don't think it's being used here.

The proof is that this library would parse that program correctly, and highlight the code properly. So perhaps you should ask visual studio or the extension author to switch to this shell parser library :)

Closing this for now.
