### ISSUE TITLE
syntax: add support for indentation of pushd/popd

### ISSUE THREAD

**Issue by GregorySWI** [mvdan/sh#293]
It would be great if there was an option to have shfmt indent code in "pushd"/"popd" blocks. This makes it so much easier to read, and debug the block, as it is easier to see what directory a given section of code is affecting.

I can see an argument that if we do this for pushd/popd, we should do it for "cd"/"chdir", but the latter do not use a stack, and there really is no closing tag to "cd"/"chdir". "pushd"/"popd" by it's nature lends to this type of formatting.

An example:

Current:
```
printf "abc123\n"
pushd /var/tmp || exit 1
wget https://google.com
pushd ~ || exit 1
printf "Home at last!\n"
popd || exit 1
find . -type f -name "google" -print
pushd /root || exit 1
printf "Bow before me, for I am root!\n"
popd
popd
```

Proposed:
```
printf "abc123\n"
pushd /var/tmp || exit 1
    wget https://google.com
    pushd ~ || exit 1
        printf "Home at last!\n"
    popd || exit 1
    find . -type f -name "google" -print
    pushd /root || exit 1
        printf "Bow before me, for I am root!\n"
    popd
popd
```

**Comment by mvdan** [comment]
It's true that pushd/popd use a stack, that they're common in Bash programs, and that some scripts would be more readable that way. However, I'm generally against doing this for several reasons:

* `pushd` and `popd` are simply Bash shell builtins. In other words, the `syntax` package doesn't know about them, nor should it ever.
* These builtins can be called in other ways, e.g. `cmd=popd; $cmd`
* The names can be redeclared to mean other things, e.g. `popd() { exit 0; }; popd`
* It's unclear to me if we should also indent on cases like `pushd /some/dir && some other command`

If you want to indent your pushd/popd stacks, I think it would be best to do that with explicit blocks, which *are* part of the shell syntax. You could thus write:

```
# outer code
pushd /some/dir
{
    # inner code
}
popd
```

I know it's a bit verbose, but it doesn't have any of the issues that I listed above, and works today already. What do you think?

**Comment by GregorySWI** [comment]
Yes, your suggestion makes sense, but not everyone will know to use that formatting (unless they see this FR). Would it be possible to add it as an optional feature, for the default usage of pushd/popd, and add it as a command line option, similar to issue 168 (https://github.com/mvdan/sh/issues/168)?

Making non-standard calls like `cmd=popd; $cmd` and redeclaring the function can happen with almost any command, and probably should be ignored or accepted as something that can't be detected. With the one liners, there should still be a popd to properly clear the stack, so maybe indent the whole one liner:

`printf "some code here\n"
    pushd /some/dir && some other command && popd
printf "some other code here\n"`

**Comment by mvdan** [comment]
To be honest, sometimes I wish I hadn't added an option for #168. Out of all the non-trivial flags into the parser and printer I've added, it's by far the most complex and what requires the most hours of bugfixing and head-scratching.

The one feature we could potentially add to `syntax.Printer` could be something like:

```
// IndentWordPair sets up a pair of opening and closing words to indent and unindent code in the printer.
// Note that these words will still be treated like any other, as they cannot be added as reserved words without breaking valid shell programs.
//
// For example, one may use IndentWordPair("pushd", "popd") to make the pushd directory stacks be indented visually.
func IndentWordPair(opening, closing string)
```

And then exposed via something like:

```
shfmt -iw 'pushd;popd,foo;bar'
```

At least this wouldn't add extra special words to the printer. So that solves point 1.

Point 2 and 3 I guess we can ignore; this would only match the commands when they appear in their direct form.

Point 4 (one-liners) I think should be left alone. The code would get too complex if we suddenly have to handle all these edge cases. I'd have this only work if the matched commands happen as a sole simple command on their own line.

I'm still on the fence about this, which usually means I shouldn't add a feature :)

**Comment by mvdan** [comment]
Pulling in past contributors, to try and get more feedback - @ebfe @andreynering @PeterDaveHello @meatballhat

**Comment by GregorySWI** [comment]
I like this suggestion, and I think it would be easier to maintain that the alternative I had thought of, which was adding a custom formatting API (i.e. a custom formatting overrides config file). I also think your solution would solve a lot of potential future custom formatting requests (although not the multi-line text alignment issue in #168 ). Going the custom formatting API route, you would have to account for all sorts of unexpected formatting configs, this route you only need account for string pairs. I wouldn't even worry about making sense of the pairs, because again, validating the pairs are valid commands would introduce a lot of maintenance work. Simply indent based on the word pairs, if they exist. Don't indent if the second word can't be found (i.e. don't worry about bad end user syntax).

**Comment by andreynering** [comment]
I never touched the formatter code (still), and I don't use it a lot, so no strong thoughts.

I think this decision should be based on whether this formatting style is used often enough in the wild, and on how complex it'd be to implement and maintain it.

**Comment by mvdan** [comment]
I've decided not to do this. The feature would make the syntax package concern itself with concepts that aren't related to syntax at all, and in the process it would get quite a bit more complicated (see my points above).

If this kind of indentation were popular, the need for the feature might outweigh the costs. As far as I've been able to see, that's not the case. For now, if one really wants to indent those, an explicit block seems like a reasonable option.

If other people would find this useful and can show proof that indenting this way is common, please speak up. We can always reopen and reconsider in the future.
