### ISSUE TITLE
cmd/gosh: problem with multiline unclosed quotes

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#295]
`gosh` sometimes incorrectly handles multiline statements with unclosed quotes.

```
~$ gosh
$ echo "f
> oo"
f
oo
$ echo "foo"; echo "b
foo
$ ar"
b
ar
$ echo "foo"; echo "b\
foo
$ ar"
bar
$ 
```

The 1st multi-line command with an unclosed quote was handled correctly.

The 2nd and 3rd are not handled correctly.

- `foo` is printed too early.
- the wrong prompt is shown.

**Comment by rob-myers** [comment]
I have a related issue with `gosh`.
Spreading binary operands over multiple lines works, but the prompt is incorrect.

```
~$ gosh
$ echo foo ||
$ bar
foo
$ echo bar | 
$ read line; echo $line
bar
```

The prompt is wrong at line `$ bar` and line `$ read line; echo $line`.

**Comment by mvdan** [comment]
Thanks for noticing! I'm going to split this into a new issue, since that makes tracking the commit simpler.
