### ISSUE TITLE
_js: add parser options

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#297]
To get the parser options working I'm using a hack e.g.

```js
const parser = syntax.NewParser();
parser['Parser'].__internal_object__.keepComments = true;
```

Is there a better way?

**Comment by mvdan** [comment]
I didn't even know this was possible :)

The better way is for me to expose these APIs in the JS wrapper code, which I haven't done yet. I'll add some for the next release.

**Comment by mvdan** [comment]
You should now be able to do this as soon as I publish a new version on NPM later today. For example, `var parser = syntax.NewParser(syntax.KeepComments)`. You can always look at `testmain.js` for more examples.
