### ISSUE TITLE
parser: solve $(( vs $( ( ambiguity with backtracking

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#30]
`$((` marks the start of an arithmetic expansion, `$(` marks the start of a command substitution and `(` marks the start of a subshell. Examples:

```
 $ echo -n 'echo $((1+2))' | bash
3
 $ echo -n 'echo $( (echo foo) | cat)' | bash
foo
```

This is easy, because we know how we should parse what follows the starting tokens directly. In other words, this is a `LL(k)` language - we don't have to backtrack.

The fun begins here:

```
 $ echo -n 'echo $((echo foo) | cat)' | bash
foo
```

Even though this should be parsed as an arithmetic expansion, it's parsed as a subshell inside a command substitution. Our parser fails at this, because it does no backtracking at all and errors on the invalid arithmetic expression:

```
 $ echo -n 'echo $((echo foo) | cat)' | shfmt
1:14: not a valid arithmetic operator: echo
```

This is clearly a bash thing, not a POSIX Shell thing:

```
 $ echo -n 'echo $((echo foo) | cat)' | dash
dash: 1: Syntax error: Missing '))'
 $ echo -n 'echo $((echo foo) | cat)' | busybox ash
ash: syntax error: missing '))'
```

Sounds to me like POSIX Shell is indeed `LL(k)`, but that bash is `LL(*)`. In other words, we may have to consume an unknown number of characters before we know what we should do with the following token.

Should we make our parser backtrack?

**Comment by dmage** [comment]
It seems that backtracking is a part of [POSIX specification](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_03):
> the shell shall first determine whether it can parse the expansion as an arithmetic expansion and shall only parse the expansion as a command substitution if it determines that it cannot parse the expansion as an arithmetic expansion.

**Comment by mvdan** [comment]
@dmage nice find, thanks. Since neither dash nor ash support this, I was assuming that the POSIX spec couldn't have defined this. If this is true, that makes both shells incompatible with POSIX, unless I'm missing something.

**Comment by mvdan** [comment]
Ah, I hadn't seen this because I was using an older POSIX spec: http://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html

This might also explain why dash/ash and others don't implement this yet.

**Comment by jillest** [comment]
Although the backtracking implementation is certainly valid, POSIX does not require it. Note that:

- shells may have extensions to arithmetic expressions, e.g. `$((cat * myfile[0-9]))` is not a valid arithmetic expression in a pure POSIX shell but is in a shell with arrays
- the effect of nested expansions is not fully specified

As maintainer of FreeBSD sh I do not plan to change its behaviour (`$((` always introduces arithmetic expansion), since this would involve unreliable and complex heuristics.

I do not expect dash and busybox ash to change here either.

**Comment by mvdan** [comment]
Hey @jillest! Thanks for dropping by. I'm currently rewriting the parser to use a stream (chunks of bytes) instead of the entire program in memory, so backtracking is proving to be a pain in the ass. It basically means the parser may need to hold any number of past bytes in memory. You mentioning that it's not the only approach is very good news.

> Although the backtracking implementation is certainly valid, POSIX does not require it
> shells may have extensions to arithmetic expressions

Could you cite these? For example, below I cite what I understand to be the opposite in the latest POSIX Shell spec.

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_03 says:

> The syntax of the shell command language has an ambiguity for expansions beginning with "$((", which can introduce an arithmetic expansion or a command substitution that starts with a subshell. Arithmetic expansion has precedence; that is, the shell shall first determine whether it can parse the expansion as an arithmetic expansion and shall only parse the expansion as a command substitution if it determines that it cannot parse the expansion as an arithmetic expansion. The shell need not evaluate nested expansions when performing this determination. If it encounters the end of input without already having determined that it cannot parse the expansion as an arithmetic expansion, the shell shall treat the expansion as an incomplete arithmetic expansion and report a syntax error. A conforming application shall ensure that it separates the "$(" and '(' into two tokens (that is, separate them with white space) in a command substitution that starts with a subshell.

Maybe I'm misreading or misunderstanding "shall".

> As maintainer of FreeBSD sh I do not plan to change its behaviour ($(( always introduces arithmetic expansion), since this would involve unreliable and complex heuristics.
>
> I do not expect dash and busybox ash to change here either.

I agree that supporting ambiguity makes no sense. I added backtracking not because bash supported it, but because it seemed like POSIX Shell specified it. If you're indeed proving otherwise, I'll be very happy to get rid of the nonsense. After all, supporting all of bash in a standalone, static parser is impossible (see #49 for another example).

**Comment by mvdan** [comment]
Ping @jillest - would be great to have confirmation on your claim :)

**Comment by mvdan** [comment]
I ended up removing it altogether. The reason, besides all the madness, is that POSIX says:

> A conforming application shall ensure that it separates the "$(" and '(' into two tokens (that is, separate them with white space) in a command substitution that starts with a subshell.

In other words, people should not rely on the `$((` ambiguity anyway. See the commit message for more details.

**Comment by jillest** [comment]
I'll admit the formulation is not the clearest. I think the idea is that FreeBSD sh considers it can parse anything as an arithmetic expression that ends with literal `))` skipping matching pairs of parentheses; if it is actually invalid, a run-time expansion error occurs.

**Comment by mvdan** [comment]
Thanks for the clarification. That's what this parser used to do - it tokenized until it found EOF or a closing `))` (getting past matching parentheses).

Whether it is tokenizing or just looking at bytes, either will not work with the current lexer as it only looks at a limited number of bytes at a time - 1024 at the moment.
