### ISSUE TITLE
Parsing history with sh

### ISSUE THREAD

**Issue by barthr** [mvdan/sh#311]
Hi, I'm looking at this package to parse commands from my history file. I was thinking of building my own parser, then I discovered you package. I'm having a hard time doing the actual parsing for example on:

```TEST=1 nasm -f elf_i386 -o calc out```

My goal is to essentially map it to an internal structure.

My command struct looks like the following:
```go
type Command struct {
	Path       string   //nasm
	Args       []string  //out
	Env        map[string]string  // [TEST:1]
	Flags      map[string]string //[-f:elf_i386, -o:calc]
	ExecutedAt time.Time // not important for now
}
```

I tried to `syntax.Walk()` the parsed content but I'm getting stuck. Do you have any tips for parsing this?

The output of the debugging shows the following.

```
*syntax.File {
.  Name: ""
.  StmtList: syntax.StmtList {
.  .  Stmts: []*syntax.Stmt (len = 1) {
.  .  .  0: *syntax.Stmt {
.  .  .  .  Comments: []syntax.Comment (len = 0) {}
.  .  .  .  Cmd: *syntax.CallExpr {
.  .  .  .  .  Assigns: []*syntax.Assign (len = 1) {
.  .  .  .  .  .  0: *syntax.Assign {
.  .  .  .  .  .  .  Append: false
.  .  .  .  .  .  .  Naked: false
.  .  .  .  .  .  .  Name: *syntax.Lit {
.  .  .  .  .  .  .  .  ValuePos: 1:1
.  .  .  .  .  .  .  .  ValueEnd: 1:6
.  .  .  .  .  .  .  .  Value: "GOENV"
.  .  .  .  .  .  .  }
.  .  .  .  .  .  .  Index: nil
.  .  .  .  .  .  .  Value: *syntax.Word {
.  .  .  .  .  .  .  .  Parts: []syntax.WordPart (len = 1) {
.  .  .  .  .  .  .  .  .  0: *syntax.Lit {
.  .  .  .  .  .  .  .  .  .  ValuePos: 1:7
.  .  .  .  .  .  .  .  .  .  ValueEnd: 1:8
.  .  .  .  .  .  .  .  .  .  Value: "1"
.  .  .  .  .  .  .  .  .  }
.  .  .  .  .  .  .  .  }
.  .  .  .  .  .  .  }
.  .  .  .  .  .  .  Array: nil
.  .  .  .  .  .  }
.  .  .  .  .  }
.  .  .  .  .  Args: []*syntax.Word (len = 6) {
.  .  .  .  .  .  0: *syntax.Word {
.  .  .  .  .  .  .  Parts: []syntax.WordPart (len = 1) {
.  .  .  .  .  .  .  .  0: *syntax.Lit {
.  .  .  .  .  .  .  .  .  ValuePos: 1:9
.  .  .  .  .  .  .  .  .  ValueEnd: 1:13
.  .  .  .  .  .  .  .  .  Value: "nasm"
.  .  .  .  .  .  .  .  }
.  .  .  .  .  .  .  }
.  .  .  .  .  .  }
.  .  .  .  .  .  1: *syntax.Word {
.  .  .  .  .  .  .  Parts: []syntax.WordPart (len = 1) {
.  .  .  .  .  .  .  .  0: *syntax.Lit {
.  .  .  .  .  .  .  .  .  ValuePos: 1:14
.  .  .  .  .  .  .  .  .  ValueEnd: 1:16
.  .  .  .  .  .  .  .  .  Value: "-f"
.  .  .  .  .  .  .  .  }
.  .  .  .  .  .  .  }
.  .  .  .  .  .  }
.  .  .  .  .  .  2: *syntax.Word {
.  .  .  .  .  .  .  Parts: []syntax.WordPart (len = 1) {
.  .  .  .  .  .  .  .  0: *syntax.Lit {
.  .  .  .  .  .  .  .  .  ValuePos: 1:17
.  .  .  .  .  .  .  .  .  ValueEnd: 1:25
.  .  .  .  .  .  .  .  .  Value: "elf_i386"
.  .  .  .  .  .  .  .  }
.  .  .  .  .  .  .  }
.  .  .  .  .  .  }
.  .  .  .  .  .  3: *syntax.Word {
.  .  .  .  .  .  .  Parts: []syntax.WordPart (len = 1) {
.  .  .  .  .  .  .  .  0: *syntax.Lit {
.  .  .  .  .  .  .  .  .  ValuePos: 1:26
.  .  .  .  .  .  .  .  .  ValueEnd: 1:28
.  .  .  .  .  .  .  .  .  Value: "-o"
.  .  .  .  .  .  .  .  }
.  .  .  .  .  .  .  }
.  .  .  .  .  .  }
.  .  .  .  .  .  4: *syntax.Word {
.  .  .  .  .  .  .  Parts: []syntax.WordPart (len = 1) {
.  .  .  .  .  .  .  .  0: *syntax.Lit {
.  .  .  .  .  .  .  .  .  ValuePos: 1:29
.  .  .  .  .  .  .  .  .  ValueEnd: 1:33
.  .  .  .  .  .  .  .  .  Value: "calc"
.  .  .  .  .  .  .  .  }
.  .  .  .  .  .  .  }
.  .  .  .  .  .  }
.  .  .  .  .  .  5: *syntax.Word {
.  .  .  .  .  .  .  Parts: []syntax.WordPart (len = 1) {
.  .  .  .  .  .  .  .  0: *syntax.Lit {
.  .  .  .  .  .  .  .  .  ValuePos: 1:34
.  .  .  .  .  .  .  .  .  ValueEnd: 1:37
.  .  .  .  .  .  .  .  .  Value: "out"
.  .  .  .  .  .  .  .  }
.  .  .  .  .  .  .  }
.  .  .  .  .  .  }
.  .  .  .  .  }
.  .  .  .  }
.  .  .  .  Position: 1:1
.  .  .  .  Semicolon: 0:0
.  .  .  .  Negated: false
.  .  .  .  Background: false
.  .  .  .  Coprocess: false
.  .  .  .  Redirs: []*syntax.Redirect (len = 0) {}
.  .  .  }
.  .  }
.  .  Last: []syntax.Comment (len = 0) {}
.  }
}
```

From the godoc I took that assigns are the environment values being passed. So those can be set by walking the tree, making the distinction for the flags would just be to check for '-' and then take the next literal as the value for the flag ?

**Comment by mvdan** [comment]
If you want to look at the syntax tree, `syntax.DebugPrint` should be useful to get a good idea.

From looking at my own `.bash_history`, I can see that more than just simple commands get saved. For example, if I run `if foo; then bar; fi` and exit the shell, that entire line gets added to my `.bash_history`.

Similarly, if I do `foo; bar`, that line with two commands gets added to the history.

So I don't think you can parse an entire shell history file as just simple commands. Each line in that file can contain any number of commands, and they might not be calls to a function or a program - they might be an if clause or a for loop.

In practice, each line in the history file is the same that an interactive shell can take as input - any number of full commands. In our syntax tree, that's https://godoc.org/mvdan.cc/sh/syntax#Stmt.

Then, a simple command (e.g. a call to `nasm`) is https://godoc.org/mvdan.cc/sh/syntax#CallExpr. A Stmt can contain that, but it can also contain an `IfClause`, for example.

So I think your `Command` struct above is not a great abstraction. It will only work for some of the lines in a history file, I think.

**Comment by barthr** [comment]
Thanks for the quick response! I've been playing a bit with the `DebugPrint` and that is very helpful. I think I found a way to properly walk the tree now. The abstraction is actually the only data I'm interested in. I want create some statistics based on which commands are executed with which arguments and flags. To generate (for example) the top 10 used commands in the past week or past hour, for this I'm not interested in if statements and such but only in executed programs and their arguments/flags.

**Comment by mvdan** [comment]
If you're only interested in the simple commands that appear anywhere in each history line, then you simply need to walk the history file and take note of each `syntax.CallExpr`. There, you have the assignments and arguments.

You can obtain the source code from those simple commands or words via `syntax.Printer.Print`. If you do that however, do note that `echo $foo` will remain that way, as a syntax tree has no notion of environment variables or parameter expansion.

Keeping track of which arguments are flags can also be tricky. For example, to some programs, `foo -bar` is a single flag, but to others it's the same as `foo -b -a -r`. And some others may not take any flags, so `-bar` may just be an argument.

**Comment by barthr** [comment]
Thank you for the advise, it is very helpful. As for the flags, that is something which you can never know until you parse the flag behavior of that particular program. Currently that is out of scope for my plan. I will parse `-bar` just as `flags: [bar:""]` ignoring the fact that it could also be an argument.
