### ISSUE TITLE
syntax: Clarification of {DblQuoted,FuncDecl,Stmt}.Position

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#313]
Is this always the same value as `Pos()`?

**Comment by mvdan** [comment]
Some nodes have position fields when it's not possible to infer the position from their children nodes.

For example, a function declaration might be `foo() { bar; }` in which case it can use `Lit.Pos()` from its name. But if it's `function foo() { bar; }`, it can't rely on that.

In general, if you want the start/end positions, use `Pos()` and `End()`. The other fields should only be used as they are documented. For example, `Stmt.Semicolon` can be used to tell if a statement had a semicolon-like end token, and where it was.
