### ISSUE TITLE
syntax: add example of multiple Word.Parts

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#314]
Could you provide an example where [`Word.Parts`](https://godoc.org/mvdan.cc/sh/syntax#Word) has more than one item?

**Comment by mvdan** [comment]
That's a good idea - will do.

**Comment by rob-myers** [comment]
To clarify: I don't know of any example.
Do you only represent it as a list because `ExpandBraces()` can return multiple words?

**Comment by mvdan** [comment]
Not exactly. Imagine `foo${bar}'baz'`. That's one single word with three word parts - a literal, a parameter expansion, and a single-quoted literal.

**Comment by mvdan** [comment]
@rob-myers please have a look at https://godoc.org/mvdan.cc/sh/syntax#example-Word. If you think it isn't clear enough or that it could be improved, please reopen this issue or send a PR.
