### ISSUE TITLE
can't format "&>" correctly

### ISSUE THREAD

**Issue by laishulu** [mvdan/sh#315]
```
type rustup &> /dev/null
```
is formatted to 
```
type rustup &
> /dev/null
```

**Comment by mvdan** [comment]
I don't follow:

```
$ shfmt <<<'type rustup &> /dev/null'
type rustup &>/dev/null
```

Also, the title shows `&<`, not `&>`. I don't think the former is a valid token.

**Comment by laishulu** [comment]
Yep, you are right.
I don't know why I got the wrong output in `emacs`, while I got the right output in command line.

**Comment by mvdan** [comment]
It could be that your editor plugin is running `shfmt` in POSIX Shell mode:

```
$ shfmt -p <<<'type rustup &> /dev/null'
type rustup &
>/dev/null
```

Still, that's not a bug. `&>` is not a token in POSIX Shell, so it's interpreted as `& >`, which means one background command, and then a second command starting with a redirection.

**Comment by laishulu** [comment]
thanks for your quick and detail explaination.
