### ISSUE TITLE
syntax: some syntactic information is lost during parsing

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#319]
Parsing `[[ ${x} = "foo" ]]` yields a `BinaryTest` whose operation is `equal` with symbol `==`.

Semantically this makes sense -- the alternative is `assign` with symbol `=`.
But shouldn't the parser reference the actual symbol, as opposed to its meaning?

**Comment by mvdan** [comment]
From `man bash`:

> The = operator is equivalent to ==.

It's not possible to assign to anything within a Bash test expression. It's only possible within an arithmetic expression. So I'm not sure I understand your suggestion; `=` is parsed as a `==`, because the latter is a clearer form that should always be used.

**Comment by rob-myers** [comment]
Yep, that's why I said it makes sense semantically.

But syntactically you lose information i.e. the part of the code corresponding to the symbol.
Your source map includes `OpPos` but using the length of `==` I'd get  `= ` in my example.

**Comment by mvdan** [comment]
Ah, gotcha. Do you need the original symbol for any specific reason? I guess that would be required for some use cases, like syntax highlighting.

I generally agree that this shouldn't be done in the syntax package; it's just not the place for it. The rewriting should likely happen in `syntax.Simplify`.

There are other instances of syntactic information being lost in the parser, though. I'll need to look into all these cases as part of v3.

**Comment by rob-myers** [comment]
Yes, I need it for syntax highlighting. Obviously not a big issue, but it came up while transpiling your parse trees. Congrats on v2 btw, it is a great package.

**Comment by mvdan** [comment]
@rob-myers thanks for the follow-up - I agree that this is inconsistent behavior in the parser. I'll have a look for v3, since this would be a breaking change in v2. The JS package will track the latest v3 version though, so you should be able to get that sooner than the final v3.0.0 release.

**Comment by mvdan** [comment]
I'm closing this for now; these were the two cases that came to mind. If you find others, I'm happy to look at more fixes.
