### ISSUE TITLE
cmd/shfmt: publish to homebrew

### ISSUE THREAD

**Issue by focusaurus** [mvdan/sh#32]
Would you consider publishing this to the homebrew OSX package manager? I am able to get it running from go source, but I think making a binary available through homebrew would greatly increase the reach of this package.

Aside: I'm also attempting to write an atom text editor plugin to format a shell script through shfmt.

**Comment by mvdan** [comment]
@focusaurus I've never used a mac and don't have one to test or do this with. Does it still make sense for me to take care of it?

I'm packaging `shfmt` for the Arch user repo and other people are doing it for NixOS and VoidLinux. I would assume homebrew doesn't require upstream to do it directly?

I've tried to find whether or not I need a mac to add a package to homebrew, but haven't been successful.

Also note that I already upload cross-compiled binaries of each release on https://github.com/mvdan/sh/releases. I don't know if that is useful to you or towards a homebrew package, but don't know if you're aware of it.

**Comment by focusaurus** [comment]
Well I think it makes the most sense for it to be scripted alongside posting to the other package ecosystems. I'm not experienced with maintaining a package in homebrew either. The template that seems probably very similar to this project would be [the keybase brew script](https://github.com/keybase/client/blob/master/packaging/brew/brew.sh) where they mostly automate a PR into homebrew for their keybase client project, which is also a golang command line utility.

Grabbing the cross-compiled binary is easier than building via go, so that's good to know (I was not aware of that).

No, homebrew does not AFAIK require the upstream maintainer to handle the homebrew package work. If I can get that mostly templated in a sitting or two, I might be willing to shepherd the homebrew work. But if it's too cumbersome I'll probably just curl the binary and get on with my life.

**Comment by mvdan** [comment]
@focusaurus I still think it's overall better for someone who uses mac to maintain it in homebrew. I'm in no way asking you to do it, more like I feel like I would be limited in terms of understanding what's going on and being able to reproduce issues with the package.

If you would like someone else to maintain it, I can leave this issue open with the "help-wanted" tag to see if anyone would be able to help.

**Comment by focusaurus** [comment]
OK so I was able to define a homebrew configuration for this. It is [here](https://github.com/focusaurus/homebrew-core/blob/shfmt/Formula/shfmt.rb). However, the homebrew docs are quite picky about what they will merge, and I suspect since this project is at v0.1.0 pre-release they will not merge it at present. However, it's there in the future for reference.

I'd like to see:

- 1.0.0 semver release
- `--help` and `--version` command line arguments

Other than that it seems to be working very solidly at least in my admittedly limited uses so far.

**Comment by mvdan** [comment]
> 1.0.0 semver release

I already follow semver. I didn't release 1.0 on purpose though, as the library API is not stable yet. And rushing that seems like the wrong way forward. There are a couple of things I might still change in the API.

> `--help` and `--version` command line arguments

You can already do `shfmt -h`.

As for a version flag, I could add `-version`. Note that Go has no native support for gnu-style flags, and pulling an external dependency just for this seems overkill. But I wonder why a version flag/command is important - is this a homebrew hard requirement?

**Comment by focusaurus** [comment]
OK we can wait for the true 1.0.0 to re-consider homebrew packaging.

Regarding the args, homebrew has no requirements here. It is just a
convention and usability thing. For GNU it's an official convention:
https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html
but
if you have no desire to follow that, it's fine with me.

**Comment by mvdan** [comment]
Cool, I'll ping this issue once 1.0 is released.

**Comment by mvdan** [comment]
@focusaurus FYI, a lot of the changes that I wanted to make before considering 1.0 are done - at least the ones that would break backwards compat. For example, https://github.com/mvdan/sh/commit/1737fd73e2cc3ff78ee9468a65db6009c309fadb#diff-7276305616e6d1e44852b1ec07803c49.

I still want to think about a few things, but I'm looking at releasing 1.0 before the end of the year if I can.

**Comment by mvdan** [comment]
@focusaurus 1.0 is released. If you need anything else, please let me know.

**Comment by mvdan** [comment]
@focusaurus friendly ping after the holidays :) If you don't have time to do it, I'll try to do it myself or leave this open for someone else to take it on. Thanks anyway!

**Comment by focusaurus** [comment]
I can update the code for 1.0 today. Let me review homebrew's policy and see whether this should end up as a Cask or fork or PR to homebrew, etc.

**Comment by focusaurus** [comment]
OK so reading how homebrew works, I think this is best done via a tap as I don't think it meets their criteria for inclusion with homebrew-core. Thus I created a tap and tested installing shfmt v1.0.0. It's ready to go.

`brew install focusaurus/homebrew-shfmt/shfmt`

That's all it takes to get it installed. If you want to document that in the README, that'd be great.

**Comment by mvdan** [comment]
Cool, will add it to the README tomorrow.

> don't think it meets their criteria for inclusion with homebrew-core

If you point me at any changes that could be done on my side to make packaging easier, I can see what I can do.

**Comment by focusaurus** [comment]
I think `shfmt` is just not "well-known" enough yet. Of course that's subjective.  I don't think there's any technical barriers remaining.
