### ISSUE TITLE
interp: command substitution cat shortcut not supported

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#323]
```sh
~$ gosh
$ cat > t <<<'Hello, world!'
$ cat t
Hello, world!
$ echo $( < t )
# should be 'Hello, world!', according to bash
```

In the [bash manual](https://www.gnu.org/software/bash/manual/bash.html#Command-Substitution) it says:
> The command substitution $(cat file) can be replaced by the equivalent but faster $(< file).

**Comment by mvdan** [comment]
Thanks again for reporting these!

**Comment by mvdan** [comment]
Ah, this is because that is a Bash trick that's not following the basic redirection rules. A plain `<t` command will not print the file's content to sdout - that only happens within a command substitution. Need to add the special case for this.

**Comment by rob-myers** [comment]
It might not be a trick if bash `exec`s the statements in a command substitution.
Recall that `exec < t` redirects the stdin of the current process.

**Comment by mvdan** [comment]
I believe both are tricks; see the `exec` section in `man bash`:

> If command is not specified, any redirections take effect in the current shell

Here's proof - the command substitution trick stops working as soon as another command is added to the list. This is because the substitution no longer matches the trick:

```
$ cat t; echo $(<t); echo $(<t; echo empty)
Hello, world!
Hello, world!
empty
```
