### ISSUE TITLE
release docker image for version 2.6.2

### ISSUE THREAD

**Issue by dimbleby** [mvdan/sh#334]
I guess the docker image is new and your release process doesn't yet include it...

**Comment by dimbleby** [comment]
Actually it looks as though you tried to release but the [build failed](https://hub.docker.com/r/mvdan/shfmt/builds/bclqvxi6udns4qhg9w9dctr/):

```
Build failed: The command '/bin/sh -c apk add --no-cache git && go get -d mvdan.cc/sh/cmd/shfmt && git -C $GOPATH/src/mvdan.cc/sh checkout -q v$VERSION && CGO_ENABLED=0 go install -ldflags '-w -s -extldflags "-static"' mvdan.cc/sh/cmd/shfmt' returned a non-zero code: 1
```

**Comment by mvdan** [comment]
Seems like there were some TLS issues earlier today. Fixed, and image pushed.
