### ISSUE TITLE
expand: ./foo/* expands to foo/bar instead of ./foo/bar

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#336]
See https://github.com/go-task/task/issues/153#issuecomment-447583930.

Not a regression, but this is a pretty bad bug, so I'm going to do 2.6.3 with it. I'll wait another couple of weeks, to see if anything else should make it into that bugfix release.

**Comment by mvdan** [comment]
Agh, this broke Windows. I'll need to look at that tomorrow.

**Comment by antonmarin** [comment]
Broken expression `docker run -tv "$PWD:/mnt" koalaman/shellcheck:v0.5.0 --color=always --shell=bash --exclude=SC2181 build/docker/*/*.sh` inside `go-task/task`

Taskfile:
```
  lint-shell:
    cmds:
      - docker run -tv "$PWD:/mnt" koalaman/shellcheck:v0.5.0
        --color=always --shell=bash --exclude=SC2181
        build/vagrant/*.sh build/docker/**/*.sh
```
