### ISSUE TITLE
exec parsing

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#340]
Running `exec echo foo > bar` from bash creates a file named `bar` with contents `foo` (then exits).

However, parsing `exec echo foo > bar` yields a `Stmt` with:
- a single redirection, and
- a `CallExpr` with three args i.e. the literals `exec`, `echo` and `foo`.

The redirection should not have been recognised as such.
Instead, it should be part of the args.

**Comment by rob-myers** [comment]
On 2nd thought, perhaps my suggestion is not a good one.

If `exec` only involves redirections, the parsed redirections can be used when exec runs.
Otherwise, the parsed redirections can be serialised and appended to the args before running exec.

It would be preferable to keep the redirections in their original code positions, but it's no big deal.

**Comment by mvdan** [comment]
I'm not sure I understand this issue. Redirections affect the current shell, since for example `exec 2>/dev/null` simply throws away stderr for the rest of a script. It wouldn't make sense if we parsed such commands as if redirections were simply word arguments.

**Comment by rob-myers** [comment]
@mvdan If the `exec` only uses redirections, then yes it will effect the current shell. But if the `exec` includes a simple command, the redirections are performed 'post-exec'.

My example `exec echo foo > bar` already shows this.
If the redirection `> bar` was perform 'pre-exec' then it wouldn't create a file with contents `foo` (which it does).
