### ISSUE TITLE
syntax: Distinguish 'for arg; do' ... from 'for arg in; do'

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#341]
How can I distinguish the cases:

- `for arg; do echo $arg; done` -- iterate over positional parameters
- `for arg in; do echo $arg; done` -- iterate over empty items

given their respective `ForClause`s?

Also, `gosh` does not implement the first item.

**Comment by mvdan** [comment]
I didn't know these did different things; you're right that the syntax and interp packages are missing this feature. I'll have a look at it as part of v3.

**Comment by mvdan** [comment]
For the time being, any script needing `for arg; do ...; done` can instead do `for arg in "$@"; do ...; done`, I presume.

**Comment by rob-myers** [comment]
Can certainly wait for v3.
Just trying to ensure as much coverage as possible.

**Comment by mvdan** [comment]
Fixed in `master.v3`. I haven't done an NPM release in over a month, and there have been at least two fixes in `master.v3` since, so I'll push a new version there in the next few days.

**Comment by mvdan** [comment]
Some more work has gone into the v3 branch in the last couple of weeks, and I've just pushed v0.4.0 to NPM. Note that some of the changes are backwards incompatible, and there likely will be other incompatible changes while v3 is still in alpha.
