### ISSUE TITLE
cmd/shfmt: add flags to read/write AST in JSON format to simplify integration with other languages

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#35]
Quite a few projects out there implement their own shell/bash parsers. Not only the shells themselves, but also some programs that work with shell scripts such as linters.

It's really a little silly for each one of them, especially tooling around shell scripts, to have to implement their own. Sadly, the shells out there don't allow their use as libraries (that I know of).

This is a library, so it does solve that problem. But being written in Go, it's not easily usable from other languages like Python or Shell itself.

Some ideas come to mind:
- Building the packages as shared libraries, linkable by C: http://blog.ralch.com/tutorial/golang-sharing-libraries/
- Adding an executable alongside `shfmt` that parses an input file and outputs the AST in json or some other easy-to-import format

Both of those could be extended to also include the printer.

Any input will be appreciated, especially from people who would use something like this.

**Comment by mvdan** [comment]
The second option could also be in the form of flags in `shfmt`, like `-dump` to go from a shell script to a json AST and `-format` to do the opposite.

**Comment by mvdan** [comment]
Another point in favour of having this inside `shfmt` would be that depending on the binary would be a lot simpler, since for distributions it wouldn't mean an extra package and people using `shfmt` would already be set. And the two binaries would contain the same code anyway.

**Comment by mvdan** [comment]
I'll go with the latter. The former will always be possible if anyone wants to build this package as a shared library.

JSON as the format makes sense because we're not too worried about efficiency in this case, since executing the program is in itself some overhead already. And it's a format well supported by many languages.

What I need to figure out is how to represent types for interface fields. For example, commands. If I just marshal a program, this type information is lost.

**Comment by mvdan** [comment]
Shell code to JSON is now done. Note that this does not include unexported fields (`File.lines`) nor positions (e.g. `Lit.ValuePos`), since they both seem largely useless for tools that just want the AST of the code.

I haven't done JSON back to shell code yet. I might in the future. Please try the existing feature out and let me know if it would be useful. In my mind, it would only be useful to write back into the original shell source code.

But then we'd need position information too, so that complicates things a bit. Hence why I haven't included that second half just yet.

**Comment by mvdan** [comment]
Also, obligatory example:

```
$ shfmt -exp.tojson <<<'echo foo'
{
        "Comments": [],
        "Name": "",
        "Stmts": [
                {
                        "Assigns": [],
                        "Background": false,
                        "Cmd": {
                                "Args": [
                                        {
                                                "Parts": [
                                                        {
                                                                "Type": "Lit",
                                                                "Value": "echo"
                                                        }
                                                ]
                                        },
                                        {
                                                "Parts": [
                                                        {
                                                                "Type": "Lit",
                                                                "Value": "foo"
                                                        }
                                                ]
                                        }
                                ],
                                "Type": "CallExpr"
                        },
                        "Coprocess": false,
                        "Negated": false,
                        "Redirs": []
                }
        ]
}
```

**Comment by cilki** [comment]
I find the `-tojson` flag useful. In particular I'm interested in manipulating the output JSON and turning it back into a script like so:
```sh
echo 'echo 123' | ./shfmt -tojson | jq '<optimizations>' | ./shfmt -fromjson >optimized.sh
```

Any guidance on what I would need to do to implement `-fromjson`? I'll send a PR if I can get it working (and this is a desirable feature outside of my probably unusual use-case).

**Comment by mvdan** [comment]
It is indeed desirable, and we've talked about it in the context of js/wasm - since calls from and to Go can only pass basic types like `string` around, and not the proper syntax tree. For example, see https://github.com/mvdan/sh/issues/885.

This issue does say _read_ and write AST in JSON format, so I'm not entirely sure why I closed it after doing just one part of it. I'll take a look.

**Comment by cilki** [comment]
@mvdan wow that was amazingly fast. I'll try it out. Thank you!
