### ISSUE TITLE
syntax: consider exposing parser as a C interface

### ISSUE THREAD

**Issue by bam80** [mvdan/sh#351]
Hi,
I wonder how hard it would be to adopt this as Plug-in parser for GNU GLOBAL Source Code Tag System:
https://www.gnu.org/software/global/globaldoc_toc.html#Plug_002din

**Comment by mvdan** [comment]
Sorry, I don't understand what you're suggesting. How does that page relate to shell code parsing or formatting?

**Comment by bam80** [comment]
The Global indexing system has built-in parser, it's only for C and the likes. But also it has possibility to write external plugins parsers. No one of them already existed capable of parsing "simple commands" in shell scripts

**Comment by bam80** [comment]
http://lists.gnu.org/archive/html/bug-global/2019-01/msg00006.html

**Comment by mvdan** [comment]
Also note that there are other shell parsing libraries out there. For example, https://git.sr.ht/~emersion/mrsh/tree/master/parser contains a somewhat complete POSIX shell parser in C.

I don't think there's any shell parser with Bash support to the level that this library does, however. So it depends on how powerful you want the plugin to be.

**Comment by bam80** [comment]
Thanks.
Well, I think I can't do it myself too. All Go things are new to me, and I don't have much time.
Only if we could have some prototype parser.. I think then doing bash stuff would be easy..

**Comment by mvdan** [comment]
If it's at all helpful, there's an experimental version of the parser in javascript: https://www.npmjs.com/package/mvdan-sh

There's none as a C interface just yet. I might work on that at some point, but the big question is who would need a C interface. I could spend a few days on it if enough people would be interested.

**Comment by mvdan** [comment]
Something which might also be helpful is shfmt's ability to print parsed syntax trees as JSON. For example, try `shfmt -tojson <<<'echo foo'`. This is reasonably fast and language-agnostic, so it could be used within pygments, or within a C program.

**Comment by bam80** [comment]
Just imagine - we could have fully indexed shell scripts in our Vim/Emac.. Jumping to function definitions AND callers, eh? ;)

**Comment by bam80** [comment]
@shigio @masatake just wanted your guys would be aware of the discussion. Welcome!

**Comment by bam80** [comment]
> shfmt's ability to print parsed syntax trees as JSON. For example, try `shfmt -tojson <<<'echo foo'.` This is reasonably fast and language-agnostic, so it could be used within pygments

Does pygments already has ability to work with JSON syntax trees that way?

**Comment by mvdan** [comment]
No idea. I only meant that it's fairly straightforward to execute a program and decode its output as JSON from most languages, such as Python.

**Comment by bam80** [comment]
Daniel, could you help me understand,
pygments uses `class BashLexer(RegexLexer)` here:
https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/lexers/shell.py#lines-28

I wonder if it reasonable easy to accomplish it so it would pick up function calls also, or it's impossible for that Regex-based lexer?

**Comment by mvdan** [comment]
There seems to be zero interest besides yourself, and I personally have no use cases for a C interface, so I'm going to close this for now.
