### ISSUE TITLE
Future of the JS version

### ISSUE THREAD

**Issue by rafamel** [mvdan/sh#354]
Hi Daniel,

I've just recently found your project and its transpiled JS version. I've been doing some experiments around it, and have to say I've found it to be the most promising out there within the JS ecosystem. I've ended up exposing an API for it that feels like native JS and fixes some of the rough edges of the Go->JS transpilation. It also adds some basic `TypeScript` typings -incomplete as of now. Here's the [`README`](https://github.com/rafamel/shell-parser) and some [additional documentation](https://rafamel.github.io/shell-parser/). It's mostly a test drive for the idea, as right now it wraps the original API, with the downsides that brings along.

However, I would like to move forwards with this so we can end up with a complete JS port of the core shell -> AST / AST -> shell functionality (essentially, most of the `syntax` module) that feels entirely native, has complete TS typings, docs, tests, and has a mostly automated pathway for updates from the main Go package.

I'd love to hear your thoughts about it, mainly whether or not having a separate repo for a JS/TS version and a similar but different API would be something you'd welcome, and whether you'd be willing to get on board with it and consider some suggestions for the main Go package that would make this transition way less problematic. They are mostly minor issues, but since I'm far from being knowledgeable in `Go`, I'd be unable to send PRs for them myself.

Let me know what you think, I'd be happy to further elaborate if you're willing to go forwards!
Rafa.

**Comment by mvdan** [comment]
Also worth noting that I'm in the process of writing v3 of the Go module, meaning that now is the time to consider backwards-incompatible changes. However, the NPM package is still a v0, so for now it has zero backwards compatibility guarantees.

**Comment by mvdan** [comment]
We've continued this discussion in private, and I believe Rafa will have something public to share soon.

In the meantime, particular issues are being worked on in this repository. For example, `js/api_dump.go` is a small Go program which gives a JSON dump of the module's API, and #374 is necessary to remove some unnecessary null checks in his library.

This issue hasn't had activity for two months, so I'm closing it for now. We can always reopen it, or use new issues for particular features or bugs.

**Comment by rob-myers** [comment]
>  have to say I've found it to be the most promising out there within the JS ecosystem.

Agreed, it is the best thing I've seen too.

>  I've ended up exposing an API for it that feels like native JS and fixes some of the rough edges of the Go->JS transpilation. It also adds some basic `TypeScript` typings -incomplete as of now. Here's the [`README`](https://github.com/rafamel/shell-parser) and some [additional documentation](https://rafamel.github.io/shell-parser/). It's mostly a test drive for the idea, as right now it wraps the original API, with the downsides that brings along.
> 

Interesting, I'll check it out.
I've written extensive typings for the entire AST, if you're interested.

Previously I wrote an implementation in the browser via generators (using `yield*` a lot).
I then got flattened by work, but now I'm rewriting it using [memfs](https://www.npmjs.com/package/memfs) and [rxjs](https://www.npmjs.com/package/rxjs).
