### ISSUE TITLE
Option -i seems not working anymore in VSCode V1.31.1

### ISSUE THREAD

**Issue by Nounours31** [mvdan/sh#359]
Hello, in VSCode I cannot set the increment anymore.
Whatever the -i number I used I have 5 whitespace in my script.
Please note
   In VSCode, all others options are working well (I tested -p, -ci, -h, -w ...)
   In terminal windows -i option is working well

In order to help you, is there a way to debug this?
Regards,
Pierre

The code
#!/bin/sh
if [ "${a}" = "a" ]; then
     echo "toto"
     echo "toto" > tata
fi
the options:
     "shellformat.flag": "-i 0 -p -ci -sr -kp",
     "shellformat.path": "E:\\programfiles\\shfmt\\shfmt.exe",
     "shellformat.showError": true,

**Comment by mvdan** [comment]
Can you reproduce this with just `shfmt` directly? For example, it seems to work fine for me, as expected:

```
$ shfmt -version
v2.6.3
$ shfmt -i 2 <<<'{ a; b; }'
{
  a
  b
}
$ shfmt -i 8 <<<'{ a; b; }'
{
        a
        b
}
```

**Comment by Nounours31** [comment]
Hello,
Thanks a lot for your quick answer 

Yes I tried to explain (sorry for my bad english) it works fine outside VSCode, Even in VSCode terminal window it works. And all others options are taking into account (-p -ci -sr -kp) in VSCode. I just have a problem with -i option.
For example, I add -version in the setting.json of VSCode and I have v2.5.1.

But I really think it is not linked to shfmt himself but it's integration in VSCode.
Perhaps something is running at 'Format document' which change the indent to '5'
But I have no idea of how I can debug this. 

Note than before this was integrated to the 'system' Format Document, I had no problem ... I am so sad ...

Thanks,
Pierre

**Comment by mvdan** [comment]
Well, I'm not a VSCode user, and I can't reproduce the issue, so I can't help you I'm afraid :)

If you're using a VSCode plugin to use `shfmt`, I'd suggest opening an issue there.

**Comment by Nounours31** [comment]
OK thanks
