### ISSUE TITLE
syntax: "array element values must be words" for associative array with empty value

### ISSUE THREAD

**Issue by kevinoid** [mvdan/sh#361]
`shfmt` is not able to format a Bash script which declares an associative array with an unquoted empty value.  For example, running `shfmt` on the following script:

```bash
#!/bin/bash
declare -A dict=(
	[foo]=
)
echo "Keys: ${!dict[*]}"
```
produces

    example.bash:4:7: array element values must be words

with exit code 1.

As far as I can tell, the script is valid.  It runs without error in Bash 5.0.2 and prints `Keys: foo`.

Thanks for considering,
Kevin

**Comment by mvdan** [comment]
Thanks for the report! This should be an easy fix.

**Comment by kevinoid** [comment]
Sure thing.  Glad to hear it.  Thanks for looking into it!

**Comment by mvdan** [comment]
I've fixed this in the `master.v3` branch, and I might or might not backport this into master for another v2 bugfix release. In any case, you can temporarily work around this by using `declare -A x=([index]='')` :)

**Comment by kevinoid** [comment]
Thanks @mvdan!  I can confirm that both the fix and the workaround solve the issue for me.  Thanks again.
