### ISSUE TITLE
syntax: Gosh does not implement printf escape codes

### ISSUE THREAD

**Issue by capnspacehook** [mvdan/sh#363]
When testing `printf` in gosh, I found that it does not implement `printf` escape codes. Reference: https://wiki.bash-hackers.org/commands/builtin/printf#escape_codes

For example, the command `printf "\\x65"` should return `e`, as 65 is the ASCII hex value for 'e'. I understand that gosh is experimental, just trying to ensure it's as faithful as possible :)

**Comment by mvdan** [comment]
Thanks for raising this issue! I'm curious - how are you using gosh?

If you fancy sending a PR against the master.v3 branch, that'd be welcome. Otherwise, I'll probably have a look next week.

**Comment by capnspacehook** [comment]
No problem! Right now, I'm just testing and evaluating it, I'm planning to use it for a project I hope to start soon where the server parses input commands, and sends the AST to the client to execute.

The only reason I know of obscure functionality like this is because I wrote a Bash obfuscation framework a few months ago, so features like this were used all the time ;)

I probably don't have time to make a PR this week sadly, I'm leaving for spring break :(

**Comment by mvdan** [comment]
Sounds cool. FYI, this seems like a bug in the interpreter program; the parser is likely what you'd use, and it shouldn't be affected.

No worries about not being able to send a PR. I was only clarifying that contributions are welcome.

**Comment by mvdan** [comment]
Also, how did you test this? It seems to work, as far as I can tell:

```
$ gosh -c 'printf "\\x65\n"'
e
$ bash -c 'printf "\\x65\n"'
e
```

Note that `master` is the mostly-frozen v2, while the development v3 is in the `master.v3` branch. I know that's weird and confusing; I plan to unify both branches in the coming days.

**Comment by capnspacehook** [comment]
Gotcha. I'm most likely going to end up using both the interpreter and the parser actually. And no problem, I understand :)

Hmm, I tested that on the master branch, haven't tested on master.v3 branch. Did it work on the master.v3 branch?

**Comment by capnspacehook** [comment]
Yep I just tested on the `master.v3` branch, works as expected! Sorry for the false negative, and thanks for such a great and useful project!
