### ISSUE TITLE
interp: Params isn't supported as an option to New

### ISSUE THREAD

**Issue by bilus** [mvdan/sh#365]
First of all, great project. We're tentatively planning to use it in an open project we'll be launching in two weeks (an automation tool with a twist) as syntax for our Makefile-like tasks. There are plenty of opportunities there as opposed to using bash directly, including better error messages and even debugging!

While integrating it with our tool, I noticed a problem with `Params`. While I was working on a fix, tests I added uncovered another issue. 

PR: https://github.com/mvdan/sh/pull/364

I hope you'll find it not entirely worthless and can merge it, it's vital for us here, would hate to have to create a fork. :)

**Comment by mvdan** [comment]
Thanks for opening the issue and the PR!

Please note, however, that the actual development happens in the `master.v3` branch. I realise that's confusing, but with Go modules still being in a form of beta, I couldn't break backwards compatibility in the master branch last year. The good news is that I'll join the two branches soon; see https://github.com/mvdan/sh/issues/266.

I've had a look at your PR, and I think I see the two bugs. It's present in the v3 branch too; it looks like this bug has been present for a while. Thanks for finding it and debugging it :)

While reviewing your code, I thought the fix could be simpler, and I believe I have a three-line fix with just ten lines of test code. I'll publish that as a PR in a second, asking you to review and test it with your program, to ensure it's still fixing the problem.

But please don't feel discouraged to send more PRs - they're always welcome!

**Comment by bilus** [comment]
@mvdan Great, thanks for a prompt reply. Don't worry, you know your code better. Creating the PR was useful as I want to wrap my head around how the code works in case it does end up in our project.

**Comment by mvdan** [comment]
On second thought, I will do a v2 bugfix release. There's a few other simple fixes which can be backported, and there's no reason to hold them up for v3.

I'll probably do the tag later today or tomorrow. See https://github.com/mvdan/sh/milestone/14.

**Comment by bilus** [comment]
Thanks!
