### ISSUE TITLE
format output for correct stderr redirection to work

### ISSUE THREAD

**Issue by GuillaumeBibaut** [mvdan/sh#370]
This shell script:
```shell
#!/bin/sh
set -v

echo 1>&2 "stderr" >stdout 2>stderr | cat
cat stdout
cat stderr

echo "stderr" >stdout 2>stderr 1>&2 | cat
cat stdout
cat stderr
```

outputs this:
```

echo 1>&2 "stderr" >stdout 2>stderr | cat
cat stdout
stderr
cat stderr

echo "stderr" >stdout 2>stderr 1>&2 | cat
cat stdout
cat stderr
stderr
```

which means to me that to correctly output to stderr, the `1>&2` has to be at the end of the command (`command1 args 1>&2 | command2`).

For now, I can see that `shfmt` outputs this formatted script:
```
$ cat echo-stderr.sh | shfmt -i 4 -p
#!/bin/sh
set -v

echo 1>&2 "stderr" >stdout 2>stderr | cat
cat stdout
cat stderr

echo "stderr" >stdout 2>stderr 1>&2 | cat
cat stdout
cat stderr
```
But I'm thinking for it to be correct, it should have output this:
```
#!/bin/sh
set -v

echo "stderr" >stdout 2>stderr 1>&2 | cat
cat stdout
cat stderr

echo "stderr" >stdout 2>stderr 1>&2 | cat
cat stdout
cat stderr
```

Is this inside the bound of what `shfmt` has to be able to format ?

**Comment by mvdan** [comment]
If I understand this issue correctly, you wish that `shfmt` fixed the inherent bug in your script, by moving the `1>&2` redirect past the other two, `>stdout 2>stderr`.

That falls under the "finding and fixing bugs" category of tools, while shfmt is simply "format a script to be easy to read". `shfmt` should never change the behavior of a program, even if the current behavior is broken. It works on the syntax alone, and doesn't try to understand what programs are doing.

Spotting bugs is the kind of thing that other tools like `shellcheck` were built for. I'd suggest giving it a try if you want to catch these kinds of problems.

This project might or might not include something like a bug finder in the future, but it's not in my plans right now. But if someone wanted to write one, it wouldn't be difficult; this repo already includes a parser, and automatic fixes could happen thanks to the printer.

**Comment by GuillaumeBibaut** [comment]
I understand. I'll use `shellcheck`, I didn't know about that one.
