### ISSUE TITLE
shfmt fails on alias

### ISSUE THREAD

**Issue by tterranigma** [mvdan/sh#372]
I am using the [Bash Infinity](https://github.com/niieani/bash-oo-framework) framework. This framework offers some aliases like `[array]`. These are valid aliases. 

The following file:

```sh
#!/bin/bash

[array] q=()
```

breaks `shfmt`:

```
[nikos@nikos-laptop tmp]$ shfmt q.sh
q.sh:3:11: a command can only contain words and redirects
```

**Comment by mvdan** [comment]
Sorry, I'm not sure I follow. The script you shared above isn't valid syntax:

```
$ bash
$ [array] q=()
bash: syntax error near unexpected token `('
```

I realise it's possible to declare `[array]` as an alias:

```
$ alias [array]='declare -a'
$ [array] q=()
```

However, that can't work with our static parser. The static parser has to treat `declare` as a keyword; otherwise it wouldn't be able to parse arrays statically.

**Comment by tterranigma** [comment]
My issue is that `[array] q=()` breaks the parser. I don't want this alias to be understood by the parser. But since it is valid bash syntax, it would be nice for the parser to not fail. When it fails, if I am not mistaken, the rest of the file does not get parsed.

If this is a situation the parses does not support, feel free to close this issue.

**Comment by mvdan** [comment]
> But since it is valid bash syntax, it would be nice for the parser to not fail.

I'm precisely pointing out that it's not valid syntax. At least, not when one implements a static parser.

In practice, Bash parses a script interactively, so its parser cannot be used statically or as a library. This is one of the major differences with our parser.

The only possible change we could apply here is to do lazy parsing. That is, whenever we see an array, we simply keep the bytes in the syntax tree, and only parse them or error when we interpret a `declare` command. However, that would be a huge disadvantage for our parser, as it would suddenly not parse certain programs fully, leaving that work for whomever is interpreting the program.

All in all, I'm sorry, but I won't modify the parser to be lazy. Abusing Bash to parse commands at run-time only is fine, but you'll find that many of the static tools like `shfmt` and `shellcheck` simply won't work on it.

**Comment by tterranigma** [comment]
OK, thanks for the explanation.
