### ISSUE TITLE
Arythmetic bitwise operator not recognized

### ISSUE THREAD

**Issue by leagris** [mvdan/sh#373]
##### Version
shfmt_v2.5.1_linux_amd64

##### Reproduce
Always with minimal code:
```Bash
((~ 0))
```

##### Description
the `~` bitwise negation operator as defined in:
[Bash Man-Page / 6.5 Shell Arithmetic](https://www.gnu.org/software/bash/manual/html_node/Shell-Arithmetic.html#index-arithmetic-evaluation)
is not recognized, and causes `shfmt` to fail

> ! ~
> 
>    logical and bitwise negation
> 

##### Issue has been reported here initially
See:
https://github.com/focusaurus/atom-format-shell/issues/9#issue-424935652

**Comment by mvdan** [comment]
Thanks for filing this - it does look like I forgot about this operator. I'll push a fix shortly.

**Comment by leagris** [comment]
Testing v3.0.0-alpha1, so far looks good

**Comment by mvdan** [comment]
I haven't done a v3 alpha release with this fix yet, but I'll probablt do alpha2 in a week. You can always build the latest commit from master before then.

**Comment by leagris** [comment]
I just built it and use it right now :)

**Comment by leagris** [comment]
I coded this today and formatted it with your `shfmt`:

#### A More interesting test case of the bit-wise negation arithmetic operator:

##### POSIX compliant Shell implementation of the CRC32 algorithm:
```Sh
#!/bin/sh
# POSIX Shell CRC32 of string
crc32_string() {
  [ ${#} -eq 1 ] || return
  printf '%s' "$1" | {
    crc=0xFFFFFFFF
    p=0xedb88320
    while c="$(dd bs=1 count=1 2>/dev/null)" && [ -n "$c" ]; do
      byte=$(printf '%d' "'${c}")
      r=$(((crc & 0xff) ^ byte))
      j=0                             # bit index
      while [ $((j <= 7)) -ne 0 ]; do # 8-bit lsb shift
        r=$(((r & 0x1) == 1 ? (r >> 1) ^ p : r >> 1))
        j=$((j + 1))
      done
      crc=$(((crc >> 8) ^ r))
    done
    # Uses bit-wise negation arithmetic operator (shfmt test-case)
    echo $((~crc & 0xFFFFFFFF))
  }
}

printf 'The CRC32 of: %s\nis: %08x\n' "$1" "$(crc32_string "$1")"

# crc32_string "The quick brown fox jumps over the lazy dog"
# yields 414fa339
```

##### Output:
```
/bin/sh ./crc32.sh "The quick brown fox jumps over the lazy dog"
The CRC32 of: The quick brown fox jumps over the lazy dog
is: 414fa339
```
