### ISSUE TITLE
Install with Go 1.7 is broken

### ISSUE THREAD

**Issue by machinekoder** [mvdan/sh#376]
Unfortunately, the updates break the installation with older Go versions. It would be nice if there would be a v1 version that could be used for those.

**Comment by mvdan** [comment]
That's how the master branch works. Unfortunately, older versions of Go don't have a way to select a specific version when installing. This is why modules exist, and the process will get better with time.

Until then, if you want to use a version of Go older than 1.11, simply check out a specific tag for a version you want to install. Or if you want the latest v1, or v2, see the respective branches, like https://github.com/mvdan/sh/tree/v2 or https://github.com/mvdan/sh/tree/v1.
