### ISSUE TITLE
nice to have: option for "spacing"

### ISSUE THREAD

**Issue by nihilus** [mvdan/sh#377]
It would be nice if the user could for example have a switch/option to select the default for spacing, shfmt seems to hate spacing and especially for redirection. Me myself and my co-workers want to have it like 'foo > /dev/null 2>&1' however shfmt wants otherwise.

Maybe a switch/option like '-ks' for 'keep sparing' where it does everything magical we love about shfmt and keep the spacing?

**Comment by mvdan** [comment]
I'd suggest you have a look at the `-sr` and `-kp` options; they probably do exactly what you need.

**Comment by nihilus** [comment]
😎 I will check it out next week, seems like new features AFAIU.

**Comment by mvdan** [comment]
They've been around for a while, so it depends on what version you were on :)

**Comment by nihilus** [comment]
I was willing to give v3/master a shot but as said I reverted back to what wouldn't break things for my co-workers before vaction.

**Comment by mvdan** [comment]
If this is for work, you probably want to stick to the latest stable v2 tag.
