### ISSUE TITLE
Problem getting the latest master version

### ISSUE THREAD

**Issue by bilus** [mvdan/sh#379]
@mvdan Sorry to bother you but I have trouble getting the params fix from master:

```
go get mvdan.cc/sh@master
go: finding mvdan.cc/sh master
go: mvdan.cc/sh@v0.0.0-20190408143120-42f0b5294804: go.mod has post-v0 module path "mvdan.cc/sh/v3" at revision 42f0b5294804
go: error loading module requirements
```

Any suggestions?

**Comment by mvdan** [comment]
The master branch is now v3, so you probably want to do `go get mvdan.cc/sh@v2` to pull from the `v2` branch.

**Comment by bilus** [comment]
I see you backported it already, that was quick! Ok, it worked but had to choose the specific commit for some reason; `v2` got me stuck on 2.6.4:

```
go get -u mvdan.cc/sh@ee3cf90
```

**Comment by mvdan** [comment]
Hm, that's weird. Maybe I should have named the branch something else like `release-v2` to make that command less ambiguous.
