### ISSUE TITLE
parser: posix mode complains about file-descriptor redirects

### ISSUE THREAD

**Issue by paulbellamy** [mvdan/sh#38]
The following script:
```sh
#/bin/sh
cat file >&2
```
Produces this error:
```text
$ shfmt -p cat.sh
cat.sh:2:10: > must be followed by a word
```

Strangely, in non-posix mode it is fine?

Maybe I have a misconception of what is allowed for redirection in posix, but this (http://pubs.opengroup.org/onlinepubs/007904875/utilities/xcu_chap02.html section 2.7.5), seems to indicate this is valid (and it runs).

**Comment by mvdan** [comment]
What `shfmt` version is this? On master, I don't see this:

```
$ echo 'cat file >&2' | shfmt -p
cat file >&2
```

**Comment by mvdan** [comment]
Would also help if you uploaded the file. This could happen if the file has non-printable characters hidden between `>&` and `2`, in which case the parser should give a better error message.

**Comment by mvdan** [comment]
Actually, this happens if I put the lines in a file, but not from the command line. What the hell?

In any case you're right - sorry for the noise.

**Comment by mvdan** [comment]
Ah, I only apply `-p` if running on files, not on stdin. Ouch.
