### ISSUE TITLE
syntax: adds trailing tabs to blank lines when formatting tab-delimited here-documents

### ISSUE THREAD

**Issue by basil** [mvdan/sh#382]
## Problem

`shfmt(1)` adds trailing tabs to blank lines when formatting tab-delimited [here-documents](https://www.gnu.org/software/bash/manual/html_node/Redirections.html#Here-Documents).

## Steps to reproduce

```bash
$ shfmt -version
v2.6.4
$ cat test.bash
#!/bin/bash

cat >foo <<-EOF
a

b

c
EOF
$ shfmt -w test.bash
```

## Expected result

Below, I use `»   ` to represent a tab character.

```bash
#!/bin/bash

cat >foo <<-EOF
»   a

»   b

»   c
EOF
```

## Actual result

Below, I use `»   ` to represent a tab character.

```bash
#!/bin/bash

cat >foo <<-EOF
»   a
»   
»   b
»   
»   c
EOF
```

Note that trailing tabs have been added to the blank lines in the here-document.

**Comment by mvdan** [comment]
Whoops! I'm not sure how this wasn't caught before.
