### ISSUE TITLE
Embedding gosh in other apps

### ISSUE THREAD

**Issue by udhos** [mvdan/sh#384]
Hi,

I am experimenting with embedding 'gosh' as a shell in my app 'conbox'.
Conbox is a kind of BusyBox clone in Go.

However I had to include full gosh code with small modifications.
This is the full code:
https://github.com/udhos/conbox/blob/master/applets/sh/run.go

I wonder whether gosh could expose a modified verson of the `runAll()` method that I could call directly, avoiding the need to duplicate most of its code?

Thanks

**Comment by mvdan** [comment]
Sorry, modified in what way? We're talking about sixty lines of code, and plenty of pieces are hard-coded, like the prompt, the context (timeout) to run each line, or whether the shell is interactive.

We could export it in a separate package, but then we'd probably have to make it configurable, which would likely add another sixty lines of code.

I think it's fine for people to copy-paste this main.go file for now. After all, most users will want either an interactive shell, or a non-interactive one, and each side is just about 20 lines of simple Go code. If you want both, you likely just want the `gosh` main package directly.

**Comment by mvdan** [comment]
Having said that, if you have any particular ideas or patches to improve the codebase, I'm all ears :)

**Comment by udhos** [comment]
Hi, thanks for sharing your thoughts.

> If you want both, you likely just want the gosh main package directly.

Yes, however I intended to consume full 'gosh' embedded in my app, not as an executable standalone shell.
So I was hoping that most of 'gosh' code could evolve into a package that one could trivially import.
I understand that 'gosh' code base is small, and that I can keep using my copy of it, but if this project improves the implementation of 'gosh', my app won't automatically benefit, then I would need to resync manually.

**Comment by mvdan** [comment]
I don't expect the code to change often at this point. It's not a full-blown shell that will gain features over time, at least not for the foreseeable future. I think a bit of copying is fine in this case.

If the code starts changing a lot in the future, or grows much larger, we can reconsider.
