### ISSUE TITLE
How to dynamically trap commands in gosh

### ISSUE THREAD

**Issue by udhos** [mvdan/sh#385]
I would like to dynamically trap some commands into 'gosh' shell.
In the example below, s.applets is a map holding the command table.
What is the recommended way to dynamically inject commands in gosh?
Can this be accomplished?

```
func runNode(s shell, ctx context.Context, node syntax.Node) error {

	args := []string{"xecho", "hi"} // FIXME how to get fields from node

	if applet, found := s.applets[args[0]]; found {
		exit := applet(s.applets, args[1:])
		return interp.ExitStatus(exit)
	}

	return s.mainRunner.Run(ctx, node)
}
```
Full code: https://github.com/udhos/conbox/blob/ef4489b350a44dd0bf2e197108946a5dbe820cbb/applets/sh/run.go#L132

**Comment by mvdan** [comment]
Have you seen https://godoc.org/mvdan.cc/sh/interp#example-ModuleExec?

**Comment by mvdan** [comment]
I'm going to close this for now.
