### ISSUE TITLE
Add support for redirect before commands

### ISSUE THREAD

**Issue by dcsobral** [mvdan/sh#389]
I'm using `shfmt` on some scripts I've just inherited, and I noticed it undid something I wrote:
```diff
-  >&2 echo "PR does not appear to be a verison bump; skipping automerge checks"
+  echo >&2 "PR does not appear to be a verison bump; skipping automerge checks"
```
I've learned to prefix commands that send messages to stderr with `>&2` some years ago, as a way to clearly indicate something is producing error output, as well as quickly drawing attention to something that should go to stderr but apparently isn't.
I've also seen some cases where complex redirection is done before anything else to emphasize the redirection itself.
So I'd rather `shfmt` not move redirection when it happens at the beginning of a line. It seems arbitrary, and when redirects appear at the beginning of a line, they do so for a reason. Failing that, at least have an option to leave them alone.

**Comment by mvdan** [comment]
Is having the redirection right after the `echo` significantly worse for these criteria? The formatter allows redirections to be either after the first argument, or after all the arguments. This is precisely to allow emphasizing some redirections, like `echo >&2 ...`.

I chose "after the first argument" because, from what I could tell, that was the widespread format. Is there any shell style/format guide that you can link to?

We could allow redirects before the first argument too, but that would make the formatter less strict, which is a disadvantage.

**Comment by kevinoid** [comment]
I came across this issue while researching the convention of redirecting `stdin` before commands.  I'm not aware of any public style guides which advocate it, but it reads from left to right like a pipeline and is frequently mentioned as a replacement for a [<em title="Useless Use of Cat">UUOC</em>](http://catb.org/jargon/html/U/UUOC.html) [[1]](https://stackoverflow.com/a/11710573)[[2]](https://stackoverflow.com/a/49254166)[[3]](https://superuser.com/a/564034)[[4]](https://stackoverflow.com/a/54051011)[[5]](https://unix.stackexchange.com/q/511827):

```sh
cat file.txt | cmd1 | cmd2
< file.txt cmd1 | cmd2
```

However, in my experience, it is much less common and can be less intuitive.  I also agree about the benefits of strictness.  I'm not advocating for or against this proposal, just thought this might be useful context to add.

**Comment by mvdan** [comment]
Thanks for the detailed info! Indeed one can find some examples of `<redir arg1 arg2`, but one can find as many or more examples of the other forms.

I'm still interested to know if there are any guides or handbooks that strongly encourage the use of this particular form. @dcsobral do you have any links you can share?

**Comment by dcsobral** [comment]
I don't have any links to share. I saw that style a few years ago, and it was _specifically_ geared towards error message output, recommending `>&2 echo` as a way to clearly mark the places where `echo` was an error message, and not normal output.

Not that I haven't seen examples elsewhere, but that was the one place where I saw a specific recommendation to this effect. Sadly, I don't have the slightest idea where it was, and, fwiw, that was the single place I ever saw advocating this particular style. Then again, I don't recall reading any other style guidance on redirect position.

**Comment by mvdan** [comment]
Thanks for the reply. Given that there's no evidence for either of these styles to clearly win over the other, let's leave things as they are. I prefer the tool to be stricter and with fewer options. The more permissive the tool becomes, the less useful it gets; and the more options it gains, the more difficult it is to maintain and use.
