### ISSUE TITLE
invalid UTF-8 encoding at docker-images

### ISSUE THREAD

**Issue by alexgit2k** [mvdan/sh#395]
Only the v2.6.1 docker-image is working, all other tags give a invalid UTF-8 encoding error:

```
# docker run --rm -it mvdan/shfmt:v2.6.4 /bin/shfmt --version
/bin/shfmt:1:25: invalid UTF-8 encoding
stat --version: no such file or directory

# docker run --rm -it mvdan/shfmt:v2.6.3 /bin/shfmt --version
/bin/shfmt:1:41: invalid UTF-8 encoding
stat --version: no such file or directory

# docker run --rm -it mvdan/shfmt:v2.6.2 /bin/shfmt --version
/bin/shfmt:1:25: invalid UTF-8 encoding
stat --version: no such file or directory

# docker run --rm -it mvdan/shfmt:v2.6.1 /bin/shfmt --version
v2.6.1
```

**Comment by mvdan** [comment]
Newer docker images were changed, so that you woulnd't have to repeat the `shfmt` argument:

```
docker run --rm -it mvdan/shfmt:v2.6.4 --version
```

This is after some people made the suggestion, since it's more standard when publishing single tools as Docker images.

I realise this should have been part of the changelog, as it could break some users. I'll add a note.

**Comment by mvdan** [comment]
Done. It now reads:

> Note that the published Docker image was changed to set `shfmt` as the entrypoint, so previous uses with arguments like `docker run mvdan/shfmt:v2.6.1 shfmt --version` should now be `docker run mvdan/shfmt:v2.6.2 --version`.

I realise I never addressed the error. I imagine it's because you're running `shfmt /bin/shfmt --version`. The first file isn't valid UTF-8 (because it's a binary), and the second doesn't exist, because flags must go before any non-flag arguments.

**Comment by alexgit2k** [comment]
I don't see the new note on https://hub.docker.com/r/mvdan/shfmt or https://github.com/mvdan/sh/blob/master/README.md but it is working, thanks.

**Comment by soullivaneuh** [comment]
For anyone who really need to override the way you launch shfmt from the dockerfile, you may doing something like this:

```
FROM mvdan/shfmt:v2.6.4

# The run script launch shfmt with some options
ADD run /bin/run

ENTRYPOINT ["sh", "-c"]

CMD /bin/run
```
