### ISSUE TITLE
Plans for support tabs count

### ISSUE THREAD

**Issue by mmazurkevich** [mvdan/sh#397]
Hi, 
I wanted to know, are there any plans to configure not only intents count but also tabs count in shfmt?
> We have a couple of issues where users ask to support this feature
> e.g https://youtrack.jetbrains.com/issue/IDEA-217877

Thanks for the great tool

**Comment by mvdan** [comment]
Sorry, I don't understand. Why would anyone want to indent with two or three tabs?

Tab size is a setting to change how a tab is displayed by an editor, not a setting to change how many tabs each indentation level should contain.

**Comment by mmazurkevich** [comment]
@mvdan It's really about tab size configuration. Sorry for disturbing you.
