### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [mvdan/sh#398]
Hi, I'm Yevgeny Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

I saw that you implemented Fuzz targets but they are currently not running as part of the CI.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by mvdan** [comment]
Hi, thanks for opening this issue.

I've seen the rewards program, and I think this project qualifies - so I was planning on adding fuzzit to CI in the coming week or two. I already fuzz locally whenever I made any significant changes to the syntax package, so I'm not in a hurry to make this happen.

Do you have any thoughts on where to store the corpus? Right now it's in a separate branch, as it's large. I definitely don't want it on master. I assume fuzzit would store a corpus as well?

**Comment by yevgenypats** [comment]
Hi:) Yes exactly fuzzit stores the corpus for you, crashes, logs of previous runs and all the versions of the fuzzers so you can rerun/investigate etc...

Cool, so we can add the PR for you but then you won't be eligible for the reward. I'll be happy to let you do that and get you rewarded just let me know if you plan to do the integration. I would prefer that you would do that, both to get you rewarded as well as to get unbiased feedback of how smooth the integration and other feature-request you though are useful during integration etc...

**Comment by mvdan** [comment]
Yup, I'll get to it - I'm just busy with work and preparing for GopherCon UK at the moment :)

**Comment by yevgenypats** [comment]
Sounds good. Good luck at conference. You can join our [slack](https://slack.fuzzit.dev) and dm for questions/feedback once you get to this integration.

**Comment by mvdan** [comment]
This has been merged in master as of 6c13161a56af5dece4e33497e909ee4cbe3ee6bf.
