### ISSUE TITLE
Invalid "ternary operator missing ? before :" error

### ISSUE THREAD

**Issue by zx8** [mvdan/sh#400]
Using https://github.com/mvdan/sh/commit/93ca2cd021fb996d639ebd97a57919d765010548:

It is not necessary for associative arrays keys to be quoted:

```
$ cat 1.sh
declare -A FOOBAR=(
  [foo:bar]=baz
)

$ shfmt 1.sh
1.bash:2:4: ternary operator missing ? before :
```

Changing `[foo:bar]` to `["foo:bar"]` solves the issue, but thought it was worth reporting anyway.

**Comment by mvdan** [comment]
Have you had a look at https://github.com/mvdan/sh#caveats? I think this falls under the associative arrays caveat. The only alternative I can think of is backtracking or parsing the input twice, which is going to be quite complex.

I realise that this means the parser isn't fully Bash compatible. But that's fine. The distinction is that Bash only fully parses expansions and index expressions at run-time, while our parser is completely static.

**Comment by zx8** [comment]
Oops, completely missed that, sorry for the noise!
