### ISSUE TITLE
shfmt: Write to files atomically instead of in place

### ISSUE THREAD

**Issue by nhooyr** [mvdan/sh#401]
See https://github.com/mvdan/sh/blob/6c13161a56af5dece4e33497e909ee4cbe3ee6bf/cmd/shfmt/main.go#L279

This causes bizarre errors with bash occasionally for us when we're formatting a script that itself calls `shfmt` and writes changes to itself because the script isn't replaced atomically.

**Comment by nhooyr** [comment]
See https://michael.stapelberg.ch/posts/2017-01-28-golang_atomically_writing/

**Comment by nhooyr** [comment]
https://github.com/google/renameio

**Comment by mvdan** [comment]
Thanks, you're right - I just hadn't thought about it. I wrote this tool in 2016, before all the talk around atomic file writes in Go :) We can definitely add a small dependency to the shfmt tool for this.

**Comment by ArturKlauser** [comment]
I can see how that would be useful in the situation described. Just one question: Does it also guarantee that the rewritten file has exactly the same metadata, like ownership, permissions, and weirder ones like ACLs and extended attributes on OSX?

**Comment by mvdan** [comment]
@ArturKlauser I don't think atomic file writing packages for Go go that far. I agree that permission and ownership must be kept. I don't think the others are as important or common, but it would be ideal to keep them too.

Whatever we come up with, remember that it must be portable. And I'd strongly prefer to not add an option for this.

Any ideas, @nhooyr?

**Comment by nhooyr** [comment]
Permissions are easy to propagate. The other stuff no, but most applications do atomic writes and I've never had any issues. I'd take a look at golang/go and see how they're writing files and just do that.

I completely agree that there shouldn't be an option for this.

**Comment by mvdan** [comment]
> Permissions are easy to propagate.

Can you clarify how? For example, `os.Chown` doesn't work at all on Windows.

**Comment by nhooyr** [comment]
I only meant `Chmod`, not ownership.

**Comment by mvdan** [comment]
For those wondering, the fix above tries to keep the permission bits, in particular for the executable bit (which is recorded in git). Aside from that, the replaced file is a new file with new metadata.
