### ISSUE TITLE
syntax: does not parse bash/ksh {varname[idx]} redirections correctly

### ISSUE THREAD

**Issue by dcsobral** [mvdan/sh#403]
This is similar to #257, but when using an index. For example:

```bash
#!/usr/bin/env bash

declare -a ARR
I=0
J=1
: {FD}<"${BASH_SOURCE[0]}"
: {ARR[$I]}<"${BASH_SOURCE[0]}"   # Not recognized
: {ARR["$J"]}<"${BASH_SOURCE[0]}" # Not recognized
: {ARR[2]}<"${BASH_SOURCE[0]}"    # Not recognized

grep "[d]eclare" <&"${FD}"
grep "[d]eclare" <&"${ARR[$I]}"
grep "[d]eclare" <&"${ARR[$J]}"
grep "[d]eclare" <&"${ARR[2]}"
```

Bash hackers' [bashchanges](https://wiki.bash-hackers.org/scripting/bashchanges) indicates this was added on 4.3-alpha, and has a remark indicating it comes from ksh93. Neither bash nor ksh93 man pages refer to `{varname[idx]}` but it is, indeed, valid.

**Comment by mvdan** [comment]
Ah, more weird syntax I wasn't aware of :) Happy to accept changes to add this. Otherwise I'll work on it myself at some point.

**Comment by mvdan** [comment]
On second thought, I'm hesitant to add support for a Bash feature that isn't even documented. I'm happy to reopen this if someone can find good documentation on the feature in Bash's official documentation. The changelog doesn't count, because it's massive and isn't an up-to-date reference of the language.

**Comment by kaey** [comment]
There seem to be a test for this in bash-5.0/tests/vredir7.sub

**Comment by mvdan** [comment]
Source code or tests still aren't very helpful, because we don't want to reverse-engineer or reimplement undocumented features :)
