### ISSUE TITLE
Inconsistent set -e behavior (?)

### ISSUE THREAD

**Issue by bilus** [mvdan/sh#404]
We run into a problem when writing an Oya pack. It appears the interpreter is not fully compatible with bash when `set -e` is used. (Or we're doing something wrong.)

```shell
set -e

aa=uu
if [ -z "$aa" ]; then
    echo "exiting"
    exit 1
fi
```

```
$ bash test.sh; echo $?
0
```

```
$ gosh test.sh; echo $?
exit status 1
1
```

The Single UNIX Specification describes the effect of `set -e` as:

> When this option is on, if a simple command fails for any of the reasons listed in Consequences of Shell Errors or returns an exit status value >0, and is not part of the compound list following a while, until, or if keyword, and is not a part of an AND or OR list, and is not a pipeline preceded by the ! reserved word, then the shell shall immediately exit.

The problem originally appeared in an [Oya](https://oya.sh) script:

```
# Oyafile
Project: sample

test: |
  set -e

  aa=uu
  if [ -z "$aa" ]; then
      echo "exiting"
      exit 1
  fi
```

```shell
$oya run test
------------------------------------------------------------------------------
Error: exit status 1

  at line 4, column 1

  3| aa=uu
> 4| if [ -z "$aa" ]; then
     ^

------------------------------------------------------------------------------
Error: task "test" failed

  in file "/Users/martinb/dev/circleci/Oyafile"
```

This is how we use the interpreter:

```go
	ctx := context.Background()
	for _, stmt := range file.Stmts {
		err := r.Run(ctx, stmt)
		switch err := err.(type) {
		case nil:
			// Continue with next statement in script.
		case interp.ExitStatus:
			// Sub-command exited.
			// Disregard, as either:
			//   - "set -e" is in effect -> and shell will exit if needed,
			//   - or not -> and exit status should be ignored anyway
		case interp.ShellExitStatus:
			// Shell interpreter exited.
			// Either early return (due to "exit" or "set -e"), or task is finished.
			errCode := int(err)
			if errCode != 0 {
				return s.errScriptFail(stmt.Pos(), headLines, err, errCode)
			}
			return nil
		default:
			return s.errScriptFail(stmt.Pos(), headLines, err, -1)
		}
	}
```

Please advise.

**Comment by mvdan** [comment]
Congratulations on grabbing #404 :)

Could you please clarify what version of the module is this? If you're on v2, could you try master (i.e. v3)?

It's entirely possible that the implementation has subtle bugs. I'm at a conference now, so I won't be able to investigate for another day or two. If you want to debug and send a fix in the meantime, that's also welcome.

**Comment by bilus** [comment]
Haven't noticed. Cool. :)

mvdan.cc/sh v2.6.5-0.20190408145316-ee3cf905f3a4+incompatible

Same thing for mvdan.cc/sh/v3 v3.0.0-alpha2 :(

**Comment by mvdan** [comment]
> and is not part of the compound list following a while, until, or if keyword, and is not a part of an AND or OR list, and is not a pipeline preceded by the ! reserved word

Ah, we simply forgot to implement this part well. I can see that now.

I'll look into a patch. Turns out `set -e` is a weirdly complex flag.

**Comment by bilus** [comment]
Works perfectly, thank you!
