### ISSUE TITLE
Expanding the home directory (~) on Windows doesn't work unless the $HOME environment variable was previously set

### ISSUE THREAD

**Issue by andreynering** [mvdan/sh#410]
Original discussion on this PR: #409, which indeed fixed the issue for me.

This bug won't reproduce, for example, on Git Bash, since it sets `$HOME` for you. But it happens while running using the Command Prompt, for example.

This was initially caught on Task while trying to setup a CI with actions: https://github.com/go-task/task/pull/239. Note how we don't use `CGO_ENABLED=0` while running tests there.

This also reproduces locally, it's just a matter of calling [shell.Fields](https://godoc.org/mvdan.cc/sh/shell#Fields) with `"~"`. It will return the current directory instead of the home directory.

**Comment by mvdan** [comment]
What test was failing? Are you calling `shell.Fields` directly?

**Comment by andreynering** [comment]
@mvdan Since you asked... [this is our failing test that reproduces this issue](https://github.com/go-task/task/blob/ad569a8a36c17a01ebf3f47a60831948f002cd18/task_test.go#L478-L495). What it does is executing [this Taskfile](https://github.com/go-task/task/blob/ad569a8a36c17a01ebf3f47a60831948f002cd18/testdata/expand/Taskfile.yml). The function the actually calls `shell.Fields` live [here](https://github.com/go-task/task/blob/ad569a8a36c17a01ebf3f47a60831948f002cd18/internal/execext/exec.go#L73-L86).

That said, I wouldn't expect you to have to understand Task's code base to debug this issue. The whole bug can be reproduced with:

```go
fields, err := shell.Fields("~", nil)
if err != nil {
	panic(err)
}
// fields[0] is the current directory instead of home
```

I think I actually understand the issue now: for `*interp.Runner` it sets the `$HOME` env [here](https://github.com/mvdan/sh/blob/0a56b9ab511e44991b6ed1dfb675b68cc747ec43/interp/interp.go#L570-L573), but that code of course only run for `*interp.Runner`, and not for `shell.Fields` for example.

**Comment by mvdan** [comment]
Ok, gotcha. I think both the `interp` and `expand` packages should use `os.UserHomeDir` and not depend on CGo. I also think you caught a valid bug in how the latter package would never end up using the existing `os/user` code.

I think the first step would be to write a short test case for `expand` or `shell` to catch this bug on Windows. The test could ensure that `HOME` is unset, to fail on the current master even if the Windows environment has the variable set. I can probably work on this in a few days, if you don't beat me to it.

**Comment by mvdan** [comment]
The CI revamp on master is complete, so we only test on Actions and on Go 1.12 and up. So we can now use `os.UserHomeDir` freely.

**Comment by andreynering** [comment]
@mvdan Thanks!
