### ISSUE TITLE
Install error: module mvdan.cc/sh@upgrade (v2.6.4+incompatible) found, but does not contain package mvdan.cc/sh/cmd/shfmt

### ISSUE THREAD

**Issue by akwala** [mvdan/sh#411]
> $ cd $(mktemp -d); go mod init tmp; go get mvdan.cc/sh/cmd/shfmt
> go: creating new go.mod: module tmp
> go: finding mvdan.cc/sh v2.6.4+incompatible
> go get mvdan.cc/sh/cmd/shfmt: module mvdan.cc/sh@upgrade (v2.6.4+incompatible) found, but does not contain package mvdan.cc/sh/cmd/shfmt

**Comment by mvdan** [comment]
What Go version is this?

**Comment by akwala** [comment]
> What Go version is this?

Just installed 1.13. 

In case it matters: I realized that I already had _shfmt_ in GOPATH -- restored from backup -- and it seems to be working with Atom pkg _format-shell_.

**Comment by mvdan** [comment]
Sorry, I can't reproduce the error. Not even on a clean Docker image:

```
$ docker run golang:1.13 bash -c 'cd $(mktemp -d); go mod init tmp; go get mvdan.cc/sh/cmd/shfmt; shfmt -version'
go: creating new go.mod: module tmp
go: finding mvdan.cc/sh v2.6.4+incompatible
go: downloading mvdan.cc/sh v2.6.4+incompatible
go: extracting mvdan.cc/sh v2.6.4+incompatible
v2.6.4
```

**Comment by akwala** [comment]
> Sorry, I can't reproduce the error. Not even on a clean Docker image:

Let me know what specifics you need. For now, I seem to have a working version of _shfmt_ so this isn't an immediate issue.

**Comment by mvdan** [comment]
If you can reproduce the error in a Docker image, that would be useful. I can't investigate a problem I can't reproduce :)

It would also be useful if you pasted your `go env`.

**Comment by akwala** [comment]
> It would also be useful if you pasted your `go env`.

```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/<truncated>/workspace/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"                                                                                               
GOMOD="/tmp/tmp.B6XNnzPdko/go.mod"                                                                            
CGO_CFLAGS="-g -O2"                                                                                           
CGO_CPPFLAGS=""                                                                                               
CGO_CXXFLAGS="-g -O2"                                                                                         
CGO_FFLAGS="-g -O2"                                                                                           
CGO_LDFLAGS="-g -O2"                                                                                          
PKG_CONFIG="pkg-config"                                                                                       
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build768121313=/tmp/go-build -gno-record-gcc-switches"   
```

**Comment by akwala** [comment]
> If you can reproduce the error in a Docker image, that would be useful.

Since you couldn't reproduce it on a Docker image, it may have to do with what's on my system. Maybe shelve the issue until someone else reports it.

**Comment by mvdan** [comment]
Yup! I haven't heard of issues with this before, so I'm closing for now :)
