### ISSUE TITLE
interp: redesign ModuleExec to not require stat calls for $PATH lookups

### ISSUE THREAD

**Issue by kaey** [mvdan/sh#413]
Say I want to implement shell command in go code, currently r.exec calls r.lookPath to find binary in PATH, even though it's not supposed to exist.
Why not rename r.lookPath to r.LookupExecutable, export it and add error return, then call it inside DefaultExec. This way there will be no unnecessary Stat() calls and path argument can be removed from ExecModule (or rename it to cmd and call like this r.Exec(r.modCtx(ctx), args[0], args[1:])).

**Comment by mvdan** [comment]
Sorry, I'm not sure I understand. You mean you want commands like `sh -c "echo foo"` to work by allowing `sh` to call the interpreter too?

I think it might be clearer if you show me a real-looking example of what you're trying to do.

**Comment by kaey** [comment]
>You mean you want commands like sh -c "echo foo" to work by allowing sh to call the interpreter too?

No.

Take a look at this example https://github.com/mvdan/sh/blob/8de1179e6c2832fb9e05e24bfe4436ba0dcecf20/interp/example_test.go#L38
It implements join command in go (ie exports go func in shell). If you run this example under strace you'll see stat call for join
```
newfstatat(AT_FDCWD, "/sbin/join", {st_mode=S_IFREG|0755, st_size=51208, ...}, 0) = 0
```
If you'll rename join to join1 (or any other name not in your PATH), you'll see even more calls
```
newfstatat(AT_FDCWD, "/sbin/join1", 0xc000096ed8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/bin/join1", 0xc000096fa8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/sbin/join1", 0xc000097078, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/bin/join1", 0xc000097148, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/local/sbin/join1", 0xc000097218, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/local/bin/join1", 0xc0000972e8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/kaey/local/bin/join1", 0xc0000973b8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/kaey/usr/bin/join1", 0xc000097488, 0) = -1 ENOENT (No such file or directory)
```

What I propose here is instead of treating commands as binaries in PATH, let ExecModule decide how to interpret them.

**Comment by mvdan** [comment]
Ah, I see what you mean now. Essentially, make ExecModule lower-level, letting it do $PATH resolution on its own.

I agree that the example you linked to shouldn't be doing a stat call; that's a limitation of the design, like you say.

I seem to remember I designed ExecModule this way to simplify common use-cases, but that can always be done with helper funcs or wrappers. I'll take a look before the v3 release, as I intend to stabilize the API of this package.

**Comment by mvdan** [comment]
@kaey should be all done; please let me know if it works for you.
