### ISSUE TITLE
interp: move OpenDevImpls code to DefaultOpen

### ISSUE THREAD

**Issue by kaey** [mvdan/sh#419]
OpenDevImpls name is confusing with regards to what it does,
`>/dev/null` is very common, making it work on windows by default is a +.
If user would want to implement /dev/null themselves, they would need to either handle it before calling DefaultOpen or copy-paste DefaultOpen, it's small anyway.

**Comment by mvdan** [comment]
If you want to suggest a better name, please do :)

I don't want to force this to be a part of the default. The default should just use the filesystem as-is.

**Comment by kaey** [comment]
Makes sense - scripts written for linux won't run on windows by default anyway, due to missing coreutils.

Maybe do it like this
`func DefaultOpen(useBuiltinDevNull bool) OpenModule {}`
See https://github.com/mvdan/sh/issues/420 for more details.

**Comment by mvdan** [comment]
If you incorporate it into the default module, then it's no longer composable. This was the point of chaining modules. If you get rid of the chaining, how can one compose this feature? It would probably need an entirely new func signature.

**Comment by kaey** [comment]
Got it. I have another idea, but I'll experiment with it a bit. Will come back later.

**Comment by mvdan** [comment]
@kaey do you still plan on refactoring the module APIs? I'd like to release v3 by the end of October, so any API suggestions must come in the next three weeks.

I agree that the current API isn't great, so I might have a crack at it myself.

**Comment by kaey** [comment]
I don't see any clear way to enable composing. It mostly comes down to wanting to support windows style paths and mingw style (`/c/Users/kaey/etc`), which is reasonable.

net/http.ServeMux style api will only work if you make different type for each path style, because they need to be cleaned before determing which handler to run. Even then creating handler which would handle C:\tmp.txt, but with any disk (D,E,F etc) would be difficult. 

Current middleware style api has problems I described here https://github.com/mvdan/sh/issues/421 but also it's difficult to communicate path cleaning (ie which mw should do it, when to do it or maybe each mw should handle it on its own)

Mixing different style paths is also difficult as you need to somehow choose whether to use `path.Clean` or `filepath.Clean`, otherwise small typos like `/dev//null` or `/dev/nul` work fine on linux (with permission denied in second case), but create $CWD\dev\nul on windows.

I think going forward with https://github.com/mvdan/sh/issues/421 is the best way right now, it creates a clear way for users to handle paths in whatever way they want for their DSLs. Once common patterns are identified, convenient api can be added here without breaking changes. 

Another thing that can be done is to create a mailing list, invite your users there and ask them directly what they want. ML eases non-bug communication between devs-users a lot.

As for this type:
>scripts written for linux won't run on windows by default anyway

so for win paths users need to write `echo foo >NUL`, for mingw style the code is
```
func open(ctx context.Context, path string, flag int, perm os.FileMode) (io.ReadWriteCloser, error) {
    path = path.Clean(path)
    if path == "/dev/null" { path = "NUL" }
    return interp.DefaultOpen()(ctx, path, flag, perm)
}
```
ie remove this function completely and handle this case by rewriting path

**Comment by mvdan** [comment]
Sure, I agree that doing 421 is a good idea. I can always delete or refactor OpenDevImpls myself; the name is confusing, and it's not much code anyway.
