### ISSUE TITLE
incorrectly fmts $((...$()..))

### ISSUE THREAD

**Issue by mmlb** [mvdan/sh#42]
bisected down to commit d1df3bcdec78e0fee97ffb5d19b008e3ab038d81

```
[manny@manny shfmt]$ echo 'echo "$(($(echo 5)+5))"' | bash
10
[manny@manny shfmt]$ git checkout -q d1df3bcdec78e0fee97ffb5d19b008e3ab038d81^
[manny@manny shfmt]$ go build &&  echo 'echo "$(($(echo 5)+5))"' | ./shfmt 
echo "$(($(echo 5) + 5))"
[manny@manny shfmt]$ git checkout -q d1df3bcdec78e0fee97ffb5d19b008e3ab038d81
[manny@manny shfmt]$ go build &&  echo 'echo "$(($(echo 5)+5))"' | ./shfmt 
echo "$( ($(echo 5)+5))"
```

**Comment by mvdan** [comment]
Nice find!

**Comment by mmlb** [comment]
awesome thanks @mvdan!

**Comment by mmlb** [comment]
so this fixes my issue, but should `shfmt` fix what was the broken case? should `shfmt` rewrite 
`"$( ($(echo 5)+5))"` -> `"$(($(echo 5)+5))"`?

**Comment by mvdan** [comment]
No - `$( (` is a subshell inside a command expansion, it should never be rewritten as `$((`. The space is forced there to avoid the ambiguity of `$((`.

See the end of http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_03.

**Comment by mmlb** [comment]
oh yeah right, I'll blame it on tunnel vision with my specific case.
