### ISSUE TITLE
interp: move KillTimeout to DefaultExec

### ISSUE THREAD

**Issue by kaey** [mvdan/sh#420]
`KillTimeout` is specific to `DefaultExec`, other exec implementations, like those written in go, don't benefit from it (you can't kill a goroutine).
I propose making `DefaultExec` a constructor, pass `killTimeout` as a param to it and remove it from interp.
`func DefaultExec(killTimeout timeDuration) ExecModule {}`
This also groups this function it under `ExecModule` type.
There is one more issue to make it more usable though, see https://github.com/mvdan/sh/issues/421

**Comment by mvdan** [comment]
Hmm, sure. Other implementations could still benefit, such as a `docker exec` implementation, but the developer can set up the kill timeout themselves. PR welcome.
