### ISSUE TITLE
interp: don't accept multiple mods in With*Modules

### ISSUE THREAD

**Issue by kaey** [mvdan/sh#421]
Current example suggests using WithExecModules like this https://github.com/mvdan/sh/blob/master/interp/example_test.go#L38
There are a few issues with it
1. Much glue code - when you want to implement 10 commands, you make a constructor and it looks like this
```
		gocmd := func(cmd string, f func(mc interp.ModuleCtx, args []string) error) func(next interp.ExecModule) interp.ExecModule {
			return func(next interp.ExecModule) interp.ExecModule {
				return func(ctx context.Context, args []string) error {
					if args[0] == cmd {
						mc, _ := interp.FromModuleContext(ctx)
						if err := f(mc, args); err != nil {
							return err
						}
					}
					return next(ctx, args)
				}
			}
		}
```
And also makes panic traces worse (lose func name) unless you implement it as package-level function.

2. Weird stack traces - say you add 2 commands - `join`, `foo`, DefaultExec, stack-trace shows like `join` calls `foo` which calls `DefaultExec`

3. DefaultExec has different func signature which means it requires wrapping. Currently it's actually always called as the last module, so I don't know why export it at all,
but see https://github.com/mvdan/sh/issues/420

I propose to change With*Module to just accept single *Module, this actually makes code simpler and fixes stack traces.
```
func exec(ctx context.Context, args []string) error {
	if logTimings {
		start := time.Now()
		defer func() {
			log.Printf("command %v finished in %v", args, time.Since(start))
		}()
	}

	mc, _ := interp.FromModuleContext(ctx)
	switch args[0] {
	case "join":
		return gojoin(ctx, mc, args)
	case "foo:
		return gofoo(ctx, mc, args)
	}

	return DefaultExec(ctx, args)
}
```
This is not HTTP, I don't think there are usecases for tons of middlewares (they're still possible, user will have to write wrapping themselves)

**Comment by mvdan** [comment]
The idea here, like you say, was middlewares. Imagine an exec module that captures when binaries aren't installed and suggests the user what package they could install. Perhaps the example I added wasn't the clearest.

You're probably right that they're generally not as needed as in HTTP, though. Feel free to send a PR.
