### ISSUE TITLE
interp: rename Open/ExecModule to Open/ExecHandler

### ISSUE THREAD

**Issue by kaey** [mvdan/sh#425]
Module is a pretty generic term and confused me a lot at first. What these functions really do is handle file open / command execution. Handler is a much less broad term.

**Comment by mvdan** [comment]
Sounds good to me - please send a patch. Be sure to update all references to "module".

Also worth noting that Go modules didn't exist when I first came up with the name. I'd probably avoid the confusion if I was designing it today.

**Comment by kaey** [comment]
How do you think `FromModuleContext` should be named?
Canonically it should be `HandlerContextFromContext(ctx)` but it looks clunky.
Maybe name type `HandlerContext` and getter `HandlerCtx(ctx)`?

**Comment by mvdan** [comment]
Following the current name, how about `FromHandlerContext`? A slightly better name would be `AsHandlerContext`, I think.

If `Handler` is not useful as a name here, then I think we should consider another replacement name for `Module`.

**Comment by kaey** [comment]
>Following the current name, how about FromHandlerContext

It looks confusing to me, that's why I suggested to change in the first place.

>If Handler is not useful as a name here

Not sure what you meant here.

I think `HandlerCtx(ctx)` is pretty good, there is also a similar example in stdlib in form of `exec.Command` and `exec.Cmd`.

You also said you didn't like OpenHandlerFunc/ExecHandlerFunc, have any other ideas?

**Comment by kaey** [comment]
Also I suggest dropping `bool` return from getter. Calling it outside of Handler warrants a panic to me. Also all examples and tests ignore it anyway, which makes panic text (in case of bugs) slightly worse.

**Comment by mvdan** [comment]
Gotcha. `HandlerCtx` sounds fine. Replacing the bool with a panic also sounds fine.

I'm not a big fan of `type FooFunc func(...`, but that's already in master, so we can tackle it in another issue/PR if I come up with a naming strategy that I like better.
