### ISSUE TITLE
interp: replace ExitStatus with functions

### ISSUE THREAD

**Issue by kaey** [mvdan/sh#426]
With extension of errors package in go 1.13 comparison with error type becomes even more clunky than it was before. Now user can wrap errors with `fmt.Errorf("my shell script failed: %w", err)` user will have to change their checks from this
```
code, ok := err.(interp.ExitStatus)
if !ok && err != nil {
   t.Fatal(err)
}

if code != 1 {
    t.Fatalf("expected exit code 1, got: %d", code)
}
```
to this
```
var code *interp.ExitStatus
if err == nil || !errors.As(err, &code) {
    t.Fatalf("expected ExitStatus error, got %v", err)
}

if code != 1 {
    t.Fatalf("expected exit code 1, got: %d", code)
}
```

I suggest making 2 funcs instead `func NewExitStatus(code int) error` `func IsExitStatus(err error) (code int, ok bool)` and unexport error type.
with this check changes to 
```
code, ok := interp.IsExitStatus(err)
if !ok && err != nil {
   t.Fatal(err)
}

if code != 1 {
    t.Fatalf("expected exit code 1, got: %d", code)
}
```

While all these examples look similar, I find first and third much easier to understand and I spent less time writing them, than second one.

There is also solves potential issue with forward compatibility, say you want to support plan9 and need to change error from `type ExitStatus uint8` to `type ExitStatus struct {Code uint8, Str string}` with types that would be a breaking change as users will need to update all their error checks. With functions you simply update 2 functions to recognize new error type add 2 more functions for new type, thats not a breaking change.

**Comment by mvdan** [comment]
I'm not sure about this one. I don't think I'll ever change the type; shells don't expose any more information than the status code. And I don't like the idea of fighting the new error wrapping semantics.

Is there a precedent to exposing extra API to work with potentially-wrapped errors?

**Comment by kaey** [comment]
>And I don't like the idea of fighting the new error wrapping semantics

It's not fighting, quite contrary. IsExitStatus will call errors.As internally.

> exposing extra API

It's not extra, it's replacement.

>Is there a precedent

```
https://godoc.org/os
func IsExist(err error) bool
func IsNotExist(err error) bool
func IsPathSeparator(c uint8) bool
func IsPermission(err error) bool
func IsTimeout(err error) bool

$ cd $(go env GOPATH)/pkg/mod
$ grep -r 'func Is.*err error.*' *
```

At one large video-streaming service I worked at we had issues with sql.ErrNoRows a few times, when it was called by a helper function and somebody would often accidentally wrap it.
Adding errs.IsNoRows(err) completely solved this at that time. That was long before popular packages like pkg/errors appeared.

**Comment by mvdan** [comment]
I don't think those os APIs are a good example; most of them have existed since Go 1.0. So they're not related to error wrapping.

I am specifically wondering if it's good practice to expose these APIs now that wrapping is a thing :)

**Comment by kaey** [comment]
>most of them have existed since Go 1.0

And the good thing, these funcs were updated to use errors.Is, so user benefit from them transparently. Those who do err == os.ErrNotExists or something now need to rewrite code manually.

>good practice to expose these APIs

it only depends on what api is easier to use and keep updating moving forward. Functionally  errors.As and IsErrXXX are the same.

**Comment by theclapp** [comment]
> shells don't expose any more information than the status code

Does the status code include the bits that indicate "killed by signal" / which signal?

**Comment by mvdan** [comment]
Do you have a link with information on that? I'm not familiar with it, and I don't think they're included.

**Comment by theclapp** [comment]
I think these about cover it:

https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html
https://manned.org/waitpid.2
https://godoc.org/os#ProcessState.ExitCode
https://godoc.org/os#ProcessState.Sys
https://godoc.org/syscall#WaitStatus

**Comment by kaey** [comment]
From those links it seems like we need to switch ExitStatus from uint8 to uint32, to match https://godoc.org/syscall#WaitStatus

**Comment by kaey** [comment]
Disregard my last comment.

**Comment by kaey** [comment]
@mvdan Have you decided on OP?

**Comment by mvdan** [comment]
Adding a func sounds good to me. But note that unexporting the type has consequences; imagine if an ExecModule wants to return an exit status error, which is very normal. That wouldn't be possible anymore after your changes.

Whatever change you propose here, it shouldn't remove useful functionality.

**Comment by kaey** [comment]
I missed text from my original message https://github.com/mvdan/sh/issues/414
there should be 2 functions: `IsExitStatus(err error)` and `NewExitStatus(code uint8) error`

**Comment by kaey** [comment]
It turns out when using `errors.As` user has to be careful when to write
`var code *interp.ExitStatus` or `var code interp.ExitStatus`
Just spent half an hour debugging this.
