### ISSUE TITLE
interp: Runner exports some unneccessary fields

### ISSUE THREAD

**Issue by kaey** [mvdan/sh#428]
Docs say that fields are read-only, which means following fields should be unexported:
```
Exec ExecModule
Open OpenModule

// And arguably these too.
Stdin  io.Reader
Stdout io.Writer
Stderr io.Writer
```

There is interesting case with `exec 2>/some/file` though, which I don't know how should be handled and exposed yet.

I would also consider actually unexporting all fields and replacing them with `runner.State() *interp.RunnerState` method. This makes api intent slightly clearer at the cost of adding new struct type, but I'm not sure whether such change is useful or not.

I think this is my last itch with current api, there are other problems, but they don't touch public api and can be fixed later.

**Comment by mvdan** [comment]
I agree on your first point there. I think these were exposed from the beginning as I didn't add the constructor options until a bit later.

I still think a separate state wouldn't be a good idea overall. I get what you're trying to get at, but what would `runner.State()` do?

* If it copies values, it's going to be slow - particularly if one wants just one field
* If it returns the values directly, then it's not really any extra protection

I think the extra godoc to clarify what the fields are for is good enough for this purpose.
