### ISSUE TITLE
After formatting, the Chinese language appears scrambled!

### ISSUE THREAD

**Issue by yuwenlong** [mvdan/sh#436]
After formatting, the Chinese language appears scrambled!

**Comment by mvdan** [comment]
Sorry, I don't understand. Please provide a way to reproduce the issue with `shfmt`, for example with an input file.

**Comment by yuwenlong** [comment]
Write shell with phpstorm.
Format code with shortcut keys.
ctrl+alt+l
At this time, the Chinese will appear scrambled code.
The code example is as follows, you can try! @mvdan 

```
#!/bin/base
# 中文乱码
echo "中文"
```

After formatting, it becomes:

```
#!/bin/base
# 涓枃涔辩爜
echo "涓枃"
```

**Comment by mvdan** [comment]
Sorry, but I still can't reproduce:

```
$ cat f.sh
#!/bin/base
# 中文乱码
echo "中文"
$ shfmt f.sh
#!/bin/base
# 中文乱码
echo "中文"
$ shfmt -w f.sh
$ cat f.sh
#!/bin/base
# 中文乱码
echo "中文"
```

**Comment by yuwenlong** [comment]
Write shell with phpstorm.
Format code with shortcut keys.
ctrl+alt+l

**Comment by yuwenlong** [comment]
Phpstorm shell script formatting tools, you write this tool!

**Comment by mvdan** [comment]
Again, I don't know what phpstorm is. You're probably using a plugin or something else that integrates `shfmt`. If you can reproduce the bug with the tool alone, I can debug and investigate. Without that, there's not much I can do here, sorry.
