### ISSUE TITLE
interp: do we really need handlerCtxKey?

### ISSUE THREAD

**Issue by h0tw4t3r** [mvdan/sh#443]
`func HandlerCtx(ctx context.Context) HandlerContext` returns `HandlerContext` based on `hc, ok := ctx.Value(handlerCtxKey{}).(HandlerContext)`. But why is it even stored in a `context.Context`, when it _could be_ a `context.Context`, and could be taken by checking the type of the `ctx`?
For example:
```
func HandlerCtx(ctx context.Context) HandlerContext {
        switch c := ctx.(type) {
	case *HandlerContext:
		return ctx.(*HandlerContext)
	default:
		panic("interp.HandlerCtx: no HandlerContext in ctx")
	}
	return nil
}
```

**Comment by mvdan** [comment]
Because that's how one stores values in a context. If we entirely take over the context, no other values can ever be stored by anyone else.

For example, imagine if one wanted to add a timeout or a deadline on the context. Then `HandlerCtx` would no longer work.

**Comment by h0tw4t3r** [comment]
But what if we add a `parent` prop to `HandlerContext`?
```
type HandlerContext struct {
	context.Context

	// Env is a read-only version of the interpreter's environment,
	// including environment variables, global variables, and local function
	// variables.
	Env expand.Environ

	// Dir is the interpreter's current directory.
	Dir string

	// Stdin is the interpreter's current standard input reader.
	Stdin io.Reader
	// Stdout is the interpreter's current standard output writer.
	Stdout io.Writer
	// Stderr is the interpreter's current standard error writer.
	Stderr io.Writer
}
```
This will allow timeouts or deadlines.

**Comment by mvdan** [comment]
You're reinventing how to layer contexts. https://golang.org/pkg/context/#WithValue accomplishes the same in a standard way.

**Comment by h0tw4t3r** [comment]
Ok, but is there any difference, or this is how it should be really done? I am writing a pausable context atm, and I want to know if should I use https://golang.org/pkg/context/#WithValue or should I layer it up?
Currently I have:
```
type asyncCtx struct {
	context.Context

	mu       sync.Mutex
	done     chan<- struct{}
	err      error
	pauseChan chan<- struct{}
	isPaused bool
}
```

And if I use https://golang.org/pkg/context/#WithValue, I can't avoid allocation for the key, so I will have to create one. Isn't context layering more efficient since it doesn't need key allocation?

**Comment by mvdan** [comment]
Context is an interface, so whatever you do you'll need allocations, sorry. If you try to break away from the standard library API, then there's no point in using contexts at all, because the main point is that they're interoperable.
