### ISSUE TITLE
for loop with curly braces not accepted

### ISSUE THREAD

**Issue by paperbenni** [mvdan/sh#444]
For loops with a syntax like this are fully supported by bash but shfmt complains about missing "do"-"done" statements. 
```sh 
   for FMT in jpg png jpeg gif; {
        downloadformat "$FMT" "$SINDEX" "$DOMAIN"
    }
```
Could be intentional, but looks like a bug/missing feature to me.

**Comment by paperbenni** [comment]
I'm so proud of getting that issue number xD

**Comment by mvdan** [comment]
Hmm, where is this bash feature documented?

**Comment by paperbenni** [comment]
It's undocumented and there for backwards compatibility with the Bourne shell (also undocumented there)
Doesn't work with while loops though.

**Comment by mvdan** [comment]
I'm sorry, but I won't implement undocumented language features. Implementing and maintaining the documented ones in bash is enough work :)

**Comment by theclapp** [comment]
I couldn't find it in the bash manpage, but it is in [the FreeBSD sh manpage](https://www.freebsd.org/cgi/man.cgi?query=sh&sektion=&n=1), in case that matters:

```
     The syntax	of the for command is:
	   for variable [in word ...]
	   do list
	   done

     If	in and the following words are omitted,	in "$@" is used instead.  The
     words are expanded, and then the list is executed repeatedly with the
     variable set to each word in turn.  The do and done commands may be re-
     placed with `{' and `}'.
```

**Comment by mvdan** [comment]
That's actually a good point @theclapp.

We follow the [POSIX Shell spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html), which doesn't document this at all. Neither does Bash, where it seems to be an undocumented historical feature.

However, we do support the mksh language (the shell bundled in Android), and it is documented there (just search for "historical"): https://linux.die.net/man/1/mksh

So, would it be useful to people if these historical braces were parsed in `shfmt -ln=mksh`? If they are needed in scripts that use Bashisms, this won't be useful. But I'd argue that those scripts should just be fixed instead.

Another option is to accept the brace forms in *all* languages, but always converting them to the documented and correct tokens. Thoughts?

**Comment by theclapp** [comment]
I would think that if a shell is not documented to accept `{/}` in place of `do/done`, this package shouldn't either.  Bash scripts that use that format should just be fixed.

**Comment by mvdan** [comment]
Right, and shfmt (i.e. the printer) would always convert them to the documented do/done form. We wouldn't support maintaining the undocumented form; we'd just make it easier to parse and fix old scripts.

**Comment by paperbenni** [comment]
I'm in support of this too. Just throwing an error although the script works fine is strange.

**Comment by mvdan** [comment]
I count three different issues and at least five unique users encountering or using this syntax in the wild, so I think being lenient here would be good. That is, parsing the braces in all languages, but always converting them to the correct form.

If some people want a "strict parser" in the future, we could add that as a parser option. It would also forbid other kinds of legacy syntax, such as backticks.
