### ISSUE TITLE
question: how to avoid sending dotfiles of files in a dot folder on a http response

### ISSUE THREAD

**Issue by deepnum** [mvdan/sh#448]
Please give me some example code

**Comment by mvdan** [comment]
What? This repository has nothing to do with http or dotfiles. You're in the wrong place, sorry.

**Comment by deepnum** [comment]
@mvdan excuse me. I know. You're a expert go user. Please help me.

**Comment by theclapp** [comment]
@deepnum Have you tried the go-nuts forum?  https://groups.google.com/forum/#!forum/golang-nuts.  That's a much better place to ask for help on random bits of Go.
