### ISSUE TITLE
Cannot build `shfmt` docker image locally

### ISSUE THREAD

**Issue by zori** [mvdan/sh#453]
Hi, just to let you know building locally on an Ubuntu 18.04 didn't work for me.

> docker build -t z-shfmt -f cmd/shfmt/Dockerfile .
Sending build context to Docker daemon  5.262MB
Step 1/6 : FROM golang:1.12-alpine3.9
1.12-alpine3.9: Pulling from library/golang
e7c96db7181b: Pull complete
5297bd381816: Pull complete
3a664477889c: Pull complete
b35909db3be3: Pull complete
8b9500b91de9: Pull complete
Digest: sha256:7a2edd6b1cfdb8efbff536b2bbcb9a006aeb44b8d2b3ce4a9a965f4f318b4808
Status: Downloaded newer image for golang:1.12-alpine3.9
 ---> d0cf363fbc2c
Step 2/6 : COPY . /go/src/mvdan.cc/sh
 ---> f8a341199446
Step 3/6 : RUN CGO_ENABLED=0 go install -ldflags '-w -s -extldflags "-static"' mvdan.cc/sh/cmd/shfmt
 ---> Running in b2c65019b373
src/mvdan.cc/sh/cmd/shfmt/main.go:17:2: cannot find package "github.com/pkg/diff" in any of:
        /usr/local/go/src/github.com/pkg/diff (from $GOROOT)
        /go/src/github.com/pkg/diff (from $GOPATH)
src/mvdan.cc/sh/cmd/shfmt/main.go:18:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
        /usr/local/go/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
        /go/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
src/mvdan.cc/sh/cmd/shfmt/main.go:19:2: cannot find package "mvdan.cc/editorconfig" in any of:
        /usr/local/go/src/mvdan.cc/editorconfig (from $GOROOT)
        /go/src/mvdan.cc/editorconfig (from $GOPATH)
The command '/bin/sh -c CGO_ENABLED=0 go install -ldflags '-w -s -extldflags "-static"' mvdan.cc/sh/cmd/shfmt' returned a non-zero code: 1

However I pulled a working docker image from here https://hub.docker.com/r/jamesmstone/shfmt/.
Cheers

**Comment by mvdan** [comment]
Thanks for catching this. The dockerfile is being used for v2 releases, but I haven't used it in master (v3) yet. I need to update it.
