### ISSUE TITLE
Help with different quote styles

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#454]
Hi, does shfmt support configurations for these different code styles?

* Always double quote: Where every string expression always use double quotes for safety and consistency. `case` matching and glob expression quote style could be preserved as-is.
* Appropriate quote: Where string expressions use no quotes (simple, single-word constants), single quotes (string phrases), and double quotes (interpolation), depending on the type of string expression.
* Minimum quote: Where strings select quote style based on the shortest character representation for the expression. For example, single quotes for 3+ word strings featuring no escape characters, whereas backslash'ed space would be shortest for a 2- word string featuring no other escape characters.

**Comment by mvdan** [comment]
Not right now, no. I don't plan on working on any of this, so I doubt it will happen unless someone comes up with a design and implementation.

**Comment by mvdan** [comment]
It doesn't seem anyone is interested in taking this on. It can be implemented in third party code or tools just as fine, so I'm closing this for now.
