### ISSUE TITLE
Backslash at the end of comment "hides" closing braces

### ISSUE THREAD

**Issue by ml-** [mvdan/sh#457]
**Version**: `3.0.0`

**Scenario:**
You have a function that calls a command with multiple options that you broke down to multiple lines due to line length or readability. You then decided to remove one flag where the line ends with a backslash by commenting it and moving it to the end of the function. Now `shfmt` fails to find the closing `}` while `bash` or other helper tools like `shellcheck` can properly handle this.

**Sample:**
```bash
hello() {
  mycmd "world" \
    --flag \
    --another-flag \
    --last-flag
    #--commented-flag-moved-to-end \
}
```

**Output**:
```
escaped_curly.sh:1:9: reached EOF without matching { with }
```

**Comment by mvdan** [comment]
Whoops. This might have been a regression in v3.0.0, since we entirely refactored how backslashes are tokenized.
