### ISSUE TITLE
Can someone explain the git assets?

### ISSUE THREAD

**Issue by rr0ss0rr** [mvdan/sh#459]
Hi .. Are these assets compiled for the associative platforms?  What format are they in?  Looking at the Mac platform.  

https://github.com/mvdan/sh/releases/download/v3.0.0/shfmt_v3.0.0_darwin_386
https://github.com/mvdan/sh/releases/download/v3.0.0/shfmt_v3.0.0_darwin_amd64

Thanks

**Comment by mvdan** [comment]
They are just binaries. On Linux, you could download the respective binary and run it. I've never used Mac, so I'm not sure if it's that simple there too, or if it's required to sign or verify the binaries in any way.

The program should be on Homebrew too, though, so you could try that instead.

**Comment by rr0ss0rr** [comment]
Thanks .. Not a problem for the Mac, I was thinking they were gzipped, but it's all good. 
I've been moving away from homebrew for the apps I use often so I don't have to wait for someone to update the formulas.

Thanks again, I use shfmt daily.
