### ISSUE TITLE
comment after heredoc is moved into heredoc

### ISSUE THREAD

**Issue by feisenko** [mvdan/sh#460]
shfmt version: shfmt_v3.0.0_linux_amd64 
if a heredoc is inside a if...; then (or while...; do), and after the heredoc is a comment with at least one whitespace in front of it, then the comment is moved into the heredoc.

Example:
```
if [ 1 -eq 1 ]; then
    cat <<+
hello
+
    # comment
fi
```
becomes:
```
if [ 1 -eq 1 ]; then
        cat <<+

        # comment
hello
+

fi
```

**Comment by mvdan** [comment]
Thanks for raising the issue. I assume this is a regression from v2?

**Comment by feisenko** [comment]
Don't know that. I have downloaded and tested shfmt for the first time some hours ago and the problem occured in the very first bash script, which I tried to optimize with shfmt. But apart from that, it brought a really good result and seems to be a useful tool.
