### ISSUE TITLE
cmd/gosh: no response to "exit"

### ISSUE THREAD

**Issue by cup** [mvdan/sh#464]
With `gosh`, if I enter `exit` and press enter, it just hangs.

As a workaround, Ctrl+C and Ctrl+Z work. I am on Windows.

**Comment by mvdan** [comment]
Heh, that's a pretty funny bug report :) Not sure how it hasn't been spotted before. I can repro on Linux.

**Comment by mvdan** [comment]
We did have lots of tests for the interactive shell, including ones with exits, but the catch was that the tests would close the shell's stdin when done. This would then force the shell to stop, even if it was hung, which it was in this case.

I've now written a test that *does not* close stdin after an exit call, to ensure that the interactive shell stops on its own. And fixed the underlying bug.

Thanks again!
