### ISSUE TITLE
expand: "$@" expands to "" when $@ is empty; should expand to nothing, i.e. be removed

### ISSUE THREAD

**Issue by theclapp** [mvdan/sh#473]
In bash (and zsh and ksh), `"$@"` should expand to nothing (0 arguments, i.e. be removed) when `$@` is empty.  (Unquoted `$@` works as expected.)

Bash man page; see bolded sentence:

> @
> 
> Expands to the positional parameters, starting from one. When the expansion occurs within double quotes, each parameter expands to a separate word. That is, "$@" is equivalent to "$1" "$2" ... If the double-quoted expansion occurs within a word, the expansion of the first parameter is joined with the beginning part of the original word, and the expansion of the last parameter is joined with the last part of the original word. **When there are no positional parameters, "$@" and $@ expand to nothing (i.e., they are removed).** [emphasis added]

Bash:
```sh
% function f {
> echo "\$# = $#"
> }

% f
$# = 0

% function g {
> f "$@"
> }

% g
$# = 0

% g x
$# = 1

% g x x
$# = 2
```

gosh:
```sh
$ function f {
> echo "\$# = $#"
> }

$ function g {
> f "$@"
> }

$ f
$# = 0

$ f x
$# = 1

$ g
$# = 1     # should be 0

$ g x
$# = 1

$ g x x
$# = 2
```

Unquoted `$@` works as expected:

gosh:
```sh
$ function f {
> echo "\$# = $#"
> }
$ function g {
> f $@
> }

$ f
$# = 0

$ f x
$# = 1

$ g
$# = 0     # correct value

$ g x
$# = 1
```

**Comment by mvdan** [comment]
Thanks for filing this bug! It does look like we missed one of the edge cases in the tests.
