### ISSUE TITLE
Manage space between pipes

### ISSUE THREAD

**Issue by soullivaneuh** [mvdan/sh#474]
My work-team as many ways to manage spacing between pipe:

```bash
cmd1 | cmd2
cmd1|cmd2
cmd1 |cmd2
```

Each are debatable, but we need consistency.

It would be great if shfmt can manage this and maybe add options about how to manage pipe spacing.

**Comment by mvdan** [comment]
The consistency is already there. Always the first form.

**Comment by soullivaneuh** [comment]
@mvdan Do we have to use an option for that? shfmt does not give any care on our scripts.

**Comment by soullivaneuh** [comment]
Oh right, this is a bit more tricky than that. It does not work if the command is inside a string:

```shell
fpmVersion=$(ssh_command "pgrep -a 'php-fpm' | grep master |awk '{print \$5}' |cut -d '/' -f4 |sort -nr |uniq |head -n 1")
```

Yes, that is quite ugly, but we have to deal with it for now. :upside_down_face: 

I'm not sure this issue is resolvable then, what do you think?

**Comment by mvdan** [comment]
Yeah, this is not resolvable right now. Parsing code inside a string is practically impossible. What if you join strings? What if it's double quotes and contains expansions? What if the parent script is POSIX shell, but the quoted shell code is bash?

The best option for you is to avoid placing code in strings whenever possible.

**Comment by theclapp** [comment]
So, just to be _that guy_, would it help if you optimized that pipeline a little?

```sh
fpmVersion=$(ssh_command "pgrep -a 'php-fpm' | awk '/master/ { split($5, f, "/"); if (f[4] > max) { max = f[4] } } END { print max }'")
```

and if not, maybe try this instead:

```sh
fpmVersion=$(ssh_command "pgrep -a 'php-fpm'" | grep master |awk '{print $5}' |cut -d '/' -f4 |sort -nr |uniq |head -n 1)
```

which puts the pipeline outside the quotes.  (For that matter, you could put my awk command outside the quote, too.)

shfmt on that gets what you want:

```sh
fpmVersion=$(ssh_command "pgrep -a 'php-fpm'" | grep master | awk '{print $5}' | cut -d '/' -f4 | sort -nr | uniq | head -n 1)
```

Of course that also means that everything from the `grep` to the `head` is run locally, which maybe you don't want.  🤷‍♂

Anyway, just a thought.
