### ISSUE TITLE
v3.0.1 release not in sync with sources

### ISSUE THREAD

**Issue by ArturKlauser** [mvdan/sh#476]
Released v3.0.1 binaries (and source tarball) report being v3.0.1
Github source tree is still on `version = "v3.0.0"`
https://github.com/mvdan/sh/blob/master/cmd/shfmt/main.go#L59

**Comment by mvdan** [comment]
You're looking at master, which is not a tagged version. You should look at the v3.0.1 tag.

The version that master currently reports just does not matter. I could keep it to "devel", only changing the version in each separate tag, but I've been a bit lazy to do that extra work.

**Comment by ArturKlauser** [comment]
Sorry, my bad, didn't realize how you had organized that.
