### ISSUE TITLE
syntax: escaping end of lines in here document leads to endless indentation

### ISSUE THREAD

**Issue by aerobounce** [mvdan/sh#486]
## Environment
```
shfmt -version 
v3.0.1
```

## Problem
If the end of lines are **escaped** inside **here-document** and **if that command is inside loop or wrapped in something**, **indentation occurs** somehow, and **moreover that never stops**.

### Versions
So far, I've tested `shfmt_v3.0.0-beta1_darwin_386` and it already had this bug.\
However not in `v.2.6.4`.

## Steps to reproduce
This problem is reproducible with just `shfmt` without any options.\
Here's the minimal example that reproduce the behavior:
```bash
for i in "$@"; do
    some-command << EOL
some-command "$i" \
    -options \
    -options \
    -options \
    -options
EOL
done
```
or even more simpler:
```bash
{
    some-command << EOL
some-command \
    -options \
    -options \
    -options \
    -options
EOL
}
```
You see both are **wrapped** in something.
So it seems the conjecture that causes this behavior is:

1. An end of line is escaped with `\`
2. `1.` is in here-doc
3. The command is wrapped in `function` or `loop` or whatever syntax indent happens for command written inside of it.

----

Now, let's see the detail.
You will see auto indent happen on all of the `-options` lines every time you format them.

#### Original

```bash
{
    some-command << EOL
some-command \
    -options \
    -options \
    -options \
    -options
EOL
}
```

I mean, if you format the above, it will be:

```bash
{
    some-command << EOL
some-command \
        -options \
        -options \
        -options \
        -options
EOL
}
```

Now format again then:
```bash
{
    some-command << EOL
some-command \
            -options \
            -options \
            -options \
            -options
EOL
}
```

Again:
```bash
{
    some-command << EOL
some-command \
                -options \
                -options \
                -options \
                -options
EOL
}
```

... so on. And it seems there is no dead-end, indentation never stops.

## Similar but not reproducible
Below are in similar syntax but are cases this behavior doesn't happen:\
\
**The same command structure, but not wrapped in anything**
```bash
some-command << EOL
some-command "$i" \
            -options \
            -options \
            -options \
            -options
EOL
```

**No EOL escaping**
```bash
{
    some-command << EOL
some-command "$i" -options -options -options -options
EOL
}
```

**No use of here-doc**
```bash
{
    some-command \
        -options \
        -options \
        -options \
        -options
}
```

## Expected behavior
Plain strings in here-docs should not be changed in anyway.

**Comment by mvdan** [comment]
Thanks for filing this bug! This was a sneaky one. I'm surprised that it went unnoticed for so long.

**Comment by aerobounce** [comment]
Wow that was quick! Thanks for this.
