### ISSUE TITLE
There's no v3.0.1 image on Docker Hub

### ISSUE THREAD

**Issue by y0ssar1an** [mvdan/sh#487]
There's no v3.0.1 image [on Dockerhub](https://hub.docker.com/r/mvdan/shfmt/tags).
Can you please cut a `v3.0.1` image? Thanks in advance, and thank you for creating this awesome project!

**Comment by mvdan** [comment]
Whoops - my bad. Someone recently contributed code to automate this via CI, and I forgot I did this release right before that merge.

**Comment by mvdan** [comment]
Done: https://hub.docker.com/layers/mvdan/shfmt/v3.0.1/images/sha256-665643ea9e94ad9e62a9ecbe3f16538d0d05354dc9a0365a2d37a4d8a877b51e

**Comment by y0ssar1an** [comment]
Thank you!
