### ISSUE TITLE
how to install this project?

### ISSUE THREAD

**Issue by Zhenye-Na** [mvdan/sh#489]
Sorry for this dumb question, but I have read the `README` several times and I am not familiar with Golang, so I am wondering how I can download or install this project to my local machine? I am considering to use `format-shell` in Atom.

Any advice or suggestion will be highly appreciated.

> Maybe I can help to add the installation section to the `README` file later.

Thanks!

**Comment by mvdan** [comment]
The README explains; just see `GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt`. If you don't know what that means, see golang.org. There are also binaries provided with each release, as well as Docker images.

**Comment by brandonjbjelland** [comment]
The install process wasn't obvious to me either. Consider adding just the word install above below the shfmt heading.

**Comment by LinuxOnTheDesktop** [comment]
Even after installing Go, and adding the Go binary to a path that an open terminal can find, I have two problems.

1) I did not realise that `GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt` has to be one line (but it does).

2) 
```

$ GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
go: finding mvdan.cc/sh v2.6.4+incompatible
go: finding mvdan.cc/sh/v3 v3.4.3
go: downloading mvdan.cc/sh v2.6.4+incompatible
go: downloading mvdan.cc/sh/v3 v3.4.3
go: extracting mvdan.cc/sh v2.6.4+incompatible
go: extracting mvdan.cc/sh/v3 v3.4.3
go: downloading github.com/pkg/diff v0.0.0-20210226163009-20ebb0f2a09e
go: downloading mvdan.cc/editorconfig v0.2.0
go: downloading golang.org/x/term v0.0.0-20210916214954-140adaaadfaf
go: downloading github.com/google/renameio v1.0.1
go: extracting mvdan.cc/editorconfig v0.2.0
go: extracting golang.org/x/term v0.0.0-20210916214954-140adaaadfaf
go: extracting github.com/google/renameio v1.0.1
go: downloading golang.org/x/sys v0.0.0-20210925032602-92d5a993a665
go: extracting github.com/pkg/diff v0.0.0-20210226163009-20ebb0f2a09e
go: extracting golang.org/x/sys v0.0.0-20210925032602-92d5a993a665
go: finding github.com/google/renameio v1.0.1
go: finding github.com/pkg/diff v0.0.0-20210226163009-20ebb0f2a09e
go: finding golang.org/x/term v0.0.0-20210916214954-140adaaadfaf
go: finding mvdan.cc/editorconfig v0.2.0
go: finding golang.org/x/sys v0.0.0-20210925032602-92d5a993a665
build mvdan.cc/sh/v3/cmd/shfmt: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
```

So I am downloading a binary from your Releases page. Hmm, where to put that binary . .
