### ISSUE TITLE
interp: test flake with -race on mac

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#493]
https://github.com/mvdan/sh/runs/417718558

```
$ go test -short -race -count=1 ./...
ok  	mvdan.cc/sh/v3/cmd/gosh	1.275s
ok  	mvdan.cc/sh/v3/cmd/shfmt	10.646s
ok  	mvdan.cc/sh/v3/expand	1.185s
?   	mvdan.cc/sh/v3/fileutil	[no test files]
--- FAIL: TestRunnerRun (0.19s)
    --- FAIL: TestRunnerRun/779 (0.02s)
##[error]        interp_test.go:2559: wrong output in "sed 's/o/e/g' <(echo foo bar)":
            want: "fee bar\n"
            got:  "open /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/sh-interp-3747852017: no such file or directory"
FAIL
FAIL	mvdan.cc/sh/v3/interp	2.472s
```

A real bug, or a weird mac-related problem? Probably the former. Sadly, I don't have a mac machine to test with.

**Comment by mvdan** [comment]
Reached ten thousand parallel runs with `cd interp; go test -c -vet=off -race -o test && stress -p 32 ./test -test.run TestRunnerRun/779`, and still no luck. If anyone is on Mac and could try the same, that woul be appreciated.

**Comment by theclapp** [comment]
```
...
4511 runs so far, 0 failures

/var/folders/32/8nd008752lv7v3vsgzlrw6qr0000gn/T/go-stress-20200201T180947-930576139
--- FAIL: TestRunnerRun (0.06s)
    --- FAIL: TestRunnerRun/779 (0.00s)
        interp_test.go:2559: wrong output in "sed 's/o/e/g' <(echo foo bar)":
            want: "fee bar\n"
            got:  "file exists\nexit status 1"
FAIL


ERROR: exit status 1

4661 runs so far, 1 failures
...
[ and a few more of the same before I hit 1000 ]
```

MacBookPro 2014 running macOS Mojave 10.14.6 (18G103), 2.8 GHz Intel Core i7.

**Comment by mvdan** [comment]
Thanks - so it is a real bug, and not simply an issue with the GitHub Actions machine.

Now, I wonder if it has anything to do with Mac in particular... I don't think it should, but so far we've only seen it there.

**Comment by mvdan** [comment]
So, we do something a bit weird. When we create a FIFO on disk, the writer deletes the file as soon as it's done writing. That seems to work well on Linux, and I haven't encountered a single flake. It seems to be flaky on Mac - maybe our code is buggy, or maybe Mac has different guarantees on deleting FIFOs with opened readers.

I've also pushed a couple of commits that might help (see above); if anyone can re-test on a Mac machine, that would be helpful. Otherwise, I'll keep an eye on CI to see if it fails again. CI appears to get about one failure per week due to this flake on Mac.

**Comment by theclapp** [comment]
Pulled master & did 11744 runs w/no error.  Same machine as before.  I think you're good.  🎉

**Comment by mvdan** [comment]
Wow, I can't believe that lazy attempt worked :) I'll reopen if CI spots it again.
