### ISSUE TITLE
expand: ${!prefix@} does not expand into separate fields

### ISSUE THREAD

**Issue by theclapp** [mvdan/sh#496]
The bash manpage says

```
       ${!prefix*}
       ${!prefix@}
              Names matching prefix.  Expands to the names of variables whose names  begin
              with  prefix,  separated by the first character of the IFS special variable.
              When @ is used and the expansion appears within double quotes, each variable
              name expands to a separate word.
```

So in gosh:
```
$ f11=1
$ f22=2
$ f33=3
$ f44=4
$ echo ${!f*}
f11 f22 f33 f44
$ set ${!f*}
$ echo $#
4
$ set "${!f@}"
$ echo $#
1
```

I'd expect that last echo to be 4, as if I'd said `set "f11" "f22" "f33" "f44"`.

Other uses of `@` should be checked for this behavior, too, e.g. `${name[@]} expands each element of name to a separate word.  When there are no array members, ${name[@]} expands to nothing.`, `${!name[@]}`, and others. 

This is similar to #473 .

(Sorry for the initial empty issue.  I managed to press shift-cmd-enter (I think) when entering the title, which submitted the form.  🤦‍♂ )

**Comment by mvdan** [comment]
Ah, this seems like a valid bug report, and something we should backport into the upcoming bugfix release. The actual fix would probably be a couple of lines with a test, like last time.

Do you want to have a look, since you already investigated quite a bit? Otherwise I'll probably find some time in the coming days.

**Comment by mvdan** [comment]
On second thought, this is far from trivial, and the changes are a bit intrusive. Let's leave this for 3.1.
