### ISSUE TITLE
interp: exit statuses do not reflect being killed by a signal

### ISSUE THREAD

**Issue by theclapp** [mvdan/sh#500]
Bash manpage says

> The  return  value of a simple command is its exit status, or 128+n if the command is terminated by signal n.

Bash:
```sh
bash-3.2$ sleep 120
# ... kill the sleep from another window ...
Terminated: 15
bash-3.2$ echo $?
143
```

gosh:
```sh
$ sleep 120
# ... kill the sleep from another window ...
$ echo $?
255
```

**Comment by theclapp** [comment]
See also https://github.com/mvdan/sh/issues/426#issuecomment-539185459.

**Comment by mvdan** [comment]
Sounds good to me. Note that POSIX doesn't cover this, but it does cover some other cases: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_08_02

I also think we can write decent standalone tests for this:

```
$ { sleep 1 & } 2>/dev/null; kill -2 $!; wait $! &>/dev/null; echo $?

130
$ { sleep 1 & } 2>/dev/null; kill -9 $!; wait $! &>/dev/null; echo $?
137
```

Note that `-2` makes bash print a newline for some reason. It's not clear to me if we should do the same.

**Comment by mvdan** [comment]
Writing a proper test for this turned out to be a bit of a nightmare. But the change itself was easy.
