### ISSUE TITLE
interp: "type" does not respect $PATH if it's set within the shell

### ISSUE THREAD

**Issue by theclapp** [mvdan/sh#502]
actual:
```sh
% gosh
$ PATH=/
$ type ping
ping is /sbin/ping
```

expected — something more like:
```sh
% PATH=/ ./gosh
$ type ping
type: ping: not found
```

Edit: It's actually a problem with "type"; see below.

**Comment by theclapp** [comment]
Turns out if you try to actually _run_ "ping" at that point it's not found, as expected:

```sh
% gosh
$ ping -c 2 127.0.0.1
# ... ping output ...
$ PATH=/
$ ping -c 2 127.0.0.1
"ping": executable file not found in $PATH
$ type ping
ping is /sbin/ping
```

so I guess the fault is in `type` itself?

**Comment by mvdan** [comment]
Ah yeah, we probably didn't implement this edge case properly. Patches welcome, otherwise I'll have a look eventually.
