### ISSUE TITLE
interp: exit status ($?) not being reset correctly in some edge cases

### ISSUE THREAD

**Issue by theclapp** [mvdan/sh#506]
I think gosh is only resetting Runner.exit when it runs an external command.  At very least, it's not setting it when it should.

bash:
```sh
% false ; echo $?
1
% false ; n=6 ; echo $?
0
```

The specific `n=6` command is irrelevant, I just want a command that a) succeeds and b) wouldn't "obviously" set $? but still _should_.

gosh:
```sh
$ false ; echo $?
1
$ false ; n=6 ; echo $?
1
```

This might be fallout from #499.   I can take a look at it later.

**Comment by mvdan** [comment]
I don't think your PR is to blame. It doesn't seem like we ever had a test case for this.

**Comment by mvdan** [comment]
I'll also take this one from you, as it's far from trivial. We need to split up "current status code" from "last status code".
