### ISSUE TITLE
interp: [[ -t n ]] test looks at the wrong file handles

### ISSUE THREAD

**Issue by theclapp** [mvdan/sh#508]
The `-t` code looks at file handle `n` directly, which will be global for the entire process, but if n == 0, 1, or 2 it should look at Runner.stdin, stdout, or stderr, which will be specific to each Runner.

**Comment by mvdan** [comment]
That's a good catch - patches welcome. Any other instances of file descriptor handling should be checked for the edge case of stdin/stdout/stderr too.

**Comment by mvdan** [comment]
Let's reopen until we add proper tests with https://github.com/creack/pty.
