### ISSUE TITLE
syntax: error parsing a quoted heredoc ending in a backslash

### ISSUE THREAD

**Issue by cr1st1p** [mvdan/sh#515]
shfmt fails on this type of here-document, that ends in '\'

/tmp/t.sh:
```
#! /usr/bin/env bash

cat <<'EOS'
This is me, I want an ending \
EOS

```
bash /tmp/t.sh works fine.
but shfmt:
```
/tmp/t.sh:3:5: unclosed here-document 'EOS'
```

**Comment by mvdan** [comment]
Thanks for the report - seems like an edge case to fix.
