### ISSUE TITLE
Installation failure in `golang.org/x/term`

### ISSUE THREAD

**Issue by zultron** [mvdan/sh#516]
We use (and love) `shfmt` for our project in CI.  Builds began failing recently during `shfmt` install.  Here's the error, and a simplified `Dockerfile` to reproduce the issue:

```
Step 7/7 : RUN go get mvdan.cc/sh/cmd/shfmt
 ---> Running in 603e4a192b1f
# golang.org/x/term
opt/go/src/golang.org/x/term/term_linux.go:11:7: ioctlReadTermios redeclared in this block
        previous declaration at opt/go/src/golang.org/x/term/term_aix.go:11:26
The command '/bin/sh -c go get mvdan.cc/sh/cmd/shfmt' returned a non-zero code: 2
```

```
FROM debian:stretch

RUN apt-get update \
    && apt-get install -y \
        wget \
        git \
    && apt-get clean

RUN wget --progress=dot:mega https://dl.google.com/go/go1.11.4.linux-amd64.tar.gz \
    && tar -xf go1.11.4.linux-amd64.tar.gz -C /usr/local \
    && rm go1.11.4.linux-amd64.tar.gz

ENV GOROOT=/usr/local/go
ENV PATH=$PATH:$GOROOT/bin   
ENV GOPATH=${GOPATH:-/opt/go}

RUN go get mvdan.cc/sh/cmd/shfmt
```

It looks like the failures may have coincided with cc3ea662, "interp: test tty detection properly".

**Comment by mvdan** [comment]
Please see the README - if you're getting the latest version, you'll need Go 1.12 or later, and you should be installing the tool via module mode, not GOPATH.

The way you're installing shfmt worked two years ago, but it's not supported anymore.

**Comment by zultron** [comment]
That did the trick, thanks, and thanks for the awesome tool.
