### ISSUE TITLE
shell: indent next lines of same command 

### ISSUE THREAD

**Issue by zemanlx** [mvdan/sh#517]
Hello,

first, thank you for creating and maintaining this project! I use to break long command to multiple lines for readability (and nicer git diffs). Each new line is then indented to show that it belongs to the original command and it helps with readability if it is chained with other commands.

```bash
./github-release "${TAG}" "${ARTEFACT}" \
     --commit "master" \
     --tag "${TAG}" \
     --github-repository "zemanlx/${PROJECT}" \
     --github-access-token "${GITHUB_API_TOKEN}" \
&& echo "word is beautiful"
```

Currently `shfmt` will remove indentation

```bash
./github-release "${TAG}" "${ARTEFACT}" \
--commit "master" \
--tag "${TAG}" \
--github-repository "zemanlx/${PROJECT}" \
--github-access-token "${GITHUB_API_TOKEN}" \
&& echo "word is beautiful"
```

What do you think @mvdan?

If you are not against my idea I may try to implement it.

**Comment by mvdan** [comment]
Hm - how exactly are you running `shfmt`? What version? It works fine for me:

```
$ shfmt -version
devel
$ cat f.sh
./github-release "${TAG}" "${ARTEFACT}" \
     --commit "master" \
     --tag "${TAG}" \
     --github-repository "zemanlx/${PROJECT}" \
     --github-access-token "${GITHUB_API_TOKEN}" \
&& echo "word is beautiful"
$ shfmt f.sh
./github-release "${TAG}" "${ARTEFACT}" \
	--commit "master" \
	--tag "${TAG}" \
	--github-repository "zemanlx/${PROJECT}" \
	--github-access-token "${GITHUB_API_TOKEN}" &&
	echo "word is beautiful"
```

**Comment by zemanlx** [comment]
I was playing in VS Code extension with it yesterday and I can't simulate that behaviour again :disappointed: I am sorry.

In this case, I have noticed that it also indent the next chained command. Is it possible to keep it without indentation?

My test script
```bash                                                                                                                  
ohyes \
--indent-me please \
--it-is-more-readable \
&& donotindent \
--test1 value1 \
--test2 \
&& please \
--test1 value1 \
--test2
```

Running `shfmt` will also indent next command in chain
```bash
$ ./shfmt_v3.0.1_linux_amd64 -i 4 -bn -ci -kp test.sh 
ohyes \
    --indent-me please \
    --it-is-more-readable \
    && donotindent \
        --test1 value1 \
        --test2 \
    && please \
        --test1 value1 \
        --test2
```

What I would l like to have
```bash
ohyes \
    --indent-me please \
    --it-is-more-readable \
&& donotindent \
    --test1 value1 \
    --test2 \
&& please \
    --test1 value1 \
    --test2
```

Maybe it can be useful to have this behaviour only with `-bn` option. Or is there a way how to get this working with current code?

**Comment by mvdan** [comment]
If we followed the logic you want, then we'd format code like:

```
foo \
&& bar \
&& baz
```

instead of the current

```
foo \
    && bar \
    && baz
```

I don't think that's a good idea.

**Comment by zemanlx** [comment]
ok, thank you for your time
