### ISSUE TITLE
No 3.0.2 Asset for MacOS?

### ISSUE THREAD

**Issue by rr0ss0rr** [mvdan/sh#518]
I have a bash script that compares the current version with the version on git and if different will download the asset and install.  This isn't working for 3.0.2 and noticed there is no darwin_amd64 asset for MacOS.

Thanks

**Comment by mvdan** [comment]
You seem to be right! I did that release on a slow connection, so maybe some of the uploads failed. I'll re-do the assets now.

**Comment by mvdan** [comment]
OK, it should be fixed now.

**Comment by rr0ss0rr** [comment]
Thanks
