### ISSUE TITLE
syntax: the printer breaks an edge case involving background commands

### ISSUE THREAD

**Issue by Janfel** [mvdan/sh#520]
When I format this example code:
```bash
for i in {1..5}; do ( echo a; echo b ); done
```
I get exactly what I expect:
```bash
for i in {1..5}; do (
    echo a
    echo b
); done
```

But when I want to run the subshell in the background:
```bash
for i in {1..5}; do ( echo a; echo b ) & done
```
I get this code:
```bash
for i in {1..5}; do (
    echo a
    echo b
) &;done
```
Which fails with a syntax error:
```
bash: line 4: syntax error near unexpected token `;'
bash: line 4: `) &;done'
```
Where I would have expected this:
```bash
for i in {1..5}; do (
    echo a
    echo b
) & done
```

Furthermore, if I replace the semicolons in the original code with newlines:
```bash
for i in {1..5}
do
    ( echo a; echo b )
done
```
Then the code gets formatted differently, which I am not sure is intended:
```bash
for i in {1..5}; do
    (
        echo a
        echo b
    )
done
```

**Comment by mvdan** [comment]
Thanks! This does look like a bug.
