### ISSUE TITLE
syntax: allow empty lines in arrays

### ISSUE THREAD

**Issue by thaJeztah** [mvdan/sh#521]
from the discussion on https://github.com/moby/moby/pull/40607#discussion_r386782203

Taking this script (`script.sh`);

```bash
#!/usr/bin/env bash

MY_ARRAY=(
        one
        two

        three

        four
)
```

Running `shfmt -d script.sh` produces:

```patch
--- script.sh.orig
+++ script.sh
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash

 MY_ARRAY=(
 	one
 	two
-
+	\
 	three
-
+	\
 	four
 )
```

~While this is _correct_, it would be nice if~ `shfmt` should either keep the empty lines, or trim them from the result; 

```patch
--- script.sh.orig
+++ script.sh
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash

 MY_ARRAY=(
 	one
 	two
-
 	three
-
 	four
 )
```

Tested on version:

```
shfmt --version
v3.0.2
```

/cc @tianon

**Comment by mvdan** [comment]
The original array looks like correct syntax to me - would it not be better to leave the empty lines as-is? Adding backslashes seems like a bug

**Comment by thaJeztah** [comment]
Good point, wasn't paying attention, yes you're right. (thinking now; are the empty lines treated as array entries? 🤔)

**Comment by mvdan** [comment]
They shouldn't be, the elements are just whitespace-sepearated words. I think the bug here originates from how backslashes are needed for word lists elsewhere (e.g. command arguments), but not here.

**Comment by thaJeztah** [comment]
Correct; just updated my script locally to verify, and they're indeed ignored.

**Comment by mvdan** [comment]
The fix was simple, but I don't think it's urgent enough to warrant a backport as 3.0.3 on its own. I'll do a 3.1.0 release in the next week or two.

**Comment by thaJeztah** [comment]
Thanks for the quick turnaround! Agreed, it's not an urgent issue

**Comment by tianon** [comment]
That was fast!! 😅❤️🎂

**Comment by mvdan** [comment]
:) if you encounter more issues in the next few days, I'm happy to include them in the upcoming release.
