### ISSUE TITLE
Add "shfmt" to the GitHub repository description

### ISSUE THREAD

**Issue by Calinou** [mvdan/sh#522]
I was trying to find this repository by searching "shfmt", but couldn't find it even when sorting with the "Most stars" option. Adding "shfmt" somewhere in the description should solve this.

I suppose it could also be added in the list of GitHub topics.

**Comment by mvdan** [comment]
That's fair :) I'll test some combinations.

**Comment by mvdan** [comment]
I've added `shfmt` as a topic, we'll see if that's enough to make it show up in regular searches. If not, then I'll try the description. If the repository name always wins, that would be unfortunate.

**Comment by mvdan** [comment]
Adding it just as a topic, it was showing up fourth in the default "best match" search, and shows up first under "most stars".

Adding it to the description too, it's now first in both. I'll leave it at that for now. Any ideas welcome.
