### ISSUE TITLE
_js: add option parameters to NewPrinter

### ISSUE THREAD

**Issue by JounQin** [mvdan/sh#523]
`PrinterOption` parameters are missing.

**Comment by mvdan** [comment]
Sorry, I don't understand. The parameter is there and works, as you can see in the code.

Remember that godoc.org only shows v2. The v3 docs aren't visible there, because it doesn't support modules.

**Comment by JounQin** [comment]
https://github.com/mvdan/sh/blob/master/_js/main.go#L74

Are `PrinterOption` options available here?

Related: https://github.com/mvdan/sh/issues/424#issuecomment-539710829

**Comment by mvdan** [comment]
Sorry, I hadn't seen you were talking about the JS library. Yeah, the API there isn't complete, simply because I didn't spend the time to add all the printer options. I did add the parser ones, so the same method could be copied.

**Comment by JounQin** [comment]
@mvdan Sorry but do you have any time to review the PR?

**Comment by mvdan** [comment]
I'll take a look when I can, yeah. This is difficult because we only support Go 1.13 and 1.14, but gopherjs only supports Go 1.12 at the moment.

**Comment by JounQin** [comment]
@mvdan I built and tested it with [go1.12](https://pkg.go.dev/golang.org/dl/go1.12) and it seems work, all tests pass.

```sh
# file `build`

#!/bin/sh

export GO111MODULE=on # build in module-aware mode

go1.12 run github.com/gopherjs/gopherjs build -o index.js || exit 1

node testmain.js || exit 1
```

**Comment by mvdan** [comment]
Yes, but we don't want to support Go 1.12 anymore. See the README.

If your changes work for you right now, just use those. I will get to updating the npm package, but it might take some time to properly do so.

**Comment by JounQin** [comment]
@mvdan Yeah it works and I want to use it via npm. 😂
Or should I publish it as another package temporarily due to your schedule?

**Comment by mvdan** [comment]
I ended up publishing 0.5.0 with v3.1.0 and Go 1.12.17 anyway, as it seems to work. that's better than the ancient version we had before.
