### ISSUE TITLE
How to not add () after function declaration, no spacing around "|" ... ?

### ISSUE THREAD

**Issue by pengyu** [mvdan/sh#524]
I'd like to make these changes to the format used by `shfmt`. Is there a way to tell shfmt to do so? Thanks.

- `function f() {` -> `function f {`
-  `-a | -b)` -> `-a|-b)` (in `case`)
- `${x[$y / abc ]}` ->`${x[$y/abc]}`

**Comment by mvdan** [comment]
None of those are configurable. The tool is aimed at having as few options as possible, and none of these bits seemed important or controversial enough.

In general, I'll only consider a formatting option if two major style/format guides support two ways to format a piece of code, or if the shell code out in the wild is split between the two formats. Another good indicator here is that noone has filed an issue for any of those three in the past four years :)

Leaving the issue open for a week, but I think we shouldn't change anything here.

**Comment by mvdan** [comment]
A week has passed.
