### ISSUE TITLE
docker buildx is broken on s390x

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#534]
See https://github.com/mvdan/sh/runs/557709593 for example, it fails every single time. I can reproduce that locally, and it only happens on that architecture.

I'll shortly push a commit to disable that platform, with a few of the messages I've seen between a dozen or so runs on my laptop.

This issue is to track re-enabling that platform.

/cc @ArturKlauser @oliv3r, who have done work on CI docker builds recently.

**Comment by mvdan** [comment]
I've run this past a person who works on Go's s390x port, and they'll be investigating in the coming days. The working theory is that this is a bug in either qemu or Go. Go 1.13.9 succeeds as well, so that seems to point to some form of regression or suspicious change in 1.14.x.

**Comment by ArturKlauser** [comment]
I've been doing some digging. Seems like you might be running into an instance of this QEMU bug https://lore.kernel.org/qemu-devel/157141545734.9164.17885241374277569569.launchpad@soybean.canonical.com/

> The following occurs while trying to build a custom project :
> 
>   go: github.com/FactomProject/basen@v0.0.0-20150613233007-fe3947df716e:
>   Get
>   https://proxy.golang.org/github.com/%21factom%21project/basen/@v/v0.0.0-20150613233007-fe3947df716e.mod:
>   local error: tls: bad record MAC

I haven't checked if that is already fixed in some recent version of QEMU.

**Comment by mvdan** [comment]
@ArturKlauser very nice find! The upstream bug is https://bugs.launchpad.net/qemu/+bug/1847232/. A similar downstream bug to ours is https://github.com/moby/moby/issues/40240.

I'm on qemu 4.2.0, which is the last stable release as per https://github.com/qemu/qemu/releases, so it doesn't appear to be fixed yet.

I assume we have to wait until 5.0.0 is out, and try again. Then ensure that CI has a new enough qemu.

**Comment by mvdan** [comment]
Not really related, but master is broken again for some reason: https://github.com/mvdan/sh/runs/562631353. I'll have to take a look tomorrow, as this is blocking me from doing a release. Any ideas welcome.

**Comment by mvdan** [comment]
Ah, hang on. I changed the `FROM` image, but didn't think about multi-platform builds.

**Comment by ArturKlauser** [comment]
Yeah, arm/v6 is a bit on the old side.

**Comment by oliv3r** [comment]
BUt isnt' arm/v6 the same as armhf; e.g. raspberry pi 1? And i'm not sure, but The raspbian builds seem to use armhf for all 32 bits pie's, e.g. arm/v6?

**Comment by ArturKlauser** [comment]
Nope, armhf is armv7.

https://en.wikipedia.org/wiki/ARM_architecture:
> In Debian GNU/Linux, and derivatives such as Ubuntu and Linux Mint,
> armhf (ARM hard float) refers to the ARMv7 architecture including the
> additional VFP3-D16 floating-point hardware extension ...

**Comment by oliv3r** [comment]
That contradicts this https://raspberrypi.stackexchange.com/questions/83374/raspberry-pi-zero-w-is-armv6-or-armv7 (which is what I know as well); but didn't realize the pi-zero is still a pi1 ...

As for the wikipedia link; I'm slightly in doubt here, as this would make it impossible to run debian armhf on the pi :) Alpine makes this slightly more clear in their naming, as they have armv7 packages, and armhf packages (which _are_ armv6 with hard-floats).

So say for now, there's a typo on wikipedia :)

**Comment by ArturKlauser** [comment]
Fix Wikipedia! ;)

**Comment by mikeBashStuff** [comment]
@mvdan Apologies for jumping in like that in here, but just wanted to ask if this is still blocking the release (from your last comment I take it's a "no", but wanted to be sure)? If no, is there any ETA on when the new release will pop up on github? :)

**Comment by mvdan** [comment]
@mikeBashStuff nothing is blocking - it's out now :)

**Comment by mvdan** [comment]
I don't think we should bother with s390x prebuilt binaries or docker images in the future. That user base should be tiny, and the prebuilt releases are just a convenience - the source should build in under ten seconds on any reasonable machine. Closing this issue for the foreseeable future.
