### ISSUE TITLE
v3.1.0 --version shows (devel)

### ISSUE THREAD

**Issue by rr0ss0rr** [mvdan/sh#536]
Loaded from shfmt_v3.1.0_darwin_amd64

/usr/local/bin/shfmt --version
(devel)

Thanks .. I update from git automatically based on version change.  Looks like 3.1.0 doesn't display the correct version number

**Comment by mvdan** [comment]
Whoops. We changed how the version information is fetched, making `go get` and `docker run` versions show up properly, but I forgot the binaries. I'll fix them and re-upload them.

**Comment by rr0ss0rr** [comment]
Thanks

**Comment by mvdan** [comment]
Keeping this open until I finish this.

**Comment by mvdan** [comment]
Fixed, and uploaded:

```
$ ./shfmt_v3.1.0_linux_amd64 -version
v3.1.0
```
