### ISSUE TITLE
Any way to tel shfmt to ignore formatting for HEREDOCs?

### ISSUE THREAD

**Issue by radcool** [mvdan/sh#537]
Hi,

First of all, thanks for this useful program. I love `go fmt`, so having something similar for Bash is great!

I was wondering if there's a way to tell `shfmt` to skip re-formatting within HEREDOCs. I've inserted some ASCII art drawing in a HEREDOC section of a script I'm writing, and `shfmt` messes up two of the lines in that section whenever I run it against the script.

Can `shfmt` be told to optionally skip formatting lines within HEREDOCs, or is there a way to turn formatting on/off within different portions of the script by using some kind of special directive, somewhat like `shellcheck`'s `disable` directive?:

```
# shellcheck disable=SC2206
```
Thanks!

**Comment by mvdan** [comment]
Can you provie a realistic example? It's hard for me to picture the actual problem you're running into, without first seeing one.

The tool is aimed at having as few knobs as possible, and that includes no special comments inside shell scripts. If the tool makes some reasonable use case impossible, we should just make the tool less aggressive. But that is yet to determine in this case.

**Comment by radcool** [comment]
*sigh*

I made a mistake.

The code in question is something like this:

```
cat <<HEREDOC
                       _
 _ __ ___   ___   __ _| |_
| '_ ` _ \ / _ \ / _` | __|
| | | | | | (_) | (_| | |_
|_| |_| |_|\___/ \__,_|\__|
HEREDOC
```
which, after running it through `shfmt`, ends up like this:

```
cat <<HEREDOC
                       _
 _ __ ___   ___   __ _| |_
| '_ $(_ \ / _ \ / _) | __|
| | | | | | (_) | (_| | |_
|_| |_| |_|\___/ \__,_|\__|
HEREDOC
```
I thought that was wrong because it changed the content of the HEREDOC. But after your comment I thought of actually trying to run the code and, of course, as is it gives a syntax error anyway:

```
> script.sh
momo.sh: line 1: _: command not found
                       _
 _ __ ___   ___   __ _| |_
| '_  | __|
| | | | | | (_) | (_| | |_
|_| |_| |_|\___/ \__,_|\__|
```
What I should have done instead is to use 'HEREDOC' (single quotes):

```
cat <<'HEREDOC'
                       _
 _ __ ___   ___   __ _| |_
| '_ ` _ \ / _ \ / _` | __|
| | | | | | (_) | (_| | |_
|_| |_| |_|\___/ \__,_|\__|
HEREDOC
```
and in this way `shfmt` leaves it alone and the script itself runs properly.

Sorry for the noise.
