### ISSUE TITLE
syntax: KeepPadding adds extra trailing spaces if command has Unicode chars

### ISSUE THREAD

**Issue by aureliojargas** [mvdan/sh#538]
First of all, thanks for the excellent tool. 

I've found out that `shfmt -kp` keeps adding extra trailing spaces after a command that has Unicode characters. Example:

```console
$ cat foo.sh
echo "a" || true
echo "é" || true
echo "★" || true

$ cat foo.sh | shfmt
echo "a" || true
echo "é" || true
echo "★" || true

$ cat foo.sh | shfmt | shfmt
echo "a" || true
echo "é" || true
echo "★" || true

$ cat foo.sh | shfmt -kp
echo "a" || true
echo "é"  || true
echo "★"   || true

$ cat foo.sh | shfmt -kp | shfmt -kp
echo "a" || true
echo "é"   || true
echo "★"     || true

$ shfmt -version
v3.1.0
```

The same happens when the command is slightly different:

```
echo "★" | true
echo "★" > true
{echo "★" }
(echo "★")
```

This is particularly annoying when you have your text editor configured to autoformat on file save. In that case, you just see those lines getting longer and longer :)

Tested in macOS 10.13.6.

**Comment by mvdan** [comment]
Heh, this kind of bug is silly and annoying at the same time. It looks like we messed up somewhere, indeed. The chosen formatting can be different from one's personal choice, but the output should always be stable - it shouldn't keep changing forever.
