### ISSUE TITLE
Can we integrate in visual studio code?

### ISSUE THREAD

**Issue by rogierlommers** [mvdan/sh#54]
There is a very nice plugin for Visual Studio Code: [Beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify). Do you guys think we can integrate `sh` with it?

**Comment by mvdan** [comment]
This is a question you should raise with the author of the plugin; this is a standalone tool, so it could be integrated anywhere.

Also, in case pure javascript is useful, you could compile to it with something like gopherjs: https://github.com/gopherjs/gopherjs

**Comment by mvdan** [comment]
Nothing for me to do here, it seems. If oftherwise, let me know @rogierlommers.
