### ISSUE TITLE
KSH function support

### ISSUE THREAD

**Issue by Nounours31** [mvdan/sh#541]
Hello, 
thanks a lot for your so great tool. and sorry for my vert bad english, i will do my best :) ...
I use shfmt for months on ksh script without any problem except on ksh function.
I have 2 ways to declare func :  
    1. function f { typeset x=1}
    2.  g( ) { x = 2 }

syntaxe 1 is use for local variable in ksh (x local to f) 
syntaxe 2 x is global

Problem, shfmt add '()' to f and is is no more a ksh function (function toto() {} is syntaxically false in ksh)
I try -ln=posix or mksh, but the syntax is then too different for my KSH script.

Please, is there an option I can use to avoid the '()' addition ? 

Thanks a lot, 
Pierre

**Comment by mvdan** [comment]
Sorry, but ksh is not a language we explicitly support. Bash is probably closest to what you want in terms of syntax. Do neither `f() { ... }` nor `function f() { ... }` work for you? Bash supports local variables in both of those cases, via `local foo=bar`.

**Comment by Nounours31** [comment]
Thanks for your quick answer.
I understand ksh is not supported by shfmt. Yes "f() { ... }" pattern is ksh compatible. It is what i used.
But I saw (this morning :)) that i need the "function f { ... }" pattern to use local variable in ksh (the bash local is not supported by ksh).
So if you cannot do something,  I understand very well, and do not worry, I asked you if an option exists but I don't find it. By cons I will not mix bash and ksh scripts I am afraid of unexpected results.

Thanks a lot for the time you spent to help me, and for your so great tool SHFMT!
Have a good day,
Pierre

**Comment by Nounours31** [comment]
a by pass for my cases: run just after shfmt this sed
sed -r "s/(^\s*function\s+[^(]*)\(\s*\)(.*)/\1 \2/g"

**Comment by Nounours31** [comment]
sorry some caractere disapeared ... 
 sed -r "s/(^\s*function\s+[^(])\(\s*\)(.*)/\1 \2/g"
