### ISSUE TITLE
interp: unset environment variables still seen in forked children

### ISSUE THREAD

**Issue by theclapp** [mvdan/sh#542]
If you have an exported variable that exists when gosh starts, and then in gosh you unset it, forked children still see it.

```sh
# in zsh
% export foo=bar

# start gosh
% gosh
$ echo $foo
bar
$ env | grep foo
foo=bar
$ unset foo
$ echo $foo

$ env | grep foo
foo=bar # expected nothing
$
```

If you create a new variable in gosh and then later unset it, then forked children don't see it.  It's only for variables that are exported into gosh when it starts.

**Comment by mvdan** [comment]
Thanks for the report! Indeed looks like a bug.

**Comment by theclapp** [comment]
Thanks for the quick fix!
