### ISSUE TITLE
Keep space padding for arithmetic expressions

### ISSUE THREAD

**Issue by DKroot** [mvdan/sh#543]
Currently, `shfmt` formats e.g. `(( i == 2 ))` into `((i == 2))`. I personally prefer space padding, but this is not only about me. [Google Shell Style](https://google.github.io/styleguide/shellguide.html) also uses space padding.

Could you implement an option to keep space padding for arithmetic expressions?

**Comment by mvdan** [comment]
Please read https://github.com/mvdan/sh/issues/525 first. My overall impression is that this is not important enough to warrant adding an entirely new flag just for arithmetic expression delimiters. What I replied to @tianon in that issue is my long-term thinking, so I've raised #544 for it now.

**Comment by mvdan** [comment]
Closing in favor of #544.
