### ISSUE TITLE
shfmt: consistent declaring of empty variables.

### ISSUE THREAD

**Issue by Kharacternyk** [mvdan/sh#545]
All of the below does the same:

* `VAR=`
* `VAR=""`
* `VAR=''`

It would be nice to reformat all of these to something consistent. My personal preference is `VAR=""` but it doesn't really matter which one to pick.

**Comment by mvdan** [comment]
Personally, this seems too aggressive. Do we also want to also reformat `''` into `""`, for example? What about cases that would become less consistent by converting to double quotes, like `VAR='' prog 'some' 'args'`?

It's fine if you prefer one of the above over the others, but then you should just use them yourself. A tool could exist to enforce stricter style/coding patterns, maybe even built on the same [syntax package](https://pkg.go.dev/mvdan.cc/sh/v3/syntax) that shfmt is built on top of, but I don't think this belongs in a formatter like shfmt.

**Comment by Kharacternyk** [comment]
Ok. Python's [black](https://github.com/psf/black) is more strict and I like it, but it's ok that tools differ.
