### ISSUE TITLE
Possible virus in shfmt_v3.1.0_windows_386.exe

### ISSUE THREAD

**Issue by dzedzey** [mvdan/sh#546]
My Windows complains about a virus in shfmt_v3.1.0_windows_386.exe

**Comment by mvdan** [comment]
You need to provide more details. Also, if you build from source yourself, is it the same?

There are a ton of false positives from antivirus checkers on Go binaries. If you don't trust my binaries, just build from source - it should take ten seconds.

**Comment by dzedzey** [comment]
Sorry, I didn't mean to blame somebody. I wanted to notify, maybe your system got a virus. I closed the issue
