### ISSUE TITLE
Config/Parameter file support

### ISSUE THREAD

**Issue by jkroepke** [mvdan/sh#552]
Hi,

i'm coming from https://github.com/mvdan/sh/issues/234 but since it's closed I will open a new one.

A sharing a configuration would be eliminate a lot of issues in projects with a lot of peoples.

I read the whole thread linked above.

I understand the order of the parameters are critical and must be keep. A typical config file in json for ini wouldn't keep this approach. 

So instead talking about a dedicated config file what about something like a parameter file?

For Example: `shfmt -i -bn -ci -kp -w -p -q 5 -r -z9 -bd -hi -mi`

Having a file like `.shfmt` that contains:

```
-i
-bn
-ci
-kp
-w
-p
-q 5 # Just a comment here.
-r
-z9
-bd
-hi
-mi
```

Then just run `shfmt` on CLI would result into the same approach.

This might be a compromise. But a great benefit on user side while it can be implement without a new concept to define a format syntax.

Feedback is much appreciated.

**Comment by mvdan** [comment]
Have you seen the README's mention of EditorConfig support?

**Comment by jkroepke** [comment]
Hi,
thanks a lot for the hint! Can I also set the parser to posix (`-p` flag) via `.editorconfig`?

**Comment by jkroepke** [comment]
nvm. I got it!
