### ISSUE TITLE
syntax: escaped newlines at the end of heredoc bodies are lost

### ISSUE THREAD

**Issue by aerobounce** [mvdan/sh#557]
## Problem
If you write a backslash in heredoc just before heredoc closing keyword causes line joining.

## Reproducible Code

- Original code
```sh
cat << EOL
a
b
c\
EOL
```

- After Formatting (with no options)
```sh
cat << EOL
a
b
cEOL
```

---

> Added env

## Env
It's installed via homebrew, running on macOS 10.15.4（19E287） :
```
$ shfmt -version
3.1.0
```

**Comment by mvdan** [comment]
What version are you on? I'm pretty sure this was already solved and released: https://github.com/mvdan/sh/issues/515

**Comment by aerobounce** [comment]
How could I forget such fundamentals... my bad, sorry.
It's installed via homebrew, running on macOS 10.15.4（19E287） :
```
$ shfmt -version
3.1.0
```

**Comment by mvdan** [comment]
Ah, indeed, this is a similar but different bug. Thanks for reporting.

**Comment by aerobounce** [comment]
Quick! Thanks for your work.
