### ISSUE TITLE
syntax: escapes newline after a test binary operator when it's not needed

### ISSUE THREAD

**Issue by mikeBashStuff** [mvdan/sh#565]
Example:
```
if [[ $foo == foo
        && $bar == foo
        && $bar == "$foo" ]]; then
        :
fi

# Here's shfmt's diff - -bn -ci -ln bash -d -sr
-if [[ $foo == foo
-       && $bar == foo
-       && $bar == "$foo" ]]; then
+if [[ $foo == foo && \
+       $bar == foo && \
+       $bar == "$foo" ]]; then
        :
 fi
```
I don't mind moving `&&` around, but I don't really understand why `\` is added at the end of the line. This is a single `[[ ]]` block, so there's no need to explicitly break the line here. This would make sense if each test was in its separate `[[ ]]` block, but that's not the case here.

Is there any chance to make `shfmt` not to do that? :)

**Comment by mvdan** [comment]
Moving the `&&` is on purpose, because the formatter prefers binary operators at the end of lines by default. You can use `-bn` to make it prefer those at the start of lines instead.

You're right that the backslash shouldn't be necessary, though. That seems like a bug.

**Comment by mikeBashStuff** [comment]
@mvdan `-bn` was actually set. This is the full cmdline that was used `-bn -ci -ln bash -d -sr` in this particular case.

**Comment by mvdan** [comment]
I'm moving this to v3.3.0, simply because it feels like a larger change that is really good, but probably not small enough for a bugfix release. You're welcome to use master until 3.3.0 is out, probably in 2-3 months.
