### ISSUE TITLE
interp: Invoking bash seems to consume a function's stdin

### ISSUE THREAD

**Issue by theclapp** [mvdan/sh#566]
Given a file:

```sh
function f {
  bash -c "echo foo"
  echo "f cat output"
  cat
  echo "f cat done"
}

function g {
  bash -c "echo foo" < /dev/null
  echo "g cat output"
  cat
  echo "g cat done"
}

echo bar | f
echo
echo bar | g
```

I expect the output of f and g to be the same (more or less), and in bash they are:

```sh
% bash < file
foo
f cat output
bar
f cat done

foo
g cat output
bar
g cat done
```

but in gosh they're not:

```sh
% gosh < file
foo
f cat output
f cat done

foo
g cat output
bar
g cat done
```

In gosh, calling `bash -c` seems to consume (or redirect or misdirect?) f's stdin.  In any case it's not available to the cat afterwards.

In the actual code, it's "sudo bash ...", but it turns out sudo is not part of the problem, so I left it out.  But that's why it's `bash -c "do stuff"` instead of just `do stuff`.

I doubt that this problem is specific to invoking bash, but that's the real code on my end, so that's what I'm reporting.

There doesn't seem to be any magic with bash calling bash, vs. gosh calling bash.  If I say `zsh < f` then it also works.

**Comment by mvdan** [comment]
Thank you for the reproducer! It is indeed not limited to bash; I assume this is related to any program that could consume our stdin, but doesn't. Here is a smaller repro:

```
$ cat f.sh
echo foo | { cat /dev/null; cat; }
$ bash f.sh
foo
$ gosh f.sh
```

**Comment by mvdan** [comment]
This one turned out to be an interesting one :) see the commit message.

It seems like a pretty critical fix, but since I doubt anyone but you is being affected by it, I think we can just let it sit in master for now. I can do a backported bugfix release if you have a strong preference for it.

**Comment by theclapp** [comment]
Thanks for the detailed commit message!  Interesting indeed!

I'm fine using master.

Thanks for the quick fix!
