### ISSUE TITLE
Feature request: checkbashisms-like functionality

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#567]
mvdan/sh is a really cool parser! Would it make sense to offer a bash parsing option and maybe replace the aging checkbashisms utility?

I think mvdan/sh's AST would be better suited for implementing these kinds of warnings.

https://sourceforge.net/p/checkbaskisms/checkbashisms/

**Comment by mvdan** [comment]
You appear to be looking at an out of date checkbashisms project/source. On Arch, I can see version 2.20.3, which appears to have been released in late April. You can see the latest source here: https://salsa.debian.org/debian/devscripts/-/blob/master/scripts/checkbashisms.pl

I think this would be a good idea. Writing this in Go with this module's syntax package would be far superior to a perl script using simple pattern matching.

However, this is a pretty big undertaking that I currently don't have time for. If you want to take this project on, I would suggest to create a new git repository with a Go module depending on this one.

**Comment by mvdan** [comment]
I'm leaving this issue open for just one week before closing. You've opened numerous other issues and never replied, so this is just a timeout for myself.

**Comment by mvdan** [comment]
Unsurprisingly, the week has passed.
