### ISSUE TITLE
shfmt does not respect max_line_length for case patterns

### ISSUE THREAD

**Issue by scop** [mvdan/sh#568]
It appears shfmt 3.1.1 is disregarding the spacing it adds between case patterns when determining the line length. One example is here:
https://github.com/scop/bash-completion/blob/328ce5be5/completions/openssl#L63

...and the .editorconfig:
https://github.com/scop/bash-completion/blob/328ce5be5/.editorconfig

If I manually remove the spaces inserted around the `|` between patterns, the line lengths are at or below the configured 79 characters.

**Comment by mvdan** [comment]
I'm a bit confused by this issue - shfmt currently does not have any setting around line length, nor does it use max_line_length from EditorConfig files. All of this would fall under #80, which isn't implemented.

At the moment, shfmt should not be splitting or joining lines purely on length basis. If it does, the decision should only be driven by the syntax tree.

If you find that it's joining lines when it should not be, that might be a bug, similar to https://github.com/mvdan/sh/issues/391. I would need a simple way to reproduce the problem.

**Comment by scop** [comment]
Oh, in this case this whole report is based on a false premise, I took it for granted without doing any homework that "of course" a tool like shfmt does line wrapping at configured length. Especially when in editorconfig (which is more or less the config file format for shfmt), the max_line_length setting is quite prominent and widely used.

**Comment by emadboctorx** [comment]
So, how to set a max line length? any useful conclusions?

**Comment by mvdan** [comment]
It's not supported right now, see #80.
