### ISSUE TITLE
Enhancement: Better messages for non-formattable languages

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#569]
When shfmt is unable to format a script due to the language being of a *KNOWN* shell family difficult to parse like zsh, then we can improve the behavior by:

* Dropping parse error messages
* Presenting a warning that such-and-such script is of a non-parsing shell language
* Ensuring that the final shfmt exit code is not tripped

This allows for shfmt to be used on large, complex shell script directories without having to carefully grep through shebangs and file patterns before handing `**/*` to shfmt!

**Comment by theclapp** [comment]
This seems problematic.  Suppose someone gives you a script starting with `#!/bin/zsh`.  Should you refuse to format it?  But they asked you to format it!  Should you try to format it?  But you know you very possibly can't!  Should you try to format it and just drop all warnings?  But then what's the point?

In any case: are you aware of the `-f` option?

```
  -f        recursively find all shell files and print the paths
```

I ran `shfmt -f` against my `$HOME/bin` which has some zsh scripts and it successfully skipped them (based on the `#!/bin/zsh` and `#! env zsh` in them, I assume).

**Comment by mvdan** [comment]
> Dropping parse error messages

We have no error recovery at the moment. We could possibly have some basic form of it, but that would definitely not be enough to "mostly parse" unsupported languages like zsh.

> Presenting a warning that such-and-such script is of a non-parsing shell language

What @theclapp said.

I appreciate the effort, but given that you haven't responded to any of my other comments on your 15+ issues, I'll just leave it here for now and close the issue.
