### ISSUE TITLE
syntax: opening braces are misaligned when using FunctionNextLine

### ISSUE THREAD

**Issue by scop** [mvdan/sh#570]
```
$ cat t.sh 
if true; then
	foo() {
		echo hello
	}
fi
$ shfmt -fn t.sh
if true; then
	foo()
{
		echo hello
	}
fi
```

I think the opening brace's indent on next line should align with the function definition start, i.e.
```
	foo()
	{
```
...in this example instead of always being placed at beginning of line.

**Comment by mvdan** [comment]
Thanks - that does look like a bug. I assume it wasn't found earlier since functions tend to be declared at the top level.
