### ISSUE TITLE
interp: tests fail on 32-bit platforms

### ISSUE THREAD

**Issue by mpolanski** [mvdan/sh#571]
Hi, I tried to add shfmt's tests to Alpine Linux (https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/8316) and I got errors on x86 and armv7 machines.

```
 --- FAIL: TestRunnerRun (0.02s)
    --- FAIL: TestRunnerRun/054 (0.01s)
        interp_test.go:2668: wrong output in "printf %i,%u -3 -3":
            want: "-3,18446744073709551613"
            got:  "-3,4294967293"
    --- FAIL: TestRunnerRun/055 (0.00s)
        interp_test.go:2668: wrong output in "printf %o -3":
            want: "1777777777777777777775"
            got:  "37777777775"
    --- FAIL: TestRunnerRun/056 (0.04s)
        interp_test.go:2668: wrong output in "printf %x -3":
            want: "fffffffffffffffd"
            got:  "fffffffd"
FAIL
FAIL	mvdan.cc/sh/v3/interp	0.333s
```

**Comment by mvdan** [comment]
Thanks for reporting; we indeed don't cover 32-bit on CI. I'll fix that.

**Comment by mvdan** [comment]
@mpolanski since the bug here was just in test code, I haven't backported this to a bugfix release. Assuming you want to package 3.1.1, you can cherry-pick the commit above until the next release is out.

**Comment by mpolanski** [comment]
This will do just fine, thanks!
