### ISSUE TITLE
Parser can't handle parameter transformation on indirect expansion

### ISSUE THREAD

**Issue by ml-** [mvdan/sh#572]
When a nameref is expanded and transformed at the same time, the parser fails to match `${`, `}`.
This is quiet specific and (I assume) rarely used, but it seems to be valid for at least GNU bash.

### `example.sh`

```bash
#!/usr/bin/env bash
array=([hello]=world)
ref=array
echo "Q: ${!ref@Q}"
echo "E: ${!ref@E}"
echo "P: ${!ref@P}"
echo "A: ${!ref@A}"
echo "a: ${!ref@a}"
```
### `shfmt` message

`example.sh:4:10: reached LitWord without matching ${ with }`

**Comment by mvdan** [comment]
Thanks! Looks like an edge case we missed in the parser. Fix incoming.
