### ISSUE TITLE
syntax: heredoc closing keyword is matched by prefix

### ISSUE THREAD

**Issue by aerobounce** [mvdan/sh#575]
## Env
- `macOS 10.15.5（19F96）`
- `$ shfmt -version` `$ 3.1.1`

## Problem

- Original

```sh
cat << EOL
cat << EOL_INNER
EOL_INNER
EOL
```

- After Formatting

```sh
cat << EOL
cat << EOL_INNER
EOL # <- !
EOL
```

## Minimum Reproducible Code

- Original

```sh
cat << EOL
EOL_
EOL
```

- After Formatting

```sh
cat << EOL
EOL # <- !
EOL
```

## Conditions

- This seems to be occured when Heredoc closing keywords shares prefix
- So the issue does not happen in such syntax:

```sh
cat << _EOL
EOL
_EOL
```

**Comment by mvdan** [comment]
Thanks for the report. Our logic to find the end of a heredoc might indeed be too aggressive.
