### ISSUE TITLE
How to use shfmt on aarch64 platform?

### ISSUE THREAD

**Issue by CZQzhiqiang** [mvdan/sh#578]
I downloaded the pre-compiled binary program “shfmt_v3.1.1_linux_arm” on the release page. But, it does not work on my aarch64 platform.

[root@ARMCI home]# uname -m
aarch64
[root@ARMCI home]# ./shfmt_v3.1.1_linux_arm -v
-bash: ./shfmt_v3.1.1_linux_arm: cannot execute binary file

I don't know much about go language. Is there a guide to compile shfmt from source code?

**Comment by mvdan** [comment]
You should see the README for building from source. I will probably include arm64 prebuilt releases in the future. If you want to build from source froma git clone, you can just do `go build ./cmd/shfmt`.

**Comment by mvdan** [comment]
I assume my comment above answers your question.
