### ISSUE TITLE
syntax: tabs in indented heredocs can be mangled in some cases

### ISSUE THREAD

**Issue by mmlb** [mvdan/sh#584]
Hey @mvdan 

I've recently updated to >2.4 (3.1.0 atm) and shfmt is now replacing leading tabs with spaces, almost like `sed s|\t| |g`.
I bisected the issue down to 67120158c024886ed31a46bc4238c71d33480bc9 but am not really sure whats going there and am afraid to undo what that commit was originally striving for.

You can take a look at one of the files that trigger this: https://github.com/tinkerbell/osie/blob/0f883f111a6d0bb01c248a006916d4a97024fcd4/installer/osie-installer.sh

**Comment by mmlb** [comment]
Oops I meant 2.6.4, but all my bisects were from 2.4.0 anyway, but that doesn't really matter :D.

**Comment by mvdan** [comment]
Huh, I'm really confused. It does sound like a regression from that commit, thanks for reporting.
