### ISSUE TITLE
syntax: incorrect parsing of double quote in single quote in parameter expansion

### ISSUE THREAD

**Issue by kevinoid** [mvdan/sh#587]
A shell script which includes double quotes in single quotes in a parameter expansion causes `shfmt` (built from 4600ee97) to fail.  For example, invoking `shfmt` on the script:

```sh
#!/bin/sh
var='key="value"'
var=${var#*'="'}
echo "$var"
```

prints

    /tmp/example.sh:4:11: reached EOF without closing quote "

The script runs as expected in Bash, Dash, Posh, and passes ShellCheck.  I don't see anything in the [SUS parameter expansion](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02) syntax which would prevent this use of single quotes, so I'm reporting it here.

Thanks,
Kevin

**Comment by mvdan** [comment]
Thanks, this is probably a bug somewhere in the lexer or parser.

**Comment by kevinoid** [comment]
Looks great, thanks @mvdan!
