### ISSUE TITLE
"&& must be followed by a word" but not sure why.

### ISSUE THREAD

**Issue by J-Siu** [mvdan/sh#590]
Following script test.sh:

```sh
#!/bin/bash

_TYPE=''
if [[ ${1} && (( $1 = "private" ) || ( $1 = "public" )) ]];	then
	_TYPE=${1}
else
	echo "Usage: $0 <public|private>"
	exit 1
fi

echo ${_TYPE}
```

Give error:

```sh
$ shfmt test.sh      
test.sh:4:12: && must be followed by a word

$ shfmt -version
3.1.2
```

**Comment by mvdan** [comment]
Thanks for filing this bug! It seems like we tokenize `((` as a single token, just like in the command `(( 2 + 3 ))`, instead of two separate `(` tokens. The error message also seems misleading.
