### ISSUE TITLE
is it possible to get std output continuously, using cmd.StdoutPipe() ?

### ISSUE THREAD

**Issue by stephencheng** [mvdan/sh#592]
Just a question whether this is possible as it will take long time to see the result if it takes too long to execute the script.

And how to do it? Is it even supported in GOSH?

**Comment by mvdan** [comment]
Yes, the output is piped directly to the output set up via https://pkg.go.dev/mvdan.cc/sh/v3/interp?tab=doc#StdIO.

**Comment by mvdan** [comment]
I'll assume my answer above resolved this. I don't see a bug or feature request here.

**Comment by stephencheng** [comment]
@mvdan Can I ask a favour from you?

I am integrating GOSH into my tool as an alternative shell parser, it works with some tuning. Currently I have made the new feature of async output + timeout work with the default /bin/sh

see it here: https://github.com/upcmd/up/blob/0e38f8de47201697d1aa396112ebececa1e1d117/biz/impl/shellfunc.go#L63

I will probably can dig deeper to understand how GOSH works but find it is challenging, would you mind help with above: pipe out + timeout context?

The entry of GOSH:

https://github.com/upcmd/up/blob/0e38f8de47201697d1aa396112ebececa1e1d117/biz/impl/shellfunc.go#L40

PS, saw that you were contributing to a few of my projects already, from an admirer here 👍
