### ISSUE TITLE
shfmt: keep_padding (-kp) should preserve alignment of the first array element

### ISSUE THREAD

**Issue by maximbaz** [mvdan/sh#593]
When writing PKGBUILDs for Arch Linux, people often align items on multiline arrays like so (the tooling even enforces this):

```bash
source=('one'
        'two'
        'three')
```

However `shfmt` annoyingly changes it to the style below, even when `-kp` is used:

```bash
source=('one'
    'two'
    'three')
```

Do you agree that this is something that can be fixed? 

Even if you have reasons for this being the desired behavior, could you please give me some hints on how to patch it for myself? I found that the formatting is done in `syntax/printer.go`, specifically in `elemJoin()` for these arrays, but at that time `el.Pos()` are all already pre-computed, and then it gets a bit hard to track down where those are set and how to make them respect alignment of the first element 🤔

**Comment by mvdan** [comment]
When indenting with spaces, I agree that this is reasonable; it would be covered by https://github.com/mvdan/sh/issues/471, I believe.

When indenting with tabs (the default), I do think that this would be a bad idea, because it would mix tabs and spaces.

**Comment by mvdan** [comment]
Also, you're on the right track when it comes to implementing this. The positions of the array element words are their original positions, and `-kp` already has the base code to keep track of whether any padding is necessary for a token/node. So it would be a relatively simple change to teach it that it's okay to add padding to the first token in a line, as long as we're indenting with spaces.

**Comment by maximbaz** [comment]
Just read through that issue, I agree with you that however popular, mixing tabs and spaces is a very weird idea 😬 

I also agree that the proposal should only be applied when intending with spaces, not tabs.

>  So it would be a relatively simple change to teach it that it's okay to add padding to the first token in a line, as long as we're indenting with spaces.

This makes sense! Would really appreciate some pointers to the code... 🙂

**Comment by mvdan** [comment]
You basically want to change this: https://github.com/mvdan/sh/blob/3a030eb308a30d0dccffbed287b65ab1df0f1cc2/syntax/printer.go#L271-L276

There's a field for the current indentation option, so you can use that to check if we're indenting with spaces. That should be the entire fix, I think; then it's just a matter of adding some tests.

**Comment by mvdan** [comment]
Also, let's continue in #471 if you have further questions, to not duplicate the thread :)
