### ISSUE TITLE
shfmt: arithmatic expression in subshell becomes ambiguous

### ISSUE THREAD

**Issue by SethMMorton** [mvdan/sh#596]
`shfmt` removes the space between the parenthesis of an arithmetic statement and subshell.

```diff
-elif ( (( USE_FOO )) || ( [ -d "${1?}" ] && detect_foo "${1?}" ) ) && ! (( USE_BAR )); then
+elif (((USE_FOO)) || ([ -d "${1?}" ] && detect_foo "${1?}")) && ! ((USE_BAR)); then
```

This causes two problems.

The first is that `shfmt` is now no longer able to parse this file because the parenthesis are ambiguous:

```
% shfmt -i 4 -ci -sr -w myscript 
myscript:380:6: reached ) without matching (( with ))
```

The second is now `shellcheck` complains (apparently correctly, because `shfmt` cannot parse this line)

```
In myscript line 380:
elif (((USE_FOO)) || ([ -d "${1?}" ] && detect_foo "${1?}")) && ! ((USE_BAR)); then
     ^-- SC1105: Shells disambiguate (( differently or not at all. For subshell, add spaces around ( . For ((, fix parsing errors.
```

It seems as though `bash` is able to handle the line OK, though.

Can this be fixed so that `shfmt` does not remove this space so that I can do a round-trip with the tool?

**Comment by mvdan** [comment]
Thanks for the report, this does look like a bug.
