### ISSUE TITLE
interp: for loop with nil Post panics

### ISSUE THREAD

**Issue by protolambda** [mvdan/sh#597]
Example script to reproduce this (in gosh, or a minimal parse/run go program):

```shell-script
for((i=0;i<=30;)) do echo "$i"; i=$((i+10)); done
```

The typical `++i` is missing here, and it seems to be valid in bash, but the parser simply puts `nil` as `Post`, and the interpreter does not expect it, and panics. While it works fine in GNU bash 5.0.17 for me.

```
panic: unexpected arithm expr: <nil>

goroutine 1 [running]:
mvdan.cc/sh/v3/expand.Arithm(0xc0000a0dc0, 0x0, 0x0, 0x1, 0x1, 0xc0000ac900)
        /home/proto/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/expand/arith.go:97 +0x89a
mvdan.cc/sh/v3/interp.(*Runner).arithm(0xc0000ac900, 0x0, 0x0, 0xc0002ac000)
        /home/proto/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:133 +0x46
mvdan.cc/sh/v3/interp.(*Runner).cmd(0xc0000ac900, 0x140f000, 0xc00012e000, 0x140adc0, 0xc000282e40)
        /home/proto/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:425 +0x158
mvdan.cc/sh/v3/interp.(*Runner).stmtSync(0xc0000ac900, 0x140f000, 0xc00012e000, 0xc0002a4000)
        /home/proto/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:275 +0x312
mvdan.cc/sh/v3/interp.(*Runner).stmt(0xc0000ac900, 0x140f000, 0xc00012e000, 0xc0002a4000)
        /home/proto/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:256 +0x1e9
mvdan.cc/sh/v3/interp.(*Runner).stmts(0xc0000ac900, 0x140f000, 0xc00012e000, 0xc0002ac020, 0x1, 0x4)
        /home/proto/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/runner.go:586 +0x56
mvdan.cc/sh/v3/interp.(*Runner).Run(0xc0000ac900, 0x140f000, 0xc00012e000, 0x14013c0, 0xc0000fe880, 0x0, 0x0)
        /home/proto/go/pkg/mod/mvdan.cc/sh/v3@v3.1.2/interp/api.go:523 +0x2ec
```

Version v3.1.2

Let me know if you need more details, or if you can give me some pointers on how to go about making a PR to this project. This library is awesome so far btw! I am building a niche stateful shell with it for debugging peer to peer applications interactively :)

**Comment by mvdan** [comment]
Thanks for the very detailed bug report! The relevant code is here, a few calls up the stack in your panic:

https://github.com/mvdan/sh/blob/1b12f132d20b205e360dd8469d5bcab26a4ca063/interp/runner.go#L432-L440

We likely need a nil check around `r.arithm(y.Post)`. If `Init` and `Cond` can also be nil, those should have nil checks too. You should add test cases too; just grep for `for ((` and you'll see where they are.
