### ISSUE TITLE
shfmt: strange permission issue

### ISSUE THREAD

**Issue by Phenitei** [mvdan/sh#609]
Hi,

I am having a strange problem: when I try running shfmt, it complains that it cannot open my .editorconfig file for permission reasons. To reproduce:
 * OS: Ubuntu 18.04.5
 * shell: bash
 * shfmt: v3.1.0, installed through snap

I have a script in dir/script.sh, and an .editorconfig file `root = true` in my cwd. Everything is owned with my user, and I even set all permissions to `777`, and still get the error. If I remove the editorconfig file, then the script is correctly parsed, formatted, etc...

I have tried to strace the process using `sudo strace sudo -u <myuser> shfmt dir/script.sh`, but the output shows no clear permission issue. The only mention of the editor config file is when the error is printed, after some sort of signal is caught. See [the strace log](https://gist.github.com/Phenitei/ed68d06630e1fcb63f341314922e9208).

It may be something obvious (it's late here), but I'm pretty baffled atm. Thanks for any help you can provide ^^"

**Comment by mvdan** [comment]
Nothing comes to mind right now, sorry. Perhaps try adding some debug prints, rebuilding, and seeing what the tool is trying to do. I can't help much more than this if I can't reproduce the error.

**Comment by mvdan** [comment]
I should clarify that the editorconfig code lives at https://github.com/mvdan/editorconfig.

**Comment by theclapp** [comment]
I took a look at your strace, and it appears to be tracing the sudo command, not the shfmt command.  So the `open .../.editorconfig: permission denied` text in the strace is the shfmt error read by sudo from shfmt's stderr.  But I'm not sure how you should strace it correctly, either.  What if you just `strace shfmt` directly?  (strace w/out sudo works on my system.)

Maybe a stupid question: Why are you `sudo -u <myuser> ...`?  Maybe that relates to the `root = true` directive?  It's unclear to me what that's supposed to do.

You might check if your $HOME or `/snap/bin/shfmt` is set nosuid: `mount | grep nosuid`.  I _think_ that might make a difference.

**Comment by Phenitei** [comment]
Hi, thank you both for your answers.
@theclapp : I use sudo because otherwise strace complains about it, for shfmt at least. I believe this is because snap must impose some restrictions, but as far as I could determine, this is not due to a filesystem mounted nosuid. Investigating snap's permission model seems to me like the best course of action right now (side note: the `root = True` has nothing to do with users or rights in editorconfig ;-))
@mvdan Thank you for answering. I'll have a look at the code, and see if something obvious comes to mind. Trying to reproduce with a local build will come later on, as unfortunately $job has other priorities ^^ I'll keep you posted if I find anything.

**Comment by mvdan** [comment]
Perhaps you were just running into https://github.com/bashfulrobot/snapcrafters-shfmt/issues/1, because the fix was only released a week ago.

**Comment by Phenitei** [comment]
Yep, that's exactly the issue I was having, and the fix does work for me. Thank you for your help! I'll close this.
