### ISSUE TITLE
cmd/shfmt: document FORCE_COLOR to always use colors for diffs

### ISSUE THREAD

**Issue by alexgit2k** [mvdan/sh#611]
When using for CI builds with `shfmt -d .` colors are not printed when output is piped like it is done in Gitlab.
Can be reproduced with: `shfmt -d . | more`

shfmt should have an option to force color like ls:
```
--color[=WHEN]
   colorize the output; WHEN can be 'never', 'auto', or 'always' (the default)
   With --color=auto, color codes are output only if standard output is connected to a terminal (tty).
```

**Comment by kaey** [comment]
There is a  [Undocumented way to force color](https://github.com/mvdan/sh/blob/master/cmd/shfmt/main.go#L167)

**Comment by alexgit2k** [comment]
Thanks kaey for the fast answer, that's working!

So I'm closing this ticket.

**Comment by mvdan** [comment]
Beware that the environment variable is undocumented and thus not guaranteed to keep working. I agree that forcing colored output might be useful, but I think a "color" flag is overkill. We already have `TERM=dumb` for never printing color, the default is already "auto", so we're just missing "always". There doesn't seem to be a standard opposite value like `TERM=color`, though.

**Comment by alexgit2k** [comment]
Thanks. The environment-variable is fine for me, maybe you can make it a documented variable if a flag is overkill.

**Comment by mvdan** [comment]
Maybe we should, unless someone else comes up with a more standard env var than FORCE_COLOR. If you reopen this issue, we can use it to track that bit of docs.

**Comment by alexgit2k** [comment]
Great, reopening.

**Comment by alexanderbazhenoff** [comment]
I have read this issue info then tried:
```
    FORCE_COLOR: '1'
    TERM: color
```
in my GitLab CI, but still no color.

How? :)

**Comment by alexgit2k** [comment]
@alexanderbazhenoff try:
```
script:
  - export FORCE_COLOR=1
  - shfmt -d .
```
  
or
```
script:
  - FORCE_COLOR=1 shfmt -d .
```

**Comment by alexanderbazhenoff** [comment]
@alexgit2k thanks for a the reply. I did it, but still no color.

![shfmt_bw](https://github.com/mvdan/sh/assets/19375799/54102c03-a2d6-4121-bf22-6d9ffa43ade0)

Also tried `FORCE_COLOR=1 TERM=color shfmt -l -s -d .`.

![shfmt_bw2](https://github.com/mvdan/sh/assets/19375799/a3ae8faf-91f5-40f1-95e4-b757e61d9560)

May be I need to change other env variables, something like TTY or CONSOLE?

**Comment by alexgit2k** [comment]
Haven't had an error for a while, but back then this was working:
```
shfmt:
  image: peterdavehello/shfmt:latest
  script:
  - export FORCE_COLOR=true
  - shfmt -d -i 4 -ci -p -l -s -w *.sh
```

**Comment by alexanderbazhenoff** [comment]
> ```
>   - shfmt -d -i 4 -ci -p -l -s -w *.sh
> ```
Yes, this set of options with colors.

![shfmt_col1](https://github.com/mvdan/sh/assets/19375799/8d8620ad-6bd3-432b-8524-50e70a6c8094)

So I did `FORCE_COLOR=true shfmt -l -s -d -w .`. It's ok now, but I didn't tested is it option `-w` or `FORCE_COLOR=true` instead of `1`.

Thanks a lot for the help!
