### ISSUE TITLE
syntax: escaped newline in variable assignment causes printer to break program

### ISSUE THREAD

**Issue by ceastlund** [mvdan/sh#615]
I start with the following program:
```bash
#!/bin/bash

function f {
    echo "$x"
}

if [ blah ]; then
    x=\
"zzzzzzz
bbbbb" f
fi
```

If I run this, it outputs:
```
zzzzzzz
bbbbb
```

If I run the program through shfmt version 3.1.2, I get:
```bash
#!/bin/bash

function f() {
  echo "$x"
}

if [ blah ]; then
  x=\
    "zzzzzzz
bbbbb" f
fi
```
Most importantly, this indents the string starting with `"zzzzzzz`.

If I run the formatted code, it fails with this error message:
```
./output.sh: line 9: $'zzzzzzz\nbbbbb': command not found
```

Indenting the string constant implicitly added whitespace after the `=`, separating it from the variable assignment.

**Comment by mvdan** [comment]
Thanks, this is indeed a bug. I think the printer just doesn't realise that it can't indent when inserting escaped newlines.

I assume you do want the escaped newline to remain in place in this case? That is, to not rewrite the line into `x="zzzzzzz`.

**Comment by ceastlund** [comment]
Thanks for looking into this!

For our purposes, the escaped newline is not a priority, as long as we get back an equivalent bash script that's reasonably readable. The backslash was there from before we used shfmt on that particular file, and it was hand-written. Once we adopt shfmt we're happy to accept its behavior for readability, and don't particularly need it to preserve our original formatting.
