### ISSUE TITLE
syntax: Simplify breaks array expansion within arithmetic expressions 

### ISSUE THREAD

**Issue by leagris** [mvdan/sh#616]
- shfmt v3.1.2

When used with the Simplify `-s` switch, arrays joined using the `$IFS` environment variable (`${array[*]}`) within an arithmetic expression are, wrongly reformatted as `array[*]`.

```bash
#!/usr/bin/env sh
values=(10 3 7 5 2 4 8 3)
_OIFS=$IFS
IFS=\+
sum=$((${values[*]})) #42
IFS=$_OIFS
printf %d\\n $sum
```

`sum=$((${values[*]}))` is erroneously reformatted as `sum=$((values[*]))`

Minimal reproducible example:
```sh
echo '$((${a[*]}))' | shfmt -s
```
Erroneous output:
```sh
$((a[*]))
```
Expected output:
```sh
$((${a[*]}))
```

**Comment by leagris** [comment]
Just found out:

Bash and Ksh do not like this array reference and requires the dollar curly braces extended syntax:

```sh
bash -c 'arr=(3 7); (IFS="+"; LC_ALL=C; echo "$((arr[*]))")'
```
> `bash: arr[*]: bad array subscript`

```sh
ksh -c 'arr=(3 7); (IFS="+"; LC_ALL=C; echo "$((arr[*]))")'
```
> `ksh: *: arithmetic syntax error`


Zsh is happy with it:

```sh
zsh -c 'arr=(3 7); (IFS="+"; LC_ALL=C; echo "$((arr[*]))")'
```
> `10`

**Comment by leagris** [comment]
@mvdan also affect table elements expansion with `${table[@]}`

```sh
echo 'a=(3 + 5);echo $((${a[@]}))' | shfmt | LC_ALL=C bash
```
> `8`

```sh
echo 'a=(3 + 5);echo $((${a[@]}))' | shfmt -s | LC_ALL=C bash
```
> `bash: line 2: a[@]: bad array subscript`

```sh
echo 'a=(3 + 5);echo $((${a[@]}))' | shfmt -s | LC_ALL=C ksh
```
> `ksh: line 2: @: arithmetic syntax error`

```sh
echo 'a=(3 + 5);echo $((${a[@]}))' | shfmt -s | LC_ALL=C zsh
```
> `8`

```sh
echo 'a=(3 + 5);echo $((${a[@]}))' | shfmt
```
> ```sh
> a=(3 + 5)
> echo $((${a[@]}))
> ```

```sh
echo 'a=(3 + 5);echo $((${a[@]}))' | shfmt -s
```
> ```sh
> a=(3 + 5)
> echo $((a[@]))
> ```

**Comment by mvdan** [comment]
Thank you - I think the fix here is just to not let `-s` "simplify" such array variable expansions.
