### ISSUE TITLE
cmd/shfmt: LangVariant flag regression in recent commits

### ISSUE THREAD

**Issue by kolyshkin** [mvdan/sh#617]
Using shfmt version `v3.1.1-0.20200930173521-08ecaf9adf4b` (latest git as of now, i.e. commit 08ecaf9adf4b) on the following code:

```sh
#!/bin/bash

declare -A VERSIONS=(
        [aaa]=bbb
)
```

(using tab for indentation), `shfmt -d` passes with flying colors:

```console
$ shfmt xx.sh; echo $?
#!/bin/bash

declare -A VERSIONS=(
	[aaa]=bbb
)
0
```

Now, if we want to change tab to 4 spaces, it chokes on `(`:

```console
$ shfmt -i 4 xx.sh 
xx.sh:3:21: a command can only contain words and redirects; encountered (
```

Same happens if the file is already formatted using 4 spaces for indentation.

This appears to be a regression since v3.1.2.

**Comment by kolyshkin** [comment]
git-bisected this to commit dfe3c9b1500f7e68c789c607f237a500fab962aa ("syntax: implement flag.Value in LangVariant")

**Comment by kolyshkin** [comment]
adding `-ln bash` rectifies the issue, although it's weird that autodetect stops working with `-i 4`

**Comment by mvdan** [comment]
Thanks for the detailed report, this does look like a regression.

**Comment by mvdan** [comment]
To be clear, language auto-detection isn't a thing just yet, I've got a half-done implementation on my local git clone. What was broken was the default of `-ln=bash` if you passed any other formatting flags.
