### ISSUE TITLE
syntax: parser endless loop with single quotes in parameter expansion replaces

### ISSUE THREAD

**Issue by laktak** [mvdan/sh#626]
The following will cause 3.2 to go into an endless loop:

```
foo="${foo/'{eo}'/$bar}"
```

With shfmt 3.1.2-1 it prints:

```
foo="${foo/'{eo/}'/$bar}"
```

`{eo}` was [used as a placeholder](https://github.com/laktak/extrakto/commit/6d953e7b7ac5cb390aac34ad63be6e8612078606#diff-79be0d8a3851e65769dfc0c7da662cf511bcdabbf03a17ec451f9698ed74acccL105) ... not the best choice but it did work in bash.

**Comment by mvdan** [comment]
Thank you, this is a regression. We would have caught it with fuzzing, but I can't properly fuzz right now as go-fuzz doesn't support Go 1.15 at the moment. That will be back as part of the release process soon.

**Comment by laktak** [comment]
Thank you for the quick response!

Will this also fix the issue where it inserted the slash into `{eo}` -> `{eo/}`?

**Comment by mvdan** [comment]
Sort of. That bug was fixed by 5bb742d102, which is what introduced this hang.

**Comment by mvdan** [comment]
I should note - if you still find that shfmt changes your program in any way, please file separate bugs, because they're not nearly as scary as the parser running into an endless loop.
