### ISSUE TITLE
nodejs: How to get the tree as json

### ISSUE THREAD

**Issue by prabhu** [mvdan/sh#629]
I followed the example and tried the walk method but has been unsuccessful so far. Is it possible to get the json output in the js version of this package?

**Comment by mvdan** [comment]
Have you seen https://github.com/mvdan/sh/blob/master/_js/testmain.js? That works for me, at least.

You can always obtain the json via `shfmt -tojson`, if you want.

**Comment by prabhu** [comment]
@mvdan shfmt -tojson works reliably so I'm keeping it as a fallback if nothing works.

I checked testmain.js. Other DebugPrint I just couldn't find a way to get all the nodes, it is not clear if I should be recursively calling the walk method etc? Will you able to add a dedicated tojson method to main.go, transpile and publish the npm package?

**Comment by mvdan** [comment]
I'm can't really work on the js package anymore, because it requires gopherjs which has been an abandoned project for two years now. A path forward might be to use webassembly instead.

**Comment by prabhu** [comment]
Awesome. I will use the cli invocation approach since I want to use AST json a bit longer term for a key product.

**Comment by mvdan** [comment]
It seems like the above works for you, so I'm closing this for now.
