### ISSUE TITLE
document installation instructions

### ISSUE THREAD

**Issue by Bhupesh-V** [mvdan/sh#632]
Adding this in README would be good especially for new users.
A script can be written which downloads the correct release form Releases and moves the file to appropriate directories.
For e.g in Linux it is `/usr/local/bin/`

Or are there any plans to publish this to various package managers?
Thoughts?

**Comment by mvdan** [comment]
Read the README. In particular, the section about `GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt`, and "Packages are available on...".

The releases are binaries. You can download them, and run them. There's nothing else to it, really.

**Comment by Bhupesh-V** [comment]
Ah, I See.
Although a suggestion would be to at least list installation commands for `brew` and `snap` in the README

**Comment by mvdan** [comment]
Sorry, but I disagree. If I have to explain how to use some of the package managers, why not explain how to use all of them? The README would double in size.

The links take you to each package, and you can do some very simple googling to figure out the rest.
