### ISSUE TITLE
syntax: 3.2.0 can break some multiline test expressions

### ISSUE THREAD

**Issue by CodingKoopa** [mvdan/sh#637]
Given this example Bash code:
```sh
#!/bin/bash

var1=true
var2=false

if [[ $var1 = true && -f \
  test.sh ]]; then
  echo a
fi
```

`shfmt` version `v3.2.0` is fine with this. Version `v3.2.0-16-g9becc72e`, though (the current `latest-alpine` Docker image), provides the following diff:
```diff
--- test.sh.orig
+++ test.sh
@@ -3,7 +3,7 @@
 var1=true
 var2=false
 
-if [[ $var1 = true && -f \
+if [[ $var1 = true && -f 
   test.sh ]]; then
   echo a
 fi
```
This code is malformed because it is necessary to escape the newline after the `-f`. `shfmt` should probably suggest:
```diff
--- test.sh.orig
+++ test.sh
@@ -3,7 +3,7 @@
 var1=true
 var2=false
 
-if [[ $var1 = true && -f \
+if [[ $var1 = true &&
+  -f test.sh ]]; then
   echo a
 fi
```
Unfortunately, this is a little bit awkward as version `v3.2.0` still tries to correct this to the form in the beginning of this issue. I suppose there's not much that can be done about that incompatibility though.

**Comment by mvdan** [comment]
Nicely spotted. I agree the current behavior seems wrong.

**Comment by CodingKoopa** [comment]
I can't test because the CI seems to be having a bad time (see image) and I don't want to install Go, so I'll take your word that it's fixed. Thanks!
![image](https://user-images.githubusercontent.com/13039555/100808549-58d70e80-3402-11eb-831c-482bb9987719.png)

**Comment by mvdan** [comment]
Yeah, that seems like an infra issue.

I'm pretty sure the issue is fixed. I've restarted CI, so a newer docker image will hopefully be pushed.

I also got the milestone wrong, as 3.2.0 is not affected by this regression.

**Comment by CodingKoopa** [comment]
Looks good to me on v3.2.1, thanks :+1:
