### ISSUE TITLE
OpenBSD binaries after v3.1.2

### ISSUE THREAD

**Issue by larryhynes** [mvdan/sh#639]
Hi

I think releases of shfmt up to and including version `3.1.2` included a binary for OpenBSD. Is it possible, or much trouble, to keep releasing these please?

**Comment by mvdan** [comment]
Interesting that there are users on OpenBSD, I wasn't aware :)

Before 3.2 I used a third party "cross-builder" program that chose a set of arbitrary platforms to build for. That was messy - the line drawn was a bit silly, and I was building some binaries that likely noone would ever download, like netbsd/386.

Now I use a very simple script that anyone can use to reproduce the binaries, and the line I chose to draw was to pre-build binaries for [all first class Go ports](https://github.com/golang/go/wiki/PortingPolicy#first-class-ports). The nice property there is that, if Go itself releases binary archives for your platform, so will shfmt.

The logic then is that, if you're using a less mainstream platform, you can afford the ten seconds to build shfmt, just like (presumably) you can afford the minute to build Go. If your platform builds and distributes Go, then perhaps it could build and distribute shfmt too?

I'm of course open to re-introducing more prebuilt platforms, but if I add OpenBSD, why not FreeBSD and NetBSD too? Then I'm back to building two dozen binaries :)

**Comment by larryhynes** [comment]
I haven't been able to find a prepackaged binary for shfmt on OpenBSD, which is why I've depended on your releases.

I think I did see mention of a port (ports then become packages) on the `ports@` mailing list, but I didn't bookmark the discussion. I'm just now searching the archive on [the mail archive](https://www.mail-archive.com/) but a search for `shfmt` brings up nothing  and, of course, searching for `sh` brings up *everything*, lol.

I'm loathe to install go. As a younger man I used to have build environments for all the things, but in my current setup I restrict myself to what's available in pkgs, or the base system. You can probably blame haskell for this state of affairs... it became such a total pia to jump through its hoops it caused me to question my approach at the time. Consequently, I tend to miss out on the latest hotness in go / rust / julia / whatever. That's on me, of course. ;)

Soooo, the long and the short of this would appear to be that I try to get an official OpenBSD build of your program, or keep using `v3.1.2` for as long as I can. :D 

Thanks for your time.

**Comment by mvdan** [comment]
I'd be happy to support someone's effort to package shfmt for OpenBSD, for what it's worth.

I do understand your thinking on not having all the build environments under the sun. At the same time though, Go builds are fast and the toolchain weighs half a gigabyte when fully installed, so it's not all that bad when compared to most others :)

**Comment by larryhynes** [comment]
I installed go, and shfmt, which all went very smoothly. And then I read the link you posted above, about go's porting policy, and the line that jumped out at me was:

> Graduating a port to "first class" is at the discretion of the Go team at Google.

And the lesser part of me said "screw them", so I've uninstalled go and shfmt and will have to live or die by my own linting. :D 

Thanks for the help, and for your great work.
