### ISSUE TITLE
Question about leaving and/or as the newline operator

### ISSUE THREAD

**Issue by cornfeedhobo** [mvdan/sh#653]
shfmt rewrites

```bash
printf 'foo' &&
	printf 'bar\n'
```

to 

```bash
printf 'foo' \
	&& printf 'bar\n'
```

The POSIX grammar explains that [linebreaks are allowed after any and/or](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02). Similarly `gofmt` allows and/or as the newline operator.

Is this something that has been discussed before?

**Comment by mvdan** [comment]
This does not happen by default; only if you provide the `-bn` option. The default is to use the form that does not require backslashes.

**Comment by cornfeedhobo** [comment]
@mvdan oh, interesting. I'm going to have a look at something local, and probably close this today. Thanks!
