### ISSUE TITLE
shfmt breaks a script by removing a pipe character 

### ISSUE THREAD

**Issue by hostmaster** [mvdan/sh#655]
shfmt: 3.2.1

The origin code snippet.
```
curl -s --connect-timeout 5 -m 120 "$URL" \
	| gunzip | sort >new_sorted.txt
```

`shfmt` breaks the script by removing a pipe character. Output is below
```
curl -s --connect-timeout 5 -m 120 "$URL" |
	gunzip | sort >new_sorted.txt

```

**Comment by mvdan** [comment]
I think you misread the output. The pipe got moved to the first line. See the `-bn` option if you don't like that.

**Comment by hostmaster** [comment]
Oops. Sorry. Thank you for your prompt reply.
