### ISSUE TITLE
syntax: "invalid var name" error involving declaration commands and brace expansion 

### ISSUE THREAD

**Issue by d630** [mvdan/sh#657]
v3.2.1

```sh
$ shfmt -ln bash <<<'declare _{a,b}='
<standard input>:1:9: invalid var name
```

Same for typeset, export, readonly, and local. alias is fine

**Comment by d630** [comment]
Ahhh, ok. I see. Don't worry. I'm ok with your design decision. But the readme could have one or two sentences more in detail. What do you think?

**Comment by mvdan** [comment]
Yep, I agree. Will do.
