### ISSUE TITLE
shfmt is broken on Go 1.6

### ISSUE THREAD

**Issue by cyphar** [mvdan/sh#66]
`io.SeekStart` is not defined for Go versions prior to `1.7`, so compilation fails on old Go versions.

**Comment by mvdan** [comment]
See the README and the commit message that introduced this - it's on purpose.

I don't think supporting more than two Go versions is worth it. You can also use 1.1.0 if you want to build from source with 1.6.

**Comment by mvdan** [comment]
I see you guys dropped 1.6, so I'm closing this.

I've also attached another suggestion there in https://github.com/opencontainers/runc/pull/1335#issuecomment-281285086.
