### ISSUE TITLE
'|' can only immediately follow a statement

### ISSUE THREAD

**Issue by bitfrei** [mvdan/sh#665]
Hi, I'm using shfmt not directly, but with [shell-format](https://github.com/foxundermoon/vs-shell-format/). 

For some files, I get errors when using pipelines / pipes with ('|'):
`| can only immediately follow a statement`

A simple example would be:
```
#!/bin/bash
echo "hello" \
        | tee 
```
It seems shfmt is not handling the line break properly as this one works:
```
#!/bin/bash
echo "hello" | \
        tee 
```
Albeit being a legit option I would prefer the first solution.
Also shfmt does not intend `tee..`, which should be the case?

**Comment by mvdan** [comment]
It almost sounds like there's a bug in shell-format, because shfmt works just fine with what you provided:

```
#!/bin/bash
echo "hello" \
        | tee
```

**Comment by bitfrei** [comment]
ok. Well, I couldn't test it with shfmt alone, so sorry and thanks.
