### ISSUE TITLE
Variable lookup and assignment in both Vars and cmdVars causes incorrect behavior.

### ISSUE THREAD

**Issue by twilly** [mvdan/sh#668]
Lookup of a variable value that is both a [Runner.Vars](https://github.com/mvdan/sh/blob/bbe6fdd2a7835357ae5fd290ee0415c9a24e7e65/interp/api.go#L56) and created as a [Runner.cmdVars](https://github.com/mvdan/sh/blob/bbe6fdd2a7835357ae5fd290ee0415c9a24e7e65/interp/api.go#L94) appears to be broken. 

For example, let's call a function twice by inspecting the value of `i`:

```bash
i=1
foo() {
    echo foo
    [ $i == 1 ] && i=0 foo
}
foo
```
[This should produce two prints and a clean exit](https://rextester.com/LUEG32754):

```
foo
foo
```

My guess is i=0 is created as a cmdVar as part of executing the CallExpr, but a later interpretation pick the value in Vars.

Here's a test case that explodes the stack:

```go
diff --git a/interp/interp_test.go b/interp/interp_test.go
index ce66c294..28abfe1f 100644
--- a/interp/interp_test.go
+++ b/interp/interp_test.go
@@ -2302,6 +2302,12 @@ set +o pipefail
                "foo: readonly variable\nexit status 1 #JUSTERR",
        },
 
+       // vars interacting with command vars
+       {
+               "i=1; foo() { echo foo; [ $i == 1 ] && i=0 foo ; }; foo",
+               "foo\nfoo\n",
+       },
+
        // globbing
        {"echo .", ".\n"},
        {"echo ..", "..\n"},
```

**Comment by mvdan** [comment]
The test case and the bug description make sense to me. It does sound like we're not properly propagating cmdVars to Vars when calling functions. Do you want to attempt a fix in a PR, given that you've done much of the legwork already?

**Comment by twilly** [comment]
I haven't started working on a fix yet. In fact this has been chilling in my "that's an interesting bug" queue for a while but haven't yet found the time to digging in deeper. Today I figured I should make this bug public just in case others are running into it and want to take a crack at it. :)

I may still take a crack at it and if I do I'll make a note here.

**Comment by mvdan** [comment]
Gotcha, thanks. I had a look just now, and the fix is far from trivial; the way we handle cmdVars is just wrong, as it doesn't support nesting properly. The fix will likely mean a small refactor, so I'll take a crack at that.

**Comment by mvdan** [comment]
Also, here's a simpler test case which fails instead of looping forever:

```
$ gosh -c 'f() { echo $inline; inline=bar true; echo $inline; }; inline=foo f'
foo

$ bash -c 'f() { echo $inline; inline=bar true; echo $inline; }; inline=foo f'
foo
foo
```

**Comment by mvdan** [comment]
@twilly do you by any chance rely on the `Runner.Vars` field? The proper refactor that the interpreter needs to fix its support for variable scoping means merging the Vars field into Env, so I want to understand if and how people are using the Vars field currently to try to avoid breaking changes.

**Comment by twilly** [comment]
> @twilly do you by any chance rely on the `Runner.Vars` field?

Nope! This was found as I in playing around and executing some bash files I had. Not much more complex than syntax.NewParser().Parse() and interp.New().Run(). That's why my example test case is so odd; it's a simplified version of what I found in the wild. Although it was useful in quickly placing suspicion on Vars/cmdVars due to the infinite recursion. :smile: 

> The proper refactor that the interpreter needs to fix its support for variable scoping means merging the Vars field into Env, so I want to understand if and how people are using the Vars field currently to try to avoid breaking changes.

Sadly I have no additional insight here. I wish I could help evaluate the impact in changing this public field.

**Comment by mvdan** [comment]
Okay, the refactor is done in the commit above, and your example now works.

I also tried to keep backwards compatibility with the Vars field.

**Comment by twilly** [comment]
Wow, that was fast! I like how `overlayEnviron` captures the logic of setting vars.

**Comment by mvdan** [comment]
It doesn't fully capture the logic of assigning vars, since that's still split with assignVal and setVar; I have a TODO about trying to unify that with the WriteEnviron interface. That will likely need to wait until v4, because the v3 interface is probably too small to be able to retrofit all those semantics.

The alternative would be to make WriteEnviron a pretty low-level "just store the new value" interface, then any assignment will need to do a Get followed by a Set, for example for operations like `foo=bar; foo+=baz`. The slight problem is that pretty much any assignment can modify an existing value, like:

```
$ foo=(bar baz); foo=x; echo ${foo[@]}
x baz
```
