### ISSUE TITLE
Failing to install main.go:118: undefined: io.SeekStart

### ISSUE THREAD

**Issue by rafaelcoutinho** [mvdan/sh#67]
I'm trying to install shfmt but i get this error:

`~$ go get -u github.com/mvdan/sh/cmd/shfmt`
`# github.com/mvdan/sh/cmd/shfmt`
`go/src/github.com/mvdan/sh/cmd/shfmt/main.go:118: undefined: io.SeekStart`

I'm Ubuntu 16.04 and my go version is go1.6.2 linux/amd64

Any idea of what's wrong?

**Comment by mvdan** [comment]
See the README:

> Requires Go 1.7 or later.

Try building an earlier version, like 1.1.0, or downloading a prebuilt binary.
