### ISSUE TITLE
Malwarebytes Malware.AI flagging SHFMT.EXE as trojan

### ISSUE THREAD

**Issue by haveard** [mvdan/sh#681]
Malwarebytes is currently flagging the IntelliJ Shell Script plugin's instance of SHFMT.EXE as trojan.

https://blog.malwarebytes.com/detections/malware-ai/

**Comment by mvdan** [comment]
Sorry, I'm not sure what you expect me to do there. The source code clearly does not have a trojan, the released builds are reproducible, and you can build from source yourself if you prefer.

**Comment by haveard** [comment]
I'm not sure why this was flagged either. I'll redirect this to the IntelliJ team as an FYI.
