### ISSUE TITLE
Feature idea: wrap command arguments to multiple lines

### ISSUE THREAD

**Issue by mikez** [mvdan/sh#690]
## Python

In Python code formatters, long lines like these:

```python
create_join_index(self.right.index, self.left.index, right_indexer, left_indexer, how="left")
```
get changed to

```python
create_join_index(
    self.right.index,
    self.left.index,
    right_indexer,
    left_indexer,
    how="left",
)
```

## Bash

How about, in bash, if sufficiently long lines:

```sh
ffmpeg -ss 12:34 -i https://example.com/video.mp4 -vframes 1 -q:v 2 path/to/wonderful/screenshot.jpg
```
were changed to

```sh
ffmpeg \
    -ss 12:34 \
    -i https://example.com/video.mp4 \
    -vframes 1 \
    -q:v 2 \
    path/to/wonderful/screenshot.jpg
```

There would be some heuristics involved, but even a close approximation would save lots of reformatting. Are there any libraries or scripts around attempting to do this already?

**Comment by mvdan** [comment]
In general, I'd say the answer in shfmt for this is https://github.com/mvdan/sh/issues/80.

If you want stricter rules, like "one argument/flag per line", I think that's too strict/aggressive for a tool as generic as shfmt. But you could certainly write a tool very similar to shfmt which applies extra transformations; the [syntax package](https://pkg.go.dev/mvdan.cc/sh/v3/syntax) contains both parsing and printing of programs.

**Comment by mikez** [comment]
👍 

It wouldn't have to be the default, but maybe something one can enable via configuration settings. Most other languages I work in have code formatters that let you wrap lines automatically in some form or the other.

Thank you for writing this tool, it's been very helpful. ☀️

**Comment by noperator** [comment]
@mikez, https://github.com/noperator/sol will do this for you. For example, using `sol -a`:

```bash
$ echo 'ffmpeg -ss 12:34 -i https://example.com/video.mp4 -vframes 1 -q:v 2 path/to/wonderful/screenshot.jpg' | sol -a

ffmpeg \
    -ss 12:34 \
    -i https://example.com/video.mp4 \
    -vframes 1 \
    -q:v 2 path/to/wonderful/screenshot.jpg
```

> There would be some heuristics involved, but even a close approximation would save lots of reformatting.

Agree—I use sol to handle 95% of formatting and then tweak the result as needed. In this case, you may want to manually insert a line break before the final path argument.

**Comment by mikez** [comment]
@noperator Thanks for the pointer to your package! 😵‍💫😎
