### ISSUE TITLE
syntax: non-idempotent formatting and trailing whitespace with -bn and comments

### ISSUE THREAD

**Issue by mikepqr** [mvdan/sh#691]
Starting from this input:
```
$ cat test
foo |
        # comment
        bar
```
`shfmt -bn` on that yields this, which looks a little weird to me (especially the line that's just a pipe), but I'm not sure there's a better option, so fine:
```
$ shfmt -bn test
foo \
        |
        # comment
        bar
```
The problem is what happens when you run shfmt on its output. That should result in no change, but instead you get this:
```
$ shfmt -bn -w test
$ shfmt -bn test
foo \
        |
	
        # comment
        bar
```
shfmt reformats its own output by adding an empty line with one indent level of trailing whitespace.

And then if you repeat that you get different output:

```
$ shfmt -bn -w test
$ shfmt -bn test
foo \
	|
	

	# comment
	bar
```
Run it _again_ and there are now two empty lines. One is just `\n` and one includes one indent level of trailing whitespace.

Curiously, if you run it on _that_ you get no change. shfmt is finally happy. The starting input is somewhat weird, and I'm not sure what the right output is, but this non-idempotent behaviour (and the trailing whitespace) certainly seem wrong.

**Comment by mvdan** [comment]
Thanks, these "a re-run still changes the input" cases are definitely bugs. I'll investigate.
