### ISSUE TITLE
syntax: unexpected error thrown by Parser.Interactive

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#692]
I'm seeing `mvdan-sh: 1:11: reached EOF without closing quote '` when providing valid partial source code `partialSrc`:
```tsx
// npm module 0.5.0
parser.Interactive(
  { read: () => partialSrc },
  () => { incomplete = parser.Incomplete(); return false; }
);
```

It seems the strange behaviour is visible in `gosh`.
I get many extra `>` when pasting this:

```sh
key | run '({ read, _: {msg} }, { stage: s }) {
  while (msg = await read()) {
    if (msg.type !== "keydown") continue;
    switch (msg.key) {
      case "f": s.brush.paint(); break;
      case "v": msg.metaKey && s.brush.paint(); break;
      case "F": s.brush.erase(); break;
      case "Backspace": s.brush.erase(); break;
      case "c": msg.metaKey && s.brush.select(); break;
      case "x": msg.metaKey && s.brush.cutSelect();
        !msg.metaKey && s.brush.transform("mirror(x)"); break;
      case "Escape": s.brush.deselect(); break;
      case "y": s.brush.transform("mirror(y)"); break;
      case "q": s.brush.transform("rotate(90)"); break;
      case "Q": s.brush.transform("rotate(-90)"); break;
      case "z": msg.metaKey && s.brush.undoRedo(); break;
      case "1": [s.walls.height, s.walls.opacity] = [10, 1]; break;
      case "2": [s.walls.height, s.walls.opacity] = [0, 0.2]; break;
      case "3": [s.walls.height, s.walls.opacity] = [10, 0.2]; break;
      case "l": s.opts.lights = !s.opts.lights; break;
    }
  }
}' &
```
<img width="534" alt="Screenshot 2021-04-02 at 10 07 15" src="https://user-images.githubusercontent.com/1658537/113401446-40b8d100-939b-11eb-84d5-544be78cf204.png">

**Comment by mvdan** [comment]
Can you clarify what version you're on? On f33507475241da6fc37b972d825c351b94300bab, both `shfmt` and `gosh` seem to handle your input correctly.

**Comment by rob-myers** [comment]
I followed the homepage instructions. I'm not sure what else I'm supposed to do:
```
$ GO111MODULE=on go get mvdan.cc/sh/v3/cmd/gosh
go: found mvdan.cc/sh/v3/cmd/gosh in mvdan.cc/sh/v3 v3.2.4

$ which gosh
/usr/local/opt/go@1.12/bin/gosh
```

**Comment by rob-myers** [comment]
A javascript repro was attached to the previous comment i.e.
- https://runkit.com/rob-myers/606c985a273736001b280275

I also tried rebuilding `index.js` but the problem persists.

**Comment by mvdan** [comment]
Thanks; this should all be enough info :)

**Comment by theclapp** [comment]
This works for me in gosh at current master (f33507475241da6fc37b972d825c351b94300bab -- which is actually the one Daniel mentioned above), though I omitted the final `&`:

```sh
% gosh
$ function key { date ; }
$ function run { echo "function run" ; cat ; }
$ key | run '({ read, _: {msg} }, { stage: s }) {
  while (msg = await read()) {
    if (msg.type !== "keydown") continue;
    switch (msg.key) {
      case "f": s.brush.paint(); break;
      case "v": msg.metaKey && s.brush.paint(); break;
      case "F": s.brush.erase(); break;
      case "Backspace": s.brush.erase(); break;
      case "c": msg.metaKey && s.brush.select(); break;
      case "x": msg.metaKey && s.brush.cutSelect();
        !msg.metaKey && s.brush.transform("mirror(x)"); break;
      case "Escape": s.brush.deselect(); break;
      case "y": s.brush.transform("mirror(y)"); break;
      case "q": s.brush.transform("rotate(90)"); break;
      case "Q": s.brush.transform("rotate(-90)"); break;
      case "z": msg.metaKey && s.brush.undoRedo(); bre> > > > > > > > > > > > > > > ak;
      case "1": [s.walls.height, s.walls.opacity] = [10, 1]; break;
      case "2": [s.walls.height, s.walls.opacity] = [0, 0.2]; break;
      case "3": [s.walls.height, s.walls.opacity] = [10, 0.2]; break;
      case "l": s.opts.lights = !s.opts.lights; break;
    }
  }
}' > > > > > > >
function run
Fri Apr 16 11:53:46 EDT 2021
$
```

All the `> > > ...` are from gosh printing its line continuation symbol.  They're clearer if you paste line by line (`switch` truncated because pasting line by line is tedious):

```sh
% gosh
$ function key { date ; }
$ function run { echo "function run" ; cat ; }
$ key | run '({ read, _: {msg} }, { stage: s }) {
>   while (msg = await read()) {
>     if (msg.type !== "keydown") continue;
>     switch (msg.key) {
>       case "f": s.brush.paint(); break;
>       case "v": msg.metaKey && s.brush.paint(); break;
>     }
>   }
> }' &
$ function run
Fri Apr 16 11:59:53 EDT 2021
```

Wild guess: The terminal or OS you're using turned one or more of the single or double quotes  (`'`, `"`) you pasted into "smart quotes", which'll (probably?) break the parser.

**Comment by rob-myers** [comment]
Hey @theclapp, thanks for having a look.

Yes, I would expect the interactive prompt to prefix each line. I provided the `gosh` screenshot because they appeared in two places: _the problematic line_ (see js repro above) and also at the end.

But I see your version of gosh has them in two places too.
I probably should have stuck to talking about the js issue...

**Comment by rob-myers** [comment]
Actually, I don't think this javascript-related issue is a bug.
It occurs when the string length exceeds `1024`i.e. parser.Interactive reads chunks of this length.

I can detect if interactively provided source code is complete using:
```ts
try {
  parser.Interactive(
    { read: () => partialSrc.slice(readCount * 1000, ++readCount * 1000) },
    () => { incomplete = parser.Incomplete(); return false; }
  );
} catch (e) {}
```

I'll close the issue unless someone feels otherwise.

**Comment by mvdan** [comment]
That's interesting. Reads on the Go side must be chunked, because otherwise we'd need a massive buffer - and even then one could still potentially chunk even longer input.

I honestly don't fully understand how streaming readers work in JS. At least in Go, the interface is like `Read([]byte) (int, error)`, so the end supplying the bytes can know how many bytes the other side wants. Ideally you would do the same here to supply no more bytes than are asked, without having to hard-code the size of 1024. That size is an internal detail and might change at any moment, after all.
