### ISSUE TITLE
syntax: $( declare ) vs declare with backticks

### ISSUE THREAD

**Issue by rob-myers** [mvdan/sh#699]
I'm using the npm module mvdan-sh@0.5.0.

I can parse `$( declare )`, but if i try to parse:

```sh
`declare`
```
I get the error `1:9: "declare" must be followed by names or assignments`.
Is there a workaround?

**Comment by mvdan** [comment]
Thanks, this seems like a bug. A workaround doesn't come to mind right now, other than using `$()`.

**Comment by mvdan** [comment]
Should be fixed now. I'll try to push a new JS version soon; see https://github.com/mvdan/sh/issues/302#issuecomment-831394912.
