### ISSUE TITLE
parse: index out of range panic with heredocs and logical ops

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#7]
$ cat x.bash
    cat <<FOO|rev&&echo done 
    foobar
    FOO
    $ bash x.bash
    raboof
    done
    $ shfmt x.bash
    panic: runtime error: index out of range
    
    goroutine 1 [running]:
    panic(0x4e4320, 0xc820010160)
    	/home/ebfe/src/go/src/runtime/panic.go:500 +0x18a
    github.com/mvdan/sh.(*parser).doHeredocs(0xc82008dae8)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:355 +0x1e3
    github.com/mvdan/sh.(*parser).next(0xc82008dae8)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:239 +0x267
    github.com/mvdan/sh.(*parser).got(0xc82008dae8, 0xfffffffffffffffd, 0xc82000a700)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:425 +0x42
    github.com/mvdan/sh.(*parser).wordPart(0xc82008dae8, 0xb, 0xb)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:647 +0x79e
    github.com/mvdan/sh.(*parser).readParts(0xc82008dae8, 0xc82000a7c0)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:599 +0x25
    github.com/mvdan/sh.(*parser).gotWord(0xc82008dae8, 0xc82000a7c0, 0x5ba000)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:584 +0x2d
    github.com/mvdan/sh.(*parser).cmdOrFunc(0xc82008dae8, 0xffffffffffffffe4, 0x0)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:1306 +0x1fd
    github.com/mvdan/sh.(*parser).gotStmtPipe(0xc82008dae8, 0xc82005a540, 0x0)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:1030 +0x95d
    github.com/mvdan/sh.(*parser).gotStmtAndOr(0xc82008dae8, 0xc82005a540, 0x0, 0x0, 0x0, 0x5ba040)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:992 +0x2a2
    github.com/mvdan/sh.(*parser).gotStmt(0xc82008dae8, 0xc82005a540, 0x0, 0x0, 0x0, 0x409e90)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:965 +0xc4
    github.com/mvdan/sh.(*parser).followStmt(0xc82008dae8, 0x1, 0xe, 0x506d35, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:468 +0x8e
    github.com/mvdan/sh.(*parser).binaryStmt(0xc82008dae8, 0x58b900, 0xc82004c440, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:1052 +0x17f
    github.com/mvdan/sh.(*parser).gotStmtAndOr(0xc82008dae8, 0xc82005a300, 0x0, 0x0, 0x0, 0xc82002a050)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:998 +0x31a
    github.com/mvdan/sh.(*parser).gotStmt(0xc82008dae8, 0xc82005a300, 0x0, 0x0, 0x0, 0x1000)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:965 +0xc4
    github.com/mvdan/sh.(*parser).stmts(0xc82008dae8, 0x0, 0x0, 0x0, 0x1000, 0x1000, 0x20)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:555 +0x119
    github.com/mvdan/sh.Parse(0x58b300, 0xc82002a048, 0x7fff891c654b, 0xf, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/ebfe/go/src/github.com/mvdan/sh/parse.go:38 +0x119
    main.format(0x7fff891c654b, 0xf, 0x58cb40, 0xc82005d6c0)
    	/home/ebfe/go/src/github.com/mvdan/sh/cmd/shfmt/main.go:75 +0xbc
    main.work(0x7fff891c654b, 0xf, 0x0, 0x0)
    	/home/ebfe/go/src/github.com/mvdan/sh/cmd/shfmt/main.go:49 +0xb4
    main.main()
    	/home/ebfe/go/src/github.com/mvdan/sh/cmd/shfmt/main.go:28 +0x68

**Comment by mvdan** [comment]
I stumbled upon the same thing late yesterday :) thanks for reporting!

**Comment by ebfe** [comment]
Here's an nonsensical input that still triggers it

```
`<<0<<0|0||""||
```

**Comment by mvdan** [comment]
@ebfe how did you reproduce the crash? None of these do it for me:

```sh
echo '`<<0<<0|0||""||' | shfmt
echo -n '`<<0<<0|0||""||' | shfmt
```

Fuzzing uncovered another one, though:

```sh
 $ echo '<<""<<0|0;' | shfmt
panic: runtime error: index out of range
```

**Comment by ebfe** [comment]
> @ebfe how did you reproduce the crash? None of these do it for me:
> ```sh
> echo '`<<0<<0|0||""||' | shfmt
> echo -n '`<<0<<0|0||""||' | shfmt
> ```

It doesn't trigger anymore after ca2a636bf05d3954ca2e92e2ebaa286a733a46ab.

**Comment by mvdan** [comment]
Oh, that's interesting. Wasn't expecting that fix to also fix crashes.
