### ISSUE TITLE
proposal: ability to disable formatting for a block of lines

### ISSUE THREAD

**Issue by jlisee** [mvdan/sh#700]
I like the consistency and accuracy  `shfmt`.  For some chunks of code though it just does not do what you want and it's tried to be accommodating with it's "keep spacing within a line feature".   It would be great if we could just turn the formatting off with a simple comment like `# fmt: off`, then back on with `#fmt: on`

This turns the example from #168 into this, with no special flags:
```shell
# fmt: off
aaa()  { test ttt  && fff     "$1"    "$2" | ggg  "$3" "$4"     ; } # aaa
aaaa() { test tttt && ffff "xxx$1" "yyy$2" | gggg      "$4" "$5"; } # aaaa
# fmt: on
```

This is common in sister tools like Black (Python) with [`# fmt: off`](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html?highlight=fmt%3A%20off#code-style) and clang-format (C++) with [`// clang-format off`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#disabling-formatting-on-a-piece-of-code).  From my experience bits of code like this are pretty rare (1 in every few thousand lines of code) so it's not a large deal to insert these manually.

From a implementation standpoint black is a similar tool that reads and dumps and AST so maybe we can take inspiration from their implementation https://github.com/psf/black/commit/0677a539370b296399854e427ce7df2955ecfe57

**Comment by mvdan** [comment]
Sorry, but no, I don't plan on adding a feature like this. It opens too many design questions:

* Would we leave the lines entirely unchanged?
* Would we still error if there are parsing errors in those lines?
* What if the off/on comments contain a partial syntax node?
* What if the comments are in weird places, like inside a heredoc?

If there are cases where shfmt could clearly do better, please file an issue. For example, see https://github.com/mvdan/sh/issues/678 or https://github.com/mvdan/sh/issues/693, which were filed after we said we'd deprecate `-kp`.

If this is a scenario where you want special formatting that doesn't follow any rules that could be generally applied by shfmt, then you have two options: either accept the generic formatting, or put the lines of shell somewhere that shfmt doesn't run. For example, in a separate file that you don't format and that is `source`d from the formatted shell file.

**Comment by jlisee** [comment]
Thanks for the super quick response.  I think a feature like this could help a maintainer because it creates an escape value for difficult cases and makes it easier to adopt the tool because it doesn't have to be perfect.

As requested here is the first use case I saw #701.  Another common case in every language, that pretty much all auto-formatters mess up, is blocks of data written in a way that is easy for a human to maintain but totally "non-standard".

So from a design standpoint my main thought is just keep it really simple, this feature is just for letting nicer code through.
 
> [...] It opens too many design questions
> * Would we leave the lines entirely unchanged?

**Unchanged** - maybe the original code is kept with the AST node and dumped when inside in an `off` state

> * Would we still error if there are parsing errors in those lines?

**Error** - broken code is still a bug

> * What if the off/on comments contain a partial syntax node?

**Error**  - this is for nice code, don't support awkward cases

> * What if the comments are in weird places, like inside a heredoc?

**Ignore** - the overlap of legimate issues and code heredoc has to be small

**Comment by mvdan** [comment]
> blocks of data written in a way that is easy for a human to maintain but totally "non-standard".

That's understandable, but you can just write that data in a way that shfmt simply won't format it. I already made a suggestion using `source`, but there can be others: a multi-line string, a heredoc string, a table-like array, etc.

> escape value for difficult cases and makes it easier to adopt the tool because it doesn't have to be perfect.

It also makes the tool more inconsistent and mixes source code with directive comments, which are problems on their own. I fully understand that some people will never be happy with generic formatting, and that's fine - but I don't think that allowing turning off formatting in parts of a file is a good tradeoff.

I appreciate you answering the open questions, but please note that the hard part is not coming up with one answer. The difficulty is that we're adding complexity to the tool and how to use it, so we would now have to implement, test, maintain, and document all these new edge cases very carefully.

I'll reply to your suggestion in the new issue separately. I'm still convinced that this proposal, as is, is not a good idea :)

**Comment by mvdan** [comment]
I don't plan to support this kind of a feature, as explained above, so I'm closing this issue for now. I replied to #701 so we can continue there.
