### ISSUE TITLE
How do I tell `shfmt` to stop removing `;` in shell scripts?

### ISSUE THREAD

**Issue by axonasif** [mvdan/sh#707]
Hi,
I need to make `shfmt` ignore `;` at the end of lines in shell scripts.
But I couldn't find any valid argument that I can pass to `shfmt` for this purpose.
Any ideas?

**Comment by mvdan** [comment]
Why would we support that? The purpose of a formatter is to enforce consistent formatting. Using semicolons when they are not needed goes against that.

**Comment by axonasif** [comment]
> Why would we support that? The purpose of a formatter is to enforce consistent formatting. Using semicolons when they are not needed goes against that.

I can understand. I am okay with rest of the formatting for my use-case.
Perhaps, [this](https://github.com/mvdan/sh/blob/7603a0cff671f952ece6239bb9b9ad1450ccb6cd/syntax/tokens.go#L46) seems to be a starting point to get tinkering with.

**Comment by mvdan** [comment]
I don't see a reason to change the format here. The code is not the question.

**Comment by 5lava** [comment]
The reason is that when you paste the script into a shell and then redo the last command, the lack of semicolons can play a bad joke. Consider the following (note the empty line between `rm` and `ls`):

```bash
(
  rm foo

  ls *
)
```
Paste that in a shell, execute, and then press ⬆️ on your keyboard:
```
(   rm foo   ls *; )
```

**Comment by SuperSandro2000** [comment]
> Paste that in a shell, execute, and then press ⬆️ on your keyboard:

My bash does this properly.

**Comment by mvdan** [comment]
Yeah, that sounds like a bug in your shell.

**Comment by 5lava** [comment]
That's the default behavior in Bash 5:

```bash
echo $'bash\n\n(true\ntrue)\n(true\n\ntrue)\n history\nexit\n' | docker run -i --rm ubuntu script -q
```
```
root@435d22424b89:/# (true
> true)
root@435d22424b89:/# (true
>
> true)
root@435d22424b89:/#  history
    1  (true; true)
    2  (true true)
```

It can be "fixed" with `shopt -s lithist` or working around by replacing an empty line with `:`, but neither is default nor intuitive. An option to keep trailing semicolons would be greatly appreciated.

Thank you.

**Comment by mvdan** [comment]
You're right that, if you leave an empty line, then Bash fails to add the semicolon in the history. That still feels like a bug that you should report to Bash.

shfmt is a code formatter, so its main purpose is to enforce a consistent and readable style. Semicolons at the end of every line are simply not in the picture, I'm afraid. It's unfortunate that you've found this bug in Bash, but the solution is to fix the bug, not to add a workaround in the form of an option here permanently.
