### ISSUE TITLE
Sh stringifier

### ISSUE THREAD

**Issue by hzlmn** [mvdan/sh#71]
Hi, thanks for awesome tool.

I am working on a tool that allows transforming custom syntax in `sh` scripts to just regular one.
And I wondering does this tool have stringifing ability so I could convert my custom generated `AST` to AST compatible with your tool and generate raw `sh` source string from it?

**Comment by mvdan** [comment]
Yes; see https://github.com/mvdan/sh/blob/57622739bc5a4543d3fba62e92c59b18997ee12e/syntax/printer.go#L48.

At the moment this is only easily accessible via Go code. As for making it easier in other languages, see https://github.com/mvdan/sh/issues/35.

Does that answer your question?

**Comment by hzlmn** [comment]
Yes. Much thanks, Daniel.

**Comment by mvdan** [comment]
Out of curiosity, can you use Go or would you be looking for something like JSON as explained in #35?

**Comment by hzlmn** [comment]
I will use it with Go, but that option could be helpful as well.
