### ISSUE TITLE
syntax: "&" in a separate line turns to ";"

### ISSUE THREAD

**Issue by kamadorueda** [mvdan/sh#710]
Hi guys, first of all: awesome tool! 
we've been using it quite a while now and formatted probably 100k+ lines of code with it

There is something, though, found it today:

Before shfmt: the command is meant to be run in the background (`cmd &`)
![image](https://user-images.githubusercontent.com/47480384/120875266-9ca4ff00-c570-11eb-862f-32592b0836a9.png)

After shfmt: the command is run in the foreground (`cmd ;`), changing the meaning of the command
![image](https://user-images.githubusercontent.com/47480384/120875277-a62e6700-c570-11eb-93e4-3df56da44532.png)

**Comment by kamadorueda** [comment]
After the code is formatted, if I change the `;` by `&` the tool no longer replaces it by `;`

(so it's easy to workaround with a small manual action)

**Comment by kamadorueda** [comment]
I confirm this can be easily workaround manually like this:

![image](https://user-images.githubusercontent.com/47480384/120875557-01148e00-c572-11eb-9cdc-706f8b82dfd3.png)

**Comment by mvdan** [comment]
Thanks, this sounds like a bug.
