### ISSUE TITLE
interp: panic when cwd is deleted

### ISSUE THREAD

**Issue by TorchedSammy** [mvdan/sh#711]
when a command is ran in a directory that has been deleted, the runner will cause a panic
image below to illustrate
![](https://modeus.is-inside.me/gtedam6h.png)

**Comment by mvdan** [comment]
Thanks, this seems like a bug - want to try sending a PR?

**Comment by TorchedSammy** [comment]
even though it seems like a simple fix, i dont think i can do it
another thing, i did some test with a minimal example
reusing the same runner doesnt cause a panic, but trying to make a new one everytime on input does

**Comment by mvdan** [comment]
I don't think this is a bug in our interpreter, per se. You're calling `Runner.Run` on a nil runner, which panics. I don't think that's something to fix.

I can't reproduce. If you can provide a standalone program that reproduces this, or perhaps a PR with a test, then I can take a look.

**Comment by TorchedSammy** [comment]
nevermind, not a bug. i was using the runner slightly wrong
