### ISSUE TITLE
interp: builtin failure does not stop script execution, even with Params("-e")

### ISSUE THREAD

**Issue by josharian** [mvdan/sh#712]
Using interp, execute something like `echo abc > /path/that/does/not/exist/somefile.txt`.

Expected: script execution stops with an error, as it does with (say) `touch /path/that/does/not/exist/somefile.txt`.

Got: script execution continues.

**Comment by mvdan** [comment]
Nice catch :) We would stop early if any redirect failed, and then the `set -e` logic would not kick in.
