### ISSUE TITLE
syntax: escaped newlines left behind when moving redirections to the end of a command

### ISSUE THREAD

**Issue by mikeBashStuff** [mvdan/sh#714]
```
shfmt: 3.3.0
cmdline: -i 0 -bn -ci -ln bash -d -sr
```

Consider this:
```
#!/bin/bash

bar() {
        > foo \
                KAKA=yes \
                BAR=yes \
                foobar
}
```
The intention here is to redirect output of `foobar` to `foo` file. The `shfmt` changes this to the following:

```
 bar() {
-       > foo \
+       \
                KAKA=yes \
                BAR=yes \
-               foobar
+               foobar > foo
 }

 }

```
So it puts the redirection at the end, if that's its preference then I am fine with it, however it leaves the extra break line at the very beginning. Another example:
```
#!/bin/bash

bar() {
        > foo \
                KAKA=yes \
                BAR=yes \
                foobar --kakabar
}
```

becomes:
```
 bar() {
-       > foo \
+       \
                KAKA=yes \
                BAR=yes \
-               foobar  --kakabar
+               foobar > foo \
+               \
+               \
+               --kakabar
 }
```
The premise here is the same, but it seems like any other string put after `foobar` causes the formatting to go all hairy - extra break line at the top is still there but now there are extra two (this number relates to the number of breaks preceding the `foobar`) put after redirection and the argument to `foobar`, `--kakabar`, is put at the end  - this is still valid code but looks a bit odd. Not sure if this is expected or not. :)

**Comment by mvdan** [comment]
It is expected to move the redirection - we only allow those after the first argument word, or after all argument words. The extra newlines are not intended, as far as I can tell - they're just edge cases that the logic probably doesn't deal with yet.

Thanks for reporting!
