### ISSUE TITLE
How to get parser error information?

### ISSUE THREAD

**Issue by jcubic** [mvdan/sh#716]
I'm using JS version and if there is an error, it throws an empty object. Is there a way to get the error message?

```javascript
const { syntax } = require('mvdan-sh');

const parser = syntax.NewParser();
try {
    let f = parser.Parse('for i in *; do echo i;/ done', 'REPL');

    syntax.DebugPrint(f)
} catch(e) {
    console.log(e); // prints {}
}
```

**Comment by mvdan** [comment]
The translation between Go and JS is a bit fiddly, as you're finding out. But the error information should be there. I wrote a bunch of tests a while ago, which should still be passing, and they include looking at error info: https://github.com/mvdan/sh/blob/master/_js/testmain.js#L42-L47

I don't have a test for the actual message or reason for the error, though. Most of the time, the actual type of parse errors will be https://pkg.go.dev/mvdan.cc/sh/v3@v3.3.0/syntax#ParseError, so you could try using the `Text` string field. Or, even better, call the `Error` method, which stringifies any error in Go.

**Comment by mvdan** [comment]
I'm going to assume my answer above solved your question. For more suggestions, see https://github.com/mvdan/sh/issues/302.

**Comment by jcubic** [comment]
Thanks for the answer, will look into this when I will use again your library.
