### ISSUE TITLE
consider allowing `do` and `then` on their own lines after `while`/`for` and `if`

### ISSUE THREAD

**Issue by gaelicWizard** [mvdan/sh#718]
I'm trying to contribute to a project which uses `shfmt` but there's no option to disable forcing "; do" or "; then" to the end of loop/conditional tests so I'm having to match all the formatting manually. Could this be made optional?

Thanks,
JP2

**Comment by mvdan** [comment]
Thanks for opening this issue. Others have asked for the same before, see https://github.com/mvdan/sh/issues/229#issuecomment-862734437. I've now opened https://github.com/mvdan/sh/issues/721 with the proposal I made in that thread.

**Comment by milhnl** [comment]
The alternative I use is to split the line after the `if`/`while` too, e.g.

```
if
    long_test_condition_statement
then
    ...
fi
```
In my opinion this is actually even better than keeping the if and the condition on the same line for long conditions, and it is already supported by shfmt. Maybe document this somewhere?

Maybe this also works for others who found this issue like me looking for a feature like this, so calling out those issues to link this comment (https://github.com/mvdan/sh/issues/229, https://github.com/mvdan/sh/issues/1248, https://github.com/mvdan/sh/issues/718)
