### ISSUE TITLE
interp: support pwd flags like -P

### ISSUE THREAD

**Issue by amancevice** [mvdan/sh#724]
I use this repo indirectly through [go-task](https://github.com/go-task) and noticed an unexpected result when executing the command `pwd -P`. The issue is outlined in [go-task#533](https://github.com/go-task/task/issues/553).

In essence, when executed from a symlinked directory, `pwd -P` outputs the symlink and not the actual physical location on disk.

Example:

```bash
mkdir real-dir
ln -s real-dir link-dir
cd link-dir
pwd -P
# => Expected: /path/to/real-dir
# => Actual: /path/to/link-dir
```

**Comment by mvdan** [comment]
Ah, that's sort-of-expected given that we don't support any pwd flags right now. See:

https://github.com/mvdan/sh/blob/ec61336f424e93c98dab0ebfaebcab7b8487b5f4/interp/builtin.go#L186-L187

I think it should be doable with https://pkg.go.dev/path/filepath#EvalSymlinks and a couple of tests, if you're up for sending a PR.

**Comment by amancevice** [comment]
I'm a Go-newbie but I can give it the old college try in the coming days. Thanks!
