### ISSUE TITLE
TestRunnerRunConfirm: `read -r -p` failes on newer systems due to missing prompt

### ISSUE THREAD

**Issue by sylv-io** [mvdan/sh#725]
```
[sylv sh]$ go test ./...
ok      mvdan.cc/sh/v3/cmd/gosh (cached)
ok      mvdan.cc/sh/v3/cmd/shfmt        (cached)
ok      mvdan.cc/sh/v3/expand   (cached)
?       mvdan.cc/sh/v3/fileutil [no test files]
--- FAIL: TestRunnerRunConfirm (0.01s)
    --- FAIL: TestRunnerRunConfirm/835 (0.00s)
        interp_test.go:3165: wrong bash output in "read -r -p 'Prompt and raw flag together: ' a <<< '\\a\\b\\c'; echo $a":
            want: "Prompt and raw flag together: \\a\\b\\c\n"
            got:  "\\a\\b\\c\n"
    --- FAIL: TestRunnerRunConfirm/834 (0.01s)
        interp_test.go:3165: wrong bash output in "read -p 'Display me as a prompt. Continue? (y/n) ' choice <<< 'y'; echo $choice":
            want: "Display me as a prompt. Continue? (y/n) y\n"
            got:  "y\n"
FAIL
FAIL    mvdan.cc/sh/v3/interp   0.517s
ok      mvdan.cc/sh/v3/pattern  (cached)
ok      mvdan.cc/sh/v3/shell    (cached)
ok      mvdan.cc/sh/v3/syntax   (cached)
FAIL
```

It looks like both test are failing on newer systems. I'm not sure why but i tested it on some systems:

failes in:
- Archlinux (5.13.13-arch1-1)
- Debian 11
- Ubuntu 21.04

works on:
- Ubuntu 20.04.2 LTS
- Ubuntu 18.04.5 LTS

**Comment by sylv-io** [comment]
I guess I'm doing something wrong here since github/workflow is working and it also works in latest ubuntu docker...

**Comment by mvdan** [comment]
Hm, I can't reproduce on Arch Linux here. I'm on Bash 5.1.008.

Does it happen on an empty $HOME? I wonder if your bashrc or bash_profile have any special settings.

**Comment by sylv-io** [comment]
> Hm, I can't reproduce on Arch Linux here. I'm on Bash 5.1.008.
> 
> Does it happen on an empty $HOME? I wonder if your bashrc or bash_profile have any special settings.

yeah sorry, I'm pretty sure it's a local issue. it works fine on an other machine :+1: There have to be something special on my host and all my VMs.

I will close it for now, since it is an layer 8 issue :sweat_smile:

**Comment by mvdan** [comment]
I'm extremely confused; it started failing for me today.

```
$ go test
--- FAIL: TestRunnerRunConfirm (0.01s)
    --- FAIL: TestRunnerRunConfirm/835 (0.01s)
        interp_test.go:3178: wrong bash output in "read -r -p 'Prompt and raw flag together: ' a <<< '\\a\\b\\c'; echo $a":
            want: "Prompt and raw flag together: \\a\\b\\c\n"
            got:  "\\a\\b\\c\n"
    --- FAIL: TestRunnerRunConfirm/834 (0.00s)
        interp_test.go:3178: wrong bash output in "read -p 'Display me as a prompt. Continue? (y/n) ' choice <<< 'y'; echo $choice":
            want: "Display me as a prompt. Continue? (y/n) y\n"
            got:  "y\n"
FAIL
exit status 1
FAIL	mvdan.cc/sh/v3/interp	0.481s
```

**Comment by mvdan** [comment]
But these are the only packages I've upgraded since I posted my last comment:

```
[2021-09-08T12:43:30+0200] [ALPM] upgraded firefox (91.0.2-1 -> 92.0-1)
[2021-09-08T23:34:22+0200] [ALPM] upgraded vim-runtime (8.2.2891-1 -> 8.2.3412-1)
[2021-09-08T23:34:22+0200] [ALPM] upgraded krb5 (1.19.1-1 -> 1.19.2-1)
[2021-09-08T23:34:22+0200] [ALPM] upgraded libedit (20210522_3.1-1 -> 20210714_3.1-1)
[2021-09-08T23:34:22+0200] [ALPM] upgraded gvim (8.2.2891-1 -> 8.2.3412-1)
[2021-09-08T23:34:22+0200] [ALPM] upgraded lib32-krb5 (1.19.1-1 -> 1.19.2-1)
[2021-09-08T23:34:22+0200] [ALPM] upgraded lib32-libidn2 (2.3.1-1 -> 2.3.2-1)
[2021-09-08T23:34:22+0200] [ALPM] upgraded libqmi (1.30.0-1 -> 1.30.2-1)
[2021-09-08T23:36:43+0200] [ALPM] upgraded tor-browser (10.5.5-1 -> 10.5.6-1)
```

Still no idea what's changed. But at least I can guess why the prompt isn't being printed: we're providing stdin too quickly.

**Comment by sylv-io** [comment]
> I'm extremely confused; it started failing for me today.

yeah I invested about ~2h to figure out why. I tried different bash, golang, gcc, envs in different VMs and was not able to pinpoint the reason, only that it happens on more uptodate/bleeding edge distros.

**Comment by mvdan** [comment]
I must have been sleep deprived when I investigated this yesterday. It's totally our fault; the test never passed.

The feature was added very recently in ec61336f424e93c98dab0ebfaebcab7b8487b5f4, along with the tests. The author and CI never caught that the tests don't pass, because the tests get silently skipped if your bash version is too old (or too new). We want version 5.0. This is also why you could only reproduce on some systems.

Bash's `read` builtin will simply never print the prompt if stdin is not a terminal - and in our test it's not, as it's just a pipe:

```
  /* If the -p, -e or -s flags were given, but input is not coming from the
     terminal, turn them off. */
  if ((prompt || edit || silent) && input_is_tty == 0)
```

The good news is we're already pulling in github.com/creack/pty to emulate TTYs, so we could probably reuse this for tests like this one.

**Comment by mvdan** [comment]
I ended up not bothering to use a PTY for that test, after seeing that it would be more than twenty minutes of work.
