### ISSUE TITLE
syntax: unable to parse heredoc inside backtick

### ISSUE THREAD

**Issue by chrismcgehee** [mvdan/sh#729]
First off, I'd like to say thank you for maintaining this project. We're using your syntax parser in [ossf/scorecard](https://github.com/ossf/scorecard) shell files from thousands of repos. We're getting an error when trying to parse a specific file, and since the syntax is valid bash, I'm opening this issue. I've created a small program that reproduces the error:
```bash
#!/usr/bin/env bash

OUTPUT=`passwd 2>&1 << EOT
old_password
old_password
new_password
EOT`

echo $OUTPUT
```
Passing this file to `shfmt` gives this error:
```
<standard input>:7:4: reached EOF without closing quote `
```

**Comment by mvdan** [comment]
Thanks for filing this detailed issue! Parsing backticks is indeed tricky. There's also https://github.com/mvdan/sh/issues/636.

In general these edge cases haven't been a huge problem, because backticks have been deprecated for a while and most people use `$()`. Still seems worthwhile to try to fix the parser if it's possible, though. Better compatibility is generally a good thing, as long as it doesn't bring significant penalties.

**Comment by mvdan** [comment]
By the way, I took a quick look at your code, and I see you're trying to look at what commands people are running in their scripts. You can do this directly with the syntax package, but it's pretty manual as you only have the syntax tree. Have you seen the expand package? For example: https://pkg.go.dev/mvdan.cc/sh/v3/expand#Fields

**Comment by chrismcgehee** [comment]
I had not seen the expand package, but it looks pretty neat. I think it's a little more than we need at the moment since we don't know the environment that these shell files are executing in.

**Comment by mvdan** [comment]
I've sent https://github.com/mvdan/sh/pull/787, which should fix this issue. A review, or a confirmation that it fixes the problem for you, would be welcome :)

**Comment by chrismcgehee** [comment]
I've ran scorecard with the latest code in your master branch, and we're no longer getting an error on the repo we were getting an error on earlier. Thanks Daniel!
