### ISSUE TITLE
syntax: not a valid test operator: ]];

### ISSUE THREAD

**Issue by schu** [mvdan/sh#73]
```
$ cat bug.bash
#!/bin/bash
if [[ $1 =~ ^foo$ ]]; then
        echo "foo"
fi
$ shfmt bug.bash
bug.bash:2:19: not a valid test operator: ]];
```

Seems to be a regression from 139bef4d2a5a2e799b02c1b4d3e6165f09bd18bf - reverting back to 57622739bc5a4543d3fba62e92c59b18997ee12e works.

xref https://github.com/weaveworks/tcptracer-bpf/pull/30

**Comment by mvdan** [comment]
Thanks for reporting, will fix.

**Comment by mvdan** [comment]
Actually, there is another issue now: `2:11: not a valid test operator: ^foo`

**Comment by mvdan** [comment]
Duh, it was just me forgetting again that `$` expands in heredocs. The program parses just fine now.

**Comment by schu** [comment]
@mvdan great, thanks for the swift fix!
