### ISSUE TITLE
Is there possible to break down multiple arguments to lines, one parameter per one line,thanks

### ISSUE THREAD

**Issue by godhelpjun** [mvdan/sh#731]
example
  /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true 

to lines like this
  /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 \
    -Des.networkaddress.cache.negative.ttl=10 \
    -XX:+AlwaysPreTouch \
    -Xss1m -Djava.awt.headless=true

**Comment by mvdan** [comment]
Have you seen https://github.com/mvdan/sh/issues/80?

**Comment by mvdan** [comment]
I'm going to assume that this is a duplicate of #80.
