### ISSUE TITLE
Is there any possible break down multiple parameters to lines?one parameter per line.

### ISSUE THREAD

**Issue by godhelpjun** [mvdan/sh#732]
example
  /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true 

to lines like this
  /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 \
    -Des.networkaddress.cache.negative.ttl=10 \
    -XX:+AlwaysPreTouch \
    -Xss1m -Djava.awt.headless=true

**Comment by mvdan** [comment]
I imagine this is an unintended dup of https://github.com/mvdan/sh/issues/731.
