### ISSUE TITLE
Don't strip trailing newline at end of file.

### ISSUE THREAD

**Issue by mccurdyc** [mvdan/sh#733]
First, I wanted to say thank you for this wonderful tool! I love it!!! However, the following is pretty annoying because I add newlines to the end of files to ensure that common bash tool such as `wc` work properly.

## Actual
```bash
cat <<EOF | shfmt
foo

EOF
foo
```

## Expected

```bash
cat <<EOF | shfmt
foo

EOF
foo

```

## Proposal

- To avoid introducing changes, I think the default behavior could be to strip the trailing new line and to just make it possible to run `shfmt` with a new flag to leaving trailing newlines.

## More details

https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

```bash
$ echo -n "Line not ending in a new line" | wc -l
0
$ echo "Line ending with a new line" | wc -l
1
```

**Comment by mvdan** [comment]
I think there might be a misunderstanding here; shfmt enforces trailing newlines :) It also removes leading or trailing *empty lines*, though, so if your file ends with two or more newlines, those will be replaced with a single newline.

For example:

```
$ echo -n $'one newline\n'
one newline
$ echo -n $'one newline\n' | wc -l
1
$ echo -n $'one newline\n' | shfmt
one newline
$ echo -n $'two newlines\n\n'
two newlines

$ echo -n $'two newlines\n\n' | wc -l
2
$ echo -n $'two newlines\n\n' | shfmt
two newlines
```

I find `$''` much easier to reason about than heredocs, because heredocs implicitly end with a newline already. With `$''`, I can make newlines very explicit.

**Comment by mccurdyc** [comment]
@mvdan thanks for this explanation and introduction to `$''`! Let me gather some more info, but I think I agree with you. I think what I am experiencing is co-workers explicitly including two trailing _empty lines_ at the end of a file to ensure that if someone's editor isn't set up to include trailing empty lines, at least there is _one_ empty line.

**Comment by mccurdyc** [comment]
Yep, when I `set nofixendofline` in Vim, `shfmt` doesn't remove the explicit trailing empty line.

**Comment by mvdan** [comment]
Thanks!
