### ISSUE TITLE
syntax: got `"}" can only be used to close a block` on a seemingly normal block

### ISSUE THREAD

**Issue by andras-kth** [mvdan/sh#739]
I'm struggling to understand what's wrong with this sample:
```console
$ shfmt
@() {
    echo "$@"
}
@ hello world\!
<standard input>:3:1: "}" can only be used to close a block
```

**Comment by mehes-kth** [comment]
Apparently, the "bug(?)" has to do with the "at" sign (`@`), since using an equal sign (`=`) instead works fine...
```console
$ shfmt
=() {
    echo "$@"
}
= Hello world\!
=() {
        echo "$@"
}
= Hello world\!
$
```

**Comment by mehes-kth** [comment]
Found a [workaround](https://github.com/bats-core/bats-core/issues/192#issuecomment-528315083) (I just **love** the internet...):
```console
$ shfmt 
@()
{
    echo "$@"
}
@ Hello world\!
@()
{
        echo "$@"
}
@ Hello world\!
```
I'm still not sure why `shfmt` treats `@` special,
or why the added line-break makes it tick,
but this solves my issue for the time being...

**Comment by mvdan** [comment]
I'm not sure how to answer to that, so I won't :)

**Comment by riacataquian** [comment]
I'll take a look at this @mvdan :)

**Comment by mvdan** [comment]
Sounds good!
