### ISSUE TITLE
Introduce 'stable' docker label

### ISSUE THREAD

**Issue by oliv3r** [mvdan/sh#740]
Currently, we have versioned tags (good) and latest, which tracks master (also good).

However users may be happy to run latest on development branches, local scripts, or occasional scheduled pipeline runs (to be aware of upcoming changes), but for general pipeline usage, they much prefer to run stable, which in theory should be slower evolving, and less-often changing.

The `stable` tag would just track the latest tagged release, so it would be a simple alias/link if anything.

This would give the opportunity, to say 'look, we want to stick to whatever @mvdan has released, but we do not want to be surprised by latest, we do have a occasional run to give us a preview of latest however and can plan and prepare for it'

**Comment by mvdan** [comment]
Also, in terms of "latest stable", I think we should use a tag name including the major version, such as `v3-stable` or `v3-latest`. Because the switch to v4 will certainly include breaking changes, and is thus not stable. Go also solves this problem by including the major version as part of the string before the version, e.g. `mvdan.cc/sh/v3/cmd/shfmt@latest` versus `mvdan.cc/sh/v4/cmd/shfmt@latest` doing the jump to v4.

**Comment by oliv3r** [comment]
I thing the post/prefixed variant of stable is definitely a decent idea; however the argument `v3` being confused with `v3.0.0` I'm not so sure of that one :)

Firstly, if we look at the most dockery container, the [docker registry container][0], we actually see exactly that.
They have latest pointing at their latest stable (they don't do dev/master images it seems), which is fair, they initially coined the latest thing (just nobody cleanly follows it :p). Then they have v2.7.1, v2.7 and v2 all to help finding the latest stable within a series. (lets not look at docker in docker here, as they do follow the same, but it includes support for a lot of variants making it much harder to digest)

A few other, completely different images are for example [sonarqube][1], busybox[2] and python[3] where they do a similar thing, albeit with a few flavors. Even [ubuntu][4] is doming something 'somehwat' similar, if you consider their 21.10 as 'one' version field.

Even  [alpine][5] does this ;)

[0]: https://hub.docker.com/_/registry?tab=tags
[1]: https://hub.docker.com/_/sonarqube?tab=tags
[2]: https://hub.docker.com/_/busybox?tab=tags
[3]: https://hub.docker.com/_/python?tab=tags
[4]: https://hub.docker.com/_/ubuntu?tab=tags
[5]: https://hub.docker.com/_/alpine?tab=tags

**Comment by mvdan** [comment]
If there's a strong understanding of what `v3` means already, I'm not opposed to just that name. I do have a slight preference for being explicit, and I have seen some instances of people assuming `v3.0` is short for `v3.0.0`, but I can't argue against a very widespread de facto standard.

(speaking of standards, I wonder whether the `v` prefix is aggressively non-standard)

**Comment by oliv3r** [comment]
The v-prefix, very good question; I see a little bit of everything. I do use it for tags for example. Semver says you shouldn't but does allow it :)

**Comment by mvdan** [comment]
Then I'd say let's just go for `v3`, with the assumption that such a docker tag format is already commonly understood to mean "the latest stable v3".

**Comment by oliv3r** [comment]
I agree! Shall I open a MR for this? Or are you happy to do this yourself @mvdan? (I'd have to figure out your push-setup first so its probably quicker for you :)

**Comment by mvdan** [comment]
I'll take a look as part of the upcoming release.

**Comment by mvdan** [comment]
I did the last release over the holidays and didn't get to this, but still intend to.

**Comment by mvdan** [comment]
Pushed the implementation straight to master after testing it via a dummy docker tag, as I want to release v3.4.3 today. Please feel free to review the changes after the fact, or send a follow-up PR if you can spot any improvement. I'll close this once the push of the v3.4.3 tag creates the docker tag.

**Comment by mvdan** [comment]
Done:

```
$ docker run mvdan/shfmt:latest --version
v3.5.0-0.dev-54-gb86b3247
$ docker run mvdan/shfmt:v3 --version
v3.4.3
```
