### ISSUE TITLE
Surrounding whitespace in variable assignment

### ISSUE THREAD

**Issue by allan2** [mvdan/sh#765]
This is a feature request to format surrounding whitespace in variable assignment.

**Example:**

Format
```bash
a = 5
```

as
```bash
a=5
```

**Comment by mvdan** [comment]
I don't think we can do that; those are different and valid programs. For instance:

```
$ a() { echo "hello!" "$@"; }
$ a = 5
hello! = 5
$ echo $a

$ a=5
$ echo $a
5
```

`shfmt` is a code formatter, so it can't do any automated changes that will change the behavior of programs, because those could easily break user's programs.

**Comment by mvdan** [comment]
Closing as per the above.
