### ISSUE TITLE
interp: new package to execute shell programs

### ISSUE THREAD

**Issue by mvdan** [mvdan/sh#77]
I've been thinking about adding a package to execute shell programs for a while. So far, `sh` includes a parser and a formatter, so it's the next logical step.

This is an issue to gauge how much interest there would be, and to get some feedback on my initial design.

First implementation would only be POSIX, as Bash has too many features and it would drive me crazy as a start.

Also worth noting that the purpose of such a package would not be speed - after all, people don't write Bash for it to run fast and the Bash interpreter in C is probably fast already. Instead, the advantages would be:

* Ability to execute shell code directly in Go
* Remove dependency on the `sh` or `bash` executables to do so (and what versions are installed)
* Similar to `exec.Command("cmd", "arg1", "arg2")`, we could have `interp.Exec("foo && bar || failsafe")`

A huge point against such a package, which is why I haven't written it yet, is that it would have limited use cases. `Bash` and other shells have been battle-tested for decades. I don't see any reason why anyone would trust a reimplementation (even if it's in a memory-safe language) just for the sake of it.

Unless any of the advantages above are useful. I think they outweigh the disadvantage in some cases, such as when you're running static shell code or when the shell code you're executing is not mission-critical.

**Comment by mvdan** [comment]
cc @mmlb @meatballhat @schu @ebfe @D630

**Comment by ebfe** [comment]
I'd love to see this, though it's probably a huge amount of work to get it to the point where it's really useful (compatibility + bug "free" enough to trust it). Most usage scenarios i can think of right now (mostly running existing scripts) would probably require at least partial bash compatibility.

**Comment by mvdan** [comment]
Yeah, it would be fairly limited if it were only POSIX. At the same time, Bash is fucking huge. The language part is done (syntax), but just thinking about the number of builtin commands and all their options makes me dizzy.

But as with the parser, I'll begin with POSIX and once done, I'll work on Bash one step at a time. Don't know if the interpreter would ever get to full Bash compatibility.

Another thought - would anyone be interested in an actual shell executable? Can't be `sh` or `bash` for obvious reasons. Perhaps `gsh` or `gosh`.

**Comment by mvdan** [comment]
I've started work (see above) but it will take at least a week before it can run any non-trivial program. I'll update this issue once it's in better shape and I want you to try it out. Thanks!

**Comment by mvdan** [comment]
Also, I won't be linking this issue in every commit as that's very repetitive. If you want to see updates, check the log or follow the repository.

**Comment by mmlb** [comment]
This is definitely really cool, though I wonder how useful it will end up being. One thing that just came to mind would be for better/saner concurrency than awkward sets of `&`, `pipes` and/or `wait`s. I've often repurposed a shell script into go just for the concurrency.

**Comment by mvdan** [comment]
> though I wonder how useful it will end up being

That's why I hadn't worked on it from the start :) I tried making some points in favor of it in the original post. Don't know if you think any of them matter.

> better/saner concurrency

Care to elaborate? This would be the same sh/bash language.

**Comment by mvdan** [comment]
> Another thought - would anyone be interested in an actual shell executable? Can't be sh or bash for obvious reasons. Perhaps gsh or gosh.

Another thought on top - what about distro packages? If we add more executables like an actual shell, should `shfmt` include those or should each executable have its own package?

**Comment by mmlb** [comment]
When I mean better/saner concurrency, I mean by connecting functions (I may have gotten ahead of myself/you ;) ). I'd be great if I could have functions in shell, and "pipes"/channels in go (which I think should be possible). These are things that I can do in `sh` now, but it's awkward to manage errors/early termination/continuing-other-procs.

**Comment by D630** [comment]
I would rather love a tool, that is able (1) to parse the dialects of mksh and zsh as well and (2) to offer configurable formats (I'm thinking of building own layouts/coding styles, but also of different output formats).

**Comment by mvdan** [comment]
> These are things that I can do in sh now, but it's awkward to manage errors/early termination/continuing-other-procs.

@mmlb I don't follow. Are you talking about extending the sh/bash language with stuff from Go like channels? Or perhaps without touching the language, with extra builtins like `send`?

> to parse the dialects of mksh

@D630 a quick google search shows that it seems to be just a POSIX-compliant shell. Are we not able to parse `mksh` now? In other words, can you give me examples of mksh programs that `shfmt` can't parse properly?

> and zsh

I've used zsh before, but only interactively. To my knowledge it is not a popular scripting language like sh or bash are. It's also not compatible with bash by default, so adding support to the parser would add quite a lot of complexity. Why do you think it would be worth the effort?

> to offer configurable formats

What are you thinking about? I'd like to keep `shfmt` as option-free as possible. Try `man indent` - I'm trying to avoid that. For now, a flag to control the indentation style has made everyone happy.

**Comment by D630** [comment]
cc @izabera
Take mksh's "valsubs": `shfmt <<< ': ${|ls}'`. For some more info see https://github.com/izabera/shellnotes

**Comment by mvdan** [comment]
@D630 let's move `mksh` to a separate issue (see above). I assume you've dropped the ball on `zsh` - if otherwise, please open a separate issue.

**Comment by mvdan** [comment]
After a week of work, this has got to the point where it's usable. Of course, not everything is implemented - some notable missing features:

* Some Bash stuff, like arrays, `coproc` or `<()`
* `IFS` (it's so darned confusing)
* Some builtins like `[` (should be using `/bin/[` for now), `trap`, `type` or `wait`

Please test and report any bugs you find.

I've mostly been implementing what I regularly use, and I won't be trying it on Bash's test suite just yet - that would be too depressing at this stage :)

**Comment by mvdan** [comment]
Oh, and to make testing easier, I've added an executable: https://github.com/mvdan/sh#gosh

It doesn't handle stdin nor interactivity yet, so just give it filenames.
