### ISSUE TITLE
interp: unset of a global var from inside a function broken since v3.4.1

### ISSUE THREAD

**Issue by dtrudg** [mvdan/sh#806]
Since v3.4.1, an `unset` call in a function is not un-setting the variable correctly:

```
$ cat unset.sh 
#!/bin/sh

myfunc() {
        echo "Unsetting MYVAR"
        unset MYVAR
        echo "MYVAR is now: ${MYVAR}"
}

MYVAR="I AM SET"
myfunc
```

```
# bash
$ bash unset.sh 
Unsetting MYVAR
MYVAR is now: 

# dash
$ dash unset.sh 
Unsetting MYVAR
MYVAR is now: 

# gosh (master)
$ gosh unset.sh 
Unsetting MYVAR
MYVAR is now: I AM SET

# gosh (v3.4.2)
$ gosh unset.sh 
Unsetting MYVAR
MYVAR is now: I AM SET

# gosh (v3.4.1)
$ gosh unset.sh 
Unsetting MYVAR
MYVAR is now: I AM SET

# gosh (v3.4.0)
$ gosh unset.sh 
Unsetting MYVAR
MYVAR is now:
```

If the `unset` is performed outside of the function it works.

**Comment by mvdan** [comment]
Sounds like https://github.com/mvdan/sh/commit/dc2e11e6cf3536833b6a0e2c7b4cc7d3c609dfd4 could be the culprit; could you confirm by reverting the change, or comparing the commit with its parent?

**Comment by mvdan** [comment]
cc @cclerget, who authored the commit above, and who I think works on the same project.

**Comment by dtrudg** [comment]
Hi @mvdan - I'd just looked into the changelog and pinged @cclerget out of band. I'm afraid that we actually work for 2 different companies now, on different sides of a fork of the Singularity project so we haven't been in direct communication for some time.

Can confirm the commit introduces the problem, while the parent is okay:

```
09:51 AM $ go install mvdan.cc/sh/v3/cmd/gosh@dc2e11e6
09:51 AM $ gosh unset.sh 
Unsetting MYVAR
MYVAR is now: I AM SET

09:51 AM $ go install mvdan.cc/sh/v3/cmd/gosh@423f205
09:52 AM $ gosh unset.sh 
Unsetting MYVAR
MYVAR is now: 
```

**Comment by dtrudg** [comment]
> Ah I see, I wasn't aware of the forking. I imagine that means both are using the shell interpreter, at least for now.

Yep, we are not very diverged at present, and both using the same code that hits this.

> Thanks for confirming the regression. Do you want to look into a fix yourself? If not, I'll try to take a look sometime in the coming days.

Hoping I have some time to try working up a fix this afternoon. Spoke with @cclerget and he's not super available right now on his side of things. If I can't get to it I'll let you know.
