### ISSUE TITLE
add warnings for ambiguous cases

### ISSUE THREAD

**Issue by calestyo** [mvdan/sh#810]
Hey.

It would be nice if the program could give warnings for (possibly) ambiguous cases, or such which produce undefined results.

Just a few examples for starter (not sure whether you'd be interested in such functionality), before I'd name more:
1. In patterns (i.e. pattern matching notation like in `case` or `${var##word}` and friends - not regular expressions), there are many subtle pitfalls:
- a bracket expression (like `[a-z]`) that starts with a `^` produces undefined results (as per POSIX, concrete shells may do something else e.g. bash does)) but **only** if the bracket expression really is one
- a bracket expression is only one, when there is a unquoted `[` **and** a matching unquoted `]`, so e.g. the pattern `[ab\]` would actually be the literal string `[ab]` (the `\` quotes the `]`
- bash would interpret e.g. `[$[\]` oddly...`$[` would introduce a deprecated form of arithmetic expansion with no matching `]`
- one might even warn if something like this is done in a pattern (e.g. of a `case`) `$var` without quotes like `"$var"` .. in the former case any e.g. * in the var would be taken as special character for the pattern... whereas the `"` quotes would make them literal characters with respect to the pattern

2. in any shell that supports `local` ... most people would assume that e.g. `local var` initialises the `var` with the empty string, however if there's already another `var` in the outer scope (depending on dynamic scoping) that is used to initialise the value by some shells (but not by all)... so one should e.g. warn about that if there is no explicit value being set.

Cheers,
Chris.

**Comment by mvdan** [comment]
Those all sound like nice ideas, but the only tool we've built here is a formatter, where warnings don't really have a place. What you're thinking of is a static analysis tool, to find potential bugs or problems with user code.

You could certainly build one such tool on top of the same Go package that the shfmt program uses - in particular, see https://pkg.go.dev/mvdan.cc/sh/v3/syntax. I do not have the time to write and test such a tool right now, but I'd be happy to give advice to whoever decides to do it :)
