### ISSUE TITLE
syntax: printer isn't stable with comments right after chained pipes

### ISSUE THREAD

**Issue by uli42** [mvdan/sh#83]
Thnaks for this tool. It helps a lot. However, I found some interesting behaviour

```
        echo sometext |
        cat | #comment1
        cat | #comment2
        cat
```

results in

```
echo sometext \
        | #comment1
        cat \
        | #comment2
        cat \
        | cat
```

comment1 appears after the second pipe but in the output it is now just after the first pipe. I think it is explainable but it is confusing in the first place...

Also, having the pipe symbol at the line start requires continuation characters in the previous line. I don't regard this as "cleaner" or "more readable", but YMMV. Making this decision an option would definitely help here.

**Comment by mvdan** [comment]
That's one crafted piece of code :) I'll have to look at the comment stuff, this scenario never occurred to me.

As for the option, see #21. It's not the first time I'm nagged about this, so I'll reopen the issue and consider it again.

**Comment by uli42** [comment]
actually, it is just a cleaned up version of some code I found in a script that I wanted to clean up... ;-)

**Comment by mvdan** [comment]
Okay, so exactly what could we do here?

Two possible outputs came to mind:

```
echo sometext \
        # comment1
        | cat \
```

```
echo sometext \
        | cat # comment1 \
```

Neither of them works. In the first, the comment breaks the line-joining and thus the `|` starts a new command, erroring. In the second, backslashes in comments are ignored thus it doens't join the next line.

I'm afraid that there is nothing to do with such weird code when we format pipes like this. Once we have an option to format them in the same line as shown in #21, then your input program would be left almost untouched.

If you can find a formatting output that's better than the current one and is valid shell, please do bring it up.

Thanks!

**Comment by mvdan** [comment]
If anything, I'm actually surprised that the formatter managed to write a program that keeps the comments somewhat near where they originally were without breaking the program :)

**Comment by mvdan** [comment]
...actually, if you re-run the formatter on its own output, it changes it again, which sucks. Reopening.

**Comment by mvdan** [comment]
Okay, now it formats like in your original post, but it doesn't break when you run it again.
