### ISSUE TITLE
syntax: the printer can split up strings when joined with escaped newlines

### ISSUE THREAD

**Issue by cilki** [mvdan/sh#832]
I came across this kind of assignment in a legacy codebase:

```sh
# Has the same effect as: wrapped='a b c'
wrapped=\
"a "\
"b "\
"c"
```

which `shfmt` turns into:
```sh
wrapped="a "\
	"b "\
	"c"
```

and causes the runtime error: `line 4: b : command not found`.

Tested on `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)` and the latest `shfmt`.

**Comment by mvdan** [comment]
Thanks, this does sound like a bug, probably in the printer. It should be taught to not indent after escaped newlines if that would change the program.
