### ISSUE TITLE
Breaks with string: echo 'test' > /var/spool/fcron/{{ USERNAME }}.orig

### ISSUE THREAD

**Issue by yonas** [mvdan/sh#836]
shfmt breaks with this string:

```
# cat test.sh
echo 'test' > /var/spool/fcron/{{ USERNAME }}.orig

# cat test.sh | shfmt
echo 'test' USERNAME }}.orig >/var/spool/fcron/{{
```

shfmt v3.4.3
FreeBSD 13.0-RELEASE-p10

**Comment by mvdan** [comment]
Are you sure your shell is valid? `/var/spool/fcron/{{ USERNAME }}.orig` is three words, not one, hence why shfmt reformats it that way.

**Comment by yonas** [comment]
Thanks, it's a template, not valid shell yet.

I'll run jinja over it first, and then shfmt. Thanks!
