### ISSUE TITLE
syntax: backslashes aren't parsed properly inside backquotes

### ISSUE THREAD

**Issue by uli42** [mvdan/sh#85]
Again I have some special code that does not work properly after shfmt (it some special messaging code):

```
$ cat x
arg=\"hello\"
echo "--"
echo "1'`echo "$arg" | sed -e s/\\'/\\'\\\\\\\\\\'\\'/g`'"
echo "--"
echo "2'$(echo "$arg" | sed -e s/\\'/\\'\\\\\\\\\\'\\'/g)'"
echo "--"
echo "3'$(echo "$arg" | sed -e s/\'/\'\\\\\'\'/g)'"
echo "--"
$ bash  x
--
1'"hello"'
--
sed: -e expression #1, char 15: unterminated `s' command
2''
--
3'"hello"'
--
```

The line marked with "2" is what shfmt makes of line "1". And as you see bash/sed does not like what shfmt produces. Line "3" has the number of backslashes halved and produces the same result as the original.

`man bash` states:
    _When the old-style backquote form of substitution is used, backslash retains its literal meaning except when followed by $, `, or \.  The first backquote not  preceded  by  a
       backslash terminates the command substitution.  When using the $(command) form, all characters between the parentheses make up the command; none are treated specially._

shfmt should take care of that, I think.

**Comment by mvdan** [comment]
God damned backticks and backslashes... I chose to ignore this back in the day, hoping it would never show up in practice :) I'll look into it, but if it turns out to be madness I'll just tell people to rewrite into `$()` manually.

**Comment by mvdan** [comment]
Okay, so I had a go at this, and now the tool returns:

```
echo "1'$(echo "$arg" | sed -e s/\'/\'\\\\\\\'\'/g)'"
```

From what I can tell by giving it inputs like `foo 'bar'`, this works as expected. I didn't get the same amount of backslashes as you, though.

It seems like your program number 3 works as well. Not sure why. How did you end up with that? Just removing every second backslash?

**Comment by mvdan** [comment]
Ah, broken logic on my part; I get the correct one now. Now I just need to add proper tests for this madness.

**Comment by mvdan** [comment]
Okay, `\\` is now handled properly in backquotes. I've left `\$` and `` \` `` in a TODO, because these are even more insane and I don't have the patience today.

**Comment by uli42** [comment]
Yes, I just replaced every \\ pair by a single \

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "Daniel Martí" <notifications@github.com>
Gesendet: ‎22.‎04.‎2017 20:21
An: "mvdan/sh" <sh@noreply.github.com>
Cc: "Ulrich Sibiller" <uli42@gmx.de>; "Author" <author@noreply.github.com>
Betreff: Re: [mvdan/sh] syntax: backslashes aren't parsed properly insidebackquotes (#85)

Okay, so I had a go at this, and now the tool returns:
echo "1'$(echo "$arg" | sed -e s/\'/\'\\\\\\\'\'/g)'"
From what I can tell by giving it inputs like foo 'bar', this works as expected. I didn't get the same amount of backslashes as you, though.
It seems like your program number 3 works as well. Not sure why. How did you end up with that? Just removing every second backslash?
