### ISSUE TITLE
syntax: array globs not parsed correctly

### ISSUE THREAD

**Issue by philsc** [mvdan/sh#850]
The following script is rejected by `shfmt`:
```bash
#!/bin/bash
readonly -a new_patches=( [0-9][0-9][0-9][0-9]-*.patch )
```
The intent is to glob up all the patch files generated with `git format-patch`.

We get this error:
```console
$ shfmt foo.sh
foo.sh:2:27: "[x]" must be followed by =
```
I'm assuming that it thinks we're using associative arrays here.

This is on the latest version as far as I can tell:
```console
$ shfmt -version
v3.4.3
```

**Comment by mvdan** [comment]
Yep, this is a known limitation of the parser; see https://github.com/mvdan/sh/issues/558. It is fixable, but not trivially so, as it requires support for ambiguous syntax parsing (e.g. backtracking).

**Comment by philsc** [comment]
Is there a way via a comment or something to disable formatting on a certain line?
Similar to clang-format's `// clang-format: off`?

**Comment by mvdan** [comment]
I'm afraid not, but you can split your code between multiple files as an alternative.
