### ISSUE TITLE
cmd/shfmt: longer CLI flags

### ISSUE THREAD

**Issue by p0da** [mvdan/sh#852]
Apologies if this is a duplicate, but would you consider adding a longer version of each CLI flag e.g -i -> --indent. It increases readability and is therefore a fairly common practice. Thanks!

**Comment by mvdan** [comment]
It's a fair request, in terms of usability. Especially for the sake of readability in scripts. Go's flag package doesn't implement full GNU flags, so I'm reluctant to pull in an external flag library just for this. But we could accept `-indent` as well as `-i`, and I think Go's flag package will also then accept `--indent`. Would that suffice?

Also note that we already do have the long form of each option when used in EditorConfig files; so the names would be those.

**Comment by p0da** [comment]
Sounds good, I believe convention has the short flag prepended with a single hyphen while the long flag is prepended with two hyphens so as long as those two formats are supported the flags should be intuitively understood.
