### ISSUE TITLE
[ShellScripting] `While` bad format with condition "<="

### ISSUE THREAD

**Issue by DevDorrejo** [mvdan/sh#855]
In the next code
```
  while [ i <= "${ips_route[@]}" ]; do
        if [ $(grep nameserver /etc/resolv.conf | sed 's/^.* //') != ]; then
            true
        fi
```

when i do shfmt file.

will sort the `while` the next way
```
while [ i "${ips_route[@]}" ] <=; do
                if [ $(grep nameserver /etc/resolv.conf | sed 's/^.* //') != ]; then
                        true
                fi
        done
```

and will break the code.

using [[ ]] will stop this happen, but using a simple [] the format will brake the script.

thanks

**Comment by mvdan** [comment]
I don't think that code does what you think it does; `[` does not have operators like `<=`, you are just redirecting stdin from a file called `=`, as in `< =`. You probably want `[ foo -le bar ]`, for "less or equal".

**Comment by DevDorrejo** [comment]
yeah, was the "less or equal", i'm sorry for this.
