### ISSUE TITLE
all: bash exec tests failing under non-english locale

### ISSUE THREAD

**Issue by andreynering** [mvdan/sh#89]
[Output of `go test ./...`](https://gist.githubusercontent.com/andreynering/1ded2c798e65f0dd789b68a50600eab0/raw/5720e4467b49d8ebecd552bd9e62a9b693b5586f/mvdan-sh-test.txt)

Interesting that all tests passes on Travis.

**Comment by mvdan** [comment]
What's your output of `bash --version`?

**Comment by andreynering** [comment]
```
GNU bash, versão 4.4.5(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Licença GPLv3+: GNU GPL versão 3 ou posterior <http://gnu.org/licenses/gpl.html>.

Este é um software livre; você é livre para alterar e redistribuí-lo.
Há NENHUMA GARANTIA, na extensão permitida pela lei.
```

**Comment by mvdan** [comment]
Also, until this is fixed, you can simply use `go test -short ./...` as all tests that run the real Bash are skipped in that mode.

**Comment by mvdan** [comment]
Oh, the issue is the locale - I hard-coded some english strings to ignore warnings and such. I need to fix this.

**Comment by andreynering** [comment]
OK, the short version passes

**Comment by mvdan** [comment]
Please try the change above - it should have fixed it for you.

**Comment by andreynering** [comment]
Hmm... seems that that commit had no effect. It still faills with the same output.

**Comment by mvdan** [comment]
Huh - could you give me your output of `locale`?

I can't test this fix locally, at least not easily. Could you try other fixes like the one I did and submit a patch?
