### ISSUE TITLE
print: moves backticks after heredoc

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#9]
$ cat x.bash
    cat <<EOF | `echo tac`
    3
    2
    1
    EOF
    
    $ bash x.bash
    1
    2
    3
    
    $ shfmt x.bash
    cat <<EOF | `echo tac
    3
    2
    1
    EOF
    	`

**Comment by mvdan** [comment]
Thanks for reporting!

Curious, how are you finding all these?

**Comment by ebfe** [comment]
> Curious, how are you finding all these?

I've done some light fuzzing, but most issues discovered while playing
around/using it.

**Comment by mvdan** [comment]
I also regularly fuzz the thing, it just didn't occur to me to do it before pushing yesterday's changes. I shouldn't have pushed that heredoc change that is triggering these crashes, as fuzzing finds them easily.
