### ISSUE TITLE
syntax: AST docs and stability

### ISSUE THREAD

**Issue by hzlmn** [mvdan/sh#91]
Hi, I am wondering is there are any docs for AST structure, I mean other than `godoc`. And also is it final structure or it will be revisited?

**Comment by mvdan** [comment]
> I am wondering is there are any docs for AST structure, I mean other than godoc.

Well, the godoc is the documentation. You can also look at `nodes.go` for internal details. What exactly are you missing?

> And also is it final structure or it will be revisited?

The current API (including the AST) is stable in 1.x. I plan on branching that off and make `master` be 2.x, at which point I'll break backwards compatibility until 2.0 is released.

In any case, be sure to vendor or pin a repo version so that your stuff doesn't break once I start working on 2.x.

**Comment by mvdan** [comment]
Also note that the changes I intend to do in 2.x are minor, so porting a package that uses 1.x to 2.x should be fairly easy.

**Comment by hzlmn** [comment]
Yeah obviously `godoc` are super cool, but  if node's like while node are self describing, some of them are not very explicit. It would be nice if you provide some samples like  how some code sample  will be parsed. Is it make sense for you?

**Comment by mvdan** [comment]
Could you give an example of a node that isn't self-explanatory?

Note that these are all shell/bash features, so if you don't know one of them, you should be able to google it. I'm not sure the godoc is the right place to describe what each node is supposed to do.

**Comment by hzlmn** [comment]
For example `Command` node. As I understand it represents  `simple_command` from POSIX shell spec?
If so there should be props like  `cmd_prefix` `cmd_word` `cmd_suffix`, but it's not described in `godoc` https://godoc.org/github.com/mvdan/sh/syntax#Command. How I can for example access value of command `echo "test"` to match `echo` cmd type?

**Comment by mvdan** [comment]
Note that since this is a static parser and it supports Bash, the AST doens't exactly match the POSIX shell spec grammar.

Multiple node types can implement `Command` - in your case, `CallExpr`. Perhaps you should parse your string and do a `syntax.Walk` on it to print each node type.

**Comment by mvdan** [comment]
@hzlmn does the commit above clear things up a bit for you? I realise that reading the godoc for the first time, it might not be clear exactly what data these interfaces hold.

Now each of them explicitly lists the possible underlying types.

**Comment by hzlmn** [comment]
@mvdan Yeah it's clearer now, thanks.
