### ISSUE TITLE
syntax: confusing error when "function" is used in posix mode

### ISSUE THREAD

**Issue by wangyushui** [mvdan/sh#911]
* error:
Euler:~ #shfmt_v3.5.1_linux_arm64 -i 4 -ci -d -bn -sr 1.sh
1.sh:2:15: a command can only contain words and redirects; encountered (
Euler:~ #cat 1.sh 
#!/bin/sh
**function** watch() {
    true
}

* no problem:
Euler:~ #shfmt_v3.5.1_linux_arm64 -i 4 -ci -d -bn -sr 1.sh
Euler:~ #cat 1.sh
#!/bin/sh
watch() {
    true
}

**Comment by mvdan** [comment]
I think you want to be using `#!/bin/bash` as your shebang, as `function` is a Bash feature. Or otherwise, explicitly pass in the `-ln=bash` flag. Although our error message here could probably be more helpful, so I think it's worth keeping this issue open for that improvement.

**Comment by wangyushui** [comment]
Thank you for your reply. I agree with you

> I think you want to be using `#!/bin/bash` as your shebang, as `function` is a Bash feature. Or otherwise, explicitly pass in the `-ln=bash` flag. Although our error message here could probably be more helpful, so I think it's worth keeping this issue open for that improvement.

**Comment by mvdan** [comment]
I'll keep this open for the sake of better errors :)
