### ISSUE TITLE
feature request: set executable bit for release binaries

### ISSUE THREAD

**Issue by jbergstroem** [mvdan/sh#940]
It would be helpful if the released binaries had a executable bit set (`chmod +x`)! That is all.

**Comment by jbergstroem** [comment]
> One alternative would be to upload assets inside a `.tar.gz` or similar, where permission bits can be included. But I think that's just replacing one manual step with another, and we only need to release one binary anyway, so I'm not a big fan.

Yeah, that'd be the way to get it done. Apologies for not being very forthcoming in suggesting a solution - poor effort on my end. I guess the potential benefit of compressing it is slight improvements to distribution size but I guess its somewhat moot?

Either way, thanks for considering. Feel free if you prefer as-is!

**Comment by mvdan** [comment]
I believe that HTTP can already do compression, so I don't think that is an issue.

Switching to tarballs would replace `chmod +x` with `tar -xf` or the equivalent, so I'm not convinced it gains us much :) maybe if we had multiple files per platform to distribute, but that is not the case.

**Comment by jbergstroem** [comment]
> Switching to tarballs would replace `chmod +x` with `tar -xf` or the equivalent, so I'm not convinced it gains us much :) maybe if we had multiple files per platform to distribute, but that is not the case.

One benefit here is `curl | tar -x` which I don't think is easily achievable with `chmod`
