### ISSUE TITLE
cmd/shfmt: link to web demo or playground

### ISSUE THREAD

**Issue by l0b0** [mvdan/sh#941]
`shfmt` is a great tool, and it would be fantastic if it was more widely adopted. Unfortunately many potential users don't have an easy way to run it: the only *nix machines they have access to are managed by others, and they don't have the expertise to set up something like a VM. To help those users out, I'm wondering if someone would be willing to host a playground like [ShellCheck](https://www.shellcheck.net/) where users can simply paste their code and get a formatted version back in another part of the page.

**Comment by mvdan** [comment]
Not sure if I follow: the releases contain binaries for both Windows and Mac. There are also plugins that integrate the tool with IDEs like JetBrains, I believe.

Totally fine with me if someone hosts a site that acts as a web playground, though. Happy to link to it in the README.

**Comment by l0b0** [comment]
> Not sure if I follow: the releases contain binaries for both Windows and Mac. There are also plugins that integrate the tool with IDEs like JetBrains, I believe.

A lot of people work in environments where they are not allowed to install any software whatsoever. A lot of people are also developers second, and an IDE is too complicated for what they are doing. So they effectively have no easy way to run `shfmt`, and a web site would be an excellent way to format the tiny handful of files they have to deal with.

**Comment by mvdan** [comment]
Sure, no disagreements there. Still happy to link to a website doing this if someone implements it. I don't have time for it myself in the short term.

**Comment by mvdan** [comment]
I'm going to close this for now, given that noone seems to have interest in building one. If someone does build one, I'll happily accept a PR that links to the website.
