### ISSUE TITLE
Multiple VirusTotal detections for Windows binairies

### ISSUE THREAD

**Issue by maxence-lagalle** [mvdan/sh#945]
Hello, I tried to install shfmt through the [scoop main bucket ](https://github.com/ScoopInstaller/Main/blob/master/bucket/shfmt.json) on my Windows 10 computer with Trellix anti-virus software, but as soon as I try to use it, this antivirus software flags the binary as malware and delete it.

This behavior seems to be shared by 5 vendors, based on VirusTotal : https://www.virustotal.com/gui/file/f759493bc55a4ea181442eb7d79b527ff6c15d62ec567b8b86a5df6a086c9c46/detection

It looks like an automatic detection rule of the Hive malware family is triggered, probably because of the Go compiler. I know I could rebuild this executable on my computer (I can't disable or change the AV vendor on this system), but I will lose the benefits of using scoop for updating my installed tools.

**Comment by mvdan** [comment]
See https://go.dev/doc/faq#virus. I can't really do anything about it because, well, shfmt is not malware.
