### ISSUE TITLE
syntax: parsing ${x[$1]} errors with "reached } without matching [ with ]"

### ISSUE THREAD

**Issue by uli42** [mvdan/sh#95]
```
#!/bin/bash
declare -a x
x[1]="hello"
echo "${x[$1]}"
```
does not work:
```
$ shfmt x.sh
x:4:10: reached } without matching [ with ]
```

The script itself is working ok:
```
$ bash x 1
hello
```

**Comment by mvdan** [comment]
Ah, this will likely be a regression introduced recently, like in https://github.com/mvdan/sh/commit/e644631a219af335a56a4c641545e860b04e73a3.

Thanks for reporting!

**Comment by mvdan** [comment]
Pushed a fix to both master and v1 branches. Won't do a `v1.3.1` just yet, will wait another week or two to see if there are any other bug fixes to add to it.

**Comment by uli42** [comment]
Looks good. I suggest to include those shell snippets in the unit tests of shfmt.

**Comment by mvdan** [comment]
What shell snippets?

I've included a test with `${foo[$bar]}` if you look at the commit that fixes this issue.

**Comment by uli42** [comment]
The snippets the are provided in the bug reports, like mine above.

**Comment by mvdan** [comment]
Well, the other two lines are already covered by other tests. I'd rather keep tests programs as small as possible. I'll only add more if they reproduce a crash/bug or if they help code coverage.
