### ISSUE TITLE
Set flags as comments inside of a file

### ISSUE THREAD

**Issue by sarmong** [mvdan/sh#951]
`-kp, --keep-padding` is handy for config files, however it is very annoying when writing scripts because with this option, shfmt doesn't fix extra indentation.

1. It would be nice to set this rule as a comment at the top of the file to only apply to certain files
2. Maybe this rule could retain spaces only in-between text, but format them when at the beginning of a line?

**Comment by mvdan** [comment]
Have you seen https://github.com/mvdan/sh/issues/658? The flag is frozen and will be removed in a future v4, so you probably don't want to rely on it.

**Comment by sarmong** [comment]
Thanks, I will probably stop using this feature then.

I hope that it will be resurrected in another way in the future, because it really helps navigating config files such as `bspwmrc`
