### ISSUE TITLE
could we add selfupdate to shfmt?

### ISSUE THREAD

**Issue by KimBioInfoStudio** [mvdan/sh#978]
https://github.com/minio/selfupdate

**Comment by mvdan** [comment]
I don't think that would be a good idea.

A portion of people install shfmt from their distribution or package manager. They likely want to get updates that way. Many downstreams are likely to patch out or disable any form of self-update as well.

Other people install from source. Installing a newer version from source is equally as easy.

Other people download prebuilt binaries from the releases page. I guess self-updating binaries would benefit those most. But I also don't think it's particularly hard to use `go install mvdan.cc/sh/v3/cmd/shfmt@latest` if one really cares about installing the latest version, or subscribe to be notified about new releases.
