### ISSUE TITLE
Request: POSIX Makefile parser

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#985]
Hi,

I rather enjoy your library for parsing/validating pure POSIX sh code.

Would it be possible to release a similar library for parsing/validating pure POSIX Makefiles? I would then consume the library in order to ensure that my projects will work equally well on both GNU/Linux and BSD.

**Comment by mvdan** [comment]
Yes, see https://github.com/mvdan/sh/issues/730, which you can find with a fairly simple search.

Also see https://github.com/mvdan/sh/issues/567#issuecomment-629230799.
